### ISSUE TITLE
[Bug]: Export table data

### ISSUE THREAD

**Issue by cavajr** [Power-Components/livewire-powergrid#1002]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.0

### Laravel

9.19

### Livewire

2.12

### Alpine JS

3.12.1

### Theme

Bootstrap

### Describe the bug.

I'm using bootstrap 5 with the coreui 4 template.
When I click on the button to export all in Excel or CSV I am redirected to the link localhost:8000/#.

When inspecting, I saw that the value '#' is in the href

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Can you put more information about this ?

**Comment by viniciusalvess** [comment]
For this issue, I had to publish the views and call the .prevent on all wire:click occurrences.

resources/views/vendor/livewire-powergrid/components/frameworks/bootstrap5/header/export.blade.php

![image](https://github.com/Power-Components/livewire-powergrid/assets/17517866/303b8d97-995c-4465-a09f-53119427d440)

**Comment by luanfreitasdev** [comment]
Done in v4.6.3
