### ISSUE TITLE
[plugin:vite:css] [postcss] Cannot find module '@tailwindcss/forms' [Bug]: 

### ISSUE THREAD

**Issue by quizafebrick** [Power-Components/livewire-powergrid#1006]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### PHP Version

8.2..0

### PowerGrid

4.5

### Laravel

10.10

### Livewire

2.12

### Alpine JS

3.12.2

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When i load the page this happens, i tried to install tailwind forms but still the same 

![image](https://github.com/Power-Components/livewire-powergrid/assets/102888867/8ffaaf28-2346-4b16-b7da-a45bb262100d)

I even put the plugin to my tailwind.config.js

![image](https://github.com/Power-Components/livewire-powergrid/assets/102888867/d64b8f29-5f9a-4392-84c2-83bb85b3315e)

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
I believe it is a typo in "rrequire(''@tailiwind/forms")"

**Comment by quizafebrick** [comment]
No, sorry i didn't mentioned the typo here in the picture. I'd still get the same error even it is correctly spelled

**Comment by luanfreitasdev** [comment]
Anyway this seems to be a problem with the @tailwindcss/forms plugin in your project and not with powergrid. I tried to reproduce the same error.
