### ISSUE TITLE
[Bug]: Dynamic MultiSelect Entangle Error

### ISSUE THREAD

**Issue by racerguy** [Power-Components/livewire-powergrid#1007]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes, Livewire Entangle Error: Livewire property 'filters.selectcustomer' cannot be found

### PHP Version

8.2

### PowerGrid

4.5.1

### Laravel

10.13

### Livewire

2.12.3

### Alpine JS

3.12.2

### Theme

Tailwind 3.x

### Describe the bug.

Dynamic Filter does not do anything when selecting options using WireUI component . 
Error shows in console Livewire Entangle Error: Livewire property 'filters.selectcustomer' cannot be found

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
Filter::dynamic('customer','customers.id')
            ->component('wireui.select') // <x-select ...attributes/>
            ->attributes([
                'class'           => 'min-w-[190px]',
                'async-data'      => route('api.wireui.customer'),
                'option-label'    => 'display_name',
                'multiselect'     => true,
                'option-value'    => 'id',
                'placeholder'     => 'Test',
                'wire:model.lazy' => 'filters.selectcustomer'
            ]),
```

**Comment by maikezan** [comment]
We are also experiencing the same exact issue. Using all dynamic filters with wire UI x-select.
Only difference in setup is 
Laravel v. 9.52.8
WireUI v. 1.17.9
Tailwind v. 3.3.1
This is the error in console
![image (1)](https://github.com/Power-Components/livewire-powergrid/assets/61838461/5f3ded0d-ef17-41e7-aba3-c48f56f1886f)

Edit:
we managed to make it work defining a public array for filters structured like this:
`public array $filter = [ 'select' => 'filters' => '<filter_1>', '<filter_2>' .... ]`

**Comment by luanfreitasdev** [comment]
Done in v4.6.3
