### ISSUE TITLE
Header Action Column Title Align

### ISSUE THREAD

**Issue by vicenterusso** [Power-Components/livewire-powergrid#1009]
How to align the actions title on header, for example to the right?

![image](https://github.com/Power-Components/livewire-powergrid/assets/80538/f6e81e00-06cd-4b84-8007-b4324428adfd)

**Comment by abhaypithadiya** [comment]
Hey!

Publish the Powergrid view file using:

```php artisan vendor:publish --tag=livewire-powergrid-views```

Go to resources\views\vendor\livewire-powergrid\components\table.blade.php:29

Here you can update the action header classes.

Hope this helps!

**Comment by luanfreitasdev** [comment]
I'm doing a PR for this :)

**Comment by vicenterusso** [comment]
> I'm doing a PR for this :)

Tks for the quick reply. Also a suggetsion: A way to customize the title headers.. (couldn't find any) .. classes or even content, the text itself

**Comment by luanfreitasdev** [comment]
Is this what you were looking for?

https://v4.livewire-powergrid.com/table/include-columns.html#headerattribute

**Comment by vicenterusso** [comment]
Yes, but I couldn't find a way to change the "actions" column

**Comment by luanfreitasdev** [comment]
Wait for this PR: https://github.com/Power-Components/livewire-powergrid/pull/1010

**Comment by luanfreitasdev** [comment]
Done in v4.6
