### ISSUE TITLE
[Bug]: Filter Labels (outside) Text not visible when using Dark mode

### ISSUE THREAD

**Issue by uksitebuilder** [Power-Components/livewire-powergrid#1014]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1.5

### PowerGrid

4.5

### Laravel

9.2

### Livewire

2.12

### Alpine JS

3.4.2

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When using filters (outside) with Dark Mode enabled, no text is visible in the filter labels

<img width="216" alt="Screenshot 2023-06-05 at 18 45 13" src="https://github.com/Power-Components/livewire-powergrid/assets/1906020/449313bf-4734-47b9-90d1-5060ebd590e9">

<img width="264" alt="Screenshot 2023-06-05 at 18 45 31" src="https://github.com/Power-Components/livewire-powergrid/assets/1906020/ba794498-cb78-4850-ad8d-da16f172f106">

### To Reproduce...

Make sure filter is set to outside

Enable Dark Mode either in the os preferences or via a dark mode switch on the website

Click on and enter data in a filter (see first screenshot)

Likewise with and additional filter (see second screenshot)

**Comment by luanfreitasdev** [comment]
Thank yout!. Done in v4.6.1
