### ISSUE TITLE
[Bug]: edit field changing spaces by &nbsp (or &amp) (editOnClick)

### ISSUE THREAD

**Issue by HerberthCaldeira** [Power-Components/livewire-powergrid#1018]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1

### PowerGrid

3.7.8

### Laravel

9

### Livewire

2.12.3

### Alpine JS

3.12.0

### Theme

Bootstrap

### Describe the bug.

When I edit a field inside the table (editOnClick) and add spaces at the end (mostly) they are replaced by &nbsp or &amp (or both)

### To Reproduce...

When editing a field in the table adding spaces. It always happens when I add spaces at the end of the string. Save and click on the field again.

It happens in the demo too:
https://demo.livewire-powergrid.com/validation

![bug](https://github.com/Power-Components/livewire-powergrid/assets/7907803/3c255861-70e9-4332-bd18-d87bc42593d6)

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Done in v4.6.2
