### ISSUE TITLE
[Bug]: Checkbox throws a bug when datasource output is empty

### ISSUE THREAD

**Issue by hbakouane** [Power-Components/livewire-powergrid#1029]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

No

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### Theme

Bootstrap

### Describe the bug.

When the output of datasource() is empty, if we check the checkbox at the top, it throws an error.

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by hbakouane** [comment]
<img width="1334" alt="image" src="https://github.com/Power-Components/livewire-powergrid/assets/57842491/f336b01b-ba3c-489f-b2ba-c226727ee1a5">

**Comment by luanfreitasdev** [comment]
Hello!. I was not able to reproduce the same problem. Can you give more details of which version you are using and how you made the component?

Try here: https://demo.livewire-powergrid.com/

**Comment by jirkacisar** [comment]
The same problem. Collection as datasource and empty table. If I check "select all" checkbox in the header, it throws the error mentioned higher....
