### ISSUE TITLE
Demo state filter status not as one would expect

### ISSUE THREAD

**Issue by MACscr** [Power-Components/livewire-powergrid#103]
**Describe the bug**
Recorded video below, but in demo, state filters dont work as expected. Has an overflow issue and multiples filters do not behave as expected as far as current filters being used.

**To Reproduce**
Installed fresh laravel, breeze, powergrid with dem, then select multiple states.

**Laravel version (exactly):**
8.6.9
 
**Alpine version:**
Not used ATM.

**Theme:**
- [x] Tailwind 
   - Version:  2.2.19     

I created a video that hopefully helps convey the two issues
https://www.screencast.com/t/FKZQvSiZ8

**Do you have any idea how we can fix it?**

**Comment by luanfreitasdev** [comment]
Hi @MACscr !  thank you very much for noticing this issue.  

It must have some relationship with CSS.  That problem with buttons that don't come out after removal is already a problem we'll solve soon.

**Comment by MACscr** [comment]
Shouldnt the filters (the state column) like that be multi select though if they are going to show an x by them? I didnt really unselect anything, I just picked a second one. I would just expect GA and ME to stay up there versus somehow becoming unselected at the top while still showing the proper results.

**Comment by luanfreitasdev** [comment]
Unfortunately for some reason it didn't work in the demo, let's take a closer look at what happened. Thanks for reporting this issue!

But in the component in standard operation it is working

![image](https://user-images.githubusercontent.com/33601626/140053545-b6226c68-36a4-43db-92d2-a34d44d7a591.png)

**Comment by luanfreitasdev** [comment]
It's a strange problem that only occurs when there are few records in the table. I'll leave it in backlog as it's working for most cases except css
