### ISSUE TITLE
[Bug]: Filters don't work correctly when the datasource is a collection

### ISSUE THREAD

**Issue by anagonzaga** [Power-Components/livewire-powergrid#1035]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8

### PowerGrid

3.7

### Laravel

8

### Livewire

2.10

### Alpine JS

3.0

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

We are currently experiencing an issue with filters not working properly on collections when it comes to the datepicker and select elements. These filters, which are essential for accurate searches, are showing unexpected and inconsistent behavior.

When trying to use the datepicker filter on a collection, the results obtained do not match the selected dates. For example, when selecting a specific date, the system returns records that do not correspond to that particular day, or even returns no results at all. This causes confusion and difficulties for users who rely on accurate data filtering.

Also, the select filter is also failing. When choosing a specific option from the dropdown menu, the results are not being filtered properly. Instead of returning only records that match the selected option, the select filter might show irrelevant results or even not filter at all.

These issues are significantly impacting the efficiency and user experience when browsing and searching for information in collections. The correct functioning of the filters is crucial to ensure that users find the relevant data quickly and accurately.

Steps to reproduce the bug:

Access the collections section.
Try using the datepicker filter by selecting a specific date.
Please note that the displayed results do not match the selected date or may be incorrect.
Try using the select filter by choosing a specific option.
Check that the results are not properly filtered or may be irrelevant.

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello!. Could you share a snippet of the code you made?

**Comment by anagonzaga** [comment]
@luanfreitasdev Hello, the problem has been solved. Thanks!

**Comment by luanfreitasdev** [comment]
Hello!, can you share the solution?
