### ISSUE TITLE
[Bug]: Flatpickr darkmode missing

### ISSUE THREAD

**Issue by markgoedegebure** [Power-Components/livewire-powergrid#1036]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

no

### PHP Version

8.1

### PowerGrid

4.8.0

### Laravel

9.52.7

### Livewire

2.12.3

### Alpine JS

3.10.2

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

The Datetime/Date filters are missing darkmode. Other filters do have dark mode.
![afbeelding](https://github.com/Power-Components/livewire-powergrid/assets/44771394/7c31b0a4-b7ad-497a-aa58-27dfaef7761a)

### To Reproduce...

Add a table with a datefilter and toggle dark mode

**Comment by luanfreitasdev** [comment]
Unfortunately, this will not be possible to be added in PowerGrid because the flatpickr classes are too big and maintenance would be unfeasible.

A solution would be to modify the file ["flatpickr/dist/themes/dark.css"](https://flatpickr.js.org/themes/) to work with dark mode and import manually
