### ISSUE TITLE
Foreign key + join => Column 'id' in order clause is ambiguous 

### ISSUE THREAD

**Issue by sebreunion** [Power-Components/livewire-powergrid#104]
Hi,

Great plugin !

I try to display the foreign table column value instead of the foreign key.

So i changed my query to make the join :

```
return Article::query()->join('type_articles', 'articles.type_article_id', '=', 'type_articles.id')
            ->select('articles.*', 'type_articles.typeArticle as type_article');
```

The sql command result in an error : SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous

My 2 tables have an "id" column and primary key.

What is the best way to get powerGrid to prefix my primary key column name with the table name in the order part of the generated query ?

Thx

**Comment by snapey** [comment]
I had the same issue and had to remove the id column from the grid entirely.  For some reason it was being included in the search even though search was not enabled for the id column.  The query ended up being like;
```
where
`id` like '%snapey%' 
and `username` like '%snapey%'
```
Then I got the error that the id column was ambiguous because of the join to another table

**Comment by luanfreitasdev** [comment]
Hello @sebreunion 

You can put `$primaryKey = 'your_column' ` in the component. - https://github.com/Power-Components/livewire-powergrid/issues/94

**Comment by sebreunion** [comment]
> Hello @sebreunion
> 
> You can put `$primaryKey = 'your_column' ` in the component. - #94.
> 
> Example:
> 
> ```
> 
> public string $primaryKey = 'dishes.id';
> public string $sortField = 'dishes.id';
> 
> public function datasource(): ?Builder
> {
>   return Dish::query()->join('categories', function($categories) { 
>       $categories->on('dishes.category_id', '=', 'categories.id'); 
>   })->select('dishes.*', 'categories.name as category_name'); 
> }
> ```

Thank you for your reply, it works great !! 

In the meantime, i have created a view in mysql and modify my powergrid to use it, it works also fine and get the same result.

Thank you all.
