### ISSUE TITLE
[Bug]:  Header action button is not showing correctly

### ISSUE THREAD

**Issue by muhammadessam** [Power-Components/livewire-powergrid#1040]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

4.8.0

### Laravel

9.2

### Livewire

2.12

### Alpine JS

3.12.2

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

I'm trying to add the following code to my project, I expected this code to add a new button in the header section. 
```
public function header(): array
    {
        return [
            Button::add('new')
                ->render(function () {
                    return Blade::render(<<<HTML
                            <x-button.circle primary icon="plus"/>
                        HTML
                    );
                })
        ];
    }
```

but nothing is showing
![image](https://github.com/Power-Components/livewire-powergrid/assets/14132452/6b16cda4-7b6a-4bbc-8754-4d7f235ede28)

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
The render method is not available in "header" section

**Comment by muhammadessam** [comment]
can you please point out what methods are available in the header section for the Button?
@luanfreitasdev

**Comment by luanfreitasdev** [comment]
`emit`, `emitTo`, `route`, `caption` (you can include Blade::render). If you want more functions, please feel free to open a Pull request
