### ISSUE TITLE
Button Groups for one too many actions required in one row.

### ISSUE THREAD

**Issue by LogicSatinn** [Power-Components/livewire-powergrid#1045]
# ⚡ PowerGrid ⚡ Feature Request

## Summary
More than once, my team and I found ourselves adding so many buttons for different actions on one row, and this makes everything look weird and cluttered. We used some unconventional, weird ways to fix this which left us desiring something cleaner. This issue asks for a button group feature, that resembles that of FilamentPHP where we can group row actions without making a mess of it.

### Brief description of what is at stake.
It might need a lot of work. Adding support for both Tailwind and Bootstrap 5. Any contribution towards this would just be some addition on top. I don't think there will be any breaking changes due to the addition of this feature.

**Comment by luanfreitasdev** [comment]
Hello, can you give more examples and details of how we could implement it in Powergrid?. Thanks
