### ISSUE TITLE
Cosmetic issue when you already have the tailwind forms plugin

### ISSUE THREAD

**Issue by snapey** [Power-Components/livewire-powergrid#105]
**Describe the bug**
Conflict with Tailwind Forms plugin

Select element has two dropdown arrows

**To Reproduce**
Use tailwind theme and install tailwind forms plugin

**Laravel version (exactly):**
* 8.54.0 ?
 
**Alpine version:**
default for package

**Theme:**
- [x] Tailwind 
        "tailwindcss": "^2.2.2"
        "@tailwindcss/forms": "^0.3.1",
        "@tailwindcss/typography": "^0.4.0",

**Screenshots** (***This helps to understand better***)

![Pegler-IoTMV](https://user-images.githubusercontent.com/328747/140045535-ce4ed380-3857-48f8-94e6-34a168288ce9.png)

**Do you have any idea how we can fix it?**
possibly a config value to ask if already using tailwind forms plugin.  Not sure you could automatically detect it.

Workaround is to comment out the lines for the SVG arrow in published assets.

**Comment by luanfreitasdev** [comment]
Hello @snapey,

There is a solution that would be to use tailwind/forms strategically to work with 'class',

Change your tailwind.config.js to:
```
require("@tailwindcss/forms")({
       strategy: 'class',
  }),
```

And add in its components input, select and others a class of type form-input, form-select, ect.

See more here: 

-> https://livewire-powergrid.docsforge.com/main/configure/#43-tailwind-forms

Thanks for using the powergrid!

**Comment by snapey** [comment]
possibly, but then I would need to go to all the forms in the rest of my project and amend them.  I'll consider it.
