### ISSUE TITLE
[Bug]: The loading button is keep freshing, can't click pagination nor any filter/sort 

### ISSUE THREAD

**Issue by suattop** [Power-Components/livewire-powergrid#1050]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

(module.esm.js:425 Uncaught ReferenceError: flatpickr is not defined)

### PHP Version

PHP 8.1.16

### PowerGrid

4.8

### Laravel

10.10

### Livewire

2.12.3 

### Alpine JS

3.12.3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

cannot click date and the pagination can't click too.

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello. Please have a look at the getting started guide to date filters. 

https://v4.livewire-powergrid.com/table/column-filters.html#filter-boolean
