### ISSUE TITLE
I want to render blade component in column closure.

### ISSUE THREAD

**Issue by tahaRazaTalibi** [Power-Components/livewire-powergrid#1051]
# ⚡ PowerGrid ⚡ Feature Request

## Summary

I would like to request the ability to render Blade components within column closures in Livewire's PowerGrid.

### Why is this needed?

Currently, column closures in PowerGrid only support raw HTML or simple PHP rendering logic. However, using Blade components within column closures would provide several benefits. It would enhance modularity, promote consistent UI patterns, improve readability and reusability, and seamlessly integrate with the existing Laravel ecosystem.

### Suggested Solution(s)

I propose enabling the use of Blade components directly within column closures. This would allow developers to encapsulate complex rendering logic within reusable Blade components, enhancing code maintainability and promoting consistency throughout the application.

### Related issue(s)/PR(s)

N/A

**Comment by luanfreitasdev** [comment]
Hello!, Can you give more examples and what would that affect the powergrid?. Thanks
