### ISSUE TITLE
[Bug]: Passing null to parameter #1 ($string) of type string is deprecated in

### ISSUE THREAD

**Issue by IljaMartinovs** [Power-Components/livewire-powergrid#1060]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

addslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vendor/power-components/livewire-powergrid/src/Helpers/Helpers.php on line 116

trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 75

### PHP Version

8.1.14

### PowerGrid

3.1.0

### Laravel

 9.52.10

### Livewire

v2.12.3

### Theme

Bootstrap

### Describe the bug.

Hello! So when the table loads, i got these errors
addslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vendor/power-components/livewire-powergrid/src/Helpers/Helpers.php on line 116

trim(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php on line 75

I guess it happens because my tables have null values in columns

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello!. Powergrid v3 is no longer supported.

Thanks
