### ISSUE TITLE
[Bug]: Filter now working and data mismatch if connection is mongodb

### ISSUE THREAD

**Issue by arjundexbytes** [Power-Components/livewire-powergrid#1062]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1.17

### PowerGrid

4.4.1

### Laravel

9.1

### Livewire

2.10.1

### Alpine JS

3.0.1

### Theme

Tailwind 3.x

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello!

It currently does not support MongoDB by default.
Feel free to send a PR to add support
