### ISSUE TITLE
[Bug]: Call to protected method PowerComponents\LivewirePowerGrid\ProcessDataSource::resolveCollection()

### ISSUE THREAD

**Issue by SebastianSchHE** [Power-Components/livewire-powergrid#1064]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Call to protected method PowerComponents\LivewirePowerGrid\ProcessDataSource::resolveCollection() from scope

### PHP Version

8.1.2

### PowerGrid

4.8.5

### Laravel

9.52.10

### Theme

Tailwind 3.x

### Describe the bug.

I'm using a simple Illuminate\Support\Collection as a datasource. And if i try to export the grid to Excel i get an error:

Traits/WithExport.php: 167
Call to protected method PowerComponents\LivewirePowerGrid\ProcessDataSource::resolveCollection() from scope

### To Reproduce...

Use a Collection as a datasource and try to export it to excel

### Extra information

```markdown
Solution

if i change $processDataSource->resolveCollection() to $processDataSource->get() in the prepareToExport function everything seems to work..
```

**Comment by luanfreitasdev** [comment]
Fixed on v4.8.6
