### ISSUE TITLE
After text editing, Model is fixed with refresh but not Collection.

### ISSUE THREAD

**Issue by tangjh** [Power-Components/livewire-powergrid#107]
When using Collection, edited text revert back to old Collection data after doing filtering.

1) Edit a text eg.  name column
2) Edited text is reflected
3) Select a filter which does not consist of the edited row
4) Select filter which consist of the edited row.  Text is reverted back to the original text.  Checked the Collection and the Collection is updated.

Cache issue?

I'm using the development main branch.  Testing the same steps with Model does not have problem.  Text is updated correctly.

**Comment by luanfreitasdev** [comment]
If you are going to use the update on the component, I advise using the datatables as Model.

But if you still want to use it to update, you can remove the cache (it is only used in collection)

`livewire-powergrid.php`:

Update to false

![image](https://user-images.githubusercontent.com/33601626/140385997-e82a9faf-445a-4b1f-ace8-6ce386710846.png)

**Comment by tangjh** [comment]
Got it.  Thanks.
