### ISSUE TITLE
View [components.frameworks.bootstrap5.header.filter] not found[Bug]: 

### ISSUE THREAD

**Issue by docetapedro** [Power-Components/livewire-powergrid#1071]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

![image](https://github.com/Power-Components/livewire-powergrid/assets/27811271/ef6eb3ed-e075-419e-8363-738eb6ef1b06)
![Print](https://github.com/Power-Components/livewire-powergrid/assets/27811271/70e57575-47bf-4510-947c-1021c554cf1a)

### PHP Version

8.1.17

### PowerGrid

4.8

### Laravel

9.52.10

### Livewire

2.10

### Theme

Bootstrap

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello!. Unfortunately, 'outside' filters are not supported for Bootstrap.

**Comment by marcelcunha** [comment]
> Hello!. Unfortunately, 'outside' filters are not supported for Bootstrap.

This is important information, maybe it should be in the docs

**Comment by yaschet** [comment]
I was able to create outside filters for Bootstrap 5 by publishing and modifying the views for the filters.

Copy the views about filters from the `tailwind` to the `bootstrap5` folder and change them to match your theme.
