### ISSUE TITLE
[Feature Request]: Support for Livewire v3

### ISSUE THREAD

**Issue by NikarashiHatsu** [Power-Components/livewire-powergrid#1077]
# ⚡ PowerGrid ⚡ Feature Request

## Summary

Support for Livewire v3

### Why is this needed?

The recently launched Livewire v3 (beta) lacks support for this package, which hinders its usefulness. It is essential to have a version of the package that is compatible with Livewire 3.

### Suggested Solution(s)

A support for Livewire v3.

**Comment by developerabdan** [comment]
Hello! That's great news! I'm excited to hear that Livewire v3 support is on its way. I checked out the discussion #1072, and it looks promising.

**Comment by luanfreitasdev** [comment]
The version will be released after the official release of v3. Thanks!
