### ISSUE TITLE
[Bug]: How can i Get Only Few Records, Take() or Limit() not working in datasource(): Builder

### ISSUE THREAD

**Issue by shakeel2717** [Power-Components/livewire-powergrid#1078]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.4

### PowerGrid

4

### Laravel

10.10

### Livewire

2.12

### Theme

Bootstrap

### Describe the bug.

```
    /**
     * PowerGrid datasource.
     *
     * @return Builder<\App\Models\Transaction>
     */
    public function datasource(): Builder
    {
        return Transaction::query()
            ->latest()
            ->whereIn('type', $this->type)
            ->limit(2);
    }
```

This is not working, i also tried for take(), it's also not working? it's showed all the matching record? Please Help.

**Comment by luanfreitasdev** [comment]
There is a similar problem, please have a look. 
https://github.com/Power-Components/livewire-powergrid/issues/61
