### ISSUE TITLE
[Bug]: Relationship column not searchable from the filter search.

### ISSUE THREAD

**Issue by shakeel2717** [Power-Components/livewire-powergrid#1079]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.4

### PowerGrid

4

### Laravel

10

### Livewire

2.12

### Theme

Bootstrap

### Describe the bug.

```
/**
     * Relationship search.
     *
     * @return array<string, array<int, string>>
     */
    public function relationSearch(): array
    {
        return [
            "User" => [
                'name'
            ]
        ];
    }
```

I added this relation search, and it's working fine form the global search, it's searchable. but if i make this column Filter::inputText and try to search, the error throw that column not found. is there any solution to make this column also searchable from the filter?

Thanks

**Comment by gpedro** [comment]
i had the same problem. check my workaround #1076

**Comment by luanfreitasdev** [comment]
Filters work differently than global, you can try using builder method

https://v4.livewire-powergrid.com/table/column-filters.html#customize-query-collection-return
