### ISSUE TITLE
Pagination Issue with filtering

### ISSUE THREAD

**Issue by tangjh** [Power-Components/livewire-powergrid#108]
Table display "No records found" if filter has lesser page than the paginated page and there is no user friendly way to display record other than manually changing the page number in the url.

To reproduce:
1) Have a data set that has 20 records
2) set per page to 10
3) change to page 2
4) filter to less than 1 page

Desirable (suggest) result:
If after filter and the number of pages is less than the current paginated number, the logic should be smart enough to goto last page.

**Comment by luanfreitasdev** [comment]
Look great

Thanks for the contribution!

**Comment by luanfreitasdev** [comment]
Fixes: https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.4.1
