### ISSUE TITLE
[Bug]: Call to undefined method PowerComponents\LivewirePowerGrid\Column::makeInputDatePicker()

### ISSUE THREAD

**Issue by kahfieidn** [Power-Components/livewire-powergrid#1081]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1

### PowerGrid

4.4.1

### Laravel

9

### Livewire

2

### Alpine JS

3

### Theme

Tailwind 3.x

### Describe the bug.

Call to undefined method PowerComponents\LivewirePowerGrid\Column::makeInputDatePicker()

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Please see release notes

https://v4.livewire-powergrid.com/get-started/release-notes.html
