### ISSUE TITLE
[Bug]: Table features aren't working

### ISSUE THREAD

**Issue by Ashour-dev** [Power-Components/livewire-powergrid#1090]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Once the page is loaded there isn't anything but once I try to do any action like (Sort,export,ecc), I start getting errors.

### PHP Version

8.1

### PowerGrid

4.8

### Laravel

9.x

### Livewire

2.12

### Alpine JS

3.12.3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

Once the page is loaded there aren't any errors but once I try to do any action like (Sort,export,ecc), I start getting errors:

1. products:2560 Uncaught TypeError: Cannot read properties of undefined (reading 'hook')
   at HTMLDocument.<anonymous> (products:2560:31)

this error is referring to this piece of code:
`document.addEventListener('DOMContentLoaded', () => {
                this.livewire.hook('message.processed', () => {
                    Alpine.nextTick(() => {
                        window.dispatchEvent(
                            new CustomEvent('pg-livewire-request-finished')
                        );
                    })
                })`

2. Uncaught TypeError: Cannot read properties of undefined (reading 'find')
    at HTMLTableCellElement.<anonymous> (app.js:8350:29)

this error is referring to this piece of code:
`/*! For license information please see powergrid.js.LICENSE.txt */
(function () {
  var e,
      n = {
    7774: function _() {
      document.addEventListener("alpine:init", function () {
        window.Alpine.directive("multisort-shift-click", function (e, n) {
          var t = n.expression;
          e.addEventListener("click", function (e) {
            window.Livewire.find(t).set("multiSort", e.shiftKey);
          });
        });
      });
    },`
The error is exactly in this line : window.Livewire.find(t).set("multiSort", e.shiftKey);

It looks like something isn't connected properly on the js side, although i have followed all the documentation steps and checked via the page source that the Powergrid and the AlpineJS are present in the page throw the js.app file

### To Reproduce...

Clicking on any table button, as nothing actually works other than the data visualization.

### Extra information

```markdown
<?php
 //...
```

**Comment by Ashour-dev** [comment]
I've just tried the v3 on another branch and it's working as expected, so I suppose the problem is with the new version.

**Comment by Ashour-dev** [comment]
### I Found out the reason of the problem

This [part ](https://i.ibb.co/7VLZqcz/Screenshot-20230810-153751.png)is missing from the 4.x documentation, that's why the features weren't working. I suggest you add it so other developers don't encounter the same issue

**Comment by luanfreitasdev** [comment]
Hi @Ashour-dev, it's documented. It was intentional to remove the scripts and styles to force the developer to load via modules.

https://v4.livewire-powergrid.com/get-started/upgrade-guide.html#deprecations

**Comment by Ashour-dev** [comment]
@luanfreitasdev Well it isn't working without adding the scripts and styles manually in the template, once added every thing starts to work, otherwise, nothing works actually.
