### ISSUE TITLE
[Bug]: Date Filter using DateTime resulting in query error

### ISSUE THREAD

**Issue by racerguy** [Power-Components/livewire-powergrid#1092]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

4.8.6

### Theme

Tailwind 3.x

### Describe the bug.

When using Filter::datepicker, the component sets the filter as datetime in filters. Causing it to add an arbitrary time and changing dates due to timezone. It is not using the "date" filter which ignores time and timezone. 

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Thank you for reporting this bug and for opening the fix. It will be fixed in the next version.
