### ISSUE TITLE
[Bug]: showSoftDeletes() doesn't filter the trashed data

### ISSUE THREAD

**Issue by danielveselinov** [Power-Components/livewire-powergrid#1096]
### Theme

Tailwind 2.x

### Describe the bug.

![image](https://github.com/Power-Components/livewire-powergrid/assets/87199149/52ff819e-48f6-4864-98c7-6c9d3182daeb)
I do click the trash icon and try to filter the data, it doesn't work at all. It displays the info modal but the data remains unfiltered.

### To Reproduce...

Make the model using soft deletes, then try to include in the Header::showSoftDeletes(), and then try to filter..

### Extra information

```markdown
<?php
public function datasource(): Builder
    {
        return Order::query()
            ->withTrashed()
            ->latest('id');
    }
```

**Comment by danielveselinov** [comment]
@dansysanalyst @luanfreitasdev

**Comment by luanfreitasdev** [comment]
Thanks for reporting this bug. It will be corrected in the next release.
