### ISSUE TITLE
[Bug]: Package isn't compatible with the new livewire version

### ISSUE THREAD

**Issue by Ashour-dev** [Power-Components/livewire-powergrid#1100]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1

### PowerGrid

4.8

### Laravel

9.x

### Livewire

2.12

### Alpine JS

3.12.3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

![image](https://github.com/Power-Components/livewire-powergrid/assets/95831414/29b89b2e-7e90-49f1-bf46-a9ae50aca03f)

### Extra information

```markdown
<?php
 //...
```

**Comment by tahaRazaTalibi** [comment]
I'm desperately waiting for this compatibility issue to get resolved, since Laracon US.

**Comment by luanfreitasdev** [comment]
We already have a branch under development (5.x) and I'm also improving some things that are pending in v4. See also this discussion #1072

Remember that the project is open source and you can help by sending improvements or even sponsoring it. 
Thanks!
