### ISSUE TITLE
Livewire V3 Support

### ISSUE THREAD

**Issue by ethanpatchell** [Power-Components/livewire-powergrid#1104]
# ⚡ PowerGrid ⚡ Feature Request

## Summary

V3 Livewire Support - _**Any Timeline?**_

### Why is this needed?

Because V3 is much better than V2.

### Suggested Solution(s)

V3 Livewire Support

### Related issue(s)/PR(s)

Let us know if this is related to any issue/request

**Comment by luanfreitasdev** [comment]
We already have a branch under development (5.x) and I'm also improving some things that are pending in v4. See also this discussion #1072

Remember that the project is open source and you can help by sending improvements or even sponsoring it. 
Thanks!
