### ISSUE TITLE
[5.x][Bug]:  error dispatchEvent

### ISSUE THREAD

**Issue by CrazyBoy49z** [Power-Components/livewire-powergrid#1106]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

VM4504 lazy-a14f93b9.js:6 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hasOwnProperty')
    at Array.<anonymous> (VM4504 lazy-a14f93b9.js:6:16749)

### PHP Version

8.2

### PowerGrid

5.x

### Laravel

10

### Livewire

3

### Alpine JS

3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

error dispatchEvent

### To Reproduce...

run livewire button click when not use powergrid

### Extra information

```markdown
https://github.com/Power-Components/livewire-powergrid/blob/5.x/resources/js/components/index.js#L15-L31
```

**Comment by orbitur-helderneves** [comment]
Current build isn't prepared for livewire v3. Wait...

**Comment by luanfreitasdev** [comment]
@CrazyBoy49z . I don't understand the problem. Can you describe how to reproduce it?

**Comment by CrazyBoy49z** [comment]
> @CrazyBoy49z . I don't understand the problem. Can you describe how to reproduce it?

I think there is one idea how to fix it without major changes

**Comment by luanfreitasdev** [comment]
But how to get to this problem? I don't know that

**Comment by CrazyBoy49z** [comment]
> But how to get to this problem? I don't know that

I added you to the project

**Comment by CrazyBoy49z** [comment]
@luanfreitasdev works but need to rebuild NPM

**Comment by CrazyBoy49z** [comment]
It would also be cool to add a selection in the popup
