### ISSUE TITLE
[Bug]: Dropdown does not show in Bootstrap 5

### ISSUE THREAD

**Issue by bSushil** [Power-Components/livewire-powergrid#1110]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

4.4.1

### Laravel

9

### Livewire

2

### Theme

Bootstrap

### Describe the bug.

I implemented Bootstrap 5 theme for the component. The dropdown for export did not show. Upon checking I found that the dropdown div element had wrong css class.
`<div class="btn-group">...`

It should be the following:
`<div class="dropdown">....`

### To Reproduce...

1. Install the plugin
2. Select Bootstrap 5 theme
3. Create a demo table`php artisan powergrid:create`
4. Implement the table with `<livewire:users-table>`
5. Run thee view in the browser

### Extra information

```markdown
<?php
 //...
```

**Comment by bSushil** [comment]
Date field also does not show.

**Comment by bSushil** [comment]
Fixed this by adding supporting files.

**Comment by sharq-labs** [comment]
@bSushil 

How did you solve it

**Comment by bSushil** [comment]
@DeveloperKareemElsharkawy I switched to livewire version.
