### ISSUE TITLE
[Bug]: bulkAction store not updated, because x-on:click not triggered in checkbox-row

### ISSUE THREAD

**Issue by fakeheal** [Power-Components/livewire-powergrid#1116]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No.

### PHP Version

8.2.7

### PowerGrid

4.8.0

### Laravel

10.10.1

### Livewire

2.12.3

### Alpine JS

3.10.2

### Theme

Tailwind 3.x

### Describe the bug.

Based on the documentation `window.pgBulkActions.count('default')` should return the number of checkboxes selected (excluding the ones checked by "Check All"). However, that's not the case.

I haven't named my table, so `default` is the correct name. Not quite familiar with alpinejs, but [I found this issue on github](https://github.com/alpinejs/alpine/discussions/2777) (because alpinejs's docs didn't emphasise on this part enough for me to spot it 😅).

So, if I add `x-data` to the [label wrapping the checkbox](https://github.com/Power-Components/livewire-powergrid/blob/v4.8.0/resources/views/components/checkbox-row.blade.php#L31):

```html
<label class="{{ $theme->checkbox->labelClass }}" x-data="{}">
...
</label>
```

And then `x-data` to the button in the table's header (similar to the docs):

```php
return [
    Button::add('bulk-delete')
        ->caption('Bulk delete <span x-data="{}"><span x-text="window.pgBulkActions.count(\'default\')"></span></span>')

];
```

Then `window.pgBulkActions.count('default')` returns the correct number & also my "Bulk Delete" button gets updated properly.

**PS:** I am not sure if it's a bug or just lack of knowledge about both livewire & alpine. I spent more than 3 hours trying to figure out what I was doing wrong, but I couldn't find my mistake.

### To Reproduce...

Create a table, add checkboxes and check one of them. Open the browser's console and run `window.pgBulkActions.count('default')`.

### Extra information

```markdown
This feature was introduced in this PR: 
https://github.com/Power-Components/livewire-powergrid/pull/801
```

**Comment by luanfreitasdev** [comment]
Fixed. Thanks!

https://github.com/Power-Components/livewire-powergrid/releases/tag/v4.8.11
