### ISSUE TITLE
Pagination is too slow when the datasource is collection

### ISSUE THREAD

**Issue by muhammedshiffin** [Power-Components/livewire-powergrid#112]
Appreciate the effort behind putting together a package like this. Thank you.

I noticed the pagination is super slow with more than 8-10s of response time when the data source method is collection.

Am I missing something? Or is it a bug?

**Comment by luanfreitasdev** [comment]
Hi, thank you so much for using powergrid.

But I did some performance tests and apparently it's working fine. There may be something on your system that is interfering with or blocking requests.

If the data comes from a Model it's not as performant with the collection.

https://user-images.githubusercontent.com/33601626/140606571-6efb57fc-c4cd-4d76-8eed-24a1bc5d6bad.mp4

**Comment by muhammedshiffin** [comment]
Hmmm okay, am gonna try and figure out what might be going wrong.

I will update you soon.

Thanks

**Comment by tangjh** [comment]
I do notice it is browser related issue.  Check Microsoft Edge on MacOS.  It's super slow.

Chrome and Safari do not suffer from this.

**Comment by luanfreitasdev** [comment]
Okay, I'll keep it closed for now, as it seems to be a problem outside of Powergrid
