### ISSUE TITLE
[Bug - V5]: pagination and change of the showing rows on the page.

### ISSUE THREAD

**Issue by mohamedansari1** [Power-Components/livewire-powergrid#1128]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

livewire.js?id=11c49d7e:6401 Uncaught TypeError: Cannot read properties of null (reading 'nextSibling')
![image](https://github.com/Power-Components/livewire-powergrid/assets/75547941/d5c88bdf-4882-4ab2-9a80-4a47d354d855)

### PHP Version

8.1

### PowerGrid

5.0.0-beta.2

### Laravel

10.22

### Livewire

3.0.1

### Alpine JS

3.4.2

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

-The table pagination is not working.
- The table show per page is not working 

### To Reproduce...

both give the same console error 

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello! I could not reproduce this problem. How do I reproduce it? PowerGrid Demo is working with livewire version 3 as well.

https://demo.livewire-powergrid.com/

**Comment by mohamedansari1** [comment]
I created new project and got the same issue 
https://github.com/mohamedansari1/laravel10livewire3-pagination

**Comment by spetz83** [comment]
I am also receiving the same errors, but it isn't very consistent. Sometimes when I click a random page number in the rendered paginator it works. Other times the page does not re-render, and I get the same error as @mohamedansari1 in the chrome console:

![image](https://github.com/Power-Components/livewire-powergrid/assets/291664/749d597b-907e-4a33-a9ec-72804510ebf3)

Trying to change the per page number consistently throws this error.

Should note, URL does update when clicking the different pagination related elements. Refreshing the page respects the URL changes for page number and what not.

**Comment by luanfreitasdev** [comment]
It's related to that https://github.com/livewire/livewire/discussions/6674. But the error doesn't happen if I set `inject_morph_markers` to false.

**Comment by luanfreitasdev** [comment]
may also be related

https://github.com/livewire/livewire/pull/6671

**Comment by mohamedansari1** [comment]
i tired to set `inject_morph_markers` to false and `legacy_model_binding` to true and still facing the same problem

**Comment by luanfreitasdev** [comment]
Here it worked with both combinations, try running php artisan optimize:clear

**Comment by mohamedansari1** [comment]
`'inject_morph_markers' => false,`  + `php artisan optimize:clear` 
this solved it for me in both projects ... Thanks a lot

**Comment by luanfreitasdev** [comment]
Following the [discussion](https://github.com/livewire/livewire/discussions/6674#discussioncomment-6922837
), I managed to solve the problem by adding more wire:key

https://github.com/Power-Components/livewire-powergrid/commit/c2f1da1bad6405102b5f4986bc04c0bbb91f3503
