### ISSUE TITLE
Livewire\Component and HasAttributes

### ISSUE THREAD

**Issue by diegoprovesi** [Power-Components/livewire-powergrid#1135]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1.4

### PowerGrid

4.9

### Laravel

10.22.1

### Livewire

3.0.2

### Alpine JS

3.13.0

### Theme

Bootstrap

### Describe the bug.

I have this error, how can I fix it?

Livewire\Component and Illuminate\Database\Eloquent\Concerns\HasAttributes define the same property ($attributes) in the composition of PowerComponents\LivewirePowerGrid\PowerGridComponent. However, the definition differs and is considered incompatible. Class was composed

**Comment by luanfreitasdev** [comment]
Hi, version 4 is not possible to install with Livewire v3. Install using version ^5.0.

https://v5.livewire-powergrid.com/get-started/

**Comment by diegoprovesi** [comment]
Perfect, I did the installation, everything went fine, but when running the project this happens:

Target class [PowerComponents\LivewirePowerGrid\Helpers\ActionRules] does not exist.

I noticed that some folders were not installed when compared to the demo provided.

**Comment by luanfreitasdev** [comment]
Using v5 ?

**Comment by diegoprovesi** [comment]
Yes

**Comment by luanfreitasdev** [comment]
You have to republish the vendor if you have one, clear the cache

```bash
php artisan vendor:publish --tag=livewire-powergrid-views --force && php artisan optimize:clear
```
