### ISSUE TITLE
Hide action buttons when the button use render method

### ISSUE THREAD

**Issue by DavidCide** [Power-Components/livewire-powergrid#1138]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1

### PowerGrid

5.0

### Laravel

10.22

### Livewire

3.0.2

### Alpine JS

3.13

### Theme

Tailwind 3.x

### Describe the bug.

I use the WireUI library in my project and so I use the render method as shown in the example, to use the button component that the library gives me. 

Now, while migrating from version 4 to version 5 I noticed that the buttons I create using the render method do not hide when the condition is met, but if I create the button without the render method it works. 

With version 4 of PowerGrid it worked fine.

### To Reproduce...

This is how i try to hide the buttons:

 ```php
   /**
     * PowerGrid Connection Action Buttons.
     *
     * @return array<int, Button>
     */
    public function actions(): array
    {
        return [
            Button::add('retry')
                ->render(function (ServiceLog $serviceLog) {

                    return Blade::render(<<<HTML
                        <x-button primary icon="refresh" wire:click="\$dispatch('retryServiceLog', {serviceLogId: $serviceLog->id})" />
                    HTML);
                }),
            Button::add('info')
                ->render(function (ServiceLog $serviceLog) {
                    return Blade::render(<<<HTML
                        <x-button primary icon="eye" wire:click="\$dispatch('showLogInfo', {serviceLogId: $serviceLog->id})" />
                    HTML);
                }),
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | Actions Rules
    |--------------------------------------------------------------------------
    | Enable the method below to configure Rules for your Table and Action Buttons.
    |
    */

    /**
     * PowerGrid Connection Action Rules.
     *
     * @return array<int, RuleActions>
     */
    public function actionRules(): array
    {
        return [
            Rule::button('retry')
                ->when(fn ($connection) => $connection->retry == null)
                ->hide(),
            Rule::button('info')
                ->when(fn ($connection) => $connection->log_info == null)
                ->hide(),
        ];
    }
```

**Comment by luanfreitasdev** [comment]
Thank you for report this bug
