### ISSUE TITLE
Undefined property: stdClass::$ on PowerGrid::addColumn() when trying to manipulate data on Closure

### ISSUE THREAD

**Issue by BoGnY** [Power-Components/livewire-powergrid#1139]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Undefined property: stdClass::$ (View: C:\www\ccii\vendor\power-components\livewire-powergrid\resources\views\components\row.blade.php)

### PHP Version

8.1.21

### PowerGrid

5.0.0

### Laravel

10.22.0

### Livewire

3.0.2

### Alpine JS

3.12.3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

The manipulation data `PowerGrid::columns()->addColumn(string $field, \Closure $closure = null);` return exception `Undefined property: stdClass::$`

I don't have problem with manipulation data if I return a Eloquent builder or a Query builder on datasource, but I'm trying this approach because my Model has 190 fields, and loading only 5 Model (on a db with total 12 Model) take 12 seconds..

With this approach seems I have reduced it to 3 seconds, and I think is preferrable because I need only ID and date fields on this datatable....

I'm doing something wrongs or is a bug?

### To Reproduce...

I've this datatable:

```php
// BalanceDatatable
public function datasource(): \Illuminate\Support\Collection
{
    return DB::table('balances')->where('user_id', Auth::user()->id)->whereNull('company_id')->orderByDesc('date')->get(['id', 'date']);
}

public function addColumns(): \PowerComponents\LivewirePowerGrid\PowerGridColumns
{
    return PowerGrid::columns()
        ->addColumn('id')
        ->addColumn('date_formatted', function ($balance) {
            var_dump(e($balance->date)); // This print correctly the date saved on db with format 'Y-m-d'
            return Carbon::parse(e($balance->date))->format('d/m/Y'); // Every return here, even a simple string '31/12/2023', return exception
        });
}

public function columns(): array
{
    return [
        Column::make('ID', 'id'),
        Column::make('Date', 'date_formatted', 'date'),
        Column::action('Action'),
    ];
}
 ```

Balance model has `'id'`, `'date'` and 187 fields unnecessary here.

**Comment by luanfreitasdev** [comment]
Hello!.

When you use Collection in the datasource this can happen, I don't understand it is possible that this does not happen if you remove ->get(['id', ...]) and return a QueryBuilder instead of Collection. Can you test it?

```php
public function datasource(): \Illuminate\Database\Query\Builder
{
    return DB::table('balances')->where('user_id', Auth::user()->id)->whereNull('company_id');
   // remove orderByDesc and get();
}
```

**Comment by brianlucaslima** [comment]
![image](https://github.com/Power-Components/livewire-powergrid/assets/23401274/da5482de-581d-46e3-a9c9-1ad44976c934)

Boa noite Luan, tudo bem?
Estou com o mesmo problema ao tentar exibir os actions buttons, quando no meu datasource fornece um array 

"power-components/livewire-powergrid": "^v5.0.0"
"livewire/livewire": "^3.0",

**Comment by BoGnY** [comment]
[**@luanfreitasdev**](https://github.com/luanfreitasdev) commented on [Sep 12, 2023, 6:22 PM GMT+2](https://github.com/Power-Components/livewire-powergrid/issues/1139#issuecomment-1716041463 "2023-09-12T16:22:50Z - Replied by Github Reply Comments"):
> Hello!.
> 
> When you use Collection in the datasource this can happen, I don't understand it is possible that this does not happen if you remove ->get(\['id', ...\]) and return a QueryBuilder instead of Collection. Can you test it?
> 
> ```html
> public function datasource(): \Illuminate\Database\Query\Builder
> {
>     return DB::table('balances')->where('user_id', Auth::user()->id)->whereNull('company_id');
>    // remove orderByDesc and get();
> }
> ```

I don't have problem with Builder, but loading ~190 fields when I need only 2 fields means losing many many seconds for loading only 5 rows (imagine with hundreds of rows)...
Extracting only `'id'` and `'date'` with `select(['id', 'date'])` which return a Builder instance is not possible because accessor and mutators on models cause exception because missing fields :(

**Comment by luanfreitasdev** [comment]
Adding select to the call doesn't work?

```php   
 return DB::table('balances')->select(['id', 'date'])->where('user_id', Auth::user()->id)->whereNull('company_id');
```

**Comment by luanfreitasdev** [comment]
Fixed. Can you test again ?

**Comment by BoGnY** [comment]
[**@luanfreitasdev**](https://github.com/luanfreitasdev) commented on [Sep 14, 2023, 12:05 AM GMT+2](https://github.com/Power-Components/livewire-powergrid/issues/1139#issuecomment-1718377396 "2023-09-13T22:05:30Z - Replied by Github Reply Comments"):
> Fixed. Can you test again ?

That's **AMAZING**!!!

Loading datasource is now ~1 second instead previously ~12 seconds 👍🏻
