### ISSUE TITLE
hi, im trying to get the action btns to show on the table, any ideas?

### ISSUE THREAD

**Issue by mkts02** [Power-Components/livewire-powergrid#1142]
Hi, im desperately trying to get the action buttons visible, did i skip some steps?

      Public function setUp(): array
    {
        $this->showCheckBox();

        return [
            Responsive::make()
            ->fixedColumns('rut', 'name', Responsive::ACTIONS_COLUMN_NAME),
            Exportable::make('export')
                ->striped()
                ->type(Exportable::TYPE_XLS, Exportable::TYPE_CSV),
            Header::make()->showSearchInput(),
            Footer::make()
                ->showPerPage()
                ->showRecordCount(),
        ];
    }

    public function datasource(): Builder
    {
        return Company::query();
    }

    public function relationSearch(): array
    {
        return [];
    }

    public function addColumns(): PowerGridColumns
    {
        return PowerGrid::columns()
            ->addColumn('rut')

           /** Example of custom column using a closure **/
            ->addColumn('rut_lower', fn (Company $model) => strtolower(e($model->rut)))

            ->addColumn('name')
            ->addColumn('phone')
            ->addColumn('created_at_formatted', fn (Company $model) => Carbon::parse($model->created_at)->format('d/m/Y H:i:s'));
    }

    public function columns(): array
    {
        return [
            Column::make('Rut', 'rut')
                ->sortable()
                ->searchable(),

                Column::make('Name', 'name')
                ->sortable()
                ->searchable(),

            Column::make('Phone', 'phone')
                ->sortable()
                ->searchable(),

            Column::make('Created at', 'created_at_formatted', 'created_at')
                ->sortable(),

        ];
    }

    public function filters(): array
    {
        return [
            Filter::inputText('rut')->operators(['contains']),
            Filter::inputText('name')->operators(['contains']),
            Filter::inputText('phone')->operators(['contains']),
            Filter::inputText('address')->operators(['contains']),
            Filter::datetimepicker('created_at'),
        ];
    }

    #[\Livewire\Attributes\On('edit')]
    public function edit($rowId): void
    {
        $this->js('alert('.$rowId.')');
    }

    public function actions(\App\Models\Company $row): array
    {
        return [
            Button::add('edit')
                ->slot('Edit: '.$row->id)
                ->id()
                ->class('pg-btn-white dark:ring-pg-primary-600 dark:border-pg-primary-600 dark:hover:bg-pg-primary-700 dark:ring-offset-pg-primary-800 dark:text-pg-primary-300 dark:bg-pg-primary-700')
                ->dispatch('edit', ['rowId' => $row->id]),
        ];
    }

    
    public function actionRules($row): array
    {
       return [
            // Hide button edit for ID 1
            Rule::button('edit')
                ->when(fn($row) => $row->id === 1)
                ->hide(),
        ];
    }

_Originally posted by @mkts02 in https://github.com/Power-Components/livewire-powergrid/discussions/1141_

**Comment by hitaloramon** [comment]
same problem here, the table action buttons are not appearing in v5

**Comment by davem1012** [comment]
tengo el mismo problema

**Comment by luanfreitasdev** [comment]
I think I already found the problem. In version 4 the actions were automatically mounted.

In version 5, for this to happen, we have to declare `Column::action('Action')`.

This is missing from the doc. Can you test this, please? Could someone send a pull request for the doc?

**Comment by mkts02** [comment]
it works, thanks!!

**Comment by luanfreitasdev** [comment]
I will send a fix to the stubs and a validation if there are actions

**Comment by davem1012** [comment]
Me funciono lo siguiente tambien

`Column::make('nameColum', '')`

cual es lo correcto?

**Comment by luanfreitasdev** [comment]
The best way to control this will be using Column::action

**Comment by luanfreitasdev** [comment]
Tip: 

![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/635b9da7-ce18-4bba-988c-71129cfd911b)

![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/cfcda09a-3042-49a4-a0ae-af5cb2ae0c96)
