### ISSUE TITLE
Outside filters toggle always open

### ISSUE THREAD

**Issue by luanfreitasdev** [Power-Components/livewire-powergrid#1146]
### Discussed in https://github.com/Power-Components/livewire-powergrid/discussions/1145

<div type='discussions-op-text'>

<sup>Originally posted by **mkts02** September 14, 2023</sup>
Hi, i wanted to know if i can have the outside filters toggle Always open from the start.
Thanks.</div>

**Comment by luanfreitasdev** [comment]
This needs to be added to the documentation.

```php
final class FiltersOutsideTable extends PowerGridComponent
{
     public bool $showFilters = true;
     //

```

**Comment by mkts02** [comment]
thanks, it works 👍

**Comment by dansysanalyst** [comment]
Added to the doc: https://livewire-powergrid.com/get-started/configure.html#filters
