### ISSUE TITLE
Demo export tab breaking

### ISSUE THREAD

**Issue by danichurras** [Power-Components/livewire-powergrid#1149]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### Theme

Tailwind 3.x

### Describe the bug.

![image](https://github.com/Power-Components/livewire-powergrid/assets/55005033/f7e414cd-a25b-431c-9bfb-83fbb51f2166)

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Thank you!. Fixed
