### ISSUE TITLE
DatePicker filter lose text value

### ISSUE THREAD

**Issue by jamesRUS52** [Power-Components/livewire-powergrid#1151]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

5

### Laravel

10

### Livewire

3

### Theme

Bootstrap

### Describe the bug.

DatePicker filter lose text in its field when datasource changed.

### To Reproduce...

select date rage in filter
if content of table is changed after applying that filter, the filter lose text representation in its filter field (now it empty)
if content of table is not changed after applying that filter, the filter has text representation in its filter field (not deleted)

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Can you give more details?

**Comment by jamesRUS52** [comment]
[video](https://www.veed.io/view/2ca1f9c6-e929-40f7-bc9f-f661f85a2182?panel=share)

1. three rows in a table
2. select from 13 to 14 of Sep . In this filter only one row and content of table changed before 3 rows and after 1 row. filter disappear
3. select from 13 to 15 of Sep . In this filter only one row too and content of table not changed before 1 row and after 1 row. filter is shown
4. select from 13 to 16 of Sep . In this filter two rows and content of table changed before 1 rows and after 2 row. filter is disappear again

**Comment by luanfreitasdev** [comment]
Thank you for fix this bug

Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.0.6

**Comment by jamesRUS52** [comment]
> Thank you for fix this bug
> 
> Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.0.6

it is not related to mentioned issues
it is another bug, but I can't find why it happens

please reopen this issue

**Comment by luanfreitasdev** [comment]
Have you checked if this problem also occurred with the tailwind?
Is it a selected behavior problem? How do you generate SQL when selecting dates?

**Comment by jamesRUS52** [comment]
> Have you checked if this problem also occurred with the tailwind?

Sorry, I don't use tailwind,  can't check.

> Is it a selected behavior problem? 

The data after applying filter is correct, this is only a UI bug

> How do you generate SQL when selecting dates?

simple eloquent query

**Comment by muhammadessam** [comment]
Did you find any solution to this ? 
The datepicker text disappear after selecting the date range
@jamesRUS52 
@luanfreitasdev

**Comment by luanfreitasdev** [comment]
@jamesRUS52 , @muhammadessam. I was able to persist the dates in this format. I don't understand the reason, but wire:ignore didn't work properly.

I plan to submit a pull request.

![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/54785352-3ee6-45f6-8ecd-437f5a050afa)
