### ISSUE TITLE
Cannot find module 'tailwindcss' while using bootstrap5 theme

### ISSUE THREAD

**Issue by killallskywalker** [Power-Components/livewire-powergrid#1161]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes , we got this error 
![Screenshot 2023-09-19 at 9 50 51 AM (2)](https://github.com/Power-Components/livewire-powergrid/assets/19742186/8ac82956-1976-4657-8728-49b30cf4813c)

### PHP Version

8.2.9 

### PowerGrid

v4.8.6 

### Laravel

v9.52.5 

### Livewire

v2.12.3

### Alpine JS

3.12.3

### Theme

Bootstrap

### Describe the bug.

Install like normal , using bootstrap5 theme . Change the theme in livewire-powergrid.php config . 
Run npm run dev , and it will throw an error 
`Loading PostCSS "tailwindcss" plugin failed: Cannot find module 'tailwindcss'`

### To Reproduce...

Install powergrid with bootstrap5

**Comment by luanfreitasdev** [comment]
You need to install tailwind and the necessary dependencies. Just switching between settings will not change the theme.

**Comment by allgood** [comment]
@luanfreitasdev 

I'm having the same problem... please explain to me... is tailwind needed even if I'm using bootstrap? All my project is using bootstrap. 

Would't have any conflict between tailwind and bootstrap if I include both on my app?
