### ISSUE TITLE
Action Rules is being applied to all buttons

### ISSUE THREAD

**Issue by hitaloramon** [Power-Components/livewire-powergrid#1166]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.9

### PowerGrid

5.1.0

### Laravel

10.24.0

### Livewire

3.0.5

### Theme

Tailwind 3.x

### Describe the bug.

When I have more than one button and I have rules for them, the rules are being applied to all buttons

![image](https://i.imgur.com/2K9DDgZ.jpeg)

### To Reproduce...

```php 
public function actions(Dish $dish): array
    {
        return [
            Button::add('edit')
                ->slot('edit'),
            
                Button::add('destroy')
                ->slot('Destroy'),
        ];
    }

    public function actionRules(): array
    {
        return [
            Rule::button('edit')
                ->when(fn ($dish) => $dish->id == 2)
                ->setAttribute('class', 'bg-green-200'),

            Rule::button('destroy')
                ->when(fn ($dish) => $dish->id == 2)
                ->slot('Delete #1'),
        ];
    }
 ```

**Comment by luanfreitasdev** [comment]
Thanks for looking into this issue! A bug fix is coming up.

**Comment by luanfreitasdev** [comment]
Fixed
