### ISSUE TITLE
Enhancement: Emit event on successful cell button action

### ISSUE THREAD

**Issue by woodspire** [Power-Components/livewire-powergrid#117]
**Enhancement**

Since there is no discussion section, I am creating this here.

After viewing this [video,](https://www.youtube.com/watch?v=Qj0GLZJzDLY) I am opening this enhancement.

Add a method to emit an event for a successful Cell Action Button.
Cancelling a button action should revert back to what the table was, so no emit is required.
This way, we can refresh the table when a value changed.

And maybe a shortcut called "refreshOnSuccess" could be added that would do it automatically.

This way, if we change a value in a cell refreshing might change the position of the row depending on chosen sorting.

**Comment by dansysanalyst** [comment]
Hi @woodspire, 

Just to mention that the issue on the video was fixed in [v1.40](https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.4.0).

**Comment by woodspire** [comment]
Ok. I see that when we finish editing a cell, we see the result in the read-only cell and if we re-edit again, we see the newly edited value.

But what about sort order ? Sorting by name ASC and changing the first entry from "Albert" to "Zenon" should bring that row down, even on other pages, no ? Is it already working this way ?

**Comment by luanfreitasdev** [comment]
Hello @woodspire , it currently keeps it in the same order, but there is a very simple way out for this, for example:

```php
public function update(array $data): bool
{      
     try {
         // update 

         $updated = true;
     } catch (QueryException $exception) {
         $updated = false;
     }

     if ($updated) (
        $this->fillData(); // This method renders the data again.
     }

     return $updated;
}
```

> If you want to respect ordering, remember this:

```php
    public string $sortField = 'name';

```

**Comment by woodspire** [comment]
Nice. Thanks.
