### ISSUE TITLE
Field information disappears when saving

### ISSUE THREAD

**Issue by marcosrnuness** [Power-Components/livewire-powergrid#1171]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.2

### PowerGrid

5.1.0

### Laravel

10.24.0

### Livewire

3.0.5

### Alpine JS

3.13.0

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When you enable edit on click, when you edit the content and save it, if you click again on the same record the content disappears, you need to refresh the page to reappear the record.

### To Reproduce...

Click on the record, edit the content and press enter to save, then click on the record again and then the content disappears.

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello! Can you check if this is still happening? I recently fixed some things in editOnClick
