### ISSUE TITLE
Column not found in online demo

### ISSUE THREAD

**Issue by gabrielrbarbosa** [Power-Components/livewire-powergrid#1172]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Theme

Tailwind 3.x

### Describe the bug.

Full error report: https://flareapp.io/share/omwpo8WP

### To Reproduce...

Try to order column 'Chef' from any page in https://demo.livewire-powergrid.com/

**Comment by cirrion-software** [comment]
Identical problem to [marcosrnuness](https://github.com/marcosrnuness)

Column is made as:
`   Column::make('Name', 'name')->editOnClick(true, 'name', null, true),`

Then the onUpdatedEditable function

`public function onUpdatedEditable($id, $field, $value): void
    {
        $this->validate();

        MaintenanceTeam::query()->find($id)->update([
            $field => $value,
        ]);

        $this->fillData();
    }`

**Comment by luanfreitasdev** [comment]
Hello. I fixed the demo.

Thanks!
