### ISSUE TITLE
Column collapsing and normal render without html and bootstrap 4 export buttons are not showing

### ISSUE THREAD

**Issue by rashmiranjanrrs** [Power-Components/livewire-powergrid#118]
**Describe the bug**
Please check the below screenshots. 
Column collapsing and normal render without html and bootstrap 4 export buttons are not shoing
* ..

**To Reproduce**
* Got to ..

**Laravel version (exactly):**
* 8.x.x ?
 
**Alpine version:**
* 3.x.x ?

**Theme:**
- [ ] Tailwind 
   - Version:        
      
- [ ] Bootstrap
   - Version:        

**Screenshots** (***This helps to understand better***)

![ice_screenshot_20211109-002443](https://user-images.githubusercontent.com/54047909/140801289-f55a80e3-4604-484a-bbe0-79225b6a3457.png)
![ice_screenshot_20211109-002457](https://user-images.githubusercontent.com/54047909/140801294-320a3d79-6c20-4158-885a-2f25d5787d9d.png)

**Do you have any idea how we can fix it?**

**Comment by devsquad-luan-freitas** [comment]
Hello. 

We haven't done any tests with bootstrap 4 but I suppose some html tag closure is missing from the class

In the case of export options, it must be some class not supported by bs4

**Comment by luanfreitasdev** [comment]
Hello.

We haven't done any tests with bootstrap 4 but I suppose some html tag closure is missing from the class

In the case of export options, it must be some class not supported by bs4

**Comment by dansysanalyst** [comment]
If some records contain unclosed tags,  a good try could be to strip tags:

```php
->addColumn('example_column', function (Model $model) {
   return strip_tags( $model->example_column );
})
```

**Comment by rashmiranjanrrs** [comment]
Thank you so much @dansysanalyst it solved the issue. Is there any way to show export buttons !!

**Comment by luanfreitasdev** [comment]
@rashmiranjanrrs , 

In the case of export options, it must be some class not supported by bootstrap4
