### ISSUE TITLE
Dropdown  Select Filter Not Working

### ISSUE THREAD

**Issue by sharq-labs** [Power-Components/livewire-powergrid#1193]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.0.1

### PowerGrid

2.2

### Laravel

9

### Livewire

2

### Alpine JS

3

### Theme

Bootstrap

### Describe the bug.

i have filter for categories model that have many children as relation when i try to filter by childs to get main category that contatin sub category i get empty but when i select the main category from dopdown list i get the same category i have sected 

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
public function datasource(): ?Builder
    {
        return Category::query()->whereNull('parent_id')->with('childCategories');
    }

    public function relationSearch(): array
    {
        return [
            'childCategories' => [
                'parent_id',
                'name_ar',
                'name_en'
            ]
        ];
    }


       ->addColumn('child_categories', function (Category $model) {
                $mobileList = '';
                foreach($model->childCategories as $childCategory) {
                    $mobileList .= "<span class='tag badge-gradient-secondary'>" . $childCategory->name_ar . " </span> ";

                }

                return $mobileList;
            })


            Column::add()
                ->title(trans('admin/datatable.sub_categories'))
                ->field('child_categories')
                ->sortable()
                ->searchable()
                ->headerAttribute('datatable-header-txt', '')
                ->bodyAttribute('datatable-body-txt', '')
                ->makeInputSelect(Category::all(), 'name_ar'),
```

**Comment by luanfreitasdev** [comment]
Hello!. I cannot identify this problem in version 2. I recommend updating the package to version 4, as this may have been corrected over time
