### ISSUE TITLE
Bootstrap 5 theme don't have a export option

### ISSUE THREAD

**Issue by madushanj** [Power-Components/livewire-powergrid#120]
**Describe the bug**

* When I am using Bootstrap 5.1, and it don't show me export to CVS button. But if I change the CSS theme to Tailwind in the config file **without changing any other details**, export button suddenly appear.

**Laravel version (exactly):**
* 8.6.5
 
**Alpine version:**
* 3.5.1

**Theme:**
- [ ] Tailwind 
   - Version:        
      
- [ ] Bootstrap
   - Version: 5.1.3

**Screenshots** (***This helps to understand better***)

With the bootstrap 5

![bb](https://user-images.githubusercontent.com/33152355/141416850-2ad7d1ae-9d53-42f8-9286-e73ddce78523.png)

With Tailwind CSS

![tt](https://user-images.githubusercontent.com/33152355/141416875-845c3e4b-97a7-447f-b893-c7a7865ed0d3.png)

**Do you have any idea how we can fix it?**
No Idea

**Comment by luanfreitasdev** [comment]
Thanks for reporting this bug,

Fixed in [v1.4.6](https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.4.6)

**Comment by madushanj** [comment]
Thanks.

**Comment by AiFxApp** [comment]
Hi, please help... 
The export button is present but not clickable (no dropdown options appear) 
![image](https://user-images.githubusercontent.com/89227642/154650109-cd1fd3a3-7a93-4f23-92c1-51202e0a37d0.png)

**Comment by AiFxApp** [comment]
When i change over to tailwinds I get the export function.. when I change back to bootstrap 5 the export button is there but the dropdown option is missing. -- Please help

**Comment by luanfreitasdev** [comment]
Hello, it's very strange, both bootstrap 5 and tailwind 2 and 3 are working, what are your versions of Alpinejs and bootstrap ?

Have you watched the demo?

https://github.com/Power-Components/powergrid-demo
