### ISSUE TITLE
saveOnMouseOut property is not working while using with editOnClick

### ISSUE THREAD

**Issue by vickybml** [Power-Components/livewire-powergrid#1204]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### PHP Version

8.2.10

### PowerGrid

5.1.5

### Laravel

10.28.0

### Livewire

3.0.7

### Theme

Tailwind 3.x

### Describe the bug.

using editOnClick to edit a field in power grid but after editing when mouse is clicked outside the cell, its not calling onUpdatedEditable method to update the data. We have already Set the required property: saveOnMouseOut: true

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
    Column::make('First name', 'first_name')
          ->sortable()
          ->editOnClick(hasPermission: true, fallback: '', saveOnMouseOut: true)
           ->searchable(),

    public function onUpdatedEditable($id, $field, $value): void
    {
        $k=$id;
        ReadyUser::query()->find($id)->update([
            $field => $value,
        ]);
    }
```

**Comment by luanfreitasdev** [comment]
Hello!, as you defined fallback as empty, this can cause this type of problem. Try leaving it as '`null`' or some specific value.

**Comment by vickybml** [comment]
Hi @luanfreitasdev

Its working on pressing **ENTER** button after editing the field, but its not working when i click mouse outside the field. Even though **saveOnMouseOut** is **TRUE**.

I tired as you said leaving it as 'null' or giving specific value but it didn't worked. 

Thanks for the support.

**Comment by luanfreitasdev** [comment]
Did you try this? It worked for me. Are there console errors?

```php
 ->editOnClick(hasPermission: true, saveOnMouseOut: true)
```

**Comment by Saba9900** [comment]
Hi everyone, 
i have the same problem on laravel 10.39.0 and powergrid 5.1.18.
I tried the two solution proposed but the save is launched only with key "Enter" have any suggestion?
