### ISSUE TITLE
Bootstrap 5 Toggle Columns not working

### ISSUE THREAD

**Issue by madushanj** [Power-Components/livewire-powergrid#121]
When I am using the Bootstrap 5 as the theme, with the ->showToggleColumns() option, a toggle button appear. but when I click on a Colum name to toggle the visibility, it won't toggle. But if I change the theme to Tailwind in the config file and the refresh the page, then Tailwind toggle button does work just fine. 
![t](https://user-images.githubusercontent.com/33152355/141436342-c202f811-eb0b-4edf-97e0-e9345306c06a.png)

Bootstrap version: 5.1.3

**Comment by luanfreitasdev** [comment]
Hi!

Can you give more details? Are there any errors in the console?

**Comment by madushanj** [comment]
Yes, I am getting error related to bootstrap-select.
![Untitled](https://user-images.githubusercontent.com/33152355/141646013-e291984e-ec0d-4e48-86ad-8d6f98eaf6ba.png)

I even tried to change the bootstrap-select cdn links to jsdelivr (as they mention in the github repo) instead cloudflare in the config file, but it didn't work. same error.

**Comment by madushanj** [comment]
I just removed and reinstalled the PowerGrid package, so v1.4.6 somehow fixed this issue. Now it's working. I was on v1.4.5.
