### ISSUE TITLE
Tailwind.css file not created in dist

### ISSUE THREAD

**Issue by corey-Robinson1337** [Power-Components/livewire-powergrid#1212]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1.23

### PowerGrid

5.1.4

### Laravel

10.25.2

### Livewire

3.0.5

### Alpine JS

3.13.2

### Theme

Tailwind 3.x

### Describe the bug.

Followed the install instructions

```
import './../../vendor/power-components/livewire-powergrid/dist/powergrid'
 
// If you use Tailwind 
import './../../vendor/power-components/livewire-powergrid/dist/tailwind.css'

// If you use Bootstrap 5 
import './../../vendor/power-components/livewire-powergrid/dist/bootstrap5.css'
```

yet these files are not present when installing.

![image](https://github.com/Power-Components/livewire-powergrid/assets/65130426/48489569-a291-4e97-b6ec-67b984a7578b)

### To Reproduce...

install version 5 .1.4 and see there are no tailwind or bootstrap css files present in dist

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello!, the documentation always follows the latest version of the package. This update was from 5.1.5. Please update your project.

Thanks!

https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.1.5
