### ISSUE TITLE
Number Filter not working with "TableName.Column" syntax

### ISSUE THREAD

**Issue by racerguy** [Power-Components/livewire-powergrid#1214]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### Theme

Tailwind 3.x

### Describe the bug.

![image](https://github.com/Power-Components/livewire-powergrid/assets/64607188/de9214ff-c55f-4843-8372-dcc63277cd79)

### To Reproduce...

have a tableName.Column value for Field in number filter

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Please specify versions

**Comment by racerguy** [comment]
PowerGrid
4.9.6

Laravel
10.28

Livewire
2

**Comment by ai123ia** [comment]
https://livewire-powergrid.com/table/column-filters.html#customize-query-collection-return

**Comment by luanfreitasdev** [comment]
I believe this has been fixed. If it persists, you can reopen the issue
