### ISSUE TITLE
Error: Uninitialized string offset 0 on DatePicker component

### ISSUE THREAD

**Issue by maatien** [Power-Components/livewire-powergrid#1217]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### PHP Version

8.2.10

### PowerGrid

5.1.6

### Laravel

10.28

### Livewire

3.0.10

### Alpine JS

3.13.2

### Theme

Tailwind 3.x, Tailwind 3.x with tailwind/forms

### Describe the bug.

The `PowerComponents\LivewirePowerGrid\Components\Filters\Builders\DatePicker` method `builder(EloquentBuilder|QueryBuilder $builder, string $field, int|array|string|null $values)` is not correctly handling the `$values` type.

On line 14, there is direct array access on `$values` without checking the attribute type. This should be easily fixed by adding a similar type check as in `PowerComponents\LivewirePowerGrid\Components\Filters\Builders\DateTimePicker`:

```php
        if (gettype($values) !== 'array') {
            return;
        }

```

### To Reproduce...

I was only able to produce this error by manually triggering a date picker change via a header button event:

```php
    Button::add('showToday')
        ->slot('Show only today entries')
        ->dispatch('showToday', []),
```

```php
    public function onShowToday(): void
    {
        $this->datePickerChanged(
            [
                now()->startOfDay()->toJSON(),
                now()->endOfDay()->toJSON(),
            ],
            'created_at',
            now()->toDateString(),
            'Show only today entries',
            'datetime',
            config('app.timezone')
        );
    }
```

After removing the custom datetime filter by click on the filter label, the mentioned error occurs on the next `$refresh` event.

### Extra information

```markdown
The same behaviour may occur on the `collection()` method, as there is also no type check.
```

**Comment by luanfreitasdev** [comment]
Fixed 

https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.1.7
