### ISSUE TITLE
Duplicate number of elements to display in table icon

### ISSUE THREAD

**Issue by EmilioVar** [Power-Components/livewire-powergrid#1225]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

No

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

[screenshot](https://ibb.co/vXHDpL4)

### PHP Version

8.2.9

### PowerGrid

5.1

### Laravel

10.10

### Livewire

3

### Theme

Tailwind 3.x

### Describe the bug.

It appears that the arrow icon on the button is duplicated to allow increasing the number of elements available in the table

### To Reproduce...

Displayed when creating the table

### Extra information

```markdown
The file causing this phenomenon is located in the following path:

/power-components/livewire-powergrid/resources/views/components/frameworks/tailwind/footer.blade.php

To fix it, I removed the element that was repeating

<div
                        class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-pg-primary-700 dark:text-pg-primary-300">
                        <x-livewire-powergrid::icons.down class="w-4 h-4" />
                    </div>


After that, the element is now displayed correctly.

Thank you very much for developing this fantastic tool! Many successes
```

**Comment by luanfreitasdev** [comment]
Hello! This was done on purpose and this only happens if you are not using the "class" strategy in tailwind plugins

```js
    plugins: [
        require("@tailwindcss/forms")({
            strategy: 'class',
        }),
    ]
```

See more: https://livewire-powergrid.com/get-started/configure.html#tailwind-forms

**Comment by MGeurts** [comment]
Ok. I did not notice this in the documentation.
For me, using the 'class' strategy on tailwind forms solves the problem in livewire-powergrid mentioned above but forces me to also adapt all other form components used in my project. That's not worth the pain.

**Comment by luanfreitasdev** [comment]
You can use custom pagination

https://livewire-powergrid.com/table/features-setup.html#pagination
