### ISSUE TITLE
Does not show validation errors

### ISSUE THREAD

**Issue by EmilioVar** [Power-Components/livewire-powergrid#1227]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### PHP Version

8.2.9

### PowerGrid

5.1

### Laravel

10.10

### Livewire

3

### Theme

Tailwind 3.x

### Describe the bug.

Validation errors are not shown when editing the element in the row itself

### To Reproduce...

first: click on the name field of the user table.
second: I edit the name, adding 2 characters when the minimum is 6.
third: pressing enter returns it to its previous state, without showing any message

### Extra information

```markdown
It seems that the error is located in the editable.blade.php file, in the following path:

/Users/emiliovargasmillan/bCall/basic/vendor/power-components/livewire-powergrid/resources/views/components/editable.blade.php

To solve it, I have replaced the $showErrorBag variable, which is responsible for validating if there are errors, with $errors, which is the generic one for livewire.

After that, it shows me the validation errors correctly.

The fragment would look like this:

@if ($errors)
        @error($field . '.' . $row->{$primaryKey})
            <div class="text-sm text-red-800 p-1 transition-all duration-200">
                {{ str($message)->replace($field . '.' . $row->{$primaryKey}, $field) }}
            </div>
        @enderror
    @endif
```

**Comment by luanfreitasdev** [comment]
Look!, That was on purpose. To show errors, you should add showErrorBag to true in the component. If you do, will it work normally?

Thanks.

**Comment by EmilioVar** [comment]
> Look!, That was on purpose. To show errors, you should add showErrorBag to true in the component. If you do, will it work normally?
> 
> Thanks.

I just declared the $showErrorBag variable to true in the component logic and now the validation message works correctly.

It would be good to comment on this point in the documentation, when talking about the "onUpdatedEditable" method, because it drove me crazy 😂.

Thank you very much for the help!
