### ISSUE TITLE
Error enabling Responsive tables with Bootstrap5

### ISSUE THREAD

**Issue by chil360** [Power-Components/livewire-powergrid#1240]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.4

### PowerGrid

5.1.9

### Laravel

10.28.0

### Livewire

3.0.10

### Alpine JS

3.13.2

### Theme

Bootstrap

### Describe the bug.

Atfer enabling the Responsive feature in a PowerGrid component, I see the following Laravel error message:

'View [components.frameworks.bootstrap5.toggle-detail-responsive] not found.'

### To Reproduce...

Add Responsive::make() to the setUp method.

**Comment by luanfreitasdev** [comment]
Hi, there is currently no defined support for Responsive in bootstrap. But feel free to send a pull request and it will be appreciated. 🙂
