### ISSUE TITLE
Items per page 

### ISSUE THREAD

**Issue by nafea107** [Power-Components/livewire-powergrid#1250]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

No

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### Theme

Tailwind 3.x

### Describe the bug.

When i am on any page then change items per page, it doesn't set page number 1 as the current page.
this makes errors as if you are in the latest page then change the number of items per page to 100 item per page you will get empty table. 

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hi, I don't understand the problem. Can you record a video or some screenshots?

**Comment by luanfreitasdev** [comment]
Hello! Has this already been resolved? I'm closing this issue. We can reopen if necessary
