### ISSUE TITLE
Weird effect where using Flowbite

### ISSUE THREAD

**Issue by jantbox** [Power-Components/livewire-powergrid#1252]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1

### PowerGrid

Latest

### Laravel

Latest

### Livewire

Latest

### Alpine JS

Latest

### Theme

Tailwind 3.x

### Describe the bug.

There is a weird effect when using dark mode with Flowbite components...
<img width="1568" alt="Captura de pantalla 2023-11-11 a las 16 59 00" src="https://github.com/Power-Components/livewire-powergrid/assets/27139162/42988695-db07-470e-99fd-52fc61540f4a">

### To Reproduce...

Default Laravel project
Default Flowbite install
Default Livewire Powergrid install

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello, unfortunately there is no native support for Flowbite, but you can easily customize it as long as it is Tailwind or Bootstrap. 

https://livewire-powergrid.com/table/custom-theme.html#custom-theme
