### ISSUE TITLE
Add Filters page to the menu in the documentation

### ISSUE THREAD

**Issue by tinusg** [Power-Components/livewire-powergrid#1256]
# ⚡ PowerGrid ⚡ Feature Request

## Summary

There is a Filters page, it's just not in the menu:
https://livewire-powergrid.com/table/column-filters.html

### Why is this needed?

People can't find it. I could only find it using the Search function.

**Comment by luanfreitasdev** [comment]
Done. Thank you!

![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/911992ab-b7f6-42ff-b198-7a068bbe910f)
