### ISSUE TITLE
The pagination is slow 

### ISSUE THREAD

**Issue by rizerzero** [Power-Components/livewire-powergrid#1258]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1

### PowerGrid

I used the demo repository 

### Laravel
9

### Describe the bug.

Hi, 
First of all, thank you for the work you're doing on the project, from a design perspective it's awesome and I wanted so much to use but ended up using another livewire data table project because the interface is slow, the pagination takes 5 seconds to change, I installed an instance locally and tested the demo online with chrome and safari on mac os, even on windows, the interface is just slow.
This a feedback I wanted to leave here as a contribution to make the open-source software better. 
Thank you!

**Comment by luanfreitasdev** [comment]
Hello! We appreciate the feedback, however performance depends on several factors to be analyzed, such as payload size and machine processing

**Comment by rizerzero** [comment]
@luanfreitasdev Sure you're right, it depends on the payload size, I compared it being aware of that, and as I said I compared it to other livewire-based data grid solutions, on the same machine. So I can't tell why, but it's clearly slower according to my tests.

**Comment by luanfreitasdev** [comment]
Can you share the test? If you want to send it by email, it will be very carefully considered.

**Comment by rizerzero** [comment]
Sorry, I did not keep any data, If I do the tests again, I will certainly post them.

**Comment by luanfreitasdev** [comment]
I placed a page with 50 items and the duration was on average 200-220ms

![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/39f9dcb3-70d3-464f-93e6-8163bcfda0e2)

**Comment by rizerzero** [comment]
This is very interesting,
He is what I get on your demo website, not much data there but it takes way longer than what you have and I compared it to other solutions on the same browsers (chrome, opera) it's the same. 

<img width="1583" alt="image" src="https://github.com/Power-Components/livewire-powergrid/assets/1518379/e3c19b13-0b5f-405b-bd4c-8123642c39e8">

<img width="1584" alt="image" src="https://github.com/Power-Components/livewire-powergrid/assets/1518379/2e14f503-9239-45a9-8564-2a66eb6ccdeb">

Compared to this other livewire-based solution, where I get around 200ms.
<img width="1584" alt="image" src="https://github.com/Power-Components/livewire-powergrid/assets/1518379/27f195b1-f95e-43c8-8d56-97823afa4172">

I noticed that in your demo table that has 13 entries, we get 40 to 80KB (I guess they use gzip) which should not justify the latency.

**Comment by luanfreitasdev** [comment]
Unfortunately, the demo server is very weak.  🙂

**Comment by rizerzero** [comment]
Well, I installed it locally from the demo repository and I noticed the same thing. I might try again

**Comment by rizerzero** [comment]
Same test using the demo repository installed locally on a core i5 9th gen 16Go of RAM pc, the same amount of data, I still get around 1.5 s for each request.

**Comment by JoaoPedroDiasMonteiro** [comment]
Hello @rizerzero !

I've downloaded the demo project on my computer using windows with WSL, and these are the results:

![image](https://github.com/Power-Components/livewire-powergrid/assets/56093063/4e6cad88-3757-49b8-b9cf-1f05f1835d4d)

With limiting the WSL to 2gb
![image](https://github.com/Power-Components/livewire-powergrid/assets/56093063/17af78fa-afbe-4acf-b8b9-0103444628e9)

**Comment by rizerzero** [comment]
Thankyou @JoaoPedroDiasMonteiro, I'll try again the demo if it's updated with the latest version of Laravel
