### ISSUE TITLE
Using editOnClick feature of inline editing, The column editor is showing 'adasda' as placeholder.

### ISSUE THREAD

**Issue by xX-MISSIT-Xx** [Power-Components/livewire-powergrid#1262]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1

### PowerGrid

5.1.13

### Laravel

10.10

### Livewire

3.2.1

### Alpine JS

3.4.2

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

Using editOnClick feature of inline editing, The column editor is showing 'adasda' as placeholder.

### Extra information

```markdown
I have found the error. It is in the blades but in the pg-editable.js "vendor/power-components/livewire-powergrid/resources/js/components/pg-editable.js"

"adasda" is permanently entered there.
```

**Comment by luanfreitasdev** [comment]
Will be fixed in the next release

https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.1.14
