### ISSUE TITLE
search problem when joining multiple tables

### ISSUE THREAD

**Issue by qhanm** [Power-Components/livewire-powergrid#129]
**Describe the bug**
![image](https://user-images.githubusercontent.com/44798292/141711888-84d2dbec-2bbb-4c97-a1e7-230a910e2102.png)

![image](https://user-images.githubusercontent.com/44798292/141711463-5b116eae-ec70-4313-96db-1a11caa02e5e.png)

when i search with field "fb.name" how to declare in function columns

**Laravel version (exactly):**
* 8.65
 
**Alpine version:**
* "power-components/livewire-powergrid": "^1.4"    

Thank for help me

**Comment by nausif111** [comment]
In my case I have a table **human_resources** and **centres**, where one HR belongs to one centre, so I need to search on centre name which comes from centres table, so I used below modification to make it work:

```
return HumanResource::query()
                                ->join(DB::raw('
                                    (SELECT id as centre_id, name as centre_name, alpha_code as centre_alpha_code, parent_id
                                    FROM centres) as centre
                                '), function ($join) {
                                    $join->on('human_resources.center_id', '=', 'centre.centre_id');
                                })
                                ->select('human_resources.*','centre.centre_name');
```

And then I add below line in columns function

`Column::add()->title('Centre')->field('centre_name')->makeInputText()`

**Comment by snapey** [comment]
See also #111  Not resolved although @luanfreitasdev believes it is.

**Comment by luanfreitasdev** [comment]
These are different problems, #111 says solve the **sortable** problem while this one is about advanced search with joins.

Maybe you'll need to put a `$table` variable inside the searchable so you don't get lost.

**Comment by snapey** [comment]
@luanfreitasdev Its a problem because you reverted the previous table prefix.  There is still a problem with sorting also, so for now, I abandoned using the project

**Comment by luanfreitasdev** [comment]
Prefix doesn't cause problem with join ?

**Comment by luanfreitasdev** [comment]
I uploaded some changes directly to main, which works with a prefix with the table name. The problem with the previous prefix is that in the back state when **sortable** is clicked, it would no longer recognize it, and the state started like this:

`$table = 'dishes';`
I clicked on sortable ('categories.name')

The component was understand like this:
`$table = 'categories.name' `(but categories is not the main one in the component).

So to solve this, I removed the round trip data from the component when the table name is the same, allowing no more table not found.

Prefix resolves table duplication.

**This change does not fix advanced filters, only component initialization and ordering**

_Remember that this project is not funded but open-source. Everyone can collaborate with him to make him better in every way.,_

**Comment by luanfreitasdev** [comment]
I just upload advanced search support with join in inputText, dataPicker and boolean filter.

Example that worked (both in searches and sorting):
```
Column::add()
                 ->title(__('Dish'))
                 ->field('dishes.name')
                 ->searchable()
                 ->editOnClick($canEdit)
                 ->makeInputText('name')
                 ->sortable('dishes.name'),

Column::add()
                 ->title(__('Created Categories'))
                 ->sortable('categories.created_at')
                 ->field('created_at_formatted')
                 ->makeInputDatePicker('categories.created_at'),
```

**Comment by luanfreitasdev** [comment]
I'm waiting for confirmation if it worked @snapey , @qhanm

**Comment by luanfreitasdev** [comment]
Hi, I made some more improvements and I just uploaded improvements.

**Comment by qhanm** [comment]
it doesn't work, when i search by "fb.name as name" field the sql sentence is rendered incorrect, the correct query should be "fb.name like %test%"
![image](https://user-images.githubusercontent.com/44798292/141880781-223ae638-11dd-42d1-a50b-416f1b15f9ab.png)
@luanfreitasdev

**Comment by luanfreitasdev** [comment]
Did you just install the last commit from main ?

**Comment by luanfreitasdev** [comment]
field('name') has to be field('fb.name') to work

**Comment by qhanm** [comment]
yes i just installed the latest livewire-powergrid

**Comment by luanfreitasdev** [comment]
dev-main ? You also have to fix the field('fb.name')

**Comment by luanfreitasdev** [comment]
There's no way your code is with the dev-main, as my last commit prefixes the column.

You need to install the package by passing the `dev-main`

**Comment by qhanm** [comment]
![image](https://user-images.githubusercontent.com/44798292/141886338-b235323f-6bf0-4b2f-9322-e6eb59fdd2cb.png)
I think it's because in the query count total record the field name is not found due to "select count(*) aggre"

**Comment by luanfreitasdev** [comment]
You need to do two things;

1. composer require power-compoments/livewire-powergrid dev-main
2. Change the field('name') method to field('fb.name')

That done. The name column will become fb.name

**Comment by qhanm** [comment]
oh sorry, since i haven't cleared cache composer, i just updated to the latest and it worked.
thanks for your help
My problem has been resolved so I'm closing this discussion
Thanks.

**Comment by qhanm** [comment]
> You need to do two things;
> 
> 1. composer require power-compoments/livewire-powergrid dev-main
> 2. Change the field('name') method to field('fb.name')
> 
> That done. The name column will become fb.name

**Comment by luanfreitasdev** [comment]
Thanks

**Comment by nazrul-dev** [comment]
```
   public function datasource(): Builder
    {
        return Models::query()
            ->join('tb_card', 'tb_transaction.card_id', '=', 'tb_card.card_id')
            ->select('tb_transaction.*', 'tb_card.masking_card_no as mask');
    }

 Column::add()->title('masking card no')
                ->field('masking_card_no')
                ->searchable()
                ->makeInputText('masking_card_no'),
```
