### ISSUE TITLE
doctrine/dbal Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by pablomadariaga** [Power-Components/livewire-powergrid#1291]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.9

### PowerGrid

5.1.16

### Laravel

10.37.1

### Livewire

3.3.0

### Theme

Tailwind 3.x, Tailwind 3.x with tailwind/forms

### Describe the bug.

Your requirements could not be resolved to an installable set of packages.

![image](https://github.com/Power-Components/livewire-powergrid/assets/69119357/79629c1e-9d6c-41b4-a2f2-17e437f9cc98)

### To Reproduce...

composer require power-components/livewire-powergrid

### Extra information

```markdown
<?php
 //...
```

**Comment by mshahrestani** [comment]
Same problem with the same configs

**Comment by luanfreitasdev** [comment]
Please run: `composer require power-components/livewire-powergrid -W`
