### ISSUE TITLE
When a button is hidden, it shows a blank space.

### ISSUE THREAD

**Issue by albrandariz** [Power-Components/livewire-powergrid#1294]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1

### PowerGrid

5.1.16

### Laravel

10

### Livewire

3.0.1

### Theme

Tailwind 3.x

### Describe the bug.

When a button is hidden, it shows a blank space.

By having the hidden buttons as a div element (even if they are null), they generate a space for the .pg-actions class

components/row.blade.php
```
<div class="pg-actions">
           <!-- Render Action -->
            @if (filled(data_get($row, 'actions')) && $column->isAction)
                @foreach (data_get($row, 'actions') as $key => $action)
                        <div wire:key="action-{{ $row->id }}-{{ $key }}">
                            {!! $action !!}
                        </div>
                @endforeach
            @endif
 </div>
```

### To Reproduce...

Create three buttons in the Action column and hide the middle one with rule()

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello, can you show an example? Do you have any idea how to resolve this?

**Comment by albrandariz** [comment]
Of course, since the button returns a Null Action when is ->hide(), it would be easy not to draw them if they contain a Null value.

Screenshots:
￼￼


my correction proposal in vendor/livewire-powergrid/components/row.blade..php:

 <div class="pg-actions">
   
   @if (filled(data_get($row, 'actions')) && $column->isAction)
      @foreach (data_get($row, 'actions') as $key => $action)
         @if ($action != null)
             <div wire:key="action-{{ $row->id }}-{{ $key }}">
               {!! $action !!}
              </div>
          @endif
       @endforeach
    @endif
</div>
