### ISSUE TITLE
latests updates on 5.x branch

### ISSUE THREAD

**Issue by edwinheij** [Power-Components/livewire-powergrid#1299]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### Theme

Bootstrap

### Describe the bug.

Tried to PR a JS update for TomSelect. Pulled the latest 5.x. After that searching was broken. For example when trying to search on 2 (text)fields only one (the first) was queried.
Think the last commits where you are updating the filters when wrong.
Hope you've got something about this issue.

### To Reproduce...

Thank you for this wonderful package.

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hi, can you give more details?

The version that worked, the version that didn't work. How are you using the feature?

**Comment by edwinheij** [comment]
Will create a repo for you.

**Comment by edwinheij** [comment]
Here's the repo which I made for you: https://github.com/edwinheij/livewire-powergrid-fail
- user2-table is failing (this one is from the database)
- user-table is working fine (from collection)

Repo install instructions:
```
git clone git@github.com:edwinheij/livewire-powergrid-fail.git
cd livewire-powergrid-fail
touch database/database.sqlite
php artisan migrate --seed
```
start website and filter both 'name' and 'email' from the first table. Only the first filter works.

**Comment by luanfreitasdev** [comment]
Thank you!

Fixed.  I will add some more tests

![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/22996df3-cacc-4873-a251-0e990b0a9c04)

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/pull/1301

**Comment by luanfreitasdev** [comment]
Fixed
