### ISSUE TITLE
Rowspan, Colspan and child row

### ISSUE THREAD

**Issue by abanghendri** [Power-Components/livewire-powergrid#130]
Hello, how to do rowspan, colspan or child row 
I cannot find it in documentation

thanks

**Comment by luanfreitasdev** [comment]
Hi. Could you give an example?

**Comment by luanfreitasdev** [comment]
If you can give a usage example of how to handle this in the backend and how to display it in the front it will be easier to introduce in powergrid. For now I'm closing because it's still not possible and so simple.
