### ISSUE TITLE
Show record count not show at Bootstrap5 theme

### ISSUE THREAD

**Issue by ryanhatuala** [Power-Components/livewire-powergrid#131]
**Describe the bug**
Thanks for the amazing work to create livewire-powregrid package.
I want to show record count at the bottom table with bootstrap5 theme but not showing properly.
I have add `->showRecordCount('full')` at the `setUp()` function.

Thanks Luan.

**Laravel version (exactly):**
* 8.54 ?
 
**Alpine version:**
* 3.x.x 

**Theme:**
- Bootstrap
   - Version:  5.0

**Comment by luanfreitasdev** [comment]
Hello!. Unfortunately the package does not support display options for bootstrap5. I will correct the documentation

But if you want to send a PR to make this happen it would be great!
