### ISSUE TITLE
Multiple Action Button is showing bellow not inline

### ISSUE THREAD

**Issue by luanfreitasdev** [Power-Components/livewire-powergrid#1316]
### Discussed in https://github.com/Power-Components/livewire-powergrid/discussions/1307

<div type='discussions-op-text'>

<sup>Originally posted by **nafiur** December 21, 2023</sup>
Multiple Action Button is showing bellow not inline

![image](https://github.com/Power-Components/livewire-powergrid/assets/4471794/4c582ff0-243b-498a-a06d-d01b64e115a7)
![Screenshot_16](https://github.com/Power-Components/livewire-powergrid/assets/4471794/d32a8b22-51dd-4d3b-a1d2-ba9f9f73caac)

Bootstrap Theme. How to solve this pls help me
</div>

**Comment by marineusde** [comment]
I use the bootstrap theme but cant reproduce it:

```
<?php

namespace App\Livewire\Test;

use Illuminate\Database\Eloquent\Model;
use PowerComponents\LivewirePowerGrid\Button;
use PowerComponents\LivewirePowerGrid\Column;
use PowerComponents\LivewirePowerGrid\PowerGridComponent;

final class TestTable extends PowerGridComponent
{
    public function datasource()
    {
        return Model::query()
            ->whereIn('id', [1, 2]);
    }

    public function columns(): array
    {
        return [
            Column::make('ID', 'id')
                ->sortable(),

            Column::make('Name', 'name')
                ->sortable(),

            Column::action('Action')
        ];
    }

    public function actions($row): array
    {
        return [
            Button::add('edit')
                ->slot('Edit')
                ->dispatch('postAdded', ['key' => $row['id']]),
            Button::add('delete')
                ->slot('Delete')
                ->dispatch('postDeleted', ['key' => $row['id']]),
        ];
    }
}
```

![Bildschirmfoto vom 2024-01-12 09-18-05](https://github.com/Power-Components/livewire-powergrid/assets/105713989/102f904c-232d-4383-b2a5-94d6828fe0fd)

The css-class is correct with "d-flex":

![Bildschirmfoto vom 2024-01-12 09-18-54](https://github.com/Power-Components/livewire-powergrid/assets/105713989/97782dbc-f62d-4e64-8022-4d6602277948)
