### ISSUE TITLE
OpenModal with PowerGrid in Tailwind & Alpine

### ISSUE THREAD

**Issue by abbasmashaddy72** [Power-Components/livewire-powergrid#132]
**Describe the bug**

[App\Http\Livewire\DeleteModal] does not implement [LivewireUI\Modal\Contracts\ModalComponent] interface.

**To Reproduce**
Used you Demo project to implement it in my project but something got missing
& also followed the [Open Model Docs](https://livewire-powergrid.docsforge.com/main/row-action-buttons/#openmodalstring-component-array-params)

**Laravel version (exactly):**
* 8.65 ?
 
**Alpine version:**
* 3.0.6 ?

**Theme:**
- [ ] Tailwind 
   - Version: 2.2.2
      
- [ ] Bootstrap
   - Version: none

**Screenshots** (***This helps to understand better***)
Unfortunately, I reverted it back as I was not able to fix it

**Do you have any idea how we can fix it?**
No

**Comment by abbasmashaddy72** [comment]
I got  it fixed by implementing the ModalComponent in DeleteModal livewire controller, but unfortunately I am getting this error now

Method App\Http\Livewire\DeleteModal::closeModalOnClickAway does not exist.

**Comment by luanfreitasdev** [comment]
Hi, I won't be able to tell you because it seems that the problem is in the modal component. 

Please have a look at this: closeModalOnClickAway at https://github.com/wire-elements/modal

**Comment by abbasmashaddy72** [comment]
Thanks

**Comment by luanfreitasdev** [comment]
If you can give feedback on the solution.

**Comment by abbasmashaddy72** [comment]
I was implementing the model component wrongly in livewire controller, I should have to extend it not implement it.

So, was able to fix it.

The Answer was from wire-elements/modal   ##community

you can reffer the [Issue](https://github.com/wire-elements/modal/issues/114) on there repo

**Comment by muhammedshiffin** [comment]
for some reason, I cannot close the modal once it is open.
Anything I am missing?
am using the modal in a TALL Stack application.

**Comment by muhammedshiffin** [comment]
> for some reason, I cannot close the modal once it is open. Anything I am missing? am using the modal in a TALL Stack application.

Resolved,
It was just the alpine js version I had, upgraded and everything works like a charm.
