### ISSUE TITLE
Problem with filter in Laravel 10.40

### ISSUE THREAD

**Issue by marineusde** [Power-Components/livewire-powergrid#1321]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

htmlspecialchars(): Argument #1 ($string) must be of type string, array given

### PHP Version

8.2.7

### PowerGrid

5.1.18

### Laravel

10.40

### Livewire

3.3.5

### Theme

Bootstrap

### Describe the bug.

Upgrade laravel/laravel 10.39 to 10.40 with composer

### To Reproduce...

Just insert a filter in the table:

```
public function filters(): array
{
    return [
        Filter::boolean('is_active', $this->tableName . '.is_active')
            ->label('Ja', 'Nein')
    ];
}
```

### Extra information

```markdown
Don't know if its a problem in the powergrid project, maybe just an information to others :)
```

**Comment by edwinheij** [comment]
confirmed

I tried to use:
```
{{  (new \Illuminate\View\ComponentAttributeBag($defaultAttributes['inputAttributes']))->toHtml() }}
```
That solved the error, but won't filter anymore (JS error)

**Comment by marineusde** [comment]
I fixed it in the file "components/frameworks/bootstrap5/filters/input-text.blade.php" replacing:

```
{{ $defaultAttributes['inputAttributes'] }}
```

with:

```
@foreach ($defaultAttributes['inputAttributes'] as $key => $value)
   {{ $key }}="{!! $value !!}"
@endforeach
```

edit: or maybe better with the code of @edwinheij replaced with "{!! !!}" instead of "{{ }}":

```
{!! (new \Illuminate\View\ComponentAttributeBag($defaultAttributes['inputAttributes']))->toHtml() !!}
```

The filter works, but I dont know if its the right way. If @luanfreitasdev say its ok, I can do a merge request and replace it in all filter-blade-files tomorrow.

**Comment by luanfreitasdev** [comment]
Hello!. This breaks in Laravel 10.40, but this version has been removed from Laravel releases, let's wait

![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/53d0aa31-5fc0-4b36-9af0-a574562cb55b)

---

![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/40f3ac56-e853-4cb0-a470-67a7de3184ad)

**Comment by luanfreitasdev** [comment]
https://github.com/laravel/framework/pull/49524

**Comment by JhonArroyo** [comment]
**Class "OpenSpout\Writer\XLSX\Options" not found.**
![issue](https://github.com/Power-Components/livewire-powergrid/assets/58745151/a08b28d8-400b-4b5b-aee2-3964e17188ee)

**Comment by shakeel2717** [comment]
Hi, i'm also facing this issue, i'm still trying to fixing it since yesterday, then after spend lot's of time, i figured out,that when i use filter, i got this error
htmlspecialchars(): Argument #1 ($string) must be of type string, array given

but when i comment all filters, then the table worked perfectly,, but without filter table is not valueable

is there any permanent solution you found, please share it with me.

Thank you so much

**Comment by marineusde** [comment]
> Hi, i'm also facing this issue, i'm still trying to fixing it since yesterday, then after spend lot's of time, i figured out,that when i use filter, i got this error htmlspecialchars(): Argument #1 ($string) must be of type string, array given
> 
> but when i comment all filters, then the table worked perfectly,, but without filter table is not valueable
> 
> is there any permanent solution you found, please share it with me.
> 
> Thank you so much

@luanfreitasdev removed the "buggy feature" in laravel 10.40 and its merged into the main branch already. :+1:  We have to wait if Laravel 10.41 will be released and use laravel 10.39 now.

**Comment by luanfreitasdev** [comment]
Probably the best solution would be to return the Laravel version to lower than 10.39 and wait for the version > 10.40 that fixes this problem

**Comment by shakeel2717** [comment]
> Probably the best solution would be to return the Laravel version to lower than 10.39 and wait for the version > 10.40 that fixes this problem

Thank you So Much, it's worked now.. Thank you SO Much <3

**Comment by marineusde** [comment]
Laravel 10.41 is released and the bug is fixed :+1:

**Comment by edwinheij** [comment]
> Laravel 10.41 is released and the bug is fixed 👍

Thanks for the tip. Missed the release.
