### ISSUE TITLE
Attempt to read property "field" on array

### ISSUE THREAD

**Issue by edwinheij** [Power-Components/livewire-powergrid#1334]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.14

### PowerGrid

5.2.2

### Laravel

10.39.0

### Livewire

3.3.5

### Theme

Bootstrap

### Describe the bug.

When toggling column I got an error: ```Attempt to read property "field" on array```
With initial load the ```$column``` var is of type ```PowerComponents\LivewirePowerGrid\Column``` but after the de-selecting a column the type changed to ```array```.
Should we change the templates to the ```data_get```-method or has it something to do with hydrate from Livewire?

### To Reproduce...

Just deselect a column from a grid

### Extra information

```markdown
No extra info
```

**Comment by luanfreitasdev** [comment]
Can you show more about the error?

**Comment by edwinheij** [comment]
Just click one of the following options from the column listing:
<img width="209" alt="image" src="https://github.com/Power-Components/livewire-powergrid/assets/1799101/43cf1f2a-6fff-461e-a64f-c4a5eda78bd6">

Here's a (clean) repo where it's failing:
https://github.com/edwinheij/livewire-powergrid-fail

Error thrown:
https://flareapp.io/share/LPl9QqD7

**Comment by luanfreitasdev** [comment]
Thank you
