### ISSUE TITLE
First click for toggling a column after page load isn't working

### ISSUE THREAD

**Issue by edwinheij** [Power-Components/livewire-powergrid#1339]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.14

### PowerGrid

5.2.2

### Laravel

10.41

### Livewire

3.3.5

### Alpine JS

3.13.3

### Theme

Bootstrap

### Describe the bug.

First click for toggling a column after page load isn't working; following click are working! Network XHR request is the same. Couldn't find so quickly where this is trugling, I guess somewhere around here:
![image](https://github.com/Power-Components/livewire-powergrid/assets/1799101/62b133c2-55ed-4ae1-a3b5-f0e7abd7cfc8)
(@ ```PowerGridComponent.php```)

Hope you can find it.

### To Reproduce...

Let the page load, open column toggle popup and select a column. Network request is send but the is no DOM update. Second time you click, things a doing like it supposed to do.

### Extra information

```markdown
Nothing here...
```

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.3.3

Can you confirm, please?

**Comment by edwinheij** [comment]
bit late here. I'm sorry.
Tried to install the newest version and also version 5.3.3, but my filters are gone. Has to investigate why (I'm using my own templates what gives me some problems with new versions).
