### ISSUE TITLE
Since updating the package, I have Tailwind css errors

### ISSUE THREAD

**Issue by philozofer** [Power-Components/livewire-powergrid#1359]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes, here is the error :

![image](https://github.com/Power-Components/livewire-powergrid/assets/9042494/afb1ebd5-6245-4473-ad05-d08796272008)

I have tried rewriting the code with an array based but afterwards there is another class that has the same kind of error of property  attempted to being read on array.

### PHP Version

8.3.1

### PowerGrid

5.3.2

### Laravel

10.10

### Livewire

3.2

### Alpine JS

3.4.2

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

I simply updated my project over the weekend, and since then when I go on a page with a livewire-powegrid table, I get these errors with Tailwind from the published files. Seems a theme related issue.

### To Reproduce...

I simply updated my package and it started doing that. I have tried removing/purging the package and complete full install and it still produces the problem.

### Extra information
Also after each changes, I ran :
php artisan optmize:clear
php artisan optmize
composer dump-autoload

to no avail.

**Comment by hipoagencia** [comment]
Facing the same problem!

**Comment by luanfreitasdev** [comment]
Hello!, did you republish the views and run php artisan optimze:clear ?

**Comment by hipoagencia** [comment]
> Hello!, did you republish the views and run php artisan optimze:clear ?

I was writing this right now! Just delete the powergrid resources.
Thanks for your time

**Comment by dansysanalyst** [comment]
Added to the doc: 
https://livewire-powergrid.com/get-started/troubleshooting.html
