### ISSUE TITLE
Set `pageName` per component

### ISSUE THREAD

**Issue by dansysanalyst** [Power-Components/livewire-powergrid#1363]
### Discussed in https://github.com/Power-Components/livewire-powergrid/discussions/1358

---

Currently, is it is not possible to set the `pageName` per component. The page name from a PowerGrid can collide with another pagination using `?page=` and will collide if the user has two components in the same page.

Solutions for this question will likely generate breaking changes. 

---

<div type='discussions-op-text'>

<sup>Originally posted by **SpeedyInternet** January 29, 2024</sup>
Greetings, I am using PowerGrid but I have a conflict with the page, when I am on page 2 or 3 PowerGrid takes the value of the "page" variable from the url and affects the page page of the table.
How can I disable pagination? Or configure it so that it doesn't take the "page" variable from the url.

I appreciate your valuable help please.
![Screenshot_1](https://github.com/Power-Components/livewire-powergrid/assets/139509539/ea976706-6574-4615-8468-1cb620526752)

</div>

**Comment by luanfreitasdev** [comment]
Done in https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.3.3
