### ISSUE TITLE
Toggle columns feature doesn't work

### ISSUE THREAD

**Issue by NikoAuso** [Power-Components/livewire-powergrid#1368]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

5.3.2

### Laravel

10.43

### Livewire

3.4.4

### Alpine JS

3.12.2

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When the button to select the column you want to hide is clicked, the loading spinner appears but nothing happens. Furthermore, I noticed that the same problem is present in the demo.

**Comment by luanfreitasdev** [comment]
Done in https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.3.3
