### ISSUE TITLE
Clearing out filters causing 500 error

### ISSUE THREAD

**Issue by caiochami** [Power-Components/livewire-powergrid#1388]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.15

### PowerGrid

5.3.6

### Laravel

10.43.0

### Livewire

3.4.4

### Theme

Tailwind 3.x

### Describe the bug.

After applying a filter to a enumSelect input field, if you click the filter badge to clear it out, a 500 error is thrown.

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/7e768c0d-2958-47ca-875c-622dc03faacf)

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/57eed2e3-a5f3-4f6a-8961-b54225377140)

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/f040b9c9-4658-401b-9c47-89d0b1e5793d)

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/3fb4a51a-c78f-46da-98f5-7df86de5df5d)

### To Reproduce...

You need to define a filter that looks like this:

Filter::enumSelect('status', 'clients.status')
                ->dataSource(AvailabilityStatus::cases())
                ->optionLabel('clients.status')

The issue here is the 'clients.status' param in the enumSelect() method. It works if you remove the dots from it.

Success: 
Filter::enumSelect('status', 'status')
                ->dataSource(AvailabilityStatus::cases())
                ->optionLabel('clients.status')

**Comment by luanfreitasdev** [comment]
Hello @caiochami

Should the current release be related to this issue?

Thanks

**Comment by caiochami** [comment]
Yes. It's been resolved. Thank you
