### ISSUE TITLE
Uncaught ReferenceError: pgFlatPickr is not defined   

### ISSUE THREAD

**Issue by ndarproj** [Power-Components/livewire-powergrid#1398]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes

![image](https://github.com/Power-Components/livewire-powergrid/assets/66521458/03fa5478-9119-4b1a-8ba8-84e7f6f043a9)

### PHP Version

8.1

### PowerGrid

3.7.8

### Laravel

10.0

### Livewire

2.12

### Alpine JS

3.11.1

### Theme

Tailwind 3.x

### Describe the bug.

  all filters are working fine except for period filters
        
            Column::make('STARTED AT', 'started_at_formatted', 'started_at')
                ->searchable()
                ->sortable()
                ->makeInputDatePicker('started_at'),

### To Reproduce...

create a new column with make input date picker

### Extra information

I have tried adding cdn at my layout & install the package and add them to app.js & app css but it didnt work so i removed them.

tried this solution window.pgFlatPickr and the error is gone but the period filter doesnt open.
https://github.com/Power-Components/livewire-powergrid/issues/961#issuecomment-1763695450

i already remove wire ui and still same issue
```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello! This bug has probably been fixed or has been resolved in some issue/discussion. Please take a look at the documentation or update to the latest version so we can help you.

https://github.com/Power-Components/powergrid-doc/tree/3x/docs/get-started
