### ISSUE TITLE
I am feeling the package is not safe for production each time i do composer update some kind of error occour

### ISSUE THREAD

**Issue by nrngajurel5** [Power-Components/livewire-powergrid#1414]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1

### PowerGrid

^5.0

### Laravel

^10.10

### Livewire

^3.0

### Theme

Bootstrap

### Describe the bug.

I am feeling the package is not safe for production each time i do composer update some kind of error occour i have to customize the design in my project so I export its view and do some customization it perfectly works
and push to production when i do composer update after few day it gives another error 

before composer update
![image](https://github.com/Power-Components/livewire-powergrid/assets/117053404/4529fbe1-2779-4582-8d3a-eed52c2aeae1)

after composer udpate
![image](https://github.com/Power-Components/livewire-powergrid/assets/117053404/e69bd121-af2b-4ad8-95c9-1607adfc62f3)

when i remove my custom behavior nothing works even default filter is not working 

![image](https://github.com/Power-Components/livewire-powergrid/assets/117053404/376d8041-3b5f-4f3e-b9fc-0105070758f3)

please dont do major breaking change in each minor version 
please

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello! Even in minor versions, views can fail, resulting in refactoring due to backend backlash.

The changes may be related to changes in the views, if you published and changed the behavior of the views, you should be able to check the compatibility between the backend and frontend, there is no way for this to be self-adaptive, as we will always need to change the views
