### ISSUE TITLE
Attempt to read property "layout" on arrayTitle

### ISSUE THREAD

**Issue by aaoff** [Power-Components/livewire-powergrid#1415]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

![2024-02-16_15-17-07](https://github.com/Power-Components/livewire-powergrid/assets/94543215/5a43fd33-e866-49c6-a633-a6dfd8ab6b14)

### PHP Version

8.2.12

### PowerGrid

5.1

### Laravel

10.44.1

### Livewire

3.0+

### Alpine JS

3+

### Theme

Tailwind 3.x

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello! We recently improved how views are read in the front end, so we had to convert objects to arrays. You can try to do the same or remove the views that were published

https://livewire-powergrid.com/get-started/troubleshooting.html#theme-layout-and-view-errors

Thanks!
