### ISSUE TITLE
Show Many-to-Many Relationship data

### ISSUE THREAD

**Issue by aligulzar729** [Power-Components/livewire-powergrid#142]
Hello,
Is it possible to show many to many relationship data in the table?
How?
I have a many to many relationship between attribute and category.
Attribute table --> attribute_category table --> Category table
Thanks in advance.

**Comment by luanfreitasdev** [comment]
Hi @aligulzar729 , can you give more advanced examples?. For now it only works with filters

**Comment by aligulzar729** [comment]
Hi @luanfreitasdev 
Products --> product-orders --> orders
I don't know any other examples because I have these in my project.
And I don't know how to show in Power grid.

**Comment by ehsantalkhouncheh** [comment]
Hi @aligulzar729 ,

You can find what you need here: https://livewire-powergrid.docsforge.com/main/datasource/

**Comment by aligulzar729** [comment]
Hi @ehsantalkhouncheh 
Couldn't find something about many to many relationship and how to pass a custom layout for each many to many item.
I mean I want to show an badge for each category of a attribute.

**Comment by ehsantalkhouncheh** [comment]
Hi @aligulzar729 ,

As https://livewire-powergrid.docsforge.com/main/datasource/  has been explained you can create custome query with whatever join that you want and you can select coloumns that you need from the join so which part is not clear to you

`public function datasource(): ?Builder
{
  return Dish::query()
            ->join('categories', function ($categories) {
                $categories->on('dishes.category_id', '=', 'categories.id');
            })
            ->select([
                'dishes.id',
                'dishes.calories',
                'categories.name as category_name',
            ]);
}

**Comment by aligulzar729** [comment]
Hi @ehsantalkhouncheh 
If you have checked the demo project you'd realized that dishes and categories relationship is many to one and not many to many.
Or I didn't catch that so if you can help me that would be awesome.
I have Attribute table --> attribute_category table --> Category table
relationship which I want to show the categories of a attribute in a Power grid column.

**Comment by luanfreitasdev** [comment]
Olá @aligulzar729 , if you do the iteration inside the closure and assemble the data you need, doesn't it work for what you need?

```php
->addColumn('categories', function (Dish $dish) {
       return '<div>...</div>';
})
```

**Comment by aligulzar729** [comment]
Thanks I didn't know it will work like this. 
I made it work like here with this hacky way:
```
->addColumn('categories', function (Attribute $attribute) {
			                $badges = [];
			                foreach ( $attribute->categories as $category ) {
				                $badges[] = "<span class='badge badge-light-info'>$category->name</span> ";
			                }

			                return implode('</span>', $badges);
		                })
```

**Comment by aligulzar729** [comment]
Now I have another problem how to show another action button only when attribute type is something?

**Comment by luanfreitasdev** [comment]
This is a feature we will be working on in the near future. For now I will close the issue related to the many-to-many issue.

About this feature, we have 3 issues (https://github.com/Power-Components/livewire-powergrid/issues/133, https://github.com/Power-Components/livewire-powergrid/issues/136) about it, so I'll let you know about any news here.

Thanks !

**Comment by aligulzar729** [comment]
Thanks
