### ISSUE TITLE
Any chance we could add the Row Index for the records? as in the $loop->iteration

### ISSUE THREAD

**Issue by muhammedshiffin** [Power-Components/livewire-powergrid#143]
Hey there,
It would be nice if we could have the row index displayed as the first column of the table.

**Comment by luanfreitasdev** [comment]
Hi, I didn't get it right. How and why would it display the column's index?

**Comment by muhammedshiffin** [comment]
> Hi, I didn't get it right. How and why would it display the column's index?

Let's say, we just want to number the data. Like a serial number or so.
Oh, and I meant row index, not the column.

**Comment by luanfreitasdev** [comment]
Can you show me what the table would look like after it's ready, if it's going to have an impact?

**Comment by muhammedshiffin** [comment]
> 
Hey @luanfreitasdev, sorry to trouble you.
And thank you for the time.

I think not many of them would require this option.
So I have tweaked table views a little and achieved this for my project.

**Comment by Stridesdata** [comment]
@muhammedshiffin 
Can you share how you achieved this? It's quite important and I am struggling to achieve this
