### ISSUE TITLE
PowerGrid Create: flatpick detection

### ISSUE THREAD

**Issue by dansysanalyst** [Power-Components/livewire-powergrid#1437]
### Discussed in https://github.com/Power-Components/livewire-powergrid/discussions/1433

<div type='discussions-op-text'>

<sup>Originally posted by **bounty12** February 28, 2024</sup>
steps to reproduce

laravel new new-project
composer require laravel/jetstream
php artisan jetstream:install livewire --dark
composer require power-components/livewire-powergrid
Import powergrid JS and CSS
in resources/js/app.js
import './../../vendor/power-components/livewire-powergrid/dist/powergrid'
 
// If you use Tailwind 
import './../../vendor/power-components/livewire-powergrid/dist/tailwind.css'

php artisan powergrid:create

 
🤔 It looks like your project is missing a dependency!

PowerGrid requires flatpickr for Date filters to work.

Please, consider installing the package.

For more information, visit: https://livewire-powergrid.com/table/column-filters.html#filter-datetimepicker</div>

**Comment by luanfreitasdev** [comment]
Released: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.4.1
