### ISSUE TITLE
I'm getting a Vue Warn and I'm not sure how to fix, ideas?

### ISSUE THREAD

**Issue by JF-626164** [Power-Components/livewire-powergrid#144]
Hello! First time using PowerGrid. I've created a table and have added the export to it, when I click to open it I get a web browser console error:
[Vue warn]: Property or method "open" is not defined on the instance but referenced during render.
I've added the script tags to the main layout file I'm using and Vue shouldn't be being called at all on/through this page.

**Comment by JF-626164** [comment]
I removed the showExportOption() from the setUp and this issue went away.

**Comment by luanfreitasdev** [comment]
Hi!

Are you using powergrid together with vue ? How is your npm configuration?

**Comment by JF-626164** [comment]
I'm using powergrid in a livewire component that is extending the layout of the app. Vue is used elsewhere in the site and is slowly being replaced with livewire. The rest of the powergrid works just fine, its just the showExportOption & showtoggleColumns that are giving errors.

**Comment by luanfreitasdev** [comment]
I understood..With vue it can give some problem even on account of alpinejs. I will close this issue since you managed to resolve it so far.

Thanks.

**Comment by JF-626164** [comment]
Hey! I've figured it out, it was a theme issue. We're using a specific version of Tailwind, in the livewire-powergrid.php I swapped the theme from Tailwind to Bootstrap5 and it works!
