### ISSUE TITLE
Camel cased sub-directory names lose formatting when creating

### ISSUE THREAD

**Issue by nilios** [Power-Components/livewire-powergrid#1450]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

![image](https://github.com/Power-Components/livewire-powergrid/assets/33160081/f351757c-593f-4ec3-ae61-0a464340d45b)

You can see in the error text the sub-directory name is changed from what I told it to be when creating

### PHP Version

8.3.3

### PowerGrid

5.4.2

### Laravel

10.47.0

### Livewire

3.4.7

### Theme

Tailwind 3.x

### Describe the bug.

When creating a new powergrid table that is going into a sub-directory and the directory name is camel cased, the creation code removes the camel casing from the sub-directory name. This is because of a call to ->title() in the resolveFolder method. The title command will cause text such as 'ThisIsMyText' to become 'Thisismytext'. This should be removed to preserve user specified naming conventions.

### To Reproduce...

I used info() to log the ran command to the default laravel.log and observed the output of each function.
This output was generated when attempting to create the table in the screenshot.

private function resolveNameFolderFilename(string $name): self
    {
        info('resolveNameFolderFilename(' . $name . ')');
        $this->folder = $this->resolveFolder($name);
        info('folder: ' . $this->folder);

        $this->name = Str::of($name)->afterLast('\\')->toString();
        info('name: ' . $this->name);

        $this->filename = Str::of($this->name)->append('.php')->toString();
        info('filename: ' . $this->filename);

        return $this;
    }

[2024-03-06 16:08:38] local.INFO: resolveNameFolderFilename(Dispatch\ServiceCalls\ServiceCallIndexTable)  
[2024-03-06 16:08:38] local.INFO: folder: Dispatch\Servicecalls  
[2024-03-06 16:08:38] local.INFO: name: ServiceCallIndexTable  
[2024-03-06 16:08:38] local.INFO: filename: ServiceCallIndexTable.php 

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Released: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.4.5
