### ISSUE TITLE
Feature Request: Configurable Storage Drivers for PowerGrid Exports

### ISSUE THREAD

**Issue by moxesh-kombee** [Power-Components/livewire-powergrid#1459]
# ⚡ PowerGrid ⚡ Feature Request ⚡ Bucket Storage

## Summary:
I'd like to propose a feature that would allow PowerGrid exports to leverage Laravel's filesystem configuration for choosing the storage destination. Currently, PowerGrid relies on OpenSpout to handle file creation, which doesn't directly integrate with Laravel's storage drivers.

### Why is this needed?
Improved Configurability: Leverage Laravel's filesystem configuration to seamlessly switch between local, cloud (e.g., S3), or other storage backends, enhancing project flexibility and centralized control.
Enhanced Fault Tolerance and Scalability:
Load Balancing: In a load-balanced environment, files remain accessible regardless of which server handles upload and download requests. This eliminates "file does not exist" errors that could occur if storage paths are hardcoded.
Scalability: Cloud storage facilitates handling large export files as your application grows.

### Current Limitations:
With hardcoded storage paths, switching storage backends requires code modifications, introducing complexity.
Load-balanced deployments can lead to "file does not exist" errors if the file isn't present on the server handling the download request. This is especially true with single-server downloads when upload and download paths might become mismatched.

### Proposed Solution:
Introduce a configuration option within PowerGrid to specify the desired storage driver.
Modify the export logic to utilize Laravel's filesystem helpers, enabling interaction with the chosen storage driver.

### Benefits:
Configuration Flexibility: Simplified management of storage destinations through Laravel's configuration.
Streamlined Development: Effortless deployment across environments without code changes.
Enhanced Fault Tolerance: Load-balanced deployments and single-server downloads function smoothly with centralized storage.
Scalability: Cloud storage empowers management of large-scale export files.

### Additional Considerations:
Specific storage solution requirements (e.g., authentication, access control) should be factored in.
Cloud storage performance implications, particularly with significant data volume, need evaluation.
Explore caching mechanisms for cloud storage downloads to improve performance.

By enabling configurable storage drivers, PowerGrid gains significant flexibility and adaptability for diverse application scenarios. This feature aligns well with Laravel's robust storage management capabilities.

We believe this feature would significantly enhance PowerGrid's usability. We encourage discussion, alternative approaches, and collaboration to implement this functionality.

Thank you for considering this feature request. I believe it would greatly enhance the flexibility and user experience of PowerGrid within Laravel applications.

Additionally, here are some resources that might be helpful:
Laravel Filesystem: https://laravel.com/docs/10.x/filesystem
PowerGrid Documentation: https://github.com/Power-Components/livewire-powergrid (assuming you're using the Livewire PowerGrid package)
OpenSpout Documentation: https://github.com/openspout/openspout

**Comment by luanfreitasdev** [comment]
Hello! @moxesh-easternts . This feature is useful, but it can be complicated to implement due to server-side testing and various use cases. Do you have any ideas for a possible simple solution for this feature? 
Feel free to open a Pull Request.

Thank you!
