### ISSUE TITLE
Two bugs in the Responsive feature.

### ISSUE THREAD

**Issue by pablov01** [Power-Components/livewire-powergrid#1471]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1.2

### PowerGrid

5.1.1

### Laravel

10.25.0

### Livewire

3.0.5

### Theme

Tailwind 3.x

### Describe the bug.

The errors I found in the Responsive functionality were the following:
1. **_Accentuations:_** the names of the titles of the fields that contain accentuations show them incorrectly, omitting the accented vowel. Example:

2. **_FixColumns Method:_** using this method for a form I realized that it does not work correctly (or the documentation is not very clear), I tried to place the fields that I did not want to be hidden in the form, I also based myself on the example of the documentation, but it is not clear to me if the parameters passed are a range or are fields of the TableComponent.

### To Reproduce...

1. **_Accentuations:_**
![image_1](https://github.com/Power-Components/livewire-powergrid/assets/102996907/02a6f611-f28d-42fa-9136-c5d587da559a)
**and this show:**
![image_2jpg](https://github.com/Power-Components/livewire-powergrid/assets/102996907/6835a7b0-f8fe-499a-84cd-5ccb24bebb09)
2. **_FixColumns Method:_**
![image_3](https://github.com/Power-Components/livewire-powergrid/assets/102996907/28948082-faca-4d7f-8fdc-7ca3aa97baf0)
**and this show:**
![image_4](https://github.com/Power-Components/livewire-powergrid/assets/102996907/c45dbdc8-a883-40fb-bf60-56a5fc6a71a6)
(It doesn't hide column 10 from me)

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello! Are the field names column1, and column2? It should be the name you define in https://livewire-powergrid.com/table/add-columns.html#add-columns-fields

Docs: https://livewire-powergrid.com/table/features-setup.html#fixed-columns

**Comment by luanfreitasdev** [comment]
No answers, so closing this

**Comment by pablov01** [comment]
hello! I think my captures were a bit confusing, I'll try again. For point 2 about the _FixedColumns_ method, I think I understood how it works, now the problem is the fields it hides to the **Responsive::make()** method, the titles of the fields it hides omit the **Accentuations**.
This some examples:
![image](https://github.com/Power-Components/livewire-powergrid/assets/102996907/d822d49b-5fca-4d26-ac36-27870095a761)
As you can see in the hidden titles, it omits the vowels which have accents. Instead of saying **"Fecha Fundación"** it says **"Fecha Fundacin"**, **"Teléfono"** says **"Telfono"**, **"Dirección"** says **"Direccin"**, as well as any word that contains accents.
This is the way he applied the titles:
![image](https://github.com/Power-Components/livewire-powergrid/assets/102996907/124fd575-bba0-4c3d-b8ea-f2bbfa654cb6)
