### ISSUE TITLE
Cannot unset string offsets

### ISSUE THREAD

**Issue by bylioxdev** [Power-Components/livewire-powergrid#1473]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1.27

### PowerGrid

5.4.8

### Laravel

10.43.0

### Livewire

3.4.5

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When I try to add to a table a filter, i get the following error:
Cannot unset string offsets (View: /var/www/vhosts/__BLUR__/resources/views/vendor/livewire-powergrid/components/frameworks/tailwind/filters/input-text.blade.php)

### To Reproduce...

Add an filter to an table:
```
public function filters(): array
    {
        return [
            Filter::inputText('id', 'id')
        ];
    }
```
Reload the page, and boom

### Extra information

```markdown
function filters(): array
    {
        return [
            Filter::inputText('id', 'id')
        ];
    }
```

**Comment by bylioxdev** [comment]
![grafik](https://github.com/Power-Components/livewire-powergrid/assets/80979886/6f314877-8a36-409c-8c03-a737da0ca6ad)

**Comment by luanfreitasdev** [comment]
Hello, @bylioxdev. Does this happen if you remove the last 'id' parameter?

```
return [
      Filter::inputText('id')
];
```

**Comment by luanfreitasdev** [comment]
No answers, so closing this
