### ISSUE TITLE
Installation/first setup bug/issue.

### ISSUE THREAD

**Issue by netsolid-ca** [Power-Components/livewire-powergrid#1479]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.3.0

### PowerGrid

5.4.8

### Laravel

10.48.4

### Livewire

3.4.9

### Alpine JS

3.13.5

### Theme

Tailwind 3.x

### Describe the bug.

Ran Powegrid to create a table view (unmodified) 
On a blank page I call: <livewire:clients-view/>
Result is: ErrorException
Attempt to read property "layout" on array
@include($theme->layout->header, [

                'enabledFilters' => $enabledFilters,

            ])

### To Reproduce...

Install everything
Run php artisan powergrid:create
Give it a name, etc, select table.
include <livewire:name />

**Comment by luanfreitasdev** [comment]
Hello. Can you give more information? I believe it is a problem with publishing old views

**Comment by netsolid-ca** [comment]
What other information do you need?
Also how would I update the views then? I have tried everything I can think of and find online to clear caches.

Sent from my Bell Samsung device over Canada’s largest network.
________________________________

**Comment by luanfreitasdev** [comment]
I believe the best solution is to remove the resouces/views/vendor/livewire-powergrid folder

https://livewire-powergrid.com/get-started/troubleshooting.html#theme-layout-and-view-errors

**Comment by luanfreitasdev** [comment]
Closing this as it doesn't seem to be a issue
