### ISSUE TITLE
no paginating on a table with a collection or array

### ISSUE THREAD

**Issue by marineusde** [Power-Components/livewire-powergrid#1490]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.7

### PowerGrid

5.4.8

### Laravel

10.48.4

### Livewire

3.4.9

### Theme

Bootstrap

### Describe the bug.

the footer with the paginating is not shown

### To Reproduce...

```
final class TestTable extends PowerGridComponent
{
    public function datasource(): ?Collection
    {
        $collection = new Collection;
        for ($i = 1; $i <= 20; $i++) {
            $collection->add([
                'id' => $i,
                'name' => 'Name ' . $i
            ]);
        }

        return $collection;
    }

    public function setUp(): array
    {
        return [
            Header::make(),
            Footer::make()
                ->showPerPage(),
        ];
    }

    public function fields(): PowerGridFields
    {
        return PowerGrid::fields()
            ->add('id')
            ->add('name');
    }

    public function columns(): array
    {
        return [
            Column::make('ID', 'id'),
            Column::make('Name', 'name'),
        ];
    }
}
```

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Released: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.4.9
