### ISSUE TITLE
select-class and -style in custom theme footer not used

### ISSUE THREAD

**Issue by marineusde** [Power-Components/livewire-powergrid#1492]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.7

### PowerGrid

5.4.8

### Laravel

10.48.4

### Livewire

3.4.9

### Theme

Bootstrap

### Describe the bug.

the variables $selectClass and $selectStyle of the class PowerComponents\LivewirePowerGrid\Themes\Components\Footer are not used in the footer-blade files from bootstrap or tailwind.

### To Reproduce...

```
class CustomTheme extends Bootstrap5
{
    public function footer(): Footer
    {
        return Theme::footer()
            ->view($this->root() . '.footer')
            ->select('my_fancy_select_class', 'my_fancy_select_style');
    }
}
```

livewire-powergrid.php:
```
'theme' => \App\PowergridThemes\CustomTheme::class,
```

then used the dev tools of the browser, picking the select-box in the footer:
```
<select wire:model.live="setUp.footer.perPage" class="form-select">...</select>
```
there is no "my_fancy_select_class" or "my_fancy_select_style"

### Extra information

```markdown
Same problem exists with tailwind
```

**Comment by luanfreitasdev** [comment]
Released: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.4.9
