### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by ashek1412** [Power-Components/livewire-powergrid#1495]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8

### PowerGrid

4.8

### Laravel

9

### Livewire

2.5

### Alpine JS

3.10.3

### Theme

Tailwind 3.x

### Describe the bug.

export all not exporting all data to Excel/CSV  when using collection data source. 
it only exports data shown in first page.
Can anyone help ?

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hi! Can you send a PR for this in version 4? 
Thank you
