### ISSUE TITLE
The create command will not work if the app/Model directory does not exist.

### ISSUE THREAD

**Issue by nocttuam** [Power-Components/livewire-powergrid#1499]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

The "/var/www/html/app/Models" directory does not exist.

Failed to run artisan powergrid:create: exit status 1

### PHP Version

8.2.15

### PowerGrid

5.4.9

### Laravel

11.0.8

### Livewire

3.4.10

### Alpine JS

3.13

### Theme

Tailwind 3.x

### Describe the bug.

I'm working on a project where the directory structure for models is not recognized. The Model directories are organized in modules in a directory called Domain.

Folder structure:
```
Domain
   |____Users
   |      |____OtherServices
   |      |____ .......
   |      |____Models
   |            |____UserModel
   |            |____OtherModel
   |
   |__OtherModule
          |____OtherServices
          |____ .......                          
```

### To Reproduce...

To replicate this problem:

1. Ensure app/Model Directory is Missing:
2. Execute create command: artisan powergrid:create.

**Comment by luanfreitasdev** [comment]
Released: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.4.10
