### ISSUE TITLE
Editar em modal usando powergrid

### ISSUE THREAD

**Issue by wjrs** [Power-Components/livewire-powergrid#15]
Estou usando o componente porém gostaria de conseguir utilizar as chamadas do modal dentro do componente. Atualmente só consigo chamar pelo método route do Button, porém preciso ir para uma tela normal ñ modal.

Se possível gostaria de sugerir algo que pudesse dar esse comportamento, a ideia que tive estão nos anexos.

![chamada-modal](https://user-images.githubusercontent.com/9887812/117552324-ff15e880-b020-11eb-95f7-862ddd5114cc.png)

![metodo-livewire](https://user-images.githubusercontent.com/9887812/117552325-00471580-b021-11eb-8e39-bb85633e79e0.png)

![sugestao](https://user-images.githubusercontent.com/9887812/117552326-00dfac00-b021-11eb-8d2e-c72118e03d0d.png)

**Comment by luanfreitasdev** [comment]
Olá Wesley!, poderia postar o seu componente modal? Talvez seria interessante adicionar no método on click o caminho da view e os parâmetros

**Comment by wjrs** [comment]
Também seria uma boa....segue o modal


<div class="fixed z-10 inset-0 overflow-y-auto ease-out duration-400">

    <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
        <div class="fixed inset-0 transition-opacity">
            <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
        </div>

        
        <span class="hidden sm:inline-block sm:align-middle sm:h-screen"></span>

        <div
            class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full"
            role="dialog" aria-modal="true" aria-labelledby="modal-headline">

            <h2 class="font-bold text-xl text-indigo-800 leading-tight px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                PLANO
            </h2>

            <hr>

            <form>
                <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                    <div class="">
                        <div class="mb-4">
                            <label for="exampleFormControlInput1" class="block text-gray-700 text-sm font-bold mb-2">Nome:</label>

                            <input type="text"
                                   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                   id="exampleFormControlInput1" placeholder="" wire:model="name">

                            @error('name') <span class="text-red-500">{{ $message }}</span>@enderror
                        </div>

                        <div class="mb-4">
                            <label for="exampleFormControlInput2" class="block text-gray-700 text-sm font-bold mb-2">Preço:</label>
                            <input type="text"
                                   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                                   id="exampleFormControlInput1" placeholder="" wire:model="price">

                            @error('price') <span class="text-red-500">{{ $message }}</span>@enderror
                        </div>
                    </div>
                </div>

                <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">

                    <span class="flex w-full rounded-md shadow-sm sm:ml-3 sm:w-auto">
                        <button wire:click.prevent="store()" type="button"
                                class="inline-flex justify-center w-full rounded-md border border-transparent px-4 py-2 bg-green-600 text-base leading-6 font-medium text-white shadow-sm hover:bg-green-500 focus:outline-none focus:border-green-700 focus:shadow-outline-green transition ease-in-out duration-150 sm:text-sm sm:leading-5">
                            Salvar
                        </button>
                    </span>
                    <span class="mt-3 flex w-full rounded-md shadow-sm sm:mt-0 sm:w-auto">
                        <button wire:click="closeModal()" type="button"
                              class="inline-flex justify-center w-full rounded-md border border-gray-300 px-4 py-2 bg-white text-base leading-6 font-medium text-gray-700 shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue transition ease-in-out duration-150 sm:text-sm sm:leading-5">
                            Cancelar
                        </button>
                  </span>
                </div>
            </form>
        </div>
    </div>
</div>

**Comment by luanfreitasdev** [comment]
@wjrs finalizei as implementações logo já faço o merge para o main.


Valeu!
