### ISSUE TITLE
Enhancement: Additional parameter for sort

### ISSUE THREAD

**Issue by throwexceptions** [Power-Components/livewire-powergrid#150]
Hi,

   I would like to give on the update of sortBy method in WithSorting trait.

  By implementing a second parameter $direction to help the developer to initialize default sort direction.

**Comment by luanfreitasdev** [comment]
Hi,

This already works in another way. But its implementation is still viable. https://github.com/Power-Components/livewire-powergrid/issues/145

Thanks
