### ISSUE TITLE
Missing App/Helpers on new install

### ISSUE THREAD

**Issue by phila088** [Power-Components/livewire-powergrid#1502]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes

`Class "App\Helpers\PowerGridThemes\TailwindHeaderFixed" not found`

### PHP Version

8.2

### PowerGrid

5.4

### Laravel

11.2.0

### Livewire

3.4.10

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

Following the documentation for the fixed header table. When installing, there is no helper files added in `app` folder. Cannot locate in the repo either. This gives an error when adding:

```
public function template(): ?string
    {
        return TailwindHeaderFixed::class;
    }
```

**Comment by dansysanalyst** [comment]
Hi @phila088,

This is a custom theme. You can see the live example [here](https://demo.livewire-powergrid.com/examples/fixed-header) and the source code is available at the demo repository:

https://github.com/Power-Components/powergrid-demo/tree/powergrid_v5/app/Helpers/PowerGridThemes

**Comment by phila088** [comment]
Thank you, I missed that!
