### ISSUE TITLE
Custom theme - only some styles will apply

### ISSUE THREAD

**Issue by phila088** [Power-Components/livewire-powergrid#1503]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

Following the guide and using the custom themes (found from my previous issue :)) I have created a custom theme. I have registered it in the config, and have verified that it is being used for my tables. The issue is that only *some* of the styles that I apply will actually style the table. For instance:

```
->trBody('odd:bg-red-500')
```
This does not apply any styling to the table itself. Using the browsers inspector, I see that the style is there, however the color that is shown is not red. Almost every color that I try to apply is shown as just white.

The previous issue I found that is similar, it is suggested to clear all caches, which I did. I have rebuilt the CSS files with `npm run dev r` and `npm run build`. I have cleared my browsers cache. I cannot for the life of me understand why. I can set the `->tdBody()` color, and the odd columns will color, but not the rows.

![image](https://github.com/Power-Components/livewire-powergrid/assets/122768105/76d441c2-7a54-4cb9-8449-234cd177c9cd)
![image](https://github.com/Power-Components/livewire-powergrid/assets/122768105/16ccdf40-17b6-4de6-a2b2-f3fdf0f9fee4)

I have even applied the `TailwindStriped::class` and it will not stripe the rows at all. However, as stated, I can change the border radius with no issues. I was able to change the text size, but cannot change the text color. Essentially, it seems anything to do with color, it will not change the style.

**Comment by marineusde** [comment]
take a look in the dev tools of the browser, maybe the css attributes cant be set cause another class has an !important for this.

**Comment by phila088** [comment]
It has been corrected. It was a style overriding my styles. Thank you!

**Comment by elsoftpy** [comment]
I'm struggling to customize my theme too.

I copied the Tailwind theme file into the App/PowerGridThemes folder and changed the configuration parameter in config/livewire-powergrid.php.

This is my custom theme file:
![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/0923d2f2-d044-46f0-8e5d-da77b411a2a0)

This is my config file:
![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/05569ce7-2c10-46f4-bfff-ad7518bf99b2)

I also registered the file in tailwind's config file:
![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/6659a3b6-6b4c-471c-8d52-d0a36e19922e)

Finally I run ``` npm run build ``` 

Now, the first time I render a table with the custom theme changes are visible. In the screenshot below you will see the background changed to ``` bg-slate-200 ```
![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/395f8ed3-0f4b-4c21-b5f3-024edefa7bf1)

![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/d8439dea-d0c7-46af-bd1a-d0cea7e628eb)

But if I make some changes after, these last changes won't be reflected in the table:

In this example I changed the ```table``` background class to ```bg-slate-800```  run ```npm run build``` and this is the result
![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/5b80ea6c-d4b9-4b54-92ec-71f81f67b058)

![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/21f2fd24-470e-431e-b5dc-80ee84c0181b)


![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/abd63456-4003-46b2-9b8f-31292acb42d7)

Only If I change the name of the class and references the powergrid configuration to that class changes are reflected again:
![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/4b438b85-5f37-45b0-bb38-bfbb69236901)

![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/2fb4b64c-9faa-453b-b391-3f11a4353f62)

![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/1e9ff873-a4cf-4c91-b97a-cc84ad19b951)

![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/474d348c-879c-411c-bc34-3fcb0f676b85)

![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/258e811c-0bdc-4c8a-ae50-eb313ac01421)

**Ps:**  I'm using css variables to configure primary, secondary and so on colors, I don't know if it has something to do with that 

![image](https://github.com/Power-Components/livewire-powergrid/assets/57192394/ec00d59f-8438-4e25-b548-2bae530d3d89)

**Comment by luanfreitasdev** [comment]
Hello @elsoftpy . Can you open a new issue about this? Thank you

**Comment by elsoftpy** [comment]
Hi, thanks for the quick response. I think I fixed it running ``php artisan optimize:clear``

**Comment by elsoftpy** [comment]
Congrats on a great! job by the way. This component is a life saver
