### ISSUE TITLE
$exportActive variable issue in powergrid

### ISSUE THREAD

**Issue by VippalaArpita** [Power-Components/livewire-powergrid#1507]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

7.3

### PowerGrid

3.5

### Laravel

9.0

### Livewire

2.10

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When I create powergrid table its is creating. After integrating it into the blade file I'm getting "Undefined variable $exportActive" exception

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by marineusde** [comment]
please upgrade to PowerGrid 5.x

**Comment by luanfreitasdev** [comment]
This can happen if you have **published views**. Removed them and updated to version ^4.0 (livewire v2) and then ^5.0 (livewire v3)

**Comment by VippalaArpita** [comment]
> For powergrid 5.x requires PHP 8.1 version which I can't upgrade currently

**Comment by VippalaArpita** [comment]
> please upgrade to PowerGrid 5.x

Thanks a lot for the reply. But It requires PHP version 8.1

**Comment by VippalaArpita** [comment]
> This can happen if you have **published views**. Removed them and updated to version ^4.0 (livewire v2) and then ^5.0 (livewire v3)

Thanq for the reply. I'll try it.
