### ISSUE TITLE
Persisting optional with session storage instead of cookies

### ISSUE THREAD

**Issue by marineusde** [Power-Components/livewire-powergrid#1508]
# ⚡ PowerGrid ⚡ Feature Request

## Summary

the developer can configure, that the persisting works with session storage instead of cookies

### Why is this needed?

lots of users dont understand the filters of a table they set some days ago. The idea is, to save the persisting in a session storage, so it will be deleted at the next login.

### Suggested Solution(s)

first idea:
- my pull request

other ideas:
- set the time in seconds for the lifetime of the cookies

### Related issue(s)/PR(s)

Let us know if this is related to any issue/request

**Comment by luanfreitasdev** [comment]
Released: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.5.0
