### ISSUE TITLE
Export filtered items

### ISSUE THREAD

**Issue by caiochami** [Power-Components/livewire-powergrid#1526]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.18

### PowerGrid

5.3.8

### Laravel

10.48.10

### Livewire

3.4.4

### Theme

Tailwind 3.x

### Describe the bug.

Filters are not being applied to the data being exported.

### To Reproduce...

1. Apply some filters to your table. 
2. Click the Export button and then 
3. Click over the "Filtered" option.

 
![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/5848a6e2-e304-406d-ad8c-03d077000c32)

**Comment by dansysanalyst** [comment]
Hi @caiochami,

I could not reproduce this issue in [PowerGrid Demo](https://demo.livewire-powergrid.com/examples/filters-outside?name=Melt).

![CleanShot 2024-05-03 at 00 01 34@2x](https://github.com/Power-Components/livewire-powergrid/assets/79267265/8c1133be-6053-4a57-8af1-228c679e606b)

Also, when filtering for a [nonexistent item](https://demo.livewire-powergrid.com/examples/filters-outside?name=Pipoca), the CSV is empty as expected.

![CleanShot 2024-05-03 at 00 05 24@2x](https://github.com/Power-Components/livewire-powergrid/assets/79267265/1bdbd72b-0898-4919-81da-dea1d9017070)

**Comment by caiochami** [comment]
@dansysanalyst I couldn't reproduce the issue in the Powergrid Demo either. I noticed this is a very specific scenario I got myself into. I managed to address the issue and I'm closing this ticket for now. Thanks for the help
