### ISSUE TITLE
Cannot export data with date filter turned on

### ISSUE THREAD

**Issue by caiochami** [Power-Components/livewire-powergrid#1533]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.18

### PowerGrid

5.3.8

### Laravel

10.48.10

### Livewire

3.4.4

### Theme

Tailwind 3.x

### Describe the bug.

I get this error when I filter data by date and click the export button.

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/f8c53687-c0af-483f-8b18-0ea70c8e5194)

### To Reproduce...

Set up a data table like so:

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/dbad4847-e632-42e5-8677-c9cbdcbc8ccf)

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/0cad1d23-29fa-43a4-853e-1d3fd7c4ce7d)

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/10c83e66-bdb1-44c1-81c7-96221f18055a)

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/18493895-f65c-49d4-acb5-df7b7439ca14)

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/5eb973d2-b783-43a0-acf4-0c1e3fdcc7ce)

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/9bb0a2ac-1055-48ec-815c-d994a9982115)

Filter data by date

Go to your data table, apply date range filter, go over the export icon and export the data

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/04993376-9de3-4c98-89ca-afd0bf4a0096)

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/8a8671fe-b8ec-4109-98cf-d9acc026d09f)

**Comment by caiochami** [comment]
It works if I do this though. This is not the approach I was looking for because users will get 500 errors if their storage holds thousands of data and they attempt to export them. The app won't make use of the queue system.

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/93d6334e-236f-4a61-9251-9e2dca6c04b9)

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.6.1

**Comment by caiochami** [comment]
Thank you so much
