### ISSUE TITLE
[BUG] Placeholder in `Filter::number` is not working

### ISSUE THREAD

**Issue by dansysanalyst** [Power-Components/livewire-powergrid#1535]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### Theme

Tailwind 3.x

### Describe the bug.

While investigating the Feature Request  https://github.com/Power-Components/livewire-powergrid/issues/1534, I've noticed the method `->placeholder()` is not working on `Filter::number`.

I have already identified the bug, it might be affecting other filters too.

I will be sending a PR soon.

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.6.1
