### ISSUE TITLE
[BUG] `hideToggleable` Action rule is not working

### ISSUE THREAD

**Issue by dansysanalyst** [Power-Components/livewire-powergrid#1539]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### Theme

Tailwind 3.x

### Describe the bug.

The Action Rule to hide the Toggleable is not working as expected.

![CleanShot 2024-05-10 at 01 20 24@2x](https://github.com/Power-Components/livewire-powergrid/assets/79267265/7167f71d-c82b-4654-95d6-d9e60618818a)
a
```php 
 public function actionRules($row): array
    {
            Rule::rows()
                ->when(fn ($dish) => $dish->in_stock == false)
                ->hideToggleable(),
        ];
    }
```

### To Reproduce...

First click on "FOO" then....

**Comment by dansysanalyst** [comment]
I am working on a PR. Should send in the next few days.

**Comment by luanfreitasdev** [comment]
Released: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.7.0
