### ISSUE TITLE
`withAvg` breaks Exporting data

### ISSUE THREAD

**Issue by dansysanalyst** [Power-Components/livewire-powergrid#1540]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

It appears that adding `withAvg()` to a column breaks exporting data, even if not visible in Export.

```php

            Column::add()
                ->title('Calories')
                ->field('calories')
                ->visibleInExport(visible: false)
                ->withAvg('Average', header: true, footer: false)
                ->sortable(),
```

![CleanShot 2024-05-11 at 12 11 38@2x](https://github.com/Power-Components/livewire-powergrid/assets/79267265/1da0c6ed-ceee-4698-b270-e7463cd3ae92)

### Theme

Tailwind 3.x

### To Reproduce...

First click on "FOO" then....

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.6.4
