### ISSUE TITLE
Action buttons with route functions are misaligned in the table

### ISSUE THREAD

**Issue by Rosembergg** [Power-Components/livewire-powergrid#1561]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1.2

### PowerGrid

5.1

### Laravel

10.48.3

### Livewire

3.0

### Theme

Tailwind 3.x

### Describe the bug.

Action buttons with route functions are misaligned in the table, however when using the dispatch function, the buttons have the correct style

### To Reproduce...

![erro_buttons](https://github.com/Power-Components/livewire-powergrid/assets/60368472/0fe67b26-3c31-4048-840e-48e57702dd93)

### Extra information

```markdown
public function actions(\App\Models\User $row): array
    {

        return [
            Button::add('edit')
                ->slot('Editar')
                ->class('bg-kblue cursor-pointer text-white px-3 py-2 m-1 rounded text-sm')
                ->openModal('form-usuario-modal', ['id' => $row->id]),

            Button::add('permission')
                ->slot('Permissões')
                ->class('bg-korange cursor-pointer text-white px-3 py-2 m-1 rounded text-sm')
                ->route('controle.permissoes', ['user_id' => $row->id]),

            Button::add('function')
                ->slot('Funções')
                ->class('bg-kblue cursor-pointer text-white px-3 py-2 m-1 rounded text-sm')
                ->route('controle.funcoes', ['user_id' => $row->id]),

            Button::add('rh')
                ->slot('RH')
                ->class('bg-korange cursor-pointer text-white px-3 py-2 m-1 rounded text-sm')
                ->openModal('form-colaborador-modal', ['user_id' => $row->id]),

            Button::add('activate')
                ->slot('Ativar')
                ->class('bg-green-600 cursor-pointer text-white px-3 py-2 m-1 rounded text-sm')
                ->dispatch('ativar', ['id' => $row->id]),
        ];
    }
 <?php
 //...
```

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.6.4
