### ISSUE TITLE
Clear Filters not showing when using queryString

### ISSUE THREAD

**Issue by carloeusebi** [Power-Components/livewire-powergrid#1563]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.3

### PowerGrid

5.6

### Laravel

11.7

### Livewire

3.4

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When using the query string function, on page load the filters are populatad from the params in the query string, but the `$enabledFilters` is not.
This means that the clear filter button for the filter is not showing.

As you can see in the image beloew, the 'Inizio Terapia' filter was populated from the query and it is not showing in the `enabledFilters` array, while the 'Stato' filter was just changed by hand, and it showing in the  `enabledFilters`, and it is correctly showing the clear filter button.

The same result heappens for each filter, so it not specific for the 'Inizio Terapia' filter.

It also happens if I use `return [ ...$this->powerGridQueryString()]` in the `queryString` as described in the [documentation](https://livewire-powergrid.com/table-features/searching-data.html#query-string).

![Screenshot from 2024-05-22 09-28-30](https://github.com/Power-Components/livewire-powergrid/assets/129429172/8a44954f-c769-4ddb-be93-861a89e30ae1)

### Extra information

```markdown
<?php
 //...
    protected function queryString(): array
    {
        return [
            'page' => ['except' => 1, 'as' => 'pagina'],
            'search' => ['except' => '', 'as' => 'cerca'],
            'filters.boolean.archived_at' => ['except' => '', 'as' => 'stato'],
            'filters.date.therapy_start_date' => ['except' => '', 'as' => 'data'],
        ];
    }
```

**Comment by luanfreitasdev** [comment]
Released: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.7.0
