### ISSUE TITLE
[BOOTSTRAP] Actions Column is missing border

### ISSUE THREAD

**Issue by dansysanalyst** [Power-Components/livewire-powergrid#1567]
### Discussed in https://github.com/Power-Components/livewire-powergrid/discussions/1564

<div type='discussions-op-text'>

<sup>Originally posted by **abhaypithadiya** May 22, 2024</sup>
I have mentioned the below in my columns array

```
            Column::action('Action')
                ->hidden(! auth()->user()->can('customer_edit') && ! auth()->user()->can('customer_delete'))
                ->visibleInExport(false),
```

The UI breaks in the filters row. The border on the right is missing. I think this worked properly in the version around 5.0.7

![Screenshot 2024-05-22 at 9 01 10 PM](https://github.com/Power-Components/livewire-powergrid/assets/107384999/f885b474-8892-419f-b704-4bfdeff3f603)

@luanfreitasdev 
</div>

**Comment by luanfreitasdev** [comment]
It is impossible to solve this in version 5. (unless someone opens a pull request).

Thanks
