### ISSUE TITLE
livewire powergrid Attempt to read property "layout" on array

### ISSUE THREAD

**Issue by eztl** [Power-Components/livewire-powergrid#1577]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No
![2024-05-29_09-41](https://github.com/Power-Components/livewire-powergrid/assets/105444078/ab0c4a12-bbe2-4e7d-9bab-e04a282d5e18)

### PHP Version

8.3.7

### PowerGrid

5.7.1

### Laravel

10.48.12

### Livewire

3.5.0

### Alpine JS

3,14.0

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

All of our pages that utilize powergrid are showing this error.

NOTE: Even when creating an enirely new powergrid table, this error occurs.

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello!. Please read this: https://livewire-powergrid.com/get-started/troubleshooting.html#theme-layout-view-and-variable-undefined-errors

Related issues: 
* https://github.com/Power-Components/livewire-powergrid/issues/1415
* https://github.com/Power-Components/livewire-powergrid/issues/1357
