### ISSUE TITLE
error when using the search engine in production

### ISSUE THREAD

**Issue by EmilioVar** [Power-Components/livewire-powergrid#1584]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'generation_expression' in 'field list' (Connection: mysql, SQL: select column_name as `name`, data_type as `type_name`, column_type as `type`, collation_name as `collation`, is_nullable as `nullable`, column_default as `default`, column_comment as `comment`, generation_expression as `expression`, extra as `extra` from information_schema.columns where table_schema = 'xxx' and table_name = 'xxx' order by ordinal_position asc)

### PHP Version

8.2

### PowerGrid

5.8.0

### Laravel

11.9

### Livewire

3.5.0

### Theme

Tailwind 3.x

### Describe the bug.

When I try to search for a record in the table, I get an error in the query. It seems that it tries to search for the variables.

<img width="850" alt="Captura de pantalla 2024-06-07 a las 10 19 49" src="https://github.com/Power-Components/livewire-powergrid/assets/103036961/af98a523-4e61-4687-b4bf-86f8d6868f6d">

### To Reproduce...

1. I enter text to search
2. I get the error text, always the same, regardless of the search

### Extra information

```markdown
I have the mysql 5.5 version in production
```

**Comment by luanfreitasdev** [comment]
Hello! Unfortunately, I cannot reproduce this problem and believe it is unrelated to PowerGrid due to the MySQL version. I suggest updating to the latest version.

Thank you

**Comment by EmilioVar** [comment]
> Hello! Unfortunately, I cannot reproduce this problem and believe it is unrelated to PowerGrid due to the MySQL version. I suggest updating to the latest version.
> 
> Thank you

Right! I have updated the version of mysql and now it works correctly. Thank you so much!
