### ISSUE TITLE
Cannot search in relationData

### ISSUE THREAD

**Issue by mohammadtarabishy** [Power-Components/livewire-powergrid#159]
**Describe the bug**

* ..

**To Reproduce**
* Got to ..

**Laravel version (exactly):**
* 8.x.x ?
 
**Alpine version:**
* 3.x.x ?

**Theme:**
- [ ] Tailwind 
   - Version:        
      
- [x] Bootstrap
   - Version:        

**Screenshots** (***This helps to understand better***)

**Do you have any idea how we can fix it?**

**Comment by devsquad-luan-freitas** [comment]
Hello @mohammadtarabishy .
Resolved?

**Comment by mohammadtarabishy** [comment]
resolved 
thanks

**Comment by iamdan-boop** [comment]
![image](https://user-images.githubusercontent.com/66265305/150361649-511fc48b-0f2c-42d4-9a7f-21a93394fab0.png)
hello how did you resolved it ? i could't search also in relationship of the data
