### ISSUE TITLE
Pesquisa em colunas com mutator

### ISSUE THREAD

**Issue by wjrs** [Power-Components/livewire-powergrid#16]
Estou tentando pesquisar um range em uma coluna de preço usando um mutator no model....coloquei da mesma forma que seria usando o padrão do componente mas ele não acha os resultados. 

Não sei se estou fazendo algo errado ou se realmente precisa ser implementado no componente pra funcionar.
(Eu iria usar essa mesma forma para a coluna da data)

![list](https://user-images.githubusercontent.com/9887812/117552591-ca0a9580-b022-11eb-922b-6a30c2d4a0a7.png)

![model](https://user-images.githubusercontent.com/9887812/117552599-cf67e000-b022-11eb-991b-df1a4d8f820f.png)

![datasource](https://user-images.githubusercontent.com/9887812/117552603-d55dc100-b022-11eb-8441-0fa97345883b.png)

![columns](https://user-images.githubusercontent.com/9887812/117552607-da227500-b022-11eb-8cc1-bf9ac54aaa95.png)

**Comment by luanfreitasdev** [comment]
Tenta fazer a mutação dentro do add_column('price_selectted', function()}) semelhante ao campo created_at_formatted... Mas você também poderia usar se colocar um $appends no model para price_selectted e colocar o método getPriceSelecttedAttribute()

**Comment by wjrs** [comment]
Desculpa @luanfreitasdev, na desatenção aqui eu acabei colocando o nome do método errado no model, mudei pra getPriceFormattedAttribute() e funcionou normalmente.

obrigado.

**Comment by luanfreitasdev** [comment]
Imagina! Qualquer coisa estamos aqui 😃

Vlw
