### ISSUE TITLE
The detail button expands all rows

### ISSUE THREAD

**Issue by caiochami** [Power-Components/livewire-powergrid#1609]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.3.8

### PowerGrid

5.8.1

### Laravel

11.14.0

### Livewire

3.5.2

### Theme

Tailwind 3.x

### Describe the bug.

If you add these settings to a data table, the detail button expands/collapses all rows. Can we specify which column to use as a row identifier?

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/fdb5a677-9d6e-4e73-9a13-04f8d68290db)

### To Reproduce...

Add custom primary keys to your data table

https://livewire-powergrid.com/table-component/data-source.html#custom-primary-key

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/13a891b3-51d8-4cb9-8b44-59c853ff2a3e)

Set up the detail button

https://livewire-powergrid.com/table-component/component-configuration.html#detail-row

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/fdb5a677-9d6e-4e73-9a13-04f8d68290db)

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/cd3d3c4d-09c0-406e-b84f-b7b8a787126d)

![image](https://github.com/Power-Components/livewire-powergrid/assets/17772351/4ac40368-5e2b-4fec-a1ca-c4e1fcb4d9db)

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.10.0
