### ISSUE TITLE
Additional search fields not working

### ISSUE THREAD

**Issue by wturrell** [Power-Components/livewire-powergrid#161]
**Describe the bug**

Hello. Anything obviously wrong with my PowerGridComponent class below? I've read a couple of the other issues concerning search, and looked at the _DishesTable_ and _DishesTableWithJoin_ examples, but I'm still stuck.

I have both the search_term_id and 'term' columns (term is a join on another table, however this doesn't seem to matter) set as searchable, but only search_term_id is ever examined - i.e. searching for text in the other columns returns zero results, and when I monitor the DB queries that are running, only one field is checked:

    select count(*) as aggregate from `google_monthly_searches` inner join `search_terms` on `search_term_id` = `search_terms`.`id` where ((`google_monthly_searches`.`search_term_id` like "%foo%")

If I turn off searching on search_term_id, *LIKE* disappears from the SQL statement completely, it's not assigned to another field.  
And if I try on the 'geotarget' field, which isn't a join on another table, that doesn't work either.

Thanks!

```
    public string $term_ids;
    public string $geo;

    public array $perPageValues = [15, 25, 100, 250];

    */
    public function datasource(): ?Builder
    {
        $query = GoogleMonthlySearch::query()
            ->join('search_terms', function ($search_terms) {
                $search_terms->on('search_term_id', '=', 'search_terms.id');
            });

        isset($this->term_ids) && $query->whereIn('search_term_id', explode(',', $this->term_ids));
        isset($this->geo) && $query->whereIn('geotarget', explode(',', $this->geo));

        $query->select('date', 'searches', 'geotarget', 'search_term_id', 'search_terms.term');
        return $query;
    }

    public function relationSearch(): array
    {
        return [];
    }

    public function addColumns(): ?PowerGridEloquent
    {
        $countries = WikiStat::loadCountryList();

        return PowerGrid::eloquent()
            ->addColumn('geotarget_fmt', function (GoogleMonthlySearch $model) use ($countries) {
                if (! empty($model->geotarget)) {
                    $output = $countries['alpha2_names'][$model->geotarget]
                        . " (" . $model->geotarget . ")" ?? $model->geotarget;
                } else {
                    $output = 'all';
                }
                return $output;
            })
            ->addColumn('date_formatted', function (GoogleMonthlySearch $model) {
                return Carbon::parse($model->date)->format('Y F');
            })
            ->addColumn('searches_fmt', function (GoogleMonthlySearch $model) {
                return number_format($model->searches);
            });
    }

    public function columns(): array
    {
        return [
            Column::add()
                ->title(__('Term ID'))
                ->field('search_term_id')
                ->sortable()
                ->searchable(),

            Column::add()
                ->title(__('Term'))
                ->field('term')
                ->sortable()
                ->searchable()
                ->clickToCopy(true, 'Copy to clipboard'),

            Column::add()
                ->title(__('Country'))
                ->field('geotarget_fmt')
                ->sortable(),

            Column::add()
                ->title(__('Month'))
                ->field('date_formatted'),

            Column::add()
                ->title(__('Searches'))
                ->field('searches')
                ->sortable()
                ->hidden()
                ->visibleInExport(true),

            Column::add()
                ->title(__('Monthly Searches'))
                ->field('searches_fmt')
                ->bodyAttribute('text-right')
                ->sortable('searches')
                ->clickToCopy(true, 'Copy to clipboard')
                ->visibleInExport(false),

            Column::add()
                ->title(__('Updated at'))
                ->field('updated_at')
                ->hidden()
                ->visibleInExport(true),

            Column::add()
                ->title(__('Updated at'))
                ->field('updated_at_formatted')
                ->hidden()
                ->visibleInExport(true),
        ];
    }

```

**Powergrid version:**
1.4.7 (on the main branch)

**Laravel version (exactly):**
* 8.73.2

**PHP version:**
* 8.0.12
 
**Alpine version:**
not sure?

**Theme:**
- Tailwind

**Comment by luanfreitasdev** [comment]
Hi @wturrell , Can you upgrade to v1.5.0 ?

Thanks

**Comment by wturrell** [comment]
@luanfreitasdev this doesn't seem to have made any difference: the ``LIKE`` is still only on ``search_term_id``.  (I renamed my published powergrid views to try and rule that out.)

**Comment by luanfreitasdev** [comment]
@wturrell . Can you test on this branch? `composer require power-components/livewire-powergrid dev-tests`

I believe I have fixed this problem.

Thanks.

**Comment by wturrell** [comment]
@luanfreitasdev that seems to work, thanks!

For anyone else reading this, for columns that use a join, you need to specifying the table and column with dot notation in the second argument of ->field(): 

```
    ->field("term",'search_terms.term')
    ->sortable()
    ->searchable()
```

The source code starts here: https://github.com/Power-Components/livewire-powergrid/blob/main/src/Helpers/Model.php#L300

or here if you're using a Collection: https://github.com/Power-Components/livewire-powergrid/blob/main/src/Helpers/Collection.php#L380
