### ISSUE TITLE
Sort by join column - correct method?

### ISSUE THREAD

**Issue by wturrell** [Power-Components/livewire-powergrid#162]
The [docs here](https://livewire-powergrid.docsforge.com/main/datasource/#sort-by-join-column) say that you can specify the table name as a second parameter of ->field(), e.g.

    ->field('category_name', 'categories.name')

however this seems to be out of date, as that method only has one property, $field (``$this->field = $field; return $this;``)

The ``->sortable()`` method does have a parameter, $tableWithColumn (which kind of makes more sense), except regardless of what I supply I still get an SQL error when trying to sort, e.g. 

```
            Column::add()
                ->title(__('Term'))
                ->field('term')
                ->sortable('search_terms.term')
                ->searchable()
                ->clickToCopy(true, 'Copy to clipboard'),
```

produces:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'google_monthly_searches.term' in 'order clause' (SQL: select `date`, `searches`, `geotarget`, `search_term_id`, `term` from `google_monthly_searches` inner join `search_terms` on `search_term_id` = `search_terms`.`id` order by `google_monthly_searches`.`term` asc limit 15 offset 30)

Note - having read #111, "term" isn't an ambiguous field, it's only in the joined table.

I tried changing field('term') to field('search_term.terms') and sortable to sortable() - that allowed sorting but wiped all the values.  
Using 'as' for the field in $query->select() doesn't seem to help either.

Have I missed something?

It's a hasOne relationship:

```
    public function term()
    {
        return $this->hasOne(SearchTerm::class, 'id', 'search_term_id' );
    }
```

This is with:

PowerGrid 1.4.7  
Laravel 8.73.2  
PHP 8.0.12
Tailwind 

Thank you…

**Comment by luanfreitasdev** [comment]
Hi @wturrell , Can you upgrade to v1.5.0 ?

**Comment by wturrell** [comment]
@luanfreitasdev done. This worked after:

- adding ``public string $sortField = 'google_monthly_searches.id';`` to the class
- replacing cols.blade.php in /resources/ with the new version in vendor

Thanks.
