### ISSUE TITLE
Call to an undefined method

### ISSUE THREAD

**Issue by imfaisii** [Power-Components/livewire-powergrid#1622]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

5.9.0

### Laravel

10.48

### Livewire

3.5

### Alpine JS

3.14

### Theme

Tailwind 3.x

### Describe the bug.

I tried creating a powergrid table using eloquent builder and found this bug.

![image](https://github.com/user-attachments/assets/8b640cd3-9609-44d2-8d32-5193bb8f2622)

### To Reproduce...

Just run php artisan powergrid:create enter table name and select eloquent builder

### Extra information

```markdown
<?php
 //...
```

**Comment by imfaisii** [comment]
@luanfreitasdev I am not able to create table, if there are 2 or more models. If there is only User model it creates, else throws this exception.

**Comment by luanfreitasdev** [comment]
Hi!, in Windows, the model name should be with full namespace. For now, I will close this issue and we can talk about whether or not this is a problem in the discussions.

Thank you
