### ISSUE TITLE
Class "PowerComponents\LivewirePowergrid\Detail" not foundTitle

### ISSUE THREAD

**Issue by budi77** [Power-Components/livewire-powergrid#1626]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

5.9

### Laravel

11

### Livewire

3

### Alpine JS

3

### Theme

Bootstrap

### Describe the bug.

Tried using DETAIL as per instruction in the  documentation but i got Class "PowerComponents\LivewirePowergrid\Detail" not found
.  use PowerComponents\LivewirePowergrid\Detail; already added 

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hi, this should work fine. Try cleaning composer with composer dump-autoload

Thanks
