### ISSUE TITLE
Datasource with union statement

### ISSUE THREAD

**Issue by Epitaffio** [Power-Components/livewire-powergrid#1628]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### PHP Version

8.3

### PowerGrid

5.8.0

### Laravel

11.10

### Livewire

3.5.0

### Theme

Tailwind 3.x

### Describe the bug.

Hey there,

I have a problem using an union statement, this is my code
```php 
public function datasource()
    {
        $table1 = Table1::query()
            ->select('name', 'desc', 'date');

        return Table2::query()
            ->select('name', 'desc', 'date')
            ->union($table1);
    }
 ```

that generate this query
```sql

select
  count(*) as aggregate
from
  (
    select
      *
    from
      (
        select name, desc, date
        from table1
      ) as temp_table
    union
    select
      *
    from
      (
        select name, desc, date
        from table2
      ) as temp_table
    order by
      date desc
  ) as temp_table

 ```

that give me this error:
```
SQLSTATE[42000]: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified. 
```

Anyone had any luck with the union statement?

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
PowerGrid does not yet support SQL Server.

If you find a solution, you can just submit a pull request.

Thanks!
