### ISSUE TITLE
when clear search filter all filters clear

### ISSUE THREAD

**Issue by mohammadtarabishy** [Power-Components/livewire-powergrid#163]
**Describe the bug**

class TicketTable extends PowerGridComponent
{
    use ActionButton;

    /*
    |--------------------------------------------------------------------------
    |  Features Setup
    |--------------------------------------------------------------------------
    | Setup Table's general features
    |
    */
    public function setUp()
    {
        $this->showPerPage()
            ->showRecordCount()
            ->showExportOption('download', ['excel', 'csv']);
    }

    /*
    |--------------------------------------------------------------------------
    |  Datasource
    |--------------------------------------------------------------------------
    | Provides data to your Table using a Model or Collection
    |
    */
    public function datasource(): ?Builder
    {

        return Ticket::query()->join('app_users', function ($app_users) {
            $app_users->on('tickets.app_user_id', '=', 'app_users.id');
        })->select([
            'tickets.id',
            'tickets.app_user_id',
            'tickets.ticket_type',
            'tickets.communication_channel',
            'tickets.ticket_status',
            'tickets.ticket_priority',
            'tickets.related_to',
            'tickets.Feedback',
            'tickets.Description',
            'tickets.call_date',
            'tickets.created_at',
            'app_users.name as name',
        ]);
    }

    /*
    |--------------------------------------------------------------------------
    |  Relationship Search
    |--------------------------------------------------------------------------
    | Configure here relationships to be used by the Search and Table Filters.
    |
    */
    public function relationSearch(): array
    {
        return ['appUser' => [ // relationship on dishes model
            'name', // column enabled to search
        ]];
    }

    /*
    |--------------------------------------------------------------------------
    |  Add Column
    |--------------------------------------------------------------------------
    | Make Datasource fields available to be used as columns.
    | You can pass a closure to transform/modify the data.
    |
    ,
    */
    public function addColumns(): ?PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ->addColumn('account_name')
            ->addColumn('ticket_type')
            ->addColumn('communication_channel')
            ->addColumn('ticket_status')
            ->addColumn('ticket_priority')
            ->addColumn('related_to')
            ->addColumn('Feedback', function (Ticket $model) {
                if ($model->Feedback === '0' || $model->Feedback === '1'||$model->Feedback === '2') {
                    return '<span class="fa fa-star"></span>';
                } elseif ($model->Feedback === '3' || $model->Feedback === '4') {
                    return '<span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>';
                } elseif ($model->Feedback === '5' || $model->Feedback === '6') {
                    return '<span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                             <span class="fa fa-star"></span>';
                } elseif ($model->Feedback === '7' || $model->Feedback === '8') {
                    return '<span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                             <span class="fa fa-star"></span>
                             <span class="fa fa-star"></span>';
                } elseif ($model->Feedback === '9' || $model->Feedback === '10') {
                    return '<span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                             <span class="fa fa-star"></span>
                             <span class="fa fa-star"></span>
                             <span class="fa fa-star"></span>';
                }

            })
            ->addColumn('call_date_formatted', function (Ticket $model) {
                return Carbon::parse($model->call_date)->format('d/m/Y H:i:s');
            })
            ->addColumn('Description')
            ->addColumn('created_at_formatted', function (Ticket $model) {
                return Carbon::parse($model->created_at)->format('d/m/Y H:i:s');
            });
    }

    /*
    |--------------------------------------------------------------------------
    |  Include Columns
    |--------------------------------------------------------------------------
    | Include the columns added columns, making them visible on the Table.
    | Each column can be configured with properties, filters, actions...
    |
    */
    public function columns(): array
    {
        return [

            Column::add()
                ->title(__('Account Name'))
                ->field('name')
                ->sortable()
                ->searchable()
                ->makeInputText('name')
                ->headerAttribute('', 'font-size:12px'),

            Column::add()
                ->title(__('TICKET TYPE'))
                ->field('ticket_type')
                ->searchable()
                ->headerAttribute('', 'font-size:12px')
                ->makeInputText('ticket_type'),

            Column::add()
                ->title(__('COMMUNICATION CHANNEL'))
                ->field('communication_channel')
                ->searchable()
                ->headerAttribute('', 'font-size:12px')
                ->makeInputText('communication_channel'),

            Column::add()
                ->title(__('TICKET STATUS'))
                ->field('ticket_status')
                ->editOnClick(true)
                ->searchable()
                ->headerAttribute('', 'font-size:12px')
                ->makeInputText('ticket_status'),

            Column::add()
                ->title(__('TICKET PRIORITY'))
                ->field('ticket_priority')
                ->searchable()
                ->headerAttribute('', 'font-size:12px')
                ->makeInputText('ticket_priority'),

            Column::add()
                ->title(__('RELATED TO'))
                ->field('related_to')
                ->searchable()
                ->headerAttribute('', 'font-size:12px')
                ->makeInputText('related_to'),

            Column::add()
                ->title(__('FEEDBACK'))
                ->field('Feedback')
                ->searchable()
                ->bodyAttribute('text-center', 'color:	#FFFF00')
                ->headerAttribute('', 'font-size:12px')
                ->makeInputText('Feedback'),

            Column::add()
                ->title(__('CALL DATE'))
                ->field('call_date_formatted')
                ->searchable()
                ->sortable()
                ->headerAttribute('', 'font-size:12px')
                ->makeInputDatePicker('call_date'),

            Column::add()
                ->title(__('DESCRIPTION'))
                ->field('Description')
                ->searchable()
                ->headerAttribute('', 'font-size:12px')
                ->makeInputText('Description'),

            Column::add()
                ->title(__('CREATED AT'))
                ->field('created_at_formatted')
                ->searchable()
                ->sortable()
                ->headerAttribute('', 'font-size:12px')
                ->makeInputDatePicker('created_at'),

        ];
    }

    /*
    |--------------------------------------------------------------------------
    | Actions Method
    |--------------------------------------------------------------------------
    | Enable this section only when you have defined routes for these actions.
    |
    */

    /*
    public function actions(): array
    {
       return [
           Button::add('edit')
               ->caption(__('Edit'))
               ->class('bg-indigo-500 text-white')
               ->route('ticket.edit', ['ticket' => 'id']),

           Button::add('destroy')
               ->caption(__('Delete'))
               ->class('bg-red-500 text-white')
               ->route('ticket.destroy', ['ticket' => 'id'])
               ->method('delete')
        ];
    }
    */

    /*
    |--------------------------------------------------------------------------
    | Edit Method
    |--------------------------------------------------------------------------
    | Enable this section to use editOnClick() or toggleable() methods
    |
    */

//    /*
    public function update(array $data): bool
    {
        try {
            $updated = Ticket::query()->find($data['id'])->update([
                $data['field'] => $data['value']
            ]);
        } catch (QueryException $exception) {
            $updated = false;
        }
        return $updated;
    }

    public function updateMessages(string $status, string $field = '_default_message'): string
    {
        $updateMessages = [
            'success' => [
                '_default_message' => __('Data has been updated successfully!'),
                //'custom_field' => __('Custom Field updated successfully!'),
            ],
            'error' => [
                '_default_message' => __('Error updating the data.'),
                //'custom_field' => __('Error updating custom field.'),
            ]
        ];

        return ($updateMessages[$status][$field] ?? $updateMessages[$status]['_default_message']);
    }

    public function template(): ?string
    {
        return null;
    }

}

// bug
when i search in name and after that i search in feedback ,when i clear search in feadback all filters cleard 
//

**To Reproduce**
* Got to ..

**Laravel version (exactly):**
* 8.1 
 
**Alpine version:**
* 3.x.x ?

**Theme:**
- [ ] Tailwind 
   - Version:        
      
- [x] Bootstrap
   - Version:        

**Screenshots** (***This helps to understand better***)

**Do you have any idea how we can fix it?**

**Comment by luanfreitasdev** [comment]
Hi @mohammadtarabishy .

I have not been able to reproduce this situation..

Can you do a demo? What versions are you using. Do you have the vendor folder in resources?

**Comment by mohammadtarabishy** [comment]
yes i have the vendor folder 
and using version 1.4

**Comment by mohammadtarabishy** [comment]
is solved the problem 
in trait filter 
code was clear all filters and clear the search
cod pefore :
public function clearFilter(string $field = ''): void
    {

        $this->serch='';
        unset($this->enabledFilters[$field]);
        unset($this->filters['number'][$field]);
        unset($this->filters['input_text'][$field]);
        unset($this->filters['boolean'][$field]);
        unset($this->filters['input_text_options'][$field]);

        $this->filters = [];
    }
cod after 👍 
public function clearFilter(string $field = ''): void
    {

      
        unset($this->enabledFilters[$field]);
        unset($this->filters['number'][$field]);
        unset($this->filters['input_text'][$field]);
        unset($this->filters['boolean'][$field]);
        unset($this->filters['input_text_options'][$field]);

        
    }

**Comment by luanfreitasdev** [comment]
as this is the expected behavior I am closing the issue
