### ISSUE TITLE
Alpine Expression Error: pgFlatpickr is not defined & Uncaught ReferenceError: pgFlatpickr is not defined

### ISSUE THREAD

**Issue by nazaruuyee** [Power-Components/livewire-powergrid#1635]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes
![image](https://github.com/user-attachments/assets/07548edb-881e-4124-917b-6771f08fca7f)
![image](https://github.com/user-attachments/assets/92e7e29f-46a5-4947-98d2-ab8ccf966080)

### PowerGrid

v5.5.0

### Laravel

v10.48.10

### Livewire

v3.4.12

### Theme

Bootstrap

### Describe the bug.

Hi..

This error causing datepicker & datetimepicker doesn't show in powergrid filter.

![image](https://github.com/user-attachments/assets/d140a829-9b17-4684-a2ad-85664c08255f)

Whereas, I checked in vendor/power-components/livewire-powergrid/resources/js/components/ there is pg_flatpickr.js there.

So, I'm sure, powergrid 5.5 already include the pgFlatpickr.
also, I already try install flatpicker using NPM, but no difference.
same as this [discussion ](https://github.com/Power-Components/livewire-powergrid/discussions/1571)

Thank you in advance for the assistance

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
This may be related to the powergrid js import.

https://livewire-powergrid.com/get-started/powergrid-configuration.html#_1-import-javascript-assets

**Comment by nazaruuyee** [comment]
> This may be related to the powergrid js import.
> 
> https://livewire-powergrid.com/get-started/powergrid-configuration.html#_1-import-javascript-assets

Yess... you right.. Thank you @luanfreitasdev , daterangepicker now is worked...
