### ISSUE TITLE
Pagination UI Glitch

### ISSUE THREAD

**Issue by Uhasith** [Power-Components/livewire-powergrid#1649]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

5.10.2

### Laravel

11.20.0 

### Livewire

 3.5.6

### Alpine JS

3.0.1

### Theme

Tailwind 3.x

### Describe the bug.

I did upgrade to the latest version. Paginations have some UI glitches and it's not working when i try to visit last page of the records. 

<img width="1292" alt="Screenshot 2024-08-20 at 09 37 05" src="https://github.com/user-attachments/assets/9a051d90-3faa-4784-bcbc-79831ef380be">

### Extra information

```markdown
<?php

namespace App\Livewire;

use App\Models\Product;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Blade;
use Illuminate\View\View;
use PowerComponents\LivewirePowerGrid\Column;
use PowerComponents\LivewirePowerGrid\Footer;
use PowerComponents\LivewirePowerGrid\Header;
use PowerComponents\LivewirePowerGrid\PowerGrid;
use PowerComponents\LivewirePowerGrid\PowerGridComponent;
use PowerComponents\LivewirePowerGrid\PowerGridFields;
use PowerComponents\LivewirePowerGrid\Responsive;
use PowerComponents\LivewirePowerGrid\Traits\WithExport;
use WireUi\Traits\WireUiActions;

final class ProductTable extends PowerGridComponent
{
    use WireUiActions;
    use WithExport;

    public string $tableName = 'ProductTable';

    public function setUp(): array
    {
        // $this->showCheckBox();

        return [
            Responsive::make(),
            Header::make()
                ->showToggleColumns()
                ->showSearchInput(),
            Footer::make()
                ->showPerPage()
                ->showRecordCount(),
        ];
    }
```
```

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v5.10.3

Thanks!
