### ISSUE TITLE
Error if model primary key is UUID

### ISSUE THREAD

**Issue by diazsasak** [Power-Components/livewire-powergrid#166]
**Describe the bug**
Hi, i have a eloquent model that use uuid as the primary key. Then i got error on the javascript.

**Laravel version (exactly):**
* 8.x.x
 
**Alpine version:**
* 3.x.x

**Theme:**
- [ ] Tailwind 
   - Version:  2      

**Screenshots** (***This helps to understand better***)

![image](https://user-images.githubusercontent.com/7880137/143970887-9bd075cd-a29b-4cc2-a23d-2da3a6fac071.png)

**Do you have any idea how we can fix it?**

I think because the uuid is a string and on the error line it doesn't have quote because by default we assume the id is auto increment which is integer?

**Comment by luanfreitasdev** [comment]
Hi @diazsasak .

This shouldn't work so far, I'm doing the correction and warning around here when I release a release with this during the week..

Thanks

**Comment by diazsasak** [comment]
Hi @luanfreitasdev ,

Thank you for your help!
