### ISSUE TITLE
Title: Missing Showing x of y from z

### ISSUE THREAD

**Issue by gopalwebdev** [Power-Components/livewire-powergrid#168]
Message: When we use bootstrap theme then we are not able to see the Showing x of y from Z unlink tailwind theme.

**Comment by luanfreitasdev** [comment]
Hello @gopalwebdev . Can you give more information, screenshots, logs?

**Comment by gopalwebdev** [comment]
@luanfreitasdev  I've attached the screenshot. We are using bootstrap4 based adminlte(v3). The total no of records is not showing. Could you please check the blade. The particular component is not there for bootstrap. If we enable tailwind, it's showing. Even though we tried with  bootstrap5, it is not showing at all. It would be better, if you can add total no of records at the bottom. 
![Screenshot from 2021-12-03 23-25-01](https://user-images.githubusercontent.com/78777044/144650814-fb364ed0-2caf-4245-ac85-a2cd9e551aef.png)

**Comment by luanfreitasdev** [comment]
Hello @gopalwebdev , Algen2203 opened a [PR](https://github.com/Power-Components/livewire-powergrid/pull/170) that I believe will fix most cases, I don't know if it will work with bootstrap4 but it's already a huge gain for the bootstrap community.

**Comment by gopalwebdev** [comment]
Thank you :)

**Comment by luanfreitasdev** [comment]
Hi @gopalwebdev . available on [v1.5.1](https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.5.0)
