### ISSUE TITLE
Create powergrid command error when Namespace is not default

### ISSUE THREAD

**Issue by elfeffe** [Power-Components/livewire-powergrid#17]
When we use 
php artisan powergrid:create Blog/Admin/Taxonomy/TaxonomyTable --model="App\Models\Taxonomy"

It creates a wrong namespace, and a wrong class name.

I think you can use something like             

preg_match_all('/(.*)\/(.*)/', $tableName, $matches);

The last item in $matches will be class name, and the one before is the namespace. 

I can send a PR, but I'm not sure if you like this solution.

**Comment by luanfreitasdev** [comment]
Olá @elfeffe , I found the question interesting!

feel free to send the PR,

Thank's 👍🏻
