### ISSUE TITLE
Issue with pagination after deleting records

### ISSUE THREAD

**Issue by Reefcrazed** [Power-Components/livewire-powergrid#1714]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.3.9

### PowerGrid

5.10

### Laravel

11

### Livewire

3.5.6

### Alpine JS

3.14.1

### Theme

Tailwind 3.x

### Describe the bug.

When using pagination, if you go to the last pagination page but then delete records on the last page you are left with a page saying no records exist, but they do. There will be no way to navigate back.

For instance, lets say you are showing 8 records per page but have 10 records and go the last page (page 2), delete records 9 and 10, you are left with a page saying "no records" and there is no way of getting back to page 1 unless you change the URL in the browser. I am including screenshots.

![paginate_1](https://github.com/user-attachments/assets/4aedcaab-b12a-4349-bb7a-e9911e1d4672)

![paginate_2](https://github.com/user-attachments/assets/f1eee623-c01c-4433-aa0c-e507ce9422a2)

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by Reefcrazed** [comment]
This appears to be behaving the same, I am using v.6.06.  Even on v6.0.6, if I am on page 2 and delete all the records on page 2, it stays on page 2. Should it not go back to page 1?

**Comment by luanfreitasdev** [comment]
The default behavior is to show the option to go back

![image](https://github.com/user-attachments/assets/b0c3eee7-ad8d-4822-9130-a656feac074e)

**Comment by Reefcrazed** [comment]
Thanks!
