### ISSUE TITLE
View [components.frameworks.bootstrap5.toggle-detail-responsive] not found. while enable Responsive

### ISSUE THREAD

**Issue by harendra2021** [Power-Components/livewire-powergrid#1715]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

When I enabled Responsive(https://livewire-powergrid.com/table-component/component-configuration.html#responsive-table). I am getting below error
View [components.frameworks.bootstrap5.toggle-detail-responsive] not found.
<img width="914" alt="responsive-bug" src="https://github.com/user-attachments/assets/e7cd55ac-4b66-4981-b854-2666c02d6f6e">

### PHP Version

8.2

### PowerGrid

5.6

### Laravel

11.0

### Livewire

3.4

### Theme

Bootstrap

### Describe the bug.

When I enabled Responsive(https://livewire-powergrid.com/table-component/component-configuration.html#responsive-table). I am getting below error
View [components.frameworks.bootstrap5.toggle-detail-responsive] not found.
<img width="914" alt="responsive-bug" src="https://github.com/user-attachments/assets/e7cd55ac-4b66-4981-b854-2666c02d6f6e">

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Unfortunately, this feature is not available for bootstrap.
