### ISSUE TITLE
Ability to change footer classes using theming

### ISSUE THREAD

**Issue by sammyaxe** [Power-Components/livewire-powergrid#1717]
# ⚡ PowerGrid ⚡ Feature Request

## Summary

Right now there is no way to use theme to remove bg-white from tailwind version of footer

<img width="1161" alt="Screenshot 2024-10-06 at 4 54 30 PM" src="https://github.com/user-attachments/assets/bd9caeb7-72e0-46a3-8f5e-fa2b9e9938e5">

Brief description of what is at stake.

### Why is this needed?

Extermely hard to make table work in dark mode

### Suggested Solution(s)

Add ability to change classes such as border color, bg color etc

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v6.0.3
