### ISSUE TITLE
WithExport trait seems to be referring to wrong class

### ISSUE THREAD

**Issue by sammyaxe** [Power-Components/livewire-powergrid#1718]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

6.0

### Laravel

11

### Livewire

3

### Describe the bug.

Added with Export trait, tried to set it up using `use PowerComponents\LivewirePowerGrid\Exportable;` as indicated in documentation, but later found conflicting example of `use PowerComponents\LivewirePowerGrid\Components\SetUp\Exportable;` whcih then makes button available in the UI.

however when clicking on the button I then get an error
```Class "PowerComponents\LivewirePowerGrid\Exportable" not found``` inside WithExport trait.

It does seem like Exportable class was refactored to another folder, but Trait was never updated. 

After manually adding:

```
use PowerComponents\LivewirePowerGrid\Components\SetUp\Exportable;
use PowerComponents\LivewirePowerGrid\DataSource\ProcessDataSource;
use PowerComponents\LivewirePowerGrid\DataSource\Processors\DataSourceBase;
```

error goes away it seems.

**Comment by luanfreitasdev** [comment]
Fixed. Thank you!
