### ISSUE TITLE
Unable to find component: [tes.user] 

### ISSUE THREAD

**Issue by abhideshpande** [Power-Components/livewire-powergrid#1720]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

 http://admin.prakalpmitram.in/org/verticals 500 (Internal Server Error)

### PHP Version

 8.3.12

### PowerGrid

5.10.7

### Laravel

10.48.22

### Livewire

3.5.6   

### Alpine JS

3.14.1

### Theme

Tailwind 3.x

### Describe the bug.

Component is not loading
php artisan powergrid:create
     __     ____                          ______     _     __
    / /_,  / __ \____ _      _____  _____/ ____/____(_)___/ /
    /_ ,' / /_/ / __ \ | /| / / _ \/ ___/ / __/ ___/ / __  / 
    /'   / ____/ /_/ / |/ |/ /  __/ /  / /_/ / /  / / /_/ /  
        /_/    \____/|__/|__/\___/_/   \____/_/  /_/\__,_/     

 ┌ Enter a name for your new PowerGrid Component: ──────────────┐
 │ tes/user                                                     │
 └──────────────────────────────────────────────────────────────┘

 ┌ Select your preferred Data source: ──────────────────────────┐
 │ Eloquent Builder                                             │
 └──────────────────────────────────────────────────────────────┘

 ┌ Select a Model or enter its Fully qualified name. ───────────┐
 │ App\Models\Role                                              │
 └──────────────────────────────────────────────────────────────┘

 ┌ Auto-import Data Source fields from $fillable in [Role] Model? ┐
 │ Yes                                                            │
 └────────────────────────────────────────────────────────────────┘

 ⚡ user was successfully created at [app/Livewire/tes/user.php].

 💡 include the user component using the tag: <livewire:tes.user/>

[2024-10-09 12:49:26] local.ERROR: Unable to find component: [tes.user] {"userId":3,"exception":"[object] (Livewire\\Exceptions\\ComponentNotFoundException(code: 0): Unable to find component: [tes.user] at /var/www/prakalpmitram.eproplus.in/vendor/livewire/livewire/src/Mechanisms/ComponentRegistry.php:116)
[stacktrace]

### To Reproduce...

create component like about

### Extra information

```markdown
<?php
 //...
```

**Comment by johannesMEGABAD** [comment]
Well.. how Livewire works you created the component with the name "**tes/user**".

In that you would need to to type the following to include it: **<livewire:tes.user />**

Depending on the folder structure of your project you would need to update the location inside the Livewire-Tag (remember the dot-notation for nested paths)

**Comment by abhideshpande** [comment]
Hi @johannesMEGABAD , 
Thanks a lot for revert.

Please consider following for more investingation

I have created component 

# find . -depth -name "user.php"
./app/Livewire/tes/user.php
using the commands in above 
Now I want to use it in 
# pwd
/var/www/prakalpmitram.eproplus.in/resources/views/security/role
root@eproplus:/var/www/prakalpmitram.eproplus.in/resources/views/security/role# ls -lrt
total 4
-rw-r--r-- 1 root root 2281 Oct 10 10:18 index.blade.php

Now the blade file looks like
<x-app-layout>
    <x-slot name="header">
        <x-ui.layouts.header title="{{ __('Roles') }}" desc="Roles for Users and Permission" icon="phosphor-user-list" />
    </x-slot>

    <x-ui.layouts.base-form>

        @livewire('tes.user')
        <div id="container">
            <div id="roleGrid"></div>
        </div>
        <script>
            var ele = document.getElementById('container');
            if (ele) {
                ele.style.visibility = "visible";
            }
        </script>
    </x-ui.layouts.base-form>
</x-app-layout>



In Laravel log I am getting following
[2024-10-10 10:18:14] local.ERROR: Unable to find component: [tes.user] {"userId":3,"exception":"[object] (Livewire\\Exceptions\\ComponentNotFoundException(code: 0): Unable to find component: [tes.user] at /var/www/prakalpmitram.eproplus.in/vendor/livewire/livewire/src/Mechanisms/ComponentRegistry.php:116)
[stacktrace]
#0 /var/www/prakalpmitram.eproplus.in/vendor/livewire/livewire/src/Mechanisms/ComponentRegistry.php(25): Livewire\\Mechanisms\\ComponentRegistry->getNameAndClass()
#1 /var/www/prakalpmitram.eproplus.in/vendor/livewire/livewire/src/LivewireManager.php(58): Livewire\\Mechanisms\\ComponentRegistry->new()
#2 /var/www/prakalpmitram.eproplus.in/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(43): Livewire\\LivewireManager->new()
#3 /var/www/prakalpmitram.eproplus.in/vendor/livewire/livewire/src/LivewireManager.php(73): Livewire\\Mechanisms\\HandleComponents\\HandleComponents->mount()
#4 /var/www/prakalpmitram.eproplus.in/storage/framework/views/380a74b94d2cd2d06ccbab0a4dcf07e7.php(51): Livewire\\LivewireManager->mount()
#5 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(123): require('...')
#6 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#7 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#8 /var/www/prakalpmitram.eproplus.in/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(22): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#9 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(72): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->evaluatePath()
#10 /var/www/prakalpmitram.eproplus.in/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(10): Illuminate\\View\\Engines\\CompilerEngine->get()
#11 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/View/View.php(207): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->get()
#12 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\\View\\View->getContents()
#13 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\\View\\View->renderContents()
#14 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()
#15 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()
#16 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Routing/Router.php(918): Illuminate\\Http\\Response->__construct()
#17 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Routing/Router.php(885): Illuminate\\Routing\\Router::toResponse()
#18 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Routing\\Router->prepareResponse()
#19 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#20 /var/www/prakalpmitram.eproplus.in/app/Http/Middleware/SubdomainUrlMiddleware.php(147): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): App\\Http\\Middleware\\SubdomainUrlMiddleware->handle()
#22 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Auth/Middleware/EnsureEmailIsVerified.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\EnsureEmailIsVerified->handle()
#24 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#26 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\AuthenticateSession->handle()
#28 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#30 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#32 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#34 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#36 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Session\\Middleware\\StartSession->handle()
#37 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#39 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#41 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\\Pipeline\\Pipeline->then()
#43 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\\Routing\\Router->runRouteWithinStack()
#44 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\\Routing\\Router->runRoute()
#45 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\\Routing\\Router->dispatchToRoute()
#46 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#47 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(144): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#48 /var/www/prakalpmitram.eproplus.in/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Livewire\\Features\\SupportDisablingBackButtonCache\\DisableBackButtonCacheMiddleware->handle()
#50 /var/www/prakalpmitram.eproplus.in/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#52 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#54 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#55 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#57 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#58 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#60 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#62 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle()
#64 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#66 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#68 /var/www/prakalpmitram.eproplus.in/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#69 /var/www/prakalpmitram.eproplus.in/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#70 {main}
"}

**Comment by johannesMEGABAD** [comment]
Did you actually wrote

`
**@livewire('tes.user')**
`

In your code or did you try to make it bold in the comment here? If you actually wrapped it try one of the other two ways:

- <livewire:tes.user />
- @livewire('tes.user')

How are you using Livewire? Did you add 

`
@livewireScriptConfig
`

To your app layout?

**Comment by abhideshpande** [comment]
Hi, I was doing bold in so it was **@livewire('tes.user')**, I used @livewire('tes.user') in code.
I am using livewire widely in my code

**Comment by luanfreitasdev** [comment]
Hello!. Try creating a component with any name and then you can rename it or change the folder.

Thanks
