### ISSUE TITLE
PowerGrid Caching Not Working with Laravel Livewire Listing

### ISSUE THREAD

**Issue by shrikhakhalasi-kombee** [Power-Components/livewire-powergrid#1722]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

6.0

### Laravel

11.9

### Livewire

3.5

### Theme

Bootstrap

### Describe the bug.

I'm working on a Laravel Livewire project where we are using PowerGrid for our data tables. I've recently upgraded to the latest version of PowerGrid, which supports default caching. Following the documentation steps, I have configured caching as described, but I'm not seeing the expected behavior—data is not being stored in the cache.

**Cache Driver**: I’ve set the cache driver to file.

**Setup**: I have enabled caching for the module as mentioned in the [documentation](https://livewire-powergrid.com/table-component/component-configuration.html#cache) and included the cache() method from the LivewirePowerGrid\Cache class in the component's setup() method.

### To Reproduce...

**Steps to Reproduce:**
Set up the caching in the component as per the documentation.
Enable the file cache driver in the config/cache.php file.
Load the data table in the Livewire component.

**Expected Behavior:**
The data should be cached and stored in the specified cache driver.

**Actual Behavior:**
The caching is not working as expected, and no data is being stored in the cache.

### Extra information

```markdown
<?php
 use PowerComponents\LivewirePowerGrid\Facades\PowerGrid;
 public function setUp(): array
    {
        // $this->showCheckBox();
        $cache = PowerGrid::cache()->prefix('user_');

        return [
            PowerGrid::header()
                ->showSearchInput(),
            PowerGrid::footer()
                ->showPerPage()
                ->showRecordCount(),
            PowerGrid::cache()
                ->customTag('users'),
        ];
    }
 

I have confirmed that the cache driver is correctly set up and that other parts of my application successfully use the file cache driver.
No error messages or exceptions are being thrown in the logs.
```

**Comment by luanfreitasdev** [comment]
Hello.

You need to add `ttl()` to set the cache lifetime

**Comment by shrikhakhalasi-kombee** [comment]
Hello @luanfreitasdev ,

I have tried adding `ttl()` also to the setup method, but it didn't work.

**Comment by jenishprajapati-kombee** [comment]
Hello, I am facing the same issue. When I set the following code in setUp, the data is not stored in cache and the query runs every time:

public function setUp(): array
    {        
        return [
           PowerGrid::cache() 
              ->ttl(600) 
              ->prefix('user_table'),  
        ]
   }

<img width="2048" height="536" alt="Image" src="https://github.com/user-attachments/assets/96603a64-38ac-4d6d-9ad0-7b8139e5a8ab" />
