### ISSUE TITLE
Cant filter when using Custom Field Blade Component 

### ISSUE THREAD

**Issue by nextstudioal** [Power-Components/livewire-powergrid#1727]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes,
Uncaught Snapshot missing on Livewire component with id: 2Yiy0BtOlId3jUfIrg0e

### PHP Version

PHP 8.2.0

### PowerGrid

6.0.2

### Laravel

11

### Livewire

3.5.10

### Theme

Tailwind 3.x

### Describe the bug.

I have a table where one of the fields is a custom Blade component. On first render everything is okay, but when using filters I get this error message on my web console: "Uncaught Snapshot missing on Livewire component with id: 2Yiy0BtOlId3jUfIrg0e" and the custom component disappears.  I tried it with a simple component that does not have props or anything, or adding keys to the parent div of the component but the issue persists.  

### Extra information

```markdown
This is how i have configured my custom component on the "fields" method:     

public function fields(): PowerGridFields
    {
        return PowerGrid::fields()
            ->add('client_id')
            ->add('first_name', function ($row) {
              
                return Blade::render('@livewire("ui::components.test-component")');
            })
         // other fields 
    }

This is the PHP class of my component: 
<?php

namespace Modules\UI\Livewire\Components;

use Livewire\Component;

class TestComponent extends Component
{

    public function render()
    {
        return view('ui::components.test-component');
    }

}


This is the blade of the component: 
<div>
    test
</div>
```

**Comment by luanfreitasdev** [comment]
Hello, it would be best if you used wire:key to manage livewire components in foreach loops

https://livewire.laravel.com/docs/components#adding-wirekey-to-foreach-loops

**Comment by ladushki** [comment]
Hi I have the same problem. Tried adding wire:key, same error.
