### ISSUE TITLE
Blade

### ISSUE THREAD

**Issue by NathanaelGT** [Power-Components/livewire-powergrid#173]
**Describe the bug**
1. https://github.com/Power-Components/livewire-powergrid/blob/2fc4279f4464039452bb0d1ba2d478a530933306/resources/views/components/frameworks/tailwind/enabled-filters.blade.php#L10
I think the correct syntax is `<span class="sr-only">{{ $filter['label'] }}</span> `
Let me know if this is intentional

2. https://github.com/Power-Components/livewire-powergrid/blob/2fc4279f4464039452bb0d1ba2d478a530933306/resources/views/components/frameworks/tailwind/multi-select.blade.php#L22-L23
And this `<div class="pl-0 align-middle cursor-pointer hover:text-black hover:text-current dark:text-gray-300 text-left text-xs font-medium text-gray-700 tracking-wider" x-model="options[option]" x-text="options[option].text"></div>`

3. https://github.com/Power-Components/livewire-powergrid/blob/2fc4279f4464039452bb0d1ba2d478a530933306/resources/views/components/frameworks/tailwind/multi-select.blade.php#L61
`class="absolute z-100 shadow top-100 border border-gray-300 bg-white z-50 w-full left-0 rounded max-h-select overflow-y-auto dark:bg-gray-700 dark:border-gray-400"` (lef-0 to left-0)

4. https://github.com/Power-Components/livewire-powergrid/blob/2fc4279f4464039452bb0d1ba2d478a530933306/resources/views/components/inline-filters.blade.php#L11
`<tr class="{{ $theme->table->trClass }}" style="{{ $theme->table->trStyle }}">`

5. https://github.com/Power-Components/livewire-powergrid/blob/2fc4279f4464039452bb0d1ba2d478a530933306/resources/views/components/row.blade.php#L38
I think the class should be configurable (`class="{{ $theme->row->spanClass }}"`?)

6. https://github.com/Power-Components/livewire-powergrid/blob/2fc4279f4464039452bb0d1ba2d478a530933306/resources/views/components/editable.blade.php#L27 https://github.com/Power-Components/livewire-powergrid/blob/2fc4279f4464039452bb0d1ba2d478a530933306/resources/views/components/row.blade.php#L12
Those `preg_replace`s are redundant, because it was handled by #146

**Theme:**
Tailwind  

**Screenshots** (***This helps to understand better***)
Original result (1):
![image](https://user-images.githubusercontent.com/32760797/144740391-f2443001-9058-43ba-a6b6-770ac217d8f6.png)
Modified result (1):
![image](https://user-images.githubusercontent.com/32760797/144740416-d329f4e9-f036-41cd-ac6e-3ad12a67fb09.png)

**Comment by luanfreitasdev** [comment]
Hi @NathanaelGT .

Then. Prevent xss attack #146 still allows displaying the script in the html even though it is invisible to the user. The preg_replace does not allow not passing before (in the case of script).

In row blade on line 12 prevents execution in other fields that are not editable.

In other cases the html passed unintentionally, can you send a PR?

Thanks

**Comment by NathanaelGT** [comment]
> Then. Prevent xss attack #146 still allows displaying the script in the html even though it is invisible to the user. The preg_replace does not allow not passing before (in the case of script).
> 
> In row blade on line 12 prevents execution in other fields that are not editable.

If the developer does not pass closure to `addColumn()`, the data will be automatically converted to HTML entities ([code](https://github.com/Power-Components/livewire-powergrid/pull/146/files#diff-590bf1d5c99a6d8b0e6a54ea57e22a4ae88a51ad39f5d8d668081db12526dea0R35)).
So, if there is a user by name `<script>alert('hello')</script>`, the name will be converted to `&lt;script&gt;alert(&quot;hello&quot;)&lt;/script&gt;`,
then it will be displayed as unescaped data ([row](https://github.com/Power-Components/livewire-powergrid/blob/main/resources/views/components/row.blade.php#L40), [editable](https://github.com/Power-Components/livewire-powergrid/pull/146/files#diff-c514ad3ff9b19657b8167631e9ae9c127388efe6b85df4e0a377419dd86f0f84R15))

so there will be no match for `#<script(.*?)>(.*?)</script>#is`.

However, if the developer does pass closure to `addColumn()`, then they need to wrap the data inside `e()` to prevent XSS
ex:
```
->addColumn('name_link', function (News $news) {
    return vsprintf('<a href="%s">%s</a>', [
        route('user.show', $user->id),
        e($user->name),
    ]);
})
```

**Comment by luanfreitasdev** [comment]
I agree, but not every user will. We have to deal with this on the inside

**Comment by NathanaelGT** [comment]
Fair enough
