### ISSUE TITLE
Problema paginação

### ISSUE THREAD

**Issue by PlimSistemas** [Power-Components/livewire-powergrid#1736]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.4

### PowerGrid

6.0.4

### Laravel

11.13.0

### Theme

Bootstrap

### Describe the bug.

Quando tem mais de uma página e muda a quantidade de registro por página, nenhum item é mostrado.

https://github.com/user-attachments/assets/488852ce-9778-4ff6-92d9-0f9d3c92fb82

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Thank you!. Fixed https://github.com/Power-Components/livewire-powergrid/pull/1742
