### ISSUE TITLE
in this 6 version much much issues.

### ISSUE THREAD

**Issue by sameerhabib72** [Power-Components/livewire-powergrid#1739]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### PHP Version

8.2.12

### PowerGrid

6

### Laravel

11.28.1

### Livewire

3.5.12

### Alpine JS

3.5.12

### Theme

Bootstrap

### Describe the bug.

in this 6 version much much issues not showing action buttons showing by default unknow message can same one help to install version of 5 because version 5 is working good  

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Please provide more details about what problems you are having.
