### ISSUE TITLE
Powergrid not clearing validation error after change in data

### ISSUE THREAD

**Issue by Reefcrazed** [Power-Components/livewire-powergrid#1747]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.3.0

### PowerGrid

6.0.0.

### Laravel

11.28

### Livewire

3.65.9

### Alpine JS

3.4.2

### Theme

Tailwind 3.x

### Describe the bug.

I have a powergrid populated with an eloquent datasource. We have a dropdown connected via livewire, basically a date filter. Lets say I am on 2023 and the data in powergrid is filtered through that year. I do an inline edit on row 1 of the data and that fails validation. Then I change the dropdown to 2024 and new data is loaded into the powergrid. At this point I cannot edit any data in the powergrid because it still seems to remember that validation has failed. The only way I can edit the grid is to either refresh the browser or change the dropdown to 2023. 

If there is a built in function to clear this error I cannot find it.  I tried $this->clearValidation() but that did not work. Also as a note, the documentation mentions $this->fillData() but that function does not seem to exist in v6.0.0, I seem to remember it being there in the prior release.

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by Reefcrazed** [comment]
I just found a similar issue. If I have data in the grid and there is a validation error, but then I call a delete on the row in eloquent, the row does delete but you can no longer edit the table, all changes are locked out until I refresh the browser window.

**Comment by luanfreitasdev** [comment]
Do you know if this happens in the demo? If not, could you demonstrate this in a short video?

Thanks

**Comment by Reefcrazed** [comment]
Here you go.  The way this is setup, there is a livewire page with the two dropdowns, the powergrid component uses the values from those dropdowns to run the eloquent query. Since a new query is run, it is unexpected for the powergrid component to even know about the old data, I tried clearing the errorbag and cleared the validation errors, but field remains locked where I cannot edit.

You will notice in the video I start by giving it a validation error on quarter 4, but then go to quarter 1 and I cannot edit quarter 1 until I go back to quarter 4. My worry is the user may mistakenly not remember or notice they had a validation error.

https://github.com/user-attachments/assets/b8009970-4314-4ba4-b6b5-5d593175709e

**Comment by luanfreitasdev** [comment]
Could you create a public repository simulating this behavior? I see that you are using external filters with validations and I have never done it that way. Thank you

**Comment by Reefcrazed** [comment]
Sure thing, it is a very rough project, just for test.  They payment model should be easy to figure out, three columns [id, payment_date, payment_amount]

https://github.com/Reefcrazed/PowerGridTest/tree/main

**Comment by luanfreitasdev** [comment]
I think the repository is incomplete for testing

**Comment by Reefcrazed** [comment]
Is it because I was using an external database? Is that the issue? If I know why you say it is incomplete, I can fix it.

**Comment by luanfreitasdev** [comment]
Add the missing data tables (models) for queries with the seeder please 😀

**Comment by Reefcrazed** [comment]
I added a migration for the payment table, instead of doing a seeder I have migration put in static data, it will make more sense instead of random data. Check my last commit.

**Comment by luanfreitasdev** [comment]
I looked, and this is a limitation of the PowerGrid component, not a bug. The best solution for this case would be to create and inject a new component instead of using the native one.

Anyway, I will redo this editing component in the future.

Thank you

**Comment by Reefcrazed** [comment]
Can you elaborate when you say "inject a new component instead of using the native one"

**Comment by luanfreitasdev** [comment]
You can create a new Alpine component using column macros like this:

```php
Column::macro('customEditable', function (
      bool $hasPermission,
  ) {
      $this->customContent['view']   = 'components.powergrid.editable';
      $this->customContent['params'] = get_defined_vars();

      return $this;
  });
```

Component:

```php
Column::make('name')
   ->customEditable(hasPermission: true)
```

**Comment by Reefcrazed** [comment]
There is a bigger issue here though, using the grid normally you can also see it. If you have a grid with pagination enabled, and have a validation error on the first page and move on to any other page you cannot edit until you go back to the page with the validation error. End users may not notice they had a validation error or think that going to the next page will clear the validation error. Better yet they may not remember what page the validation error was on.

If you turn on pagination on your validation demo and add more records, I can visually show you the issue.
