### ISSUE TITLE
how to search in column when i use with method 

### ISSUE THREAD

**Issue by mohammadtarabishy** [Power-Components/livewire-powergrid#175]
public function datasource(): ?Builder
    {
      return   AppUser::query() ->with('parent');
  }
 public function columns(): array
    {
  Column::add()
                ->title(__('Admin Name'))
                ->field('parent')
                ->searchable()
                ->makeInputText('parent'),
}

**Comment by luanfreitasdev** [comment]
Hello, can you use RelationSearch method

* https://livewire-powergrid.docsforge.com/main/column-filters/#filter-by-relationship
