### ISSUE TITLE
Problem custom pagination

### ISSUE THREAD

**Issue by PlimSistemas** [Power-Components/livewire-powergrid#1750]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.4

### PowerGrid

6.0.6

### Laravel

11.29.0

### Livewire

3.3

### Theme

Bootstrap

### Describe the bug.

I’m adding custom pagination, but the view isn’t rendering.

### To Reproduce...

![pagination](https://github.com/user-attachments/assets/5120fdd7-13eb-4cb7-b67d-21c8b7ac4525)

### Extra information

```markdown
public function setUp(): array
  {
    //$this->showCheckBox();

    return [
      PowerGrid::footer()
        ->showPerPage(10)
        ->showRecordCount()
        ->includeViewOnTop('components.table.a')
        ->includeViewOnBottom('components.table.b')
        ->pagination(viewPath: 'components.table.pagination'),
    ];
  }
```
```

**Comment by PlimSistemas** [comment]
@luanfreitasdev consegue verificar porque não está mostrando a paginação customizada? obrigado!

**Comment by luanfreitasdev** [comment]
Fixed https://github.com/Power-Components/livewire-powergrid/pull/1779
