### ISSUE TITLE
Action Buttons conflicts with Laravel Nova's trait

### ISSUE THREAD

**Issue by daniel-banciulea** [Power-Components/livewire-powergrid#1751]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.3.11

### PowerGrid

6.0.6

### Laravel

11.27.2

### Livewire

3.5.12

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

Action buttons no longer render, if you add Laravel Nova's `Actionable` trait on the model used in `datasource` method.

### To Reproduce...

Add `Actionable` trait on the Laravel model.

### Extra information

```markdown
<?php

namespace Laravel\Nova\Actions;

use Laravel\Nova\Nova;

trait Actionable
{
    /**
     * Get all of the action events for the user.
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function actions()
    {
        return $this->morphMany(Nova::actionEvent(), 'actionable');
    }
}
 
 <?php
 //...
```

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v6.1.0
