### ISSUE TITLE
Class "PowerComponents\LivewirePowerGrid\Responsive" not found

### ISSUE THREAD

**Issue by AdlyAlimin** [Power-Components/livewire-powergrid#1757]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.3.12

### PowerGrid

latest

### Laravel

11.30.0

### Livewire

3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

Class "PowerComponents\LivewirePowerGrid\Responsive" not found when to use Responsive::make

![Capture](https://github.com/user-attachments/assets/5a731c1e-fa82-45df-b916-8bc6c789065a)

### To Reproduce...

create new datatable and add Responsive::make()

**Comment by brnhache** [comment]
The docs are a good mix of V5 and V6. If you're running V6 you need to look at the upgrade guide here [https://livewire-powergrid.com/release-notes-and-upgrade/upgrade-guide.html](url) 

I think you need to use PowerComponents\LivewirePowerGrid\Facades\Responsive; as well as change your invocation to PowerGrid::responsive();

**Comment by OrakFR** [comment]
@luanfreitasdev you closed this as completed but it would also be nice if you could take the time to update the Docs for v6 https://livewire-powergrid.com/table-component/component-configuration.html#responsive-table

**Comment by OrakFR** [comment]
> The docs are a good mix of V5 and V6. If you're running V6 you need to look at the upgrade guide here [https://livewire-powergrid.com/release-notes-and-upgrade/upgrade-guide.html](url)
> 
> I think you need to use PowerComponents\LivewirePowerGrid\Facades\Responsive; as well as change your invocation to PowerGrid::responsive();

only replacing with PowerGrid::responsive(); is enough because it is available through the PowerGrid Facade namespace "PowerComponents\LivewirePowerGrid\Facades\PowerGrid"
