### ISSUE TITLE
Exporting results in InvalidArgumentException

### ISSUE THREAD

**Issue by frederik-wolf** [Power-Components/livewire-powergrid#176]
**Describe the bug**

Because some date field is NULL in database, the following error occurs:
<img width="1299" alt="Export error" src="https://user-images.githubusercontent.com/464303/145053773-c1b41e79-1d98-4cbc-bf86-a8e767b5933e.png">

**To Reproduce**

Export Date or DateTime fields with NULL values I'd suppose.

**Laravel version (exactly)**: 8.29.0

**Alpine version**: 3.2.4

**Livewire version**: 2.5

**Theme**: Bootstrap 5

**Comment by luanfreitasdev** [comment]
Hello @frederik-wolf .

Can you transform treat this data as empty when it is null? Unfortunately this happens with the spout box package.

I'll think of something to solve this behavior, but if you want to open a PR that implements this functionality, feel free

https://github.com/box/spout/issues/349

**Comment by frederik-wolf** [comment]
Hello @luanfreitasdev

Where would I try to transform the data inside the table component?
Or should this happen on a more global level?

I need the data to be NULL in the database but if there was an option to treat the data directly before the export, that would help

**Comment by dansysanalyst** [comment]
Hi @frederik-wolf,

I believe @luanfreitasdev is referring to transform the data using a  closure:

https://livewire-powergrid.docsforge.com/main/add-columns/#closure-examples


For instance, if your column `name` has NULL values, you could to the following:

```php
    public function addColumns(): ?PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ->addColumn('id')
            ->addColumn('name', function (Model $model) {
                return  '' . $model->name;
            });
    }
```

Nothing changes on your database, but your table will output NULL as "" (empty string).

I believe the downside is that you would not be able to filter for "is null".

If you need your user to find "null values", you could then output the string "null":

```php
//...
->addColumn('name', function (Model $model) {
    return  is_null($model->name) ? 'null' : $model->name;
});
```

Then your user can filter for "ist" +  "null" in the same way as they would filter for "ist" +  "Frederik".

**Comment by luanfreitasdev** [comment]
That's right @dansysanalyst , thanks so much for the example. In the future we can deal with this under the bonnets, what do you think?

**Comment by dansysanalyst** [comment]
@luanfreitasdev My pleasure :) 

I fully agree. I suggest having a property `$ExportNullAs = '';`. 

It should be enough customization power for the user to control how `NULL` data should appear, empty strings or a fallback value like: `** not filled **`.

To customize it on the column level, PowerGrid already offers the closure feature.
