### ISSUE TITLE
 [6.x] can method not working in bulk action buttons inside header

### ISSUE THREAD

**Issue by eafarooqi** [Power-Components/livewire-powergrid#1766]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.9

### PowerGrid

6.1.1

### Laravel

11.31

### Livewire

3.5.12

### Alpine JS

3.12.0

### Theme

Bootstrap

### Describe the bug.

Can method not working in bulk action buttons inside header. I am trying to add conditional bulk actions. Rules are also not working on buttons inside header.

### To Reproduce...

```
public function header(): array
    {
        return [
            Button::add('bulk-delete')
                ->slot('Bulk delete')
                ->class('pg-btn-white')
                ->can(false)
                ->dispatch('bulkDelete.' . $this->tableName, []),
        ];
    }
```

**Comment by jinyancool** [comment]
In 6.1.2 with livewire 3.5.12, showToggleColumns() only hides row data but not header data.

**Comment by marineusde** [comment]
> In 6.1.2 with livewire 3.5.12, showToggleColumns() only hides row data but not header data.

same problem here, its just in 6.1.2 and not in 6.1.1.

The problem is in the cols.blade.php, dont know why the semicolon should be outside the string. Line 44 has to be:

    style="{{ data_get($column, 'hidden') === true ? 'display:none;' : '' }} width: max-content !important; @if (data_get($column, 'enableSort')) cursor:pointer; @endif {{ data_get($column, 'headerStyle') }}"

**Comment by luanfreitasdev** [comment]
Can you revert this? https://github.com/Power-Components/livewire-powergrid/pull/1761/files

**Comment by luanfreitasdev** [comment]
I'm still not sure about this issue.

**Comment by jinyancool** [comment]
Maybe need 6.1.3 to fix this problem. If my website using bootstrap5, can livewire-powergrid use Tailwind?

**Comment by jinyancool** [comment]
I do not know why in 6.1.2, they bring this bug back. I have seen someone have reported this bug before.

> > In 6.1.2 with livewire 3.5.12, showToggleColumns() only hides row data but not header data.
> 
> same problem here, its just in 6.1.2 and not in 6.1.1.
> 
> The problem is in the cols.blade.php, dont know why the semicolon should be outside the string. Line 44 has to be:
> 
> ```
> style="{{ data_get($column, 'hidden') === true ? 'display:none;' : '' }} width: max-content !important; @if (data_get($column, 'enableSort')) cursor:pointer; @endif {{ data_get($column, 'headerStyle') }}"
> ```

**Comment by jinyancool** [comment]
> I do not know why in 6.1.2, they bring this bug back. I have seen someone have reported this bug before.
> 
> > > In 6.1.2 with livewire 3.5.12, showToggleColumns() only hides row data but not header data.
> > 
> > 
> > same problem here, its just in 6.1.2 and not in 6.1.1.
> > The problem is in the cols.blade.php, dont know why the semicolon should be outside the string. Line 44 has to be:
> > ```
> > style="{{ data_get($column, 'hidden') === true ? 'display:none;' : '' }} width: max-content !important; @if (data_get($column, 'enableSort')) cursor:pointer; @endif {{ data_get($column, 'headerStyle') }}"
> > ```

https://github.com/Power-Components/livewire-powergrid/issues/1716

**Comment by marineusde** [comment]
@luanfreitasdev you dont have to revert the hole branch, the bug is just in one file. I have tested and fixed it: https://github.com/Power-Components/livewire-powergrid/pull/1768

@all: my suggestion is, please work in good PHP IDEs like phpstorm. The error was shown in the blade file while opening.

**Comment by eafarooqi** [comment]
Hi, 
i think we have merged two issues here. This toggle column only hides is another issue from what i have mentioned. Yes this toggle column issue needs to be fixed with the following line. The semicolon should be at the right place. 
```
style="{{ data_get($column, 'hidden') === true ? 'display:none' : ''; }} width: max-content !important; @if (data_get($column, 'enableSort')) cursor:pointer; @endif {{ data_get($column, 'headerStyle') }}"
```
The issue i have mentioned is that i want to have conditional actions in the header. In the headers we are creating actions using Button Class and when we pass false to can method is still showing the action in the header.

**Comment by luanfreitasdev** [comment]
I did a test with cypress and changed the logic

https://github.com/user-attachments/assets/9c79a504-ad91-404a-81e1-556094b0a241

https://github.com/Power-Components/livewire-powergrid/pull/1770
