### ISSUE TITLE
Bug When hideToggleable and filter using drowdown  

### ISSUE THREAD

**Issue by sharq-labs** [Power-Components/livewire-powergrid#1769]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

6.x

### Laravel

11

### Livewire

3.0.1

### Alpine JS

3.0.1

### Theme

Bootstrap

### Describe the bug.

when i add rule to  hideToggleable and try to filter 

![image](https://github.com/user-attachments/assets/60368c8a-64f2-40ec-a9e1-114ca84da2b2)

      Column::add()
        ->title('status') // is Active
        ->field('active')
        ->toggleable(),
        
        
           Rule::rows()
        ->when(fn($admin) => auth('admin')->user()->can('delete_administrator') === false || $admin->id === 1)
        ->hideToggleable(),
        
        

### To Reproduce...

        if I select filter where status true and i have record where status true and hideToggleable is applied i got error in screenshot

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Can you remove published views? 

Thanks
