### ISSUE TITLE
can we search in calculated column ??

### ISSUE THREAD

**Issue by mohammadtarabishy** [Power-Components/livewire-powergrid#177]
public function datasource(): ?Builder
    {
 AppUser::query()->withcount(['joinRequests as joined' => function ($query) {
                $query->where('case', '=', 'a');
            }, 'orders as order' => function ($query) {
                $query->where([['last_status', '!=', 'canceled'], ['order_type', '=', 'sale']]);
            }]);
 }

 public function columns(): array
    {
        return [ Column::add()
                ->title(__('Account Name'))
                ->field('account_name', 'app_users.name')
                ->searchable()
                ->makeInputText('app_users.name')
                ->sortable(),
  Column::add()
                ->title('join')
                ->field('joined')
                ->searchable()
                ->makeInputText('joined'),

            Column::add()
                ->title('orders')
                ->field('order')
                ->searchable()
                ->makeInputText('order'),
}

**Comment by luanfreitasdev** [comment]
I believe it is not possible
