### ISSUE TITLE
Cannot use Bootstrap5 theme with 6.1.4

### ISSUE THREAD

**Issue by jinyancool** [Power-Components/livewire-powergrid#1771]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

6.1.4

### Laravel

11.28.1

### Livewire

3.1.12

### Theme

Bootstrap

### Describe the bug.

Following the install and PowerGrid Configuration seps, it seems that we cannot setup bootstrap5 theme. 
The action button is undefined.

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by jinyancool** [comment]
If my website is using Bootstrap5 theme, it seems I cannot using tailwind theme for livewire-powergrid. There will have a conflict.

**Comment by jinyancool** [comment]
With a fresh install, tailwind theme is fine. But Bootstrap5 theme has a bug.

**Comment by luanfreitasdev** [comment]
Can you share the screenshot error?

**Comment by backstageel** [comment]
@jinyancool  maybe because the Laravel Fresh install doesnt come with Bootstrap but with Tailwind by default?

Maybe you need to configure bootstrap first.

**Comment by jinyancool** [comment]
> Can you share the screenshot error?

![1731938252366](https://github.com/user-attachments/assets/ab47c6ce-cbb0-4d72-9a78-40de8475a5ce)
![1731938252366](https://github.com/user-attachments/assets/fbc5d32d-b2e5-426f-924f-761f2270b342)

**Comment by jinyancool** [comment]
> @jinyancool maybe because the Laravel Fresh install doesnt come with Bootstrap but with Tailwind by default?
> 
> Maybe you need to configure bootstrap first.

`<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>`
After added above codes, it seems the them is changed.



![1731938536839](https://github.com/user-attachments/assets/3713a39f-8920-4678-8ef5-a631c9801a4a)

**Comment by jinyancool** [comment]
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

Manually add the above codes, the theme looks better.

> @jinyancool maybe because the Laravel Fresh install doesnt come with Bootstrap but with Tailwind by default?
> 
> Maybe you need to configure bootstrap first.

**Comment by luanfreitasdev** [comment]
The Bootstrap theme works normally if no other CSS layer is on top, such as templates. You may have to make some adjustments with CSS for it to work. For now I'm closing this

I also tested it here and it works
