### ISSUE TITLE
[V6] Conditional bulk action buttons

### ISSUE THREAD

**Issue by eafarooqi** [Power-Components/livewire-powergrid#1772]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.9

### PowerGrid

6.1.4

### Laravel

11.31

### Livewire

3.5.12

### Alpine JS

3.12.0

### Theme

Bootstrap

### Describe the bug.

Can method not working in bulk action buttons inside header. I am trying to add conditional bulk actions. Rules are also not working on buttons inside header.

### To Reproduce...

Add bulk action button and add can method and set it to false., it was working fine with version 4.

```
public function header(): array
    {
        return [
            Button::add('bulk-delete')
                ->slot('Bulk delete')
                ->class('pg-btn-white')
                ->can(false)
                ->dispatch('bulkDelete.' . $this->tableName, []),
        ];
    }
```

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v6.1.5

**Comment by eafarooqi** [comment]
Thanks, working fine now.
