### ISSUE TITLE
saveOnMouseOut is not working with editOnClick 

### ISSUE THREAD

**Issue by jinyancool** [Power-Components/livewire-powergrid#1773]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

6.1.4

### Laravel

11.32

### Alpine JS

3.1.12

### Theme

Bootstrap

### Describe the bug.

Column::make('Sample name', 'sample_name')
                ->editOnClick(
                    hasPermission: auth()->check(),
                    fallback: '- empty -',
                    saveOnMouseOut: true,
                )
                ->sortable()
                ->searchable(),
This is not working.
Column::make('Sample name', 'sample_name')
                ->editOnClick(
                    hasPermission: auth()->check(),
                    saveOnMouseOut: true,
                )
                ->sortable()
                ->searchable(),
This is also not working.

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by jinyancool** [comment]
If I change the theme to tailwind, it works.
It seems that livewire-powergrid is not friendly to Bootstrap.

**Comment by luanfreitasdev** [comment]
Hello @jinyancool. Unfortunately, some things may not work with Bootstrap as expected. But feel free to open a PR to fix this.

Thanks
