### ISSUE TITLE
Header search no longer works after version 6.1.0

### ISSUE THREAD

**Issue by daniel-banciulea** [Power-Components/livewire-powergrid#1776]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.3.1

### PowerGrid

6.1.1

### Laravel

11.33.2

### Livewire

3.5.12

### Theme

Tailwind 3.x with tailwind/forms

### To Reproduce...

Upgrade to any version greater than 6.1.0

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
This is working normally, could you give more details? Try the most updated version

**Comment by daniel-banciulea** [comment]
I have this searchable column which is a `BelongsTo` relation on my datasouce model.
As soon as I upgrade to any version higher than 6.1.0, the global data search input in the table header, no longer works.
Basically searching for a string and pressing enter no longer updates the powergrid table.

`Column::make('Media', 'media', 'deals.domain_name')->sortable()->searchable(),`

**Comment by eafarooqi** [comment]
Working fine with the latest version. but i am using relationSearch method. Try with relationSearch method and remove the third parameter from make method. 
should be something like this
```
 public function relationSearch(): array
    {
        // Relational columns enabled to search
        return [
            'deals' => [
                'domain_name', // column enabled to search
            ],
        ];
    }
```

to make column also sortable, you may have to include the column with join as suggested by documentation. Then you can pass the join column name in third parameter.

**Comment by daniel-banciulea** [comment]
That solved my problem, search header is working again as expected after updating to latest version, thanks a lot!
