### ISSUE TITLE
Can we add a total row at the bottom

### ISSUE THREAD

**Issue by shishamchudal** [Power-Components/livewire-powergrid#178]
Feature Request,

At the very bottom can we add a new row for the sum of values of the column. For example, it would be just great to get the total quantity of the quantity column at the very end with all the filters working.

Thank you

**Comment by vs0uz4** [comment]
> Feature Request,
> 
> At the very bottom can we add a new row for the sum of values of the column. For example, it would be just great to get the total quantity of the quantity column at the very end with all the filters working.
> 
> Thank you

Sorry for the delay, this feature is under discussion at the moment, as soon as we have some news about it, we will give you feedback. You can follow the progress through 👉 #179

**Comment by vs0uz4** [comment]
Oh! Sorry @shishamchudal, now that I looked closer and noticed it was you. You are already developing the functionality in #179. My lack of attention, KKK

**Comment by vs0uz4** [comment]
Taking a moment, thank you very much for your interest in our package and for developing a feature for it.

**Comment by shishamchudal** [comment]
It's my pleasure to contribute to the package. I need the functionality myself so developed it. It's still to be reviewed and released. It would be great to see it on the release without delays. 

Thank you
Shisham Chudal
