### ISSUE TITLE
Demo site down day 2 

### ISSUE THREAD

**Issue by jillianbeann** [Power-Components/livewire-powergrid#1792]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

N/A

### PowerGrid

N/A

### Laravel

N/A

### Livewire

N/A

### Alpine JS

N/A

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

Navigated to http://demo.livewire-powergrid.com/ for the past two days and have been unable to reach the server. Site is not responding. 

### To Reproduce...

Navigate to http://demo.livewire-powergrid.com/

### Extra information

```markdown
None needed
```

**Comment by johannesMEGABAD** [comment]
It is not a bug or error...
Look here https://github.com/Power-Components/livewire-powergrid/commit/c30c4fc931a6195e8647d1b27f13f496a7579e2e

**Comment by luanfreitasdev** [comment]
Yes, the demo site is temporarily disabled. Soon he will be on the air again. 
Thank you
