### ISSUE TITLE
Interactive Demo is offline

### ISSUE THREAD

**Issue by Zaita** [Power-Components/livewire-powergrid#1805]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### Theme

Tailwind 3.x

### Describe the bug.

Interactive Demo is offline.

https://www.isitdownrightnow.com/demo.livewire-powergrid.com.html

### To Reproduce...

Go to https://demo.livewire-powergrid.com/

### Extra information

```markdown
N/A
```

**Comment by dansysanalyst** [comment]
Thanks for reporting.

We are currently moving the demo to another server. 

It should be back soon! 😊

The demo source code is available in this repository: https://github.com/Power-Components/powergrid-demo

You can browse the examples or run it on your computer.

**Comment by luanfreitasdev** [comment]
Demo Is now online! Thank you @dansysanalyst
