### ISSUE TITLE
Method PowerComponents\LivewirePowerGrid\Button::render does not exist

### ISSUE THREAD

**Issue by caiochami** [Power-Components/livewire-powergrid#1808]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

powergrid.js:2 PowerGrid: Unable to load icons in javascript window in row: [null]

### PHP Version

8.3.14

### PowerGrid

6.1.7

### Laravel

11.33.2

### Livewire

3.5.6

### Theme

Tailwind 3.x

### Describe the bug.

Getting this error after the upgrade

![image](https://github.com/user-attachments/assets/b55f894b-e59f-47f4-b52c-395054855d28)

### To Reproduce...

public function actions(Payment $payment): array
    {
        return [
            Button::add('view')
                ->can(Gate::check('view', $payment))
                ->render(function (Payment $payment) {
                    $url = route('payments.show', $payment->id);

                    return Blade::render(<<<HTML
                <x-button sm
                    outline
                    icon="link"
                    secondary
                    href="$url" />
                HTML);
                }),
            Button::add('edit')
                ->can(Gate::check('update', $payment))
                ->render(function (Payment $payment) {
                    $action = '$dispatch(\'edit-payment\', { payment: ' . $payment->id . '})';

                    return Blade::render(<<<HTML
                    <x-button sm 
                        positive 
                        icon="pencil-square"
                        wire:click="$action" />
                    HTML);
                }),
            Button::add('delete')
                ->can(Gate::check('delete', $payment))
                ->render(function (Payment $payment) {
                    $action = '$dispatch(\'delete-payment\', { payment: ' . $payment->id . '})';

                    return Blade::render(<<<HTML
                <x-button sm
                    negative
                    icon="trash"
                    wire:click="$action" />
                HTML);
                }),
            Button::add('download')
                ->can(!empty($payment->provider_data['link'] ?? ''))
                ->render(function (Payment $payment) {
                    $link = $payment->provider_data['link'] ?? '';

                    return Blade::render(<<<HTML
                <x-button sm icon="arrow-down-tray"
                    target="_blank"
                    href="$link" />
                HTML);
                }),
        ];
    }

**Comment by eafarooqi** [comment]
Try with the slot
```
->slot(view('livewire.includes.view_name'))
```

you can also pass data to the view.

**Comment by luanfreitasdev** [comment]
This method has been removed from PowerGrid

https://livewire-powergrid.com/release-notes-and-upgrade/release-notes.html#deprecations

![image](https://github.com/user-attachments/assets/505226d0-0e42-4b44-b506-c674db8ca130)
