### ISSUE TITLE
Column summary: Min amount label issue

### ISSUE THREAD

**Issue by caiochami** [Power-Components/livewire-powergrid#1809]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.3.14

### PowerGrid

6.1.7

### Laravel

11.33.2

### Livewire

3.5.6

### Theme

Tailwind 3.x

### Describe the bug.

![image](https://github.com/user-attachments/assets/e74a1bfc-5f40-450a-a6f3-64596f26c5d4)

https://demo.livewire-powergrid.com/examples/summarize

**Comment by alloylab** [comment]
FYI, this is the same as issue #1806

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v6.1.8
