### ISSUE TITLE
Unable to access parameters on 6.0

### ISSUE THREAD

**Issue by caiochami** [Power-Components/livewire-powergrid#1810]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### PHP Version

8.3.14

### PowerGrid

6.1.7

### Laravel

11.33.2

### Livewire

3.5.6

### Theme

Tailwind 3.x

### Describe the bug.

I'm no longer able to access component properties as parameters on export  as I used to on 5.0

![image](https://github.com/user-attachments/assets/dcc42201-ac5c-49ec-803b-25b097c88e9e)

**Comment by eafarooqi** [comment]
You can access the properties with `$this`

```
$this->teamId
```

**Comment by caiochami** [comment]
> You can access the properties with `$this`
> 
> ```
> $this->teamId
> ```

Hello. The property isn't available within the job when you export the data.

**Comment by eafarooqi** [comment]
yes, it has to be set in job. whats your logic behind this property?

**Comment by caiochami** [comment]
This is a SAAS application and the user should only see records that belong to their workspace. The teamId property is required to filter those records.

**Comment by luanfreitasdev** [comment]
Working normally in v6

![image](https://github.com/user-attachments/assets/cb1204f2-d37a-44ea-b79b-09d84a90ba6c)
