### ISSUE TITLE
Enum field

### ISSUE THREAD

**Issue by jonasalvarado** [Power-Components/livewire-powergrid#184]
good day,
I have several tables, with enum fields. I am getting the following error:

` Doctrine\DBAL\Exception 

  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

  at vendor/doctrine/dbal/src/Platforms/AbstractPlatform.php:394
    390▕ 
    391▕         $dbType = strtolower($dbType);
    392▕ 
    393▕         if (! isset($this->doctrineTypeMapping[$dbType])) {
  ➜ 394▕             throw new Exception(
    395▕                 'Unknown database type ' . $dbType . ' requested, ' . static::class . ' may not support it.'
    396▕             );
    397▕         }
    398▕ `

any idea??

**Comment by luanfreitasdev** [comment]
Hi @jonasalvarado . What is your MySQL version?

**Comment by vs0uz4** [comment]
> Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it.

Is the error occurring when you try to change some column through a migration, where one of the columns or more are of type `enum`? If so, try reading this [issue](https://github.com/doctrine/dbal/issues/3161) in Doctrine's own repository to see if it helps you solve the problem.

In one of the comments ([comment](https://github.com/doctrine/dbal/issues/3161#issuecomment-635419448)), one of the developers mentions that the solution can be found by adding the following lines to the migration constructor method:

```php
DB::getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', Types::STRING);
```

In the constructor it would look something like this.
```php
use Doctrine\DBAL\Types\Types;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class YourEditClass extends Migration
{
    public function __construct()
    {
        DB::getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', Types::STRING);
    }
}
```
Give us feedback if you can solve it.

**Comment by ViaductMedia** [comment]
> 

Hi,

I have the same error, In my users table, I have 6 options which are enums ['Enabled', 'Disabled'] 

The migration works fine, I have added the mapping to the construct method.

When I try to create a Powergrid this is what is returned.

```shell
php artisan powergrid:create

 What is the name of your new ⚡ PowerGrid Table (E.g., UserTable)?:
 > Users

 Create Datasource with [M]odel or [C]ollection? (Default: Model):
 > m

 Enter your Model path (E.g., App\Models\User):
 > App\Models\User

 Create columns based on Models fillable property? (yes/no) [no]:
 > Yes


   Doctrine\DBAL\Exception 

  Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.

  at D:\Websites\Ontime\app\vendor\doctrine\dbal\src\Platforms\AbstractPlatform.php:394
    390▕ 
    391▕         $dbType = strtolower($dbType);
    392▕
    393▕         if (! isset($this->doctrineTypeMapping[$dbType])) {
  ➜ 394▕             throw new Exception(
    395▕                 'Unknown database type ' . $dbType . ' requested, ' . static::class . ' may not support it.'
    396▕             );
    397▕         }
    398▕

  1   D:\Websites\Ontime\app\vendor\doctrine\dbal\src\Schema\MySQLSchemaManager.php:138
      Doctrine\DBAL\Platforms\AbstractPlatform::getDoctrineTypeMapping("enum")

  2   D:\Websites\Ontime\app\vendor\doctrine\dbal\src\Schema\AbstractSchemaManager.php:981
      Doctrine\DBAL\Schema\MySQLSchemaManager::_getPortableTableColumnDefinition()
```

Here is my migration file

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Doctrine\DBAL\Types\Types;
use Doctrine\DBAL\Types\Type;
use Doctrine\DBAL\Types\StringType;
use Illuminate\Support\Facades\DB;

class AddShippingOptionsToUsers extends Migration
{

    public function __construct()
    {
        DB::getDoctrineSchemaManager()->getDatabasePlatform()->registerDoctrineTypeMapping('enum', Types::STRING);
        Type::hasType('enum') ? Type::hasType('enum') : Type::addType('enum', StringType::class);
    }

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('users', function (Blueprint $table) {
            $table->enum('royal_mail', ['Enabled', 'Disabled']);
            $table->enum('parcel_force', ['Enabled', 'Disabled']);
            $table->enum('dpd', ['Enabled', 'Disabled']);
            $table->enum('yodel', ['Enabled', 'Disabled']);
            $table->enum('hermes', ['Enabled', 'Disabled']);
            $table->enum('dhl', ['Enabled', 'Disabled']);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('users', function (Blueprint $table) {
            //
        });
    }

    
}

```

I have tried it with and without the ```php Type::hasType('enum') ? Type::hasType('enum') : Type::addType('enum', StringType::class);```

For the time being, I am just going to switch my enum to a Bool for this purpose, as it is effectively returning a true or false value, but would be good to know a workaround for future.

**Comment by luanfreitasdev** [comment]
Hi @jonasalvarado . 

I managed to find the problem. I cast the enum column to string.

I will go up in the next release.

Thanks
