### ISSUE TITLE
Unable to search with relation model in ->makeInputText() and ->makeInputSelect() with where condition.

### ISSUE THREAD

**Issue by Seema27h** [Power-Components/livewire-powergrid#185]
<img width="523" alt="filter input" src="https://user-images.githubusercontent.com/66829485/146188150-2c854147-7024-47e6-8896-d459def1bdc6.PNG">
Hi,
I am trying to search and filter huge data with power grid component using ->makeInputText() and ->makeInputSelect() in table. In select its taking time to load page for filter. That's why I want to use where condition which not fetching data in ->makeInputSelect() with and model with the condition, If its all data, It will load later and in  ->makeInputText() it will through page reload error with raw query and relation model both. Kindly help with the problem.

**Comment by Seema27h** [comment]
Model Issue
->makeInputSelect(State::where('id', 'state_id')->with('branch')->first(), 'name', 'state_id', ['live-search' => true])
I want to use above query to display only related data in select filter but its not applicable for select as well text.
Any other way to resolve this issue kindly suggest.

**Comment by luanfreitasdev** [comment]
I think this is a very interesting feature but powergrid is not able to handle this type of request because the **makeInputText** method will only filter inside the model or some relation. To work **makeInputText** would have to change direction and filter using **whereHas** along the way..

It seems to be quite complex.

**Comment by luanfreitasdev** [comment]
Due to the complexity of this case and not necessarily being a bug, this may receive performance improvements in the future. I'm marking it as a feature request.

Thanks
