### ISSUE TITLE
PowerGrid theme not found

### ISSUE THREAD

**Issue by judethaddeus20** [Power-Components/livewire-powergrid#186]
I've been finding a solution about why does it not read the bootstrap class. hope someone could help

**Comment by luanfreitasdev** [comment]
Hi. I didn't understand your question. Can rephrase to understand. whether it's a bug?.

Thanks.

**Comment by judethaddeus20** [comment]
I think the variables was not adding up. I just directly named the theme
with bootstrap 5. The file inside config wasnt reading the class properly

**Comment by luanfreitasdev** [comment]
Can you give more details or send a PR?

**Comment by judethaddeus20** [comment]
I already fixed the issue. I commented on the bootstrap class line. By the
way toggleColumns and showExport isn't working should i enable some
variables first?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by luanfreitasdev** [comment]
What version are you using?. Only version ^5 is supported. 

Does this problem you fixed not happen to other users?
