### ISSUE TITLE
How can I create a cell with a link

### ISSUE THREAD

**Issue by uhexos** [Power-Components/livewire-powergrid#187]
Hello please the features state that we can create link inside powergrid, however I am unable to find the docs for this. How can I create a link to another blade view inside my table. Thanks

**Comment by luanfreitasdev** [comment]
Hello. You can render a tag or even a view inside the callback in addColumn.

**Comment by dansysanalyst** [comment]
@uhexos I have added an example in the docs:

[https://livewire-powergrid.docsforge.com/main/add-columns/#link-in-cell](https://livewire-powergrid.docsforge.com/main/add-columns/#link-in-cell)

**Comment by uhexos** [comment]
> 

Thank you for all your efforts

**Comment by Abdallah-Tah** [comment]
> @uhexos I have added an example in the docs:
> 
> https://livewire-powergrid.docsforge.com/main/add-columns/#link-in-cell

Hello,

I would like to create a link to another blade view inside the table with the $id. The link above is not working. Thank you

**Comment by dansysanalyst** [comment]
https://livewire-powergrid.com/#/table/add-columns?id=link-in-cell
