### ISSUE TITLE
How can I translate the datatables?

### ISSUE THREAD

**Issue by diegoba73** [Power-Components/livewire-powergrid#190]
I am doing a project with datatables and I would like to know how to translate the components. Thanks

**Comment by dansysanalyst** [comment]
Hi @diegoba73 

Run:

```bash
php artisan vendor:publish --tag=livewire-powergrid-lang
```

This will copy the language files into `/resources/lang/vendor/livewire-powergrid`. I believe you can also copy `es` into`es-ar` to have Argentinian Spanish if needed.

Then, change the locale on your Laravel app.config:

```php
 /*
    |--------------------------------------------------------------------------
    | Application Locale Configuration
    |--------------------------------------------------------------------------
    |
    | The application locale determines the default locale that will be used
    | by the translation service provider. You are free to set this value
    | to any of the locales which will be supported by the application.
    |
    */

    'locale' => 'es',
```

and you will get the translated table:

<img width="632" alt="CleanShot 2021-12-20 at 10 05 58@2x" src="https://user-images.githubusercontent.com/79267265/146741400-87e5ee65-a020-48b4-9d3a-4567e6496bf3.png">


(In my case, the table headers are writing in English).

**Comment by diegoba73** [comment]
Thank you! Excellent
