### ISSUE TITLE
php artisan powergrid:create fails to create a working collection based component

### ISSUE THREAD

**Issue by uhexos** [Power-Components/livewire-powergrid#191]
**Describe the bug**

* .. php artisan powergrid:create fails to create a working collection based component. The error occurs when trying to create a subfolder using a dot in the name eg( Products.VendorDataTables ). You get an error
```
 ParseError
syntax error, unexpected '/', expecting '{' 
```
The generated component has the class 
`final class Products/VendorDataTables extends PowerGridComponent
`
removing the / will take away this error. However you will now get this error when you attempt to use   '<livewire:products-vendor-data-tables>' (as recommended by cli) same result when you use  <livewire:products.vendor-data-tables>.

```
Livewire\Exceptions\ComponentNotFoundException
Unable to find component: [products-vendor-data-tables]
```
Same thing happens if you move the component into a sub-directory manually. However if creating a model based component it works as intended.
**To Reproduce**
run php artisan powergrid:create enter name as Products.VendorDataTables and select Collection instead of model. try to use component in template.
**Laravel version (exactly):**
* 8.76.2?
 
**Alpine version:**
* 3.x.x ?

**Theme:**
- [ ] Tailwind 
   - Version:        
      
- [x] Bootstrap
   - Version:        

**Screenshots** (***This helps to understand better***)

**Do you have any idea how we can fix it?**

**Comment by luanfreitasdev** [comment]
Thanks for the bug report.

It really happened. I've already done the correction and will go up in the next release.

![image](https://user-images.githubusercontent.com/33601626/146999120-8bdd7653-972c-4029-8700-b902205bc866.png)
