### ISSUE TITLE
Minor issue with pagination/total display

### ISSUE THREAD

**Issue by jefferose** [Power-Components/livewire-powergrid#192]
**Describe the bug**
* The phrasing of "Showing 1 to 10 of {total} results becomes broken after showing "All"

**To Reproduce**
* Using the demo, switch from 10 to "All" and then choose 10 again and the word "of" and the spacing is missing

**Laravel version (exactly):**
* 8.65
 
**Alpine version:**
* 3.7.1

**Theme:**
- [x] Tailwind 
   - Version:    2

**Screenshots** (***This helps to understand better***)
![Screen Shot 2021-12-20 at 1 22 44 PM](https://user-images.githubusercontent.com/1217201/146835339-942be8f1-3cd5-4ccd-b6a9-7d14853621d1.png)

**Do you have any idea how we can fix it?**
No.

**Comment by luanfreitasdev** [comment]
Hi @jefferose .

I am trying to verify this problem. But if you know you can send a PR that we accept

**Comment by luanfreitasdev** [comment]
Oddly enough, I changed the name of the css class where this happens in the brah dev and it looks like it fixed it. But I couldn't identify what happened. It could be a livewire failure in rendering.
