### ISSUE TITLE
Boolean field not working

### ISSUE THREAD

**Issue by diegoba73** [Power-Components/livewire-powergrid#194]
I have a boolean field in the datatable that is displayed with no function grayed out. I have tried modifying various things and have not resolved it.
The weird thing is that I have another one on the same table that works well for me.
What could be the problem?

**Comment by luanfreitasdev** [comment]
Hello @diegoba73 .

Can I show you how to make your component, take a screenshot and check how the console is doing?

**Comment by diegoba73** [comment]
![Captura de Pantalla 2021-12-21 a la(s) 19 24 51](https://user-images.githubusercontent.com/1211931/147005790-76ead691-355d-43c6-8baf-882dc5acbdc3.png)
This is how the column that does not work (REVISADA) looks in the Datatable, next to it is the one that does work (ACEPTADA)
![Captura de Pantalla 2021-12-21 a la(s) 19 26 15](https://user-images.githubusercontent.com/1211931/147006005-c3cf17e2-2c76-4471-9f80-0811e15adb47.png)
And this is what appears in the console that I do not understand very well that I have to correct
Very grateful for your answer

**Comment by luanfreitasdev** [comment]
What version of alpine are you using?

**Comment by diegoba73** [comment]
I use 2.7, but I realized that the problem is with the fields that have the value "null"
Is there a solution for that?

**Comment by luanfreitasdev** [comment]
Version 2x is being deprecated. Soon I will upload a release only with Alpine 3x that will fix this problem

**Comment by diegoba73** [comment]
Perfect!

**Comment by luanfreitasdev** [comment]
can you give us feedback installing the alpine3 branch?

**Comment by diegoba73** [comment]
The error continues despite the change

**Comment by luanfreitasdev** [comment]
You can show how the inspected html looks and how you set up the table in the component?. if you dd the line. what returns?
