### ISSUE TITLE
Error exporting data

### ISSUE THREAD

**Issue by diegoba73** [Power-Components/livewire-powergrid#196]
When I want to export filtered data, it throws me the following error:

![Captura de Pantalla 2021-12-22 a la(s) 00 00 57](https://user-images.githubusercontent.com/1211931/147028524-90e2c921-8e8f-438c-860e-7fd64be2c212.png)

**Comment by luanfreitasdev** [comment]
This could happen because of the way the join was assembled.

https://livewire-powergrid.docsforge.com/main/datasource/#join-tables

**Comment by diegoba73** [comment]
I made the change and it works perfect, it is seen that this is the problem with respect to the id.
What if making that change now changes the fields of the booleans and does not make them toggleable, which can be the problem with the latter. If I remove the "primaryKey" thing it works again.
Very rare

**Comment by luanfreitasdev** [comment]
Did this work on version 1.5.1 or on the alpine3 branch? Can you explain better about the primaryKey?

**Comment by diegoba73** [comment]
The export function works when I add these 2 lines:

    public string $primaryKey = 'muestras.id';
    public string $sortField = 'muestras.id';

But the toggleable buttons disappear:

![Captura de Pantalla 2021-12-24 a la(s) 03 11 57](https://user-images.githubusercontent.com/1211931/147323587-a1602a36-7fc0-436e-91b4-3156b4a20e50.png)

**Comment by luanfreitasdev** [comment]
This is because it is not yet safe to update with this type of primary key. I'll investigate

**Comment by luanfreitasdev** [comment]
Unfortunately for now this is not possible because it handles the column dynamically, for example: column 'id' = $row->{$id} = $row->id. I haven't seen an output so far to use with joins. Example: $row->{$id} = $row->dishes.id

**Comment by pauleniz** [comment]
Is it possible to export filtered data without checkboxes? maybe there could be export options: all / filtered / selected(checked)
filtered export could take the same query but without pagination or is it possible to assign an array to a variable like 
$this->exportData= $data;
