### ISSUE TITLE
Minor bug class style tailwind theme doesn't effect

### ISSUE THREAD

**Issue by Slamet24** [Power-Components/livewire-powergrid#198]
**Describe the bug**
After create first tabel, i try to enable the action button. it did show up, but the css style didn't work properly. the button edit should be indigo color but just show up a text with white color almost transparent also delete button. i thought it was just in action button but when i try in column attribute, it's same. 

**To Reproduce**
* Got to ..

**Laravel version (exactly):**
* 8.75
 
**Alpine version:**
* 3.7.1

**Theme:**
- [x] Tailwind 
   - Version: 3

**Screenshots** (***This helps to understand better***)
![Screenshot from 2021-12-25 00-23-48](https://user-images.githubusercontent.com/44310733/147367048-a3fed1ee-5e97-4334-91a9-ebcab2bf8750.png)

**Do you have any idea how we can fix it?**
No.

**Comment by luanfreitasdev** [comment]
Hi, can you show how the html was assembled into this element using the browser inspector and how is the actions code in the backend ?

**Comment by iamdan-boop** [comment]
![image](https://user-images.githubusercontent.com/66265305/147750832-71f19f17-ad6c-46e0-a6e9-ea4b2f0cbc80.png)
![image](https://user-images.githubusercontent.com/66265305/147750869-8a0c509a-3fd5-4fb0-b228-d9282084f6a2.png)

same with laravel 8 toggleable couldn't render correctly

**Comment by luanfreitasdev** [comment]
I believe this has already been resolved.

https://livewire-powergrid.docsforge.com/main/configure/#43-tailwind-forms 

#105

**Comment by iamdan-boop** [comment]
![image](https://user-images.githubusercontent.com/66265305/147838756-128fcf5f-fbff-42db-8657-4fde51cf86fe.png)
![image](https://user-images.githubusercontent.com/66265305/147838761-1b654e2d-5770-458f-8592-c484af196838.png)

 "@tailwindcss/forms": "^0.4.0",
 "tailwindcss": "^3.0.0"

heres my dependencies version

it still wasn't working on my side, hope we can find a workaround about the issue thanks again Mr @luanfreitasdev  for answering my issues

**Comment by luanfreitasdev** [comment]
Strange. what version are you using of powergrid? if you uninstall tailwind forms does it work?

**Comment by vs0uz4** [comment]
> Strange. what version are you using of powergrid? if you uninstall tailwind forms does it work?

Hi @luanfreitasdev and @iamdan-boop !

It is really very strange that it doesn't work, because it is recommended in the [documentation](https://github.com/tailwindlabs/tailwindcss-forms#using-classes-instead-of-element-selectors) itself. The configuration is correct.

@iamdan-boop, just out of conscience, did you do a `npm run dev` after the change to `tailwind.config.js`? Could you show us how the `html` was assembled on this element using the `browser inspector` and how the action code is presented on the backend?

**Comment by luanfreitasdev** [comment]
Hello @iamdan-boop and @vs0uz4 , thank you very much for the explanation, I also believe that, I will close this issue.
