### ISSUE TITLE
Unable to find component: [manage-user-table]

### ISSUE THREAD

**Issue by mrbscott** [Power-Components/livewire-powergrid#199]
Livewire tag produced by artisan powergrid script uses wrong character for folder producing "Unable to find component: [manage-user-table]" error.

**To Reproduce**
* `php artisan powergrid:create`
* Q1: Manage.UserTable
* Q2: M
* Q3: App\Models\User
* Q4: yes
* Outputs: Your PowerGrid can be now included with the tag: <livewire:manage-user-table/>
* Include `<livewire:manage-user-table/>` in blade file to get error

**Laravel version (exactly):**
* 8.77.1
 
**Alpine version:**
* 3.7.1

**Theme:**     
- [X] Bootstrap
   - Version: 5.1.3

**Do you have any idea how we can fix it?**
Maybe this world work?
In [src/Commands/CreateCommand.php](https://github.com/Power-Components/livewire-powergrid/blob/main/src/Commands/CreateCommand.php) change [line 169](https://github.com/Power-Components/livewire-powergrid/blob/main/src/Commands/CreateCommand.php#L169) to `->replace('/', '.')`

**Comment by luanfreitasdev** [comment]
Hi @mrbscott .

I'm fixing this and it will be released in the next release.

Thanks
