### ISSUE TITLE
`Attempt to read property "searchable" on array` after toggleable update

### ISSUE THREAD

**Issue by maatien** [Power-Components/livewire-powergrid#207]
Using a datasource with hundreds of entries, a boolean field is configured to be `toggleable`.
After filtering a specific record using the table wide search input, I want to toggle the boolean field.
The field get's updated but then this error is thrown:

```
ErrorException
Attempt to read property "searchable" on array

vendor/power-components/livewire-powergrid/src/Helpers/Model.php:266
```

The stack trace refers to the `fillData` method on `PowerGridComponent.php:368`.

The error also happens with empty `relationSearch` configuration.

The error does not happen if using the column text filter, only using the table-wide search.

**PHP Version**
* 8.0.14

**Laravel version (exactly):**
* 8.77.1
 
**Alpine version:**
* 3.7.1

**Theme:**
- [x] Tailwind 
   - Version:  3.0.8      
     
**Screenshots**
![Screenshot from 2021-12-30 14-22-31](https://user-images.githubusercontent.com/420445/147756248-e9a257b4-1e2d-4c61-8baf-2109c9996a7e.png)

**Do you have any idea how we can fix it?**
As `$this->columns` is an array of arrays when the error happens, this may be related to the before update request handled by livewire.

**Comment by maatien** [comment]
After some more testing I can confirm that this error occurs on every update action, not only on `toggleable` update.

**Comment by luanfreitasdev** [comment]
Hi, 

can't reproduce the error... do you have any suggestions on how you would solve the problem?

**Comment by Mo7sin** [comment]
I didn't go deep with this issue, but the main problem is when filling data after updating any column, `$ this->column` an array of objects, after the update it is an array of arrays, so the conditional `if ($column->searchable) {...}` should now be `if ($column['searchable']) {...}` because it's an array, we need to maintain data structure for columns array to be the same after the update.

**Comment by luanfreitasdev** [comment]
I understood what you said but I couldn't reproduce the problem.

I'm going up in the dev that later will be 2.0 a suggestion that should handle data being array or not using data_get. I believe it solves

Thanks.

**Comment by ludioao** [comment]
I had same problem because I was using this packag since version 1.x and datasource() method was with "Model::all()". Changed to "Model::query()"
