### ISSUE TITLE
Delete open a new window and return 1

### ISSUE THREAD

**Issue by odin88** [Power-Components/livewire-powergrid#208]
I try to use the delete feature.
The behavior : 
it will open another window.
it will show number 1.

```
Button::add('destroy')
               ->caption('Delete')
               ->class('bg-red-500 cursor-pointer text-white px-3 py-2 m-1 rounded text-sm')
               ->route('admin.prospect.destroy', ['prospect' => 'id'])
               //->target('')
               ->method('delete')
```

```
Route::delete('/prospect/delete', [UsersController::class, 'deleteProspect'])
                ->name('admin.prospect.destroy');
```

```
public function deleteProspect(Request $request) : bool
    {
        $prospect = $request->input('prospect');
        $record = Prospect::find($prospect);
        $record->delete();
        return true;
        #dd($prospect);
    }
```
<img width="398" alt="image" src="https://user-images.githubusercontent.com/680300/147849562-486a2ff8-7beb-4f2b-915b-fd534a8562b8.png">

``
"power-components/livewire-powergrid": "^1.4",
``

My expectation : i click button delete. it will send like an ajax request to delete and it will auto update the table since the record is deleted.

**Comment by luanfreitasdev** [comment]
As much as this is possible, I believe that the best way out for data deletion would be to use events inside the livewire component itself, an example would be:

```php
       Button::add('destroy')
             ->caption('Delete')
             ->class('bg-red-500 cursor-pointer text-white px-3 py-2 m-1 rounded text-sm')
             ->emit('deleteProspect', ['prospect' => 'id'])
```
---
```php
    public function deleteProspect(int $prospectId) : bool
    {
        $record = Prospect::find($prospectId);
        $record->delete();
       
        $this->fillData(); // update data list  
    }
```

**Comment by paulgiorgi** [comment]
hi. I tried with  @luanfreitasdev solution but id din't work out for me.
I used 

`protected function getListeners()
    {
        return array_merge(
            parent::getListeners(), [
                'deleteRecord'
            ]);
    }`

to declare the listener inside the table component.

Then I just arrived to nowhere. I can intercept the function 'deleteRecord' in my case (inside the table component itself) but I can't do much more.
