### ISSUE TITLE
Filtrar por atributos virtuais / campos personalizados

### ISSUE THREAD

**Issue by gonribeiro** [Power-Components/livewire-powergrid#214]
First of all, did you see if your problem has happened to other people before?
- [x] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**
Olá!

Gostaria de saber se é possível realizar pesquisas por atributos virtuais/personalizados.

Imagine que tenho um modelo de pagamentos ou compras ou etc.
Nele, entre seus atributos há: 
- parcela: vezes em que a compra foi parcelada.
- parcela_paga: quantidade de parcelas já pagas.

Quando a parcela for igual a parcela_paga (parcelado em 10 parcelas e todas pagas), a compra está "quitada".
Claro que aqui o processo/sistema não permitiria que a parcela_paga seja maior que a parcela (enfim...)

No datatable, gostaria de ter uma coluna onde pudessem filtrar pelos itens quitados ou ainda pendentes ou todos.
Entretanto, logo abaixo defino que "quitado" não é um atributo na tabela, mas sim é um campo virtual.

Quando tento realizar o exemplificado mais abaixo, recebo:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'quitado' in 'where clause' (SQL: select count(*) as aggregate from `compras` where ((`quitado` = 1)) and `compras`.`deleted_at` is null)
```

Entendo que o Eloquent não consegue buscar por campos virtuais, o "correto" seria trabalhar com uma collection e fazer um filtro nele:

```
$compras = Compra::all();
$compras = $compras->filter(function($model){
    return $model->quitado == 0;
});
```

Mas caso haja alguma forma de conseguir atingir esse objetivo com o powergrid, seria muito interessante.
* 

**To Reproduce**
```
<?php

// Model

namespace App\Models;

class Compra extends Model
{
    protected $table = 'compras';

    protected $appends = ['quitado'];

    protected $fillable = [
        'parcela',
        'parcela_paga'
    ];

    public function getQuitadoAttribute(): bool
    {
        return $this->parcela == $this->parcela_paga ? true : false;
    }
}

// PowerGrid

public function addColumns(): ?PowerGridEloquent
{
    return PowerGrid::eloquent()
        ->addColumn('quitado');
}

public function columns(): array
{
    return [
        Column::add()
            ->title(__('Quitado'))
            ->field('quitado')
            ->sortable()
            ->searchable()
            ->makeBooleanFilter('quitado', 'Sim', 'Não'),
    ];
}

?>
```

**Laravel version (exactly)** 
"laravel/framework": "^8.0",
*

**Livewire version (exactly)**
"power-components/livewire-powergrid": "^1.5",
*

**AlpineJS:** 

*

**Theme:**
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [ ] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)

**Do you have any idea how we can fix it?**
Consegui resolver dessa forma me inspirando no PowerGridDemoTable:
Seria essa a solução definitiva?

```
public function datasource()
    {
        return $this->compras();
    }

protected function compras(): \Illuminate\Support\Collection
    {
        $compras = Compra::all();

        return $compras ;
    }
```

**Put part of your code, an html screenshot of the problem element:**

**Comment by gonribeiro** [comment]
Curiosidade:

Eu estava com dificuldades para filtrar os relacionamentos. Como sou novo na utilização do powergrid, pode ser algum mau entendimento meu sobre a forma correta de fazer os filtros funcionar.

https://livewire-powergrid.com/#/table/column-filters?id=filter-by-relationship
https://livewire-powergrid.com/#/table/datasource?id=datasource

Só consegui trabalhar com filtros nos relacionamentos realizando um join e selecionando cada valor da tabela, exemplo:

```
public function datasource(): ?Builder
    {
        return Compra::query()
            ->join('item', function ($itens) {
                $itens->on('compra.item_id', '=', 'item.id');
            })
            ->select([
                'compra.id',
                'item.nome'
            ]);
    }
```

Somente assim conseguia filtrar pelo nome do item.

Mas com a solução proposta em "Do you have any idea how we can fix it?", não precisei declarar os relacionamentos no powergrid table para conseguir filtrar pelos relacionados.

**Comment by luanfreitasdev** [comment]
Olá @gonribeiro , para resolver o problema do campo 'quitado', você pode adicionar no powergrid dentro de addColumn, ficaria assim (isso provavelmente irá sobrescrever o attributo getQuitadoAttribute nessa classe ):

```php
    return PowerGrid::eloquent()
            ->addColumn('quitado', function(Compra $compra) {
               return $this->parcela_paga ? true : false;
            });
```

A segunda questão do filtro, se você estiver usando join não precisaria usar o relationSearch pois o campo já estaria na tabela
