### ISSUE TITLE
showToggleColumns() mess with <td>

### ISSUE THREAD

**Issue by sebreunion** [Power-Components/livewire-powergrid#218]
**Describe the bug**
When using ->showToggleColumns() in setUp(), when you show / hide column, the table td is messed up. Some extra TDs are added to the end of the row.
* 

**To Reproduce**
Fresh laravel project.
composer require power-components/livewire-powergrid
php artisan powergrid:demo
Add ->showToggleColumns() in setUp()
Load the page => First Load, all column are shown, all is fine
Hide a column => Table is refreshed and the columns on the first row are messed up.

On my actual project, i do not have any action, the added TDs are present on all rows, not only the first one. 
The number of extra added TDs is equal to the number of hidden columns.

**Laravel version (exactly)** 
v8.78.1 (PHP v8.0.7)
*

**Livewire version (exactly)**
 v2.8.2
*

**AlpineJS:** 

*

**Theme:**

**Screenshots** (***This helps to understand better***)
**DEMO with actions**
Before toggling Email => All is fine
![image](https://user-images.githubusercontent.com/4515810/148741531-5535c564-e51c-4497-a44f-f59f9b424bd6.png)
After toggling email => Added TD on the first row
![image](https://user-images.githubusercontent.com/4515810/148741623-f28de565-68c8-44c8-90a2-e64b3e6dcf0e.png)
**Demo without actions**
Before toggling any column => All is fine
![image](https://user-images.githubusercontent.com/4515810/148742276-4dea782a-7aed-4c44-8beb-880c01b615c7.png)
After toggling **2** columns => **2** added TDs on every row.
![image](https://user-images.githubusercontent.com/4515810/148742194-a4d9929f-4b7c-4583-9401-3bea344c8442.png)

**Do you have any idea how we can fix it?**

components\row.blade.php line 18
`wire:key="{{ md5('row') }}"` => All TDs of a row have the same wire:id and the issue occurs.

Getting all TDs of a row to have different wire:id => Issue is gone.

Thx for any help

**Comment by luanfreitasdev** [comment]
Hello, @sebreunion .

Unfortunately I still haven't been able to understand why this bug exists even though I've been constantly investigating.

If you have any suggestions of what it could be, that would help everyone a lot.

But I will keep investigating

Thanks

**Comment by luanfreitasdev** [comment]
I made some improvements to wire:key and changed the logic to show/hide.

It's already in [2.1.2](https://github.com/Power-Components/livewire-powergrid/releases/tag/v2.1.2)

Thanks
