### ISSUE TITLE
Livewire powergrid undefined $row when defining a single button in header method

### ISSUE THREAD

**Issue by pathros** [Power-Components/livewire-powergrid#220]
I'm using the [Livewire PowerGrid package](https://github.com/Power-Components/livewire-powergrid) latest version on Laravel 8 Jetstream, TailwindCSS 3 and AlpineJS 3.7.

What I want to do is to add a single *new* button to allow the user create a new record.

According to the [official docs](https://livewire-powergrid.com/#/table/row-actions-buttons?id=usage), I have defined a button like so, inside the header() function:

    //..
    public function header(): array
    {
        return [
            Button::add('new-modal')
                ->caption('New window')
                ->class('bg-gray-300')
                ->openModal('new', []),
                
            //...
        ];
    }

However, I get the following error:

> Undefined variable $row in
> View::/vendor/livewire-powergrid/components/actions-header.blade.php
> on line 22

What am I missing? How do I fix it?

**Comment by luanfreitasdev** [comment]
Thanks for reporting this bug, I'm uploading an update with the fix.

https://github.com/Power-Components/livewire-powergrid/releases/tag/v2.0.1
