### ISSUE TITLE
Create a report to help us improve

### ISSUE THREAD

**Issue by PeterVoskuilen** [Power-Components/livewire-powergrid#224]
First of all, did you see if your problem has happened to other people before?
- [ ] Yes - I did not find it 
- [X ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [X ] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [X ] No

**Describe the bug**
When using Button in acctions() function the route parameters with value 0 (zero) are not set but the value 'id' instead is used.

My Code:
`Button::add('select')
               ->caption(__('View'))
               ->class('btn bg-blue-500')
               ->route('doc.showAccount', ['id' => 'id', 'dummy' => 'id'])
               ->target('_self') ,`

In this case the value of id is 0 (zero) in the database. 
Instead of a link with the value zero the text id is used in the button link

so i except http://127.0.0.1:8000/doc/account/show/0/0
but i get http://127.0.0.1:8000/doc/account/show/id/id

**To Reproduce**
Add button like code above and have a id or otherfield in your table with the value 0

**Laravel version (exactly)** 

> PS C:\Projects\PHPStorm\athena> php artisan --version
> Laravel Framework 8.79.0
> PS C:\Projects\PHPStorm\athena>

**Livewire version (exactly)**

> livewire/livewire                    v2.8.2    A front-end framework for Laravel.

**AlpineJS:** 

yes, but version unknown

**Theme:**
- [X] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [ ] Bootstrap - Version:        

**Do you have any idea how we can fix it?**
no clue :-)

**Comment by luanfreitasdev** [comment]
Hi, I believe I did this!

Thanks for the bug report

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/releases/tag/v2.1.0
