### ISSUE TITLE
When selecting date range query date is different then in the input (-2hrs)

### ISSUE THREAD

**Issue by pauleniz** [Power-Components/livewire-powergrid#230]
First of all, did you see if your problem has happened to other people before?
- [x] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**
Im selecting date range from 2022-01-01 to 2022-01-03 and the query range is  2021-12-31 22:00:00  2022-01-02 22:00:00
* 

**To Reproduce**
I think its because there are not time zones on the flatpicker

**Laravel version (exactly)** 
8.40
*

**Livewire version (exactly)**
2.5
*

**AlpineJS:** 
3.x.x from powergrid config
*

**Theme:**
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [x] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)
![image](https://user-images.githubusercontent.com/65357711/149624737-7d4eb183-85be-4793-9828-353b831c0790.png)

**Do you have any idea how we can fix it?**
well my fix is that I removed the time from the input data by including little foreach and date conversion in datePikerChanged() function
file location: livewire-powergrid/src/Traits/Filter.php

```
public function datePikerChanged(array $data): void
    {
        $this->resetPage();

        $input                                   = explode('.', $data['values']);
       
        //this is my solution
        foreach ($data['selectedDates'] as $key => $selectedDate) {
            $data['selectedDates'][$key] = Carbon::parse($selectedDate)->addHour(2)->format('y-m-d');
        }
        //end of my solution

        $this->enabledFilters[$data['field']]['data-field']      = $data['field'];
        $this->enabledFilters[$data['field']]['label']           = $data['label'];

        if (count($input) === 3) {
            $this->filters['date_picker'][$input[2]] = $data['selectedDates'];

            return;
        }

        if (count($input) === 4) {
            $this->filters['date_picker'][$input[2] . '.' . $input[3]] = $data['selectedDates'];

            return;
        }

        if (count($input) === 5) {
            $this->filters['date_picker'][$input[2] . '.' . $input[3] . '.' . $input[4]] = $data['selectedDates'];
        }
    }
```

then i get this query:
![image](https://user-images.githubusercontent.com/65357711/149624908-81690d45-7616-4d7f-8cb4-2cec454d55fd.png)

it still shows time but maybe you can implement in config file some kind of variable like time zone or something that will add or subtract hours from input date based on time zone

**Put part of your code, an html screenshot of the problem element:**

**Comment by luanfreitasdev** [comment]
Hello, very well observed and I believe this can bring false positives. But that way the bank still wouldn't return the correct value on the last date because it would have to get the last hour of the last date right?.

I believe, correct me if I'm wrong, but with this function we have the most accurate date in relation to times

```php
data_set($data, 'selectedDates.0', Carbon::parse(data_get($data, 'selectedDates.0'))->setTime(0, 0));
data_set($data, 'selectedDates.1', Carbon::parse(data_get($data, 'selectedDates.1'))->setTime(23, 59, 59));
```

**Objective: I want you to return dishes from the 16th**
![image](https://user-images.githubusercontent.com/33601626/149626567-55420fcc-22dc-4859-a570-cd3bef7e2cb1.png)

DB:
![image](https://user-images.githubusercontent.com/33601626/149626539-7708d1cf-fc33-446d-899c-40928d27cd34.png)

----

With its implementation:

![image](https://user-images.githubusercontent.com/33601626/149626525-ec77ffda-15f4-438e-a977-8ce65db44520.png)

On the issue of assigning the time zone, I believe it is not the best option since in the database we do not save with the Timezone defined (we usually convert the date according to the local user).

What do you tell me with this implementation?

Thanks

**Comment by pauleniz** [comment]
You are right with my solution I cant filter properly because its form 2022-01-16 00:00:00 to 2022-01-16 00:00:00 (same time) but when I implement your function right after my foreach loop it works perfectly. If I remove foreach loop it gives me 1 day earlier because of that -2hours thing. So that the only problem to solve the issue with that -2hours I tried changing time zone in app config file from "Europe/Vilnius" to "Europe/London" nothing changed my time zone is Europe/Vilnius (GMT+2) and I think its because of that there is 2hrs difference.
I tried changing time zone in my computer setting to UTC (GMT+0) and it fixed the problem (no need for that foreach loop). 

But the issue still exists and its that if PC has time zone settings that has GMT+X the then date is one day earlier then specified.
I dont know why that conversion even happens maybe its because of Chorme.

**Comment by pauleniz** [comment]
I think this is a flatpicker issue. It does the conversions instead of passing just the input date that is displayed in the field

**Comment by luanfreitasdev** [comment]
From what I understand, the times are sent with UTC starting at 00:00, that is, for me, the UTC is 03:00, for you it is 23:00, so I believe that the correct thing would be to change the start and end times to 0:00 to 23:00 . What do you think ?

**Comment by pauleniz** [comment]
Im not sure my brain is about to explode since I dont know javascript all i know is that javascript from flat picker passes the date that is changed to utc from my local time so it makes that -2hours thing and i dont understand why does it even do that tried looking for solution that would remove this conversion by providing custom config but didnt find anything

**Comment by luanfreitasdev** [comment]
Hi, can you do this implementation in your place to test?

```
data_set($data, 'selectedDates.0', Carbon::parse(data_get($data, 'selectedDates.0'))->setTime(0, 0));
data_set($data, 'selectedDates.1', Carbon::parse(data_get($data, 'selectedDates.1'))->setTime(23, 59, 59));
```

**Comment by pauleniz** [comment]
It does help because its fixes the problem with range because by default it would be xxxx-xx-xx 00:00:00 to xxxx-xx-xx 00:00:00
but now its xxxx-xx-xx 00:00:00 to xxxx-xx-xx 23:59:59 but the other issue is that since my time zone on the laptop is GMT+2 and flatpicker takes my datetime and subtracts that +2 to make it UTC and then i get both dates -1 day
![image](https://user-images.githubusercontent.com/65357711/150057532-70bd0085-b257-4328-8d9c-1ba37f870e59.png)

**Comment by pauleniz** [comment]
My solution is this if date->format('H') > 12 that means timezone is GTM+X and if so then i add 1 day to both dates and that solves the problem for me

![image](https://user-images.githubusercontent.com/65357711/150059575-43778f80-69f4-4c23-b105-f95081ce8cdc.png)

code:

```
public function datePikerChanged(array $data): void
    {
        $this->resetPage();

        $input                                   = explode('.', $data['values']);


        $date1 = Carbon::parse(data_get($data, 'selectedDates.0'));
        $date2 = Carbon::parse(data_get($data, 'selectedDates.1'));

        if($date1->format('H') > 12)
        {
            $date1 = $date1->addDay();
            $date2 = $date2->addDay();
        }

        data_set($data, 'selectedDates.0', $date1->setTime(0, 0));
        data_set($data, 'selectedDates.1', $date2->setTime(23, 59, 59));

        $this->enabledFilters[$data['field']]['data-field']      = $data['field'];
        $this->enabledFilters[$data['field']]['label']           = $data['label'];

        if (count($input) === 3) {
            $this->filters['date_picker'][$input[2]] = $data['selectedDates'];

            return;
        }

        if (count($input) === 4) {
            $this->filters['date_picker'][$input[2] . '.' . $input[3]] = $data['selectedDates'];

            return;
        }

        if (count($input) === 5) {
            $this->filters['date_picker'][$input[2] . '.' . $input[3] . '.' . $input[4]] = $data['selectedDates'];
        }
    }
```

**Comment by luanfreitasdev** [comment]
Glad it went right!. But you can put it outside the package and put it inside the component or in a trait like this example:

Time corrections are already in release 2.2

thank you

```php
protected function getListeners(): array
{
     return array_merge(
          parent::getListeners(), [
          'pg:datePicker-' . $this->tableName => 'formatPickerChanged'
     ]);
}

public function formatPickerChanged(array $data)
{
     $startDate = Carbon::parse(data_get($data, 'selectedDates.0'));
     $endDate = Carbon::parse(data_get($data, 'selectedDates.1'));

     if ($endDate->format('H') > 12) {
          data_set($data, 'selectedDates.0', $startDate->addMonth());
          data_set($data, 'selectedDates.1', $endDate->addDay());
     }

     $this->datePikerChanged($data);
}
```
