### ISSUE TITLE
Getting Error During creation of table

### ISSUE THREAD

**Issue by mwnthainarzary** [Power-Components/livewire-powergrid#247]
First of all, did you see if your problem has happened to other people before?
- [ ] Yes - I did not find it 
- [x] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [x] Yes - I'll put a screenshot
- [ ] No

**Describe the bug**

*  During the creation of the table with the console, an unusual text comes along with output. I have attached the screenshot.
*  After attachment of the table with view blade, It throws helper method error.

**To Reproduce**
* Got to ..

**Laravel version (exactly)** 

* 8.40

**Livewire version (exactly)**

* 2.5

**AlpineJS:** 

* 3.0.6

**Theme:**
- [x] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [ ] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)
![issue-1](https://user-images.githubusercontent.com/71560029/151322944-36e51b22-0356-4f09-95dd-22d04e5ec9dd.png)

![Issue](https://user-images.githubusercontent.com/71560029/151323004-2286534d-d9c1-456a-86db-346b5d0d0004.png)

**Do you have any idea how we can fix it?**

**Put part of your code, an html screenshot of the problem element:**

**Comment by dansysanalyst** [comment]
Thank you for submitting an issue,

@luanfreitasdev As I can see, `Arr:undot` was introduced in Laravel [8.74](https://laravel-news.com/laravel-8-74-0).

@mwnthainarzary would you consider upgrading your Laravel installation from 8.40 to the most recent release?

**Comment by mwnthainarzary** [comment]
Thank you for letting me know. I will upgrade to the latest release.
