### ISSUE TITLE
Update method is not updating the correct record.

### ISSUE THREAD

**Issue by Mo7sin** [Power-Components/livewire-powergrid#258]
First of all, did you see if your problem has happened to other people before?
- [x] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**
I have a powergrid table that has many searchable fields, the issue happens only when I use search to filter a record and then update that record (**using click to edit feature**).

I did some debugging and I found that the update method always updates the latest record in the table instead of the filtered one.

### More details
I search for one record and I found it correctly, that record has an ` id  = 14234`.

when I `dd($data);` I found that the id included in the $data array is always the latest record in the table `id = 14221`, So it's updating that latest record instead of the desired one.

**Laravel version (exactly)** 
8.82.0

**Livewire version (exactly)**
2.10.1

**AlpineJS:** 
3.8.1

**Theme:**
- [ ] Tailwind 2.x
- [x] Tailwind 3.x
  - [x] With tailwind/forms
- [ ] Bootstrap - Version:

**Comment by luanfreitasdev** [comment]
Hi @Mo7sin , thank you for your report of this bug!

I managed to fix the bug and I'm already uploading an update

Thanks

**Comment by Mo7sin** [comment]
Thank you for the quick fix.

Are you going to push this commit to the main branch?

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/releases/tag/v2.2.5

**Comment by Mo7sin** [comment]
Thank you @luanfreitasdev 

Unfortunately, the issue remains still, The update method still updating the last record in the table.

**Comment by luanfreitasdev** [comment]
That's weird, I simulated the same error and it worked. Do you use the vendor inside the resources folder? Could you check the installation if it contains the latest fixes?

**Comment by Mo7sin** [comment]
Let me duple check the updated files once again.

**Comment by Mo7sin** [comment]
My files were outdated indeed, now everything just working normally once they got updated.

Thank you very much.
