### ISSUE TITLE
Pesquisa em coluna com relationship

### ISSUE THREAD

**Issue by jhosepharaujo** [Power-Components/livewire-powergrid#26]
Salve equipe do powergrid, antes de tudo parabéns pela ferramenta, simplesmente incrível. Gostaria de tirar uma dúvida, acredito que esteja fazendo algo errado quero realizar uma busca por um campo relationship. Cheguei até adicionar o campo como um atributo no model mas não deu certo. Seguem as implementações:

```
Models\Lancamento.php

class Lancamento extends Model
{
    public function transacao()
    {
        return $this->belongsTo(Transacao::class);
    }

    public function getUserAttribute()
    {
        return $this->attributes['user'] = $this->transacao->user->name;
    }
}
```
```
Components\LancamentoTable.php

class LancamentosTable extends PowerGridComponent
{
    use ActionButton;

    public function setUp()
    {
            $this->showPerPage()
            ->showSearchInput();
    }

    public function dataSource()
    {
        return Lancamento::query();
    }

    public function addColumns()
    {
        return PowerGrid::eloquent()
            ->addColumn('id')
            ->addColumn('user', function(Lancamento $model){
                return $model->user;
            })
            ->addColumn('descricao')
            ->addColumn('status')
            ->addColumn('created_at_formatted', function(Lancamento $model) {
                 return Carbon::parse($model->created_at)->format('d/m/Y H:i:s');
             });
    }

    public function columns(): array
    {
        return [
            Column::add()
                ->title(__('ID'))
                ->field('id'),

            Column::add()
                ->title(__('Usuário'))
                ->field('user')
                ->searchable(),

            Column::add()
                ->title(__('Descrição'))
                ->field('descricao'),

            Column::add()
                ->title(__('Status'))
                ->field('status')
                ->searchable(),

            Column::add()
                ->title(__('Data'))
                ->field('created_at_formatted'),

        ];
    }
}
```
Quando não é realizado nenhuma pesquisa a tabela exibe os dados normalmente conforme imagem abaixo:

![image](https://user-images.githubusercontent.com/2037683/122223500-988ab280-ce89-11eb-902d-4b28a6149208.png)

Quando busco pelo nome do usuário no campo search, não retorna nenhum dado:

![image](https://user-images.githubusercontent.com/2037683/122223811-ea333d00-ce89-11eb-838c-5ae6f29e7f49.png)

Outro detalhe que verifiquei foi que na requisição todos os campos estão marcados como searchable = true, mesmo eu tendo adicionado apenas os campos user e status:

![image](https://user-images.githubusercontent.com/2037683/122224290-5877ff80-ce8a-11eb-923c-d60aa4db9b01.png)

Como fazer essa pesquisa corretamente?

**Comment by luanfreitasdev** [comment]
Salve @jhosepharaujo , jóia?

No momento ainda não é possível implementar esse tipo de filtro, porém já está em nosso radar para implementar.

O que você pode fazer no momento é usar o filtro **makeInputMultiSelect** para pesquisar um campo numa tabela relacional, por exemplo:

Da uma olhada na linha 116 em https://github.com/Power-Components/powergrid-demo/blob/main/app/Http/Livewire/DishesTable.php

![image](https://user-images.githubusercontent.com/33601626/122413672-f0461e00-cf5c-11eb-9879-9903f12a057f.png)

Quanto ao searchable, obrigado pela observação, vou dar uma olhada nessa semana
 
Qualquer coisa da um toque e muito obrigado por usar o Powergrid

**Comment by luanfreitasdev** [comment]
added into [v1.2](https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.2.0)

**Comment by luanfreitasdev** [comment]
added into [v1.1.6](https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.1.6)
