### ISSUE TITLE
Table Styling Colors are Incorrect

### ISSUE THREAD

**Issue by rev9tech** [Power-Components/livewire-powergrid#261]
Noticed a significant difference in color styling for the Powergrid demo when changing from the CDN applied styled to a Laravel webmix compiled stylesheet.  Below is the detail:

Tailwind version 3.0.18
Laravel Jetstream 2.6
Laravel Version 8.75

In the Powergrid demo, changed the stylesheet reference from 
`<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">`

to my laravel compiled Tailwind 3.0 CSS:
`<link rel="stylesheet" href="{{ mix('css/app.css') }}">`

The table does not render the colors correctly as seen per the screen shot.  They are extremely dark.  I also ran npm run dev to ensure the app.css is updated.
![screenshot](https://user-images.githubusercontent.com/56508172/152457319-1afe5223-a8a0-4adc-b9b5-e04898356625.jpg)

Here is my tailwind.config.js:
```
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',

        // Add for PowerGrid Package
        './app/Http/Livewire/**/*Table.php',
        './vendor/power-components/livewire-powergrid/resources/views/**/*.php',
        './vendor/power-components/livewire-powergrid/src/Themes/Tailwind.php'
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Nunito', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [
        require("@tailwindcss/forms")({
            strategy: 'class',
          }),
        require('@tailwindcss/typography')
    ],
};
```
Laravel webmix compiled CSS:
[app.txt](https://github.com/Power-Components/livewire-powergrid/files/7999382/app.txt)

**Comment by bitstreambiker** [comment]
Let me know if you figure it out ... I have the exact same issue.  Using Laravel and Jetstream.

**Comment by luanfreitasdev** [comment]
I couldn't reproduce this behavior even when downloading a new project with jetstream. Can you publish your project?

**Comment by rev9tech** [comment]
@luanfreitasdev I was just able to reproduce the issue with a new project.  Here are the steps:

- [ ] composer create-project laravel/laravel powergrid
- [ ] composer require livewire/livewire
- [ ] Add SQLite config to .env and create databases/database.sqlite
- [ ] composer require laravel/jetstream
- [ ] php artisan jetstream:install livewire
- [ ] npm install
- [ ] npm run dev
- [ ] php artisan migrate
- [ ] composer require power-components/livewire-powergrid
- [ ] php artisan powergrid:demo
- [ ] Add  to web.php - `Route::view('/powergrid', 'powergrid-demo');`
- [ ] Comment out CDN reference `<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">` and add `<link rel="stylesheet" href="{{ mix('css/app.css') }}">`
- [ ] npm run dev (ISSUE STARTS NOW)
- [ ] Make the changes to the tailwind.config.js file per the docs:
```
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './app/Http/Livewire/**/*Table.php',
        './vendor/power-components/livewire-powergrid/resources/views/**/*.php',
        './vendor/power-components/livewire-powergrid/src/Themes/Tailwind.php'
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Nunito', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [
        require("@tailwindcss/forms")({
            strategy: 'class',
        }), 
      require('@tailwindcss/typography')],
};
```

- [ ] npm run dev 
Issue is like this screenshot:
![screenshot-1](https://user-images.githubusercontent.com/56508172/152626152-dad4cd4a-6129-4b67-8c4e-b4566421f02b.jpg)

**Comment by luanfreitasdev** [comment]
I did all the steps above and I didn't have this dark screen, it's usually applied when it's in dark mode

![image](https://user-images.githubusercontent.com/33601626/152638136-216e580d-1926-4412-a97d-798beff148ad.png)

![image](https://user-images.githubusercontent.com/33601626/152638080-43626c84-2ae2-4429-a3b3-8f4a00f4d30e.png)

**Comment by bitstreambiker** [comment]
For me the fix to getting it white and disable dark mode which I got by
default was to follow the steps to enable it.  So it was working opposite.

—Mark

**Comment by luanfreitasdev** [comment]
Hi @bitstreambiker , could you share your solution?

**Comment by rev9tech** [comment]
I had to add: `darkMode: 'class',` under module.exports and run npm run dev and the issue resolved itself!  Thanks @bitstreambiker
