### ISSUE TITLE
Create a report to help us improve

### ISSUE THREAD

**Issue by ludioao** [Power-Components/livewire-powergrid#262]
First of all, did you see if your problem has happened to other people before?
- [X] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [X] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [X] Yes - I'll put a screenshot
- [ ] No

**Describe the bug**
* It seems that columns sometimes is an array instead of object. 

**To Reproduce**
* When I try to update a field I got an error. 

**Laravel version (exactly)** 
* 8.65

**Livewire version (exactly)**
* 2.5

**AlpineJS:** 
* 3

**Theme:**
- [ ] Tailwind 2.x
- [x] Tailwind 3.x
  - [ ] With tailwind/forms
- [ ] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)
![image](https://user-images.githubusercontent.com/7070404/152465717-5f38fbcb-bfed-4f81-9c75-86dd1798028d.png)

**Do you have any idea how we can fix it?**
Forcing to be object or investigate where columns are registered.

**Put part of your code, an html screenshot of the problem element:**
-

**Comment by luanfreitasdev** [comment]
Hi @ludioao . Did you manage to solve this problem? I was still investigating and testing.
