### ISSUE TITLE
Question: @powerGridScripts vs @powerScripts

### ISSUE THREAD

**Issue by odin88** [Power-Components/livewire-powergrid#263]
Question :
I just notice you have release version 2.
I am upgrading and already read the docs in this page - https://livewire-powergrid.com/#/get-started/upgrade-v1
Does it mean we can replace @powerGridScripts to @powerScripts ?
How about the rest of the tag ? like  @powerGridStyles, does it become @powerStyles ?
Do we also need to update in this page ? https://livewire-powergrid.com/#/get-started/configure?id=_1-include-scripts-and-styles

**Comment by luanfreitasdev** [comment]
Hi, it's still mandatory, but it was a typo in the doc.

Thanks
