### ISSUE TITLE
Feature Request: `makeInputEnum`

### ISSUE THREAD

**Issue by NathanaelGT** [Power-Components/livewire-powergrid#264]
Hi, this is a feature request, not an bug report

With the release of PHP 8.1, enum was introduced and laravel supports enum casting. It would be great if we could make use of it.
For example, we already have `makeInputSelect` for relationship, how about something like `makeInputEnum`?

PS: I have tried to "hack" `makeInputSelect`
```php
makeInputSelect(collect(TableStatus::cases())->map(fn ($status) => (array) $status), 'value', 'status')
```
thats show the filter options correctly, but do nothing whatsoever when selected
![image](https://user-images.githubusercontent.com/32760797/152638557-b7223812-a6ec-4cbb-b25b-e67f1c212ead.png)
![image](https://user-images.githubusercontent.com/32760797/152638577-e128b074-ed5a-4f96-a33c-3ea166ce555b.png)

**Comment by joaonivaldo** [comment]
I managed to get around this difficulty by manually creating a simple enum class as shown in the code below: 

`<?php

namespace App\Enumerations;

class UserStatusEnum
{
    const UNCONFIRMED = 0;
    const ACTIVE      = 1;
    const SUSPENDED   = 2;
    const BANNED      = 3;
    const INACTIVE    = 4;
    
    public static function getValues()
    {
        return[
            self::UNCONFIRMED,
            self::ACTIVE,
            self::SUSPENDED,
            self::BANNED,
            self::INACTIVE,
        ];
    }

    public static function getOptions()
    {
        return[
            self::UNCONFIRMED => "Não Confirmado",
            self::ACTIVE      => "Ativo",
            self::SUSPENDED   => "Suspenso",
            self::BANNED      => "Banido",
            self::INACTIVE    => "Inativo",
        ];
    }

    public static function getCollect()
    {
        $userStatus=collect();
        foreach (UserStatusEnum::getOptions() as $key=>$value){
            $userStatus->push(['id'=>$key, 'value'=>$value]);
        }

        return $userStatus;
    }
}
`
Then in InputSelect it was like this:
`Column::add()->title('STATUS')->field('status')->makeInputSelect(UserStatusEnum::getCollect(),'value','id'),`

Doing so worked fine in use. Hope this can help you.
