### ISSUE TITLE
UUID as primary key, not displaying as expected in the table

### ISSUE THREAD

**Issue by sharathdn1** [Power-Components/livewire-powergrid#267]
I'm using primary key id as uuid, powergrid table only displays the first char of the uuid  (if first char is number, 0 otherwise) in the table.

migration file:
$table->uuid('id')->primary();

datatable:
![image](https://user-images.githubusercontent.com/12691864/152948964-d5a4ecce-20d6-4f19-85e7-27b81fd203bf.png)

powergrid table:
![image](https://user-images.githubusercontent.com/12691864/152949189-7bc6498e-4f43-4c2a-89dc-3ab248ab1e13.png)

**Comment by luanfreitasdev** [comment]
Olá @sharathdn1 . 

This was a solution I found:

`App\Models\YourModel.php`
```php
protected $casts = [
     'id' => 'string'
];
```

![image](https://user-images.githubusercontent.com/33601626/153089332-89ec94bb-6c8e-43bf-94ae-bea47069c937.png)

**Comment by sharathdn1** [comment]
Thanks @luanfreitasdev, it worked.
