### ISSUE TITLE
Multiple tables join issue

### ISSUE THREAD

**Issue by sharathdn1** [Power-Components/livewire-powergrid#268]
Unable to join multiple tables, only the last join is reflecting in the query result.

**Comment by luanfreitasdev** [comment]
Hi @sharathdn1 . can be more specific? what version are you using?.

Could you show us how you are using the component in more detail.

**Comment by sharathdn1** [comment]
I'm using latest version i.e. ^2.2

This is how i'm using:
public function datasource(): ?Builder
    {
        return Table1Model::query()
            ->join('table2', function ($qry1) {
                $qry1->on('table1.table2_id', '=', 'table2.id');
            })
            ->join('table3', function ($qry2) {
                $qry2->on('table1.table3_id', '=', 'table3.id');
            });
    }

public function addColumns(): ?PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ->addColumn('id',)
            ->addColumn('table2_key')
            ->addColumn('table3_key')
            ;
    }

public function columns(): array
    {
        return [
            Column::add()
                ->title('ID')
                ->field('id')
                ->searchable()
                ->sortable(),

            Column::add()
                ->title('Table2 Key')
                ->field('table2_key', 'table2.table2_key')
                ->searchable()
                ->sortable(),

            Column::add()
                ->title('Table3 Key')
                ->field('table3_key', 'table3.table3_key')
                ->searchable()
                ->sortable()
        ];
    }

<img width="677" alt="image" src="https://user-images.githubusercontent.com/12691864/153408255-4bfd0ed8-4aec-4a58-a6cd-4c10c052580c.png">

**Comment by luanfreitasdev** [comment]
If you put this query inside the dd() it appears correct?.

**Comment by luanfreitasdev** [comment]
![image](https://user-images.githubusercontent.com/33601626/160615509-70543dca-1f53-4038-b4aa-ab44ebdff0d6.png)

Please check the attachment

[table-join.zip](https://github.com/Power-Components/livewire-powergrid/files/8371595/table-join.zip)
