### ISSUE TITLE
Select Filter Rendering

### ISSUE THREAD

**Issue by amaurycid** [Power-Components/livewire-powergrid#27]
Why is this select filter renders this way?
![Screenshot from 2021-06-17 07-33-48](https://user-images.githubusercontent.com/6839739/122389355-dac1fb80-cf3e-11eb-864d-0edd6e7e68b9.png)

**Comment by luanfreitasdev** [comment]
Hi @amaurycid 

have you tried the following commands?
`php artisan view:clear` or 
`composer dump-autoload` ?

**Comment by amaurycid** [comment]
Hi @luanfreitasdev 

Yes, I tried that with no difference. It keeps rendering like that whatsoever.

**Comment by luanfreitasdev** [comment]
did you try to delete vendor and composer.lock and composer install ?

**Comment by RishabSwift** [comment]
@luanfreitasdev It seems like the language file `en/datatable.php` only has `multi_select` key but not `select` key. However, this is not the case for `es/datatable.php` for instance.

**Comment by luanfreitasdev** [comment]
Hello @RishabSwift , thanks for noticing this bug!

I'm already uploading the correction immediately and putting the new version
