### ISSUE TITLE
Missing Action Buttons after changing Per Page count.

### ISSUE THREAD

**Issue by malvin01** [Power-Components/livewire-powergrid#276]
First of all, did you see if your problem has happened to other people before?
- [X] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [X] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [X] No

**Describe the bug**
I noticed that when I change the Per Page count from 10 to 25, the 10 row loses the action button
* 

**To Reproduce**
* Got to ..

**Laravel version (exactly)** 
^8.0
*

**Livewire version (exactly)**
^2.4
*

**AlpineJS:** 
^3.0
*

**Theme:**
- [ ] Tailwind 2.x
- [ X] Tailwind 3.x
  - [ X] With tailwind/forms
- [ ] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)

**Do you have any idea how we can fix it?**

**Put part of your code, an html screenshot of the problem element:**

**Comment by malvin01** [comment]
https://user-images.githubusercontent.com/42507283/154121116-9df611d6-90cc-470d-9fd5-97083bae4fe6.mp4

**Comment by luanfreitasdev** [comment]
Hello @malvin01 

Are you using ActionRules ? Can you post part of the component you generated?

What version of powergrid?.

**Comment by malvin01** [comment]
Hello @luanfreitasdev , I don't use action rules. just use the actions method. maybe this can help.
My version = 2.2.6

![Screenshot_330](https://user-images.githubusercontent.com/42507283/154223605-a36abd94-2549-47c6-96e2-cb77d6bafc38.png)
![Screenshot_331](https://user-images.githubusercontent.com/42507283/154223617-258decf1-1edd-4998-9012-3e143ec8ebc7.png)

![Screenshot_329](https://user-images.githubusercontent.com/42507283/154223133-55e328ac-91e4-45f6-85b8-3c4f0e2923d3.png)

**Comment by luanfreitasdev** [comment]
Curious, here it is working normally. Did you get an error in the console? apparently your component is right.

https://user-images.githubusercontent.com/33601626/154256359-9cd0ea06-056b-4233-a3e2-6f17010b0bef.mp4


If you inspect the html element what appears?

**Comment by malvin01** [comment]
https://user-images.githubusercontent.com/42507283/154260167-97633ffa-eb7c-4081-85f9-6deee36abbd3.mp4

empty td

**Comment by luanfreitasdev** [comment]
If you start the table with 25 does it work?
Can you put a dump on line 8 of the actions.blade.php view?

@dump($actions, $row->id)

![image](https://user-images.githubusercontent.com/33601626/154265730-5e16c569-2d24-401b-bb9f-0d78450ca76a.png)

Something like this should appear

![image](https://user-images.githubusercontent.com/33601626/154265873-5a824c94-9d0e-4636-ace3-2e8604e8b6d6.png)

**Comment by malvin01** [comment]
https://user-images.githubusercontent.com/42507283/154275773-8b4ec08e-7a99-42ad-b56f-8bb9ca3334fd.mp4

I'm not really sure, the data is there but the button is missing

**Comment by luanfreitasdev** [comment]
Can you send the dump of id 9, 10 and 11 right here for easier reading

**Comment by malvin01** [comment]
![Screenshot_332](https://user-images.githubusercontent.com/42507283/154372556-9f6b41ec-ce51-452e-86c7-b4e613ac9bec.png)
![Screenshot_333](https://user-images.githubusercontent.com/42507283/154372562-c18cf890-3e01-4d12-bc18-c6d89651a206.png)
![Screenshot_334](https://user-images.githubusercontent.com/42507283/154372559-ff569e03-2e17-4e65-979f-8422638d4775.png)

**Comment by luanfreitasdev** [comment]
Still investigating. 👀

**Comment by NathanaelGT** [comment]
Happen to me several times, maybe [dom diffing issue](https://laravel-livewire.com/docs/2.x/troubleshooting#dom-diffing-issues)?

**Comment by luanfreitasdev** [comment]
@malvin01 , can you test with the dev-main branch?

**Comment by zaimazhar** [comment]
#308 should solve this, I got the same bug too when emitting an event (delete query). I have made a check on the `$key` by echoing it, it display the integer 0 for each row.

**Comment by luanfreitasdev** [comment]
do you also believe you should run out of wire:key at this point?

**Comment by luanfreitasdev** [comment]
As I didn't get an answer. I'm closing this issue.
