### ISSUE TITLE
Can we add Bulk Action ? 

### ISSUE THREAD

**Issue by businessdotkom2020** [Power-Components/livewire-powergrid#278]

**Comment by dansysanalyst** [comment]
Hello @businessdotkom2020,

Thank you for submitting an issue.

You can see an example of Bulk Actions in the [PowerGrid Demo Repository](https://github.com/Power-Components/powergrid-demo).

<img width="976" alt="CleanShot 2022-02-16 at 21 22 19@2x" src="https://user-images.githubusercontent.com/79267265/154350681-9c5ddeeb-9546-4080-a1ac-861162d59d75.png">

If you are looking to contribute to PowerGrid, please feel free to submit a PR with your idea. 

You can find more information in the [Contributing guide](https://github.com/Power-Components/livewire-powergrid/blob/main/CONTRIBUTING.md).

**Comment by sampath-kumara-herath** [comment]
Cant use it with bootstrap 5. Not showing the bulk action button
