### ISSUE TITLE
export xlsx error

### ISSUE THREAD

**Issue by fnoopv** [Power-Components/livewire-powergrid#28]
mycode
![image](https://user-images.githubusercontent.com/24599198/124347621-3915fc00-dc18-11eb-984b-64f8f8f6e27e.png)
export xlsx file
![image](https://user-images.githubusercontent.com/24599198/124347662-61055f80-dc18-11eb-8b4d-6d0ca146e4f3.png)
it's not the true value, include my custom style

**Comment by luanfreitasdev** [comment]
Hi @fnoopv

In order for you to display the status correctly, you will have to call addColumns one more time but without the formation. For example:
```

->addColumns('status_export', function(Instance $instance) {
     if ($instance === 1) {
          return 'Ok';
     }
    
     return 'Not Ok';
})
```

And in the columns method, it will look like this:

For the status field add this: `->visibleInExport(false)
`And for the status_export field add this: `->visibleInExport(true)`

Thanks for using PG ⚡!

**Comment by fnoopv** [comment]
Thanks
