### ISSUE TITLE
Format numeric value and display a sum in header / footer

### ISSUE THREAD

**Issue by sebreunion** [Power-Components/livewire-powergrid#281]
First of all, did you see if your problem has happened to other people before?
- [ ] Yes - I did not find it 
- [X] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [X] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [X] No

**Describe the bug**
I'm unable to format numeric value on screen while being able to display sum in header / footer.

I've got some numeric value in DB. 

I format them in addColumns()

```
->addColumn('base', function(MyModel $model) {
    return number_format($model->base, 2, ',', ' ');
})
```
in columns() 

```
Column::add()
      ->title('Base')
      ->field('base')
      ->withSum('', true, true)
```

no sum is diplayed in header / footer because the of the  `&& is_numeric($withoutPaginatedData[0][$field])` in table-header/footer.blade.php

When removing the number_format(), the sum is displayed but neither the column or the sum is formatted.

When removing the `&& is_numeric($withoutPaginatedData[0][$field])`, `$withoutPaginatedData->collect()->sum($field)` throw an error `A non-numeric value encountered`

Is there a way to format the column on screen && show a sum in hearder / footer ?? Bonus point if i'm able to format the sum too ;)

Thx for your help

**To Reproduce**
* Got to ..

**Laravel version (exactly)** 
9.1
*

**Livewire version (exactly)**

*

**AlpineJS:** 
3.8.1
*

**Theme:**
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [X] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)

**Do you have any idea how we can fix it?**

**Put part of your code, an html screenshot of the problem element:**

**Comment by luanfreitasdev** [comment]
Hello @sebreunion , At the moment there is still no way to format the sum, but it is already in the backlog.

If you don't want to wait for that moment, you can send a PR with the solution you find and I'll help you.

Thanks

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/releases/tag/v2.3.0

**Comment by felixmpa** [comment]
Sorry, I am aware that the issue was closed with a release. However, I was analyzing the comment because, in my current version v3.5.10, I had the same problem using column formatted and the footer didn't display data.

I think it would help to add another important **blockquote**, for _withSum(), withAvg(), ..., warning to use the formatted field as it is currently documented in the topic for "searchable in add-columns".

So, here is my case also can help another one in the future.

Actual:

```
public function addColumns(): PowerGridEloquent
{
    ...
    $powergrid->addColumn('salary', function($model){
           return money($model->salary, 'USD', true)->format();
    });
}

public function columns(): array
{
   ...
   $columns = [
    Column::make('salary', 'Salary')
            ->sortable()
            ->searchable()
            ->makeInputRange('salary', '.', ',')
            ->withSum('Total salary', false, true), //not display formatted values.
   ];
}
```

Update to:

```
public function addColumns(): PowerGridEloquent
{
    ...
    $powergrid->addColumn('salary_formatted', function($model){ //using alias
           return money($model->salary, 'USD', true)->format();
    });
}

public function columns(): array
{
   ...
   $columns = [
    Column::add()
            ->title('Salary')
            ->field('salary_formatted', 'salary') //using alias 
            ->sortable()
            ->searchable()
            ->makeInputRange('salary', '.', ',')
            ->withSum('Total salary', false, true), //then the function know about the formatted_field
   ];
}
```

Greetings to PG-Team.
Thanks.

**Comment by luanfreitasdev** [comment]
I made a nice improvement here that will be available in version 5. x

https://github.com/Power-Components/livewire-powergrid/commit/3b4b79c8c9a5fa602c4e50c40366c79507eb9677

* Performance improvement (does not use get());
* Custom format

```php
 public function summarizeFormat(): array
 {
      return [
          'price' => function ($value) {
              return (new \NumberFormatter('en_US', \NumberFormatter::CURRENCY))
                  ->formatCurrency($value, 'USD');
           }
      ];
}

public function columns()
{
      return [
            Column::make('Price', 'price')
                ->withSum('Sum Price', true, false)
                ->withCount('Count Price', true, false)
                ->withAvg('Avg Price', true, false)
                ->sortable(),
      ];
}
```

![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/caae3122-00b5-4d1a-9266-283c2972af2f)


https://github.com/Power-Components/livewire-powergrid/commit/3b4b79c8c9a5fa602c4e50c40366c79507eb967
![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/304971b7-2613-4442-af9e-df60895b31e8)

**Comment by alzen8vtg** [comment]
facing the same issue when i use laravel's selectRaw or use select "field as some_other_name" it wound sum

**Comment by alzen8vtg** [comment]
> I made a nice improvement here that will be available in version 5. x
> 
> [3b4b79c](https://github.com/Power-Components/livewire-powergrid/commit/3b4b79c8c9a5fa602c4e50c40366c79507eb9677)
> 
> * Performance improvement (does not use get());
> * Custom format
> 
>  public function summarizeFormat(): array
>  {
>       return [
>           'price' => function ($value) {
>               return (new \NumberFormatter('en_US', \NumberFormatter::CURRENCY))
>                   ->formatCurrency($value, 'USD');
>            }
>       ];
> }
> 
> public function columns()
> {
>       return [
>             Column::make('Price', 'price')
>                 ->withSum('Sum Price', true, false)
>                 ->withCount('Count Price', true, false)
>                 ->withAvg('Avg Price', true, false)
>                 ->sortable(),
>       ];
> }
> ![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/caae3122-00b5-4d1a-9266-283c2972af2f)
> 
> [3b4b79c](https://github.com/Power-Components/livewire-powergrid/commit/3b4b79c8c9a5fa602c4e50c40366c79507eb967) ![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/304971b7-2613-4442-af9e-df60895b31e8)



i notice this issue was close, i want to achieve something like this but fail:
![Image](https://github.com/user-attachments/assets/0248b458-94b1-4f5b-b1b6-b25d50100e50)


added a new issue here, feel free to replicate:
https://github.com/Power-Components/livewire-powergrid/discussions/1895
