### ISSUE TITLE
Issues with Pagination on Mobile

### ISSUE THREAD

**Issue by Stridesdata** [Power-Components/livewire-powergrid#282]
First of all, did you see if your problem has happened to other people before?
- [x] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**
The Pagination Links shoots out of the card and is not contained in the div in which the table is present.
Secondly, How can one add conditional classes to table column.
* 

**To Reproduce**
* Got to ..switch to mobile view

**Laravel version (exactly)** 
8.1
*

**Livewire version (exactly)**

*2

**AlpineJS:** 
3
*

**Theme:**
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [x] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)
![image](https://user-images.githubusercontent.com/82326559/154508055-d20042ea-c6db-4e22-8dab-7a9145ba3d20.png)

**Do you have any idea how we can fix it?**

No
**Put part of your code, an html screenshot of the problem element:**
![image](https://user-images.githubusercontent.com/82326559/154508340-a9e1aef2-2b40-4732-abc4-9498f5c6088c.png)

**Comment by luanfreitasdev** [comment]
Hi @Stridesdata , I will check this problem. Please what version of Bootstrap are you using?

**Comment by luanfreitasdev** [comment]
I made some corrections, can you test main before doing a release?

**Comment by Stridesdata** [comment]
> Hi @Stridesdata , I will check this problem. Please what version of Bootstrap are you using?

Bootstrap 5

**Comment by Stridesdata** [comment]
Fixes the responsivness issues.. thanks

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/releases/tag/v2.3.0

**Comment by Stridesdata** [comment]
Sorry.. Still having issues
this works
![image](https://user-images.githubusercontent.com/82326559/154748373-5eff7f1d-8794-45d7-8c3e-d32912e837a1.png)

![image](https://user-images.githubusercontent.com/82326559/154748733-c0a015bc-1131-4501-a67a-d50a2ed6688e.png)

![image](https://user-images.githubusercontent.com/82326559/154748925-37186b21-e5ff-46cd-b60b-c7f0073cb0a2.png)

**Comment by Stridesdata** [comment]
Earlier the pagination was not scrolling properly in mobile
New result


![](https://user-images.githubusercontent.com/82326559/154748925-37186b21-e5ff-46cd-b60b-c7f0073cb0a2.png)

![image](https://user-images.githubusercontent.com/82326559/154749159-edb3ea56-394b-40d3-ab16-fb47f7a98273.png)

![image](https://user-images.githubusercontent.com/82326559/154749257-30c0c605-d5b4-4633-8b41-de1f4037db4b.png)

**Comment by luanfreitasdev** [comment]
Curious,Here it worked because it is a simpler implementation. can you submit a fix and submit a PR with tweaks for your system?

**Comment by Stridesdata** [comment]
Okay.
