### ISSUE TITLE
Table does not refresh after adding , deleting or editing information(I am not using inline edit)

### ISSUE THREAD

**Issue by Stridesdata** [Power-Components/livewire-powergrid#283]
First of all, did you see if your problem has happened to other people before?
- [x] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**
I use a modal component to edit and add new item to the database. Edit, delete and create functions are called by emit and grabbing the Id where necessary. All these works well but whenever I add, delete or edit, I have to refresh the page to see changes. I tried calling the Filldata() helper using an event listener but is still doesn't work.

Note.. This was also mentioned in the Laravel Daily review video
* 

**To Reproduce**
* Got to .. Add, create or delete using a different modal component

**Laravel version (exactly)** 
8.1
*

**Livewire version (exactly)**
2
*

**AlpineJS:** 
3
*

**Theme:**
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [x] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)

**Do you have any idea how we can fix it?**
No

**Put part of your code, an html screenshot of the problem element:**

**Comment by Stridesdata** [comment]
@luanfreitasdev @snapey @emtudo @trippo 

Found a temporary work around. Noticed that on column toggle, the table refreshes while maintaining current state hence, I call the toggle event twice every time I update or delete a record.

I added the highlighted code below to my code and everything works fine

![image](https://user-images.githubusercontent.com/82326559/154523239-dcb1c1d9-7c06-4c38-a871-2a66cf37c5ad.png)

Let me know if there is a more efficient way

**Comment by dansysanalyst** [comment]
❗ @Stridesdata, please do not mention contributors unless they are actively working on the very same issue. 

PowerGrid collaborators are volunteers. Drawing attention of random people will not make your issue get solved any fester.

**Comment by luanfreitasdev** [comment]
Hi @Stridesdata , your approach is not wrong. however you can easily do this in the backend using events from one component to another. 

Take a look at the demo repo. There is a modal and the table is updated. 

https://github.com/Power-Components/powergrid-demo

**Comment by Stridesdata** [comment]
> ❗ @Stridesdata, please do not mention contributors unless they are actively working on the very same issue.
> 
> PowerGrid collaborators are volunteers. Drawing attention of random people will not make your issue get solved faster.

My apologies
