### ISSUE TITLE
Excel download shows HTML code instead of rendered result

### ISSUE THREAD

**Issue by Stridesdata** [Power-Components/livewire-powergrid#284]
First of all, did you see if your problem has happened to other people before?
- [x] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**

* I followed your documentation on the use of closures to render HTML it rendered fine. 
![image](https://user-images.githubusercontent.com/82326559/154532907-005f44a8-2473-4299-bfdc-fd1396d29364.png)

*Result
![image](https://user-images.githubusercontent.com/82326559/154533000-ea12655d-79fa-4119-b39c-5a8301410675.png)

*Issue
On Export columns rendered from HTML shows HTML code in Excel instead of HTML result.
![image](https://user-images.githubusercontent.com/82326559/154533320-98ebdc2c-2984-4bd1-8a3f-5036cab59e33.png)

I tried using the Visibleinexport method but that feature is not working.
![image](https://user-images.githubusercontent.com/82326559/154547338-1b886766-a961-4562-92ec-109a7169ebd5.png)

* 

**To Reproduce**
* Got to .. export to excel or csv

**Laravel version (exactly)** 
8.1
*

**Livewire version (exactly)**
2
*

**AlpineJS:** 
3
*

**Theme:**
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [x] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)

**Do you have any idea how we can fix it?**

**Put part of your code, an html screenshot of the problem element:**
See my Code
![image](https://user-images.githubusercontent.com/82326559/154533387-2e168ac5-2ed5-4c18-a249-80125c11af04.png)

**Comment by Stridesdata** [comment]
Issue resolved by source code edit.
As recommended in earlier issue  https://github.com/Power-Components/livewire-powergrid/issues/165

Anyways this works for me
![image](https://user-images.githubusercontent.com/82326559/154558145-381386fe-2a1e-426d-8b6f-452bc0d2108d.png)

**Comment by b4oshany** [comment]
Hmmmm.... I'm using `v2.3`, `visisbleInExport` isn't working for me.
