### ISSUE TITLE
Problems with row action buttons styling

### ISSUE THREAD

**Issue by gapfranco** [Power-Components/livewire-powergrid#301]
First of all, did you see if your problem has happened to other people before?
- [ ] Yes - I did not find it 
- [x] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

Cannot style the row action buttons. The buttons are there, are functional, but almost invisible. If I take off the class clause the buttons appear outlined with transparent background and black lines. 

       return [
           Button::add('edit')
               ->caption('Edit')
               ->class('bg-blue-500 cursor-pointer text-white rounded text-sm')
               ->route('user.edit', ['user' => 'id']),

           Button::add('destroy')
               ->caption('Delete')
               ->class('bg-red-500 cursor-pointer text-white rounded text-sm')
               ->route('users', ['user' => 'id'])
        ];
 
The class(...) has no effect. Only the text-white is functional. If we change to text-red or any other color they change to black.

**Laravel version (exactly)** 

* 9.0.2

**Livewire version (exactly)**

* 2.10.2

**AlpineJS:** 

* 3.4.2

**Theme:**
- [ ] Tailwind 2.x
- [x] Tailwind 3.x
  - [x] With tailwind/forms
- [ ] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)
![Captura de Tela 2022-02-20 às 09 44 56](https://user-images.githubusercontent.com/10227356/154843590-9db23c6e-4c25-4e9d-9078-946163b18553.png)

**Do you have any idea how we can fix it?**
No

**Put part of your code, an html screenshot of the problem element:**

**Comment by luanfreitasdev** [comment]
Hello, did you check if the component classes are in the tailwind config ?

https://livewire-powergrid.com/#/get-started/configure?id=_42-jit-production

**Comment by gapfranco** [comment]
That's it! Problem solved. Thank you very much, it was my mistake.
