### ISSUE TITLE
Question/Feature request: Is it possible to conditionally style <tr> or <td> element?

### ISSUE THREAD

**Issue by pauleniz** [Power-Components/livewire-powergrid#306]
I want to reproduce invoices table on powergrid component and current table is color coded based on when invoice was created is there a way to access model in "public function columns(): array" function? I think I could style each <td> element if I can access the model if not maybe this functionality could appear in not too far future?

**Comment by pauleniz** [comment]
I would like to color code <tr> element base on calculation like this:
![image](https://user-images.githubusercontent.com/65357711/155530123-50feb919-8cdb-4962-a399-c15a4aa726b7.png)
In my case I calculate how much days have passed since invoice has been uploaded then if its more than 1week the invoice row becomes red is it possible to do that with powergrid table?

**Comment by luanfreitasdev** [comment]
Yes. 

https://livewire-powergrid.com/#/table/action-rules?id=action-rules
