### ISSUE TITLE
Header is not rendering with Bootstrap 5 Theme

### ISSUE THREAD

**Issue by kasuneranda1991** [Power-Components/livewire-powergrid#317]
First of all, did you see if your problem has happened to other people before?
- [ ] Yes - I did not find it 
- [x] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**
Header action buttons didn't render, But when switching Theme it works for Tailwind. Action buttons showing inside the livewire object. The same happened to on column filter when changing its configurations to `outside` 
* 

**To Reproduce**
* Got to ..

**Laravel version (exactly)** 
"laravel/framework": "^8.0",
*

**Livewire version (exactly)**
"livewire/livewire": "^2.10",
"power-components/livewire-powergrid": "^2.3",
*

**AlpineJS:** 
<script src="//unpkg.com/alpinejs" defer></script>
*

**Theme:**
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [x] Bootstrap - Version: 5

**Screenshots** (***This helps to understand better***)
- With Tailwind
![tailwind](https://user-images.githubusercontent.com/51038035/156969347-ef4f5ebe-edee-4da3-a177-71c658e36305.png)
- with Bootstrap 5
![Bootstrap 5](https://user-images.githubusercontent.com/51038035/156969374-1bc6bf0e-23ce-4f91-9b03-3be71b798dd3.png)

**Do you have any idea how we can fix it?**
Seems like when changing the theme to bootstrap Header does not render properly

**Put part of your code, an HTML screenshot of the problem element:**

Bootstrap  Config

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>⚡ PowerGrid Demo Table ⚡</title>

    
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">

    
    <style>
        body {
            font-family: 'Nunito', sans-serif;
        }
    </style>
    @livewireStyles
    @powerGridStyles
</head>

<body class="antialiased px-10 py-8 bg-gray-50">
    <div class="row">
        <p>Product Home</p>
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <livewire:ch-eshop-product-table />
                </div>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    
    @livewireScripts
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    @powerGridScripts
    <script src="//unpkg.com/alpinejs" defer></script>
    <script>
        console.log(this.Livewire.components);
        window.addEventListener('showAlert', event => {
            alert(event.detail.message);
        })
    </script>
</body>

</html>

**Comment by luanfreitasdev** [comment]
Hello.
Unfortunately this option is currently not available for bootstrap 5. I will update the documentation regarding this.
But feel free to send a PR with this action!.

I believe that few things need to be seen, for example:
in the [bootstrap5/header.blade.php](https://github.com/Power-Components/livewire-powergrid/blob/main/resources/views/components/frameworks/bootstrap5/header.blade.php#L5) the following can be added:

```html
<div>
      <x-livewire-powergrid::actions-header
          :theme="$theme"
          :actions="$this->headers"/>
  </div>
```

However, it needs to be refactored to have responsiveness and support for both themes


Thanks

**Comment by kasuneranda1991** [comment]
Thanks for the reply. BTW a really useful package.Keep up
