### ISSUE TITLE
i can;t show my action button

### ISSUE THREAD

**Issue by zamcoder** [Power-Components/livewire-powergrid#325]
First of all, did you see if your problem has happened to other people before?
- [x] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**

* i can't show my action button

**To Reproduce**
* Got to ..

**Laravel version (exactly)** 

*9

**Livewire version (exactly)**

*2.10

**AlpineJS:** 

*3.4.2

**Theme:**
- [ ] Tailwind 2.x
- [x] Tailwind 3.x
  - [x] With tailwind/forms
- [ ] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)
![image](https://user-images.githubusercontent.com/76896394/158066076-8726c3bb-6245-45ca-a488-b1f4798b29f0.png)

**Do you have any idea how we can fix it?**

**Put part of your code, an html screenshot of the problem element:**

![image](https://user-images.githubusercontent.com/76896394/158066103-8ec88cd5-c6de-4c7e-bf95-1d8cd9fbcff3.png)

**Comment by dansysanalyst** [comment]
Hi @zamcoder.

What is in your `ActionRules`?

A condition could be hiding the button. For example:

```php
public function actionRules(): array
    {
        return [

            Rule::button('foo')
                ->when(fn($model) => $model->id > 0)
                ->hide(),
        ];
    }
```

**Comment by luanfreitasdev** [comment]
In your table the variables $edit and $delete are conditioned to the config. Note that it expects the text 'tailwind'.

Be sure to import the files in tailwind.config.js

https://livewire-powergrid.com/#/get-started/configure?id=_4-tailwind-settings

**Comment by zamcoder** [comment]
sorry it fixed
