### ISSUE TITLE
Create a report to help us improve

### ISSUE THREAD

**Issue by brandon-9** [Power-Components/livewire-powergrid#337]
First of all, did you see if your problem has happened to other people before?
- [x ] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x ] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x ] No

**Describe the bug**
Livewire component is missing a closing tag somewhere? My next immediate component is always getting nested within the powergrid livewire component, suggesting a missing closing tag somewhere. 
* 

**To Reproduce**
Create a new powergrid component. Add to page.  Have another component below. Look in DOM and the 2nd component ends up within the powergrid component.

**Laravel version (exactly)** 
9.0
*

**Livewire version (exactly)**
2.5
*

**AlpineJS:** 
3
*

**Theme:**
- [ ] Tailwind 2.x
- [x ] Tailwind 3.x
  - [ ] With tailwind/forms
- [ ] Bootstrap - Version:        

![Screen Shot 2022-03-19 at 7 41 52 PM](https://user-images.githubusercontent.com/5572470/159144438-e72d837c-7bd8-489f-a04d-f43f4514ea4b.png)

**Comment by luanfreitasdev** [comment]
Hello. There is something strange within its structure. I just checked here and it's closing

![image](https://user-images.githubusercontent.com/33601626/159162048-296e844a-2762-496f-9e13-5b8b300e298f.png)
