### ISSUE TITLE
Bug With CSS Powergrid

### ISSUE THREAD

**Issue by zamcoder** [Power-Components/livewire-powergrid#340]
First of all, did you see if your problem has happened to other people before?
- [x] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**
my other element is behind powergrid component,
* 

**To Reproduce**
* Got to ..

**Laravel version (exactly)** 
9
*

**Livewire version (exactly)**
2
*

**AlpineJS:** 
3
*

**Theme:**
- [ ] Tailwind 2.x
- [x] Tailwind 3.x
  - [x] With tailwind/forms
- [ ] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)
![image](https://user-images.githubusercontent.com/76896394/159413814-a26c1e61-0b3a-4d7f-89c0-49323f324066.png)
Powergrid css
![image](https://user-images.githubusercontent.com/76896394/159413833-5db1b409-18fd-4093-afc7-f3ddbf6b7968.png)
Dropdown css
![image](https://user-images.githubusercontent.com/76896394/159413867-13532f3e-abc1-4d5d-a9e8-3173867abb91.png)

**Do you have any idea how we can fix it?**

**Put part of your code, an html screenshot of the problem element:**

**Comment by luanfreitasdev** [comment]
Can you put more z-Index in your dropdown?

**Comment by zamcoder** [comment]
already did , but no effect at all, still same problem

**Comment by zamcoder** [comment]
how? and now problem with table responsive @luanfreitasdev

**Comment by luanfreitasdev** [comment]
I did not understand. Did you fix the previous problem and another one appeared?. can you show me how it turned out?

If the previous issue has been fixed, please open another issue so that we can investigate the specific issue.

Thanks
