### ISSUE TITLE
Bug with Queue export

### ISSUE THREAD

**Issue by imfaisii** [Power-Components/livewire-powergrid#343]
First of all, did you see if your problem has happened to other people before?
No

Did you read the [documentation](https://livewire-powergrid.com/) ?
Yes

Is there an error in the console?
Yes, screenshot attached

**Describe the bug**

In queue export after clicking All I saw cdn.min.js:5 Uncaught TypeError: Illegal invocation error.
After processing the queues successfully the files isn't downloaded or what I am assuming there will be a download button which in my case is not visible probably because of AlpineJS error

**Laravel version (exactly)** 
9.2

**Livewire version (exactly)**
2.10

**AlpineJS:** 
3.X

**Theme:**
Tailwind 3.x

**Screenshots** (***This helps to understand better***)
![image](https://user-images.githubusercontent.com/59202459/159468502-84c56760-7c2f-4723-afb9-dc87a29ac215.png)

**Do you have any idea how we can fix it?**
Most probably fixing the alpineJS version ?

**Put part of your code, an html screenshot of the problem element:**

    public int $queues = 2; // Use two queues

    public string $onConnection = 'database'; // default sync

    public bool $showExporting = true; //Show progress on screen

**Comment by luanfreitasdev** [comment]
Could you show me on video? I tried to reproduce and I didn't get this error. There must be some blocking on the front, as javascript is not used in this step

![image](https://user-images.githubusercontent.com/33601626/159678685-d3ed0245-3399-4d29-b415-d5f221a3a2f1.png)

**Comment by imfaisii** [comment]
Yes, to show this progress and download links to the files the AlpineJS faces an error. 

https://user-images.githubusercontent.com/59202459/159852671-1dd2321d-3e06-400a-b0da-fc4a10e9e909.mp4

**Comment by luanfreitasdev** [comment]
From what I understand, your component has a different behavior when making a request. 
The element was probably removed from the DOM when loading

![image](https://user-images.githubusercontent.com/33601626/160177148-89fc6b59-3304-4035-8196-d56fec4ae4e1.png)

**Comment by luanfreitasdev** [comment]
I am closing this issue as it appears to have been resolved.
