### ISSUE TITLE
Livewire:Pagination issue

### ISSUE THREAD

**Issue by punna1138** [Power-Components/livewire-powergrid#362]
Pagination is not working after search the records. Getting the response from server as page 1 records.

**Comment by CrazyBoy49z** [comment]
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/3448603/161802291-07e0d0fb-c7d9-43d4-98eb-bf8b91a142ee.png">

Search works correctly, maybe you use the component incorrectly?

**Comment by punna1138** [comment]
https://user-images.githubusercontent.com/16316372/161948231-fa261a39-e7b2-4c21-9fc8-d3e77bcae946.mp4

Search is working fine, but pagination is not working!

**Comment by CrazyBoy49z** [comment]
This problem in the work trait Livewire\WithPagination

**Comment by punna1138** [comment]
![Capture](https://user-images.githubusercontent.com/16316372/162125644-564f63ad-00d7-444b-8348-48a41ca231b8.PNG)

**Comment by luanfreitasdev** [comment]
Hello, what version of Powergrid and themes are you using?

Got a console error?

**Comment by punna1138** [comment]
"livewire/livewire": "^2.10",
 "power-components/livewire-powergrid": "^2.4"

'theme' => \PowerComponents\LivewirePowerGrid\Themes\Tailwind::class,

**Comment by CrazyBoy49z** [comment]
> Hello, what version of Powergrid and themes are you using?
> 
> Got a console error?

Bootstrap too

**Comment by punna1138** [comment]
nope! it is not changing anything.

**Comment by CrazyBoy49z** [comment]
> 

Are you using Builder or Collection?

public function datasource(): ?Builder

The builder does not work

**Comment by punna1138** [comment]
Using datasource(): ?Builder only
 trait is : use Illuminate\Database\Eloquent\Builder;

then what is working datasource type?

**Comment by luanfreitasdev** [comment]
This has to do with this fix I made recently

https://github.com/Power-Components/livewire-powergrid/releases/tag/v2.4.6

**Comment by punna1138** [comment]
thanks it got resolved!
