### ISSUE TITLE
Powergrid Demo Error - Undefined array key ""

### ISSUE THREAD

**Issue by rev9tech** [Power-Components/livewire-powergrid#364]
First of all, did you see if your problem has happened to other people before?
- [x] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [x] Yes - I'll put a screenshot
- [ ] No

**Describe the bug**

* When sorting or searching in a column, an undefined array key "" error is generated.  I only receive this error with version 2.4.2.  Version 2.4.1 does not produce this error.

**To Reproduce**
* Run the powergrid demo.

**Laravel version (exactly)** 

* 9.7.0

**Livewire version (exactly)**

* 2.10.4

**AlpineJS:** 

* 3.9.5

**Theme:**
- [ ] Tailwind 2.x
- [x] Tailwind 3.0.23
  - [x] With tailwind/forms 0.4.0
- [ ] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)
![screenshot](https://user-images.githubusercontent.com/56508172/161877281-bca34e32-db3d-4339-b4f5-5bbcb6fd8bd6.jpg)

**Do you have any idea how we can fix it?**

**Put part of your code, an html screenshot of the problem element:**

**Comment by luanfreitasdev** [comment]
Hello, thanks for reporting, but this problem is related to key exchange in the back-end and from what I saw your files were not updated because it is inside resources/views

`php artisan vendor:publish --tag=livewire-powergrid-views`
