### ISSUE TITLE
 tailwind cdn dark mode

### ISSUE THREAD

**Issue by mani1430** [Power-Components/livewire-powergrid#366]
I have problem to tailwind cdn clash.
![image](https://user-images.githubusercontent.com/90332512/162173091-94228ed9-e83c-4e32-9f82-1fd16e678a43.png)

**Comment by luanfreitasdev** [comment]
Please provide more information as described in the issue outline

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/issues/261
