### ISSUE TITLE
Create a report to help us improve

### ISSUE THREAD

**Issue by mani1430** [Power-Components/livewire-powergrid#368]
1. I have problem to tailwind cdn clash and I don't need dark mode option .
2. Need to ID increment numbers.

**Comment by luanfreitasdev** [comment]
Duplicated: https://github.com/Power-Components/livewire-powergrid/issues/367

**Comment by mani1430** [comment]
1. How I add the $loop->index values in ID column. I don't want to use database table primary id values in the table row number.

2. I need to use encrypted URL , So please help me to how to encrypt the edit route parameter.

please help me.

**Comment by mani1430** [comment]
3. Need to place Actions buttons near to id columns in the table.
