### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by edwinheij** [Power-Components/livewire-powergrid#37]
When filterring data and using the export functionality, the filters are not reflected. I mean, all of the records are exported. Is this the intention or should I make a pull request to reflect the filters when exporting? Or you may also do it yourself :)

ps: when selecting a couple of records, they are already reflected while exporting

**Comment by luanfreitasdev** [comment]
Hello @edwinheij 

It doesn't actually work well when we run the search, but it would be nice if we let the user choose what kind of behavior he expects when selecting all records.

It would be interesting if we leave both options if possible, as there are people who prefer to click once and select all bank records.

Perhaps if this was available for tuning in the config file?
For example:

```
'export' => [
        'on_selected_all' => 'pagination' // or all
]
```

I also liked the idea of exporting only the records that were a result of the filter.

**Comment by edwinheij** [comment]
Maybe something like Google is doing, so you're even more flexible.
![image](https://user-images.githubusercontent.com/1799101/128046827-87c820a3-969d-44fa-93c4-558f5d0ae0d1.png)

**Comment by luanfreitasdev** [comment]
I understand, but how would it look if we went page by page, the box would appear?

**Comment by edwinheij** [comment]
Maybe 2 extra options in the export dropdown.
All options would be something like this:

* Excel (all)
* Excel (selected)
* CSV (all)
* CSV (selected)

**Comment by luanfreitasdev** [comment]
It may work, but the issue is when the user clicks select all items. Example: I have a table with 100 items paged into 10.

When user selects all items, 10 items or 100 will be selected ?

If you solve this issue in the backend, the dropdown can be unique, as it should only export the ones the user selected

**Comment by edwinheij** [comment]
I think select all checkbox for all 100 records is not relevant anymore while having the new export options.

**Comment by luanfreitasdev** [comment]
It makes sense.

**Comment by luanfreitasdev** [comment]
Unfortunately I will have to close the PR so as not to break the part of exporting all selected records in the entire listing. However I liked the implementation you made and we will work on it soon, or if you can provide a PR to solve this problem we would be very grateful!.

Hug.
