### ISSUE TITLE
Create a report to help us improve

### ISSUE THREAD

**Issue by ettiennelouw** [Power-Components/livewire-powergrid#370]
First of all, did you see if your problem has happened to other people before?
- [ ] Yes - I did not find it 
- [ ] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**
How can you show long text in the grid but have it wrap and fit on the screen. We need to display the full text in the screen as this is notes related to the item but I have tried everything to make it fit but it keeps overflowing and adding the scroll option to the grid instead of wrapping the text.
* 

**To Reproduce**
* Got to ..

**Laravel version (exactly)** 

*8.83.5

**Livewire version (exactly)**

*2.10.4

**AlpineJS:** 

*3.0.6

**Theme:**
- [ ] Tailwind 2.x
- [x] Tailwind 3.x
  - [ ] With tailwind/forms
- [ ] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)
![Screenshot 2022-04-07 at 14 48 43](https://user-images.githubusercontent.com/1754421/162202437-dcb71c5f-3870-434e-8ebc-6c264e1d02e7.png)

Shows like this in another grid
![Screenshot 2022-04-07 at 14 52 38](https://user-images.githubusercontent.com/1754421/162203188-ae3aa3a4-f1e8-4a7c-a9f0-cffd58b962de.png)

**Do you have any idea how we can fix it?**

**Put part of your code, an html screenshot of the problem element:**
Column::add()
                ->title(trans_choice('custom/member.notes', 1))
                ->field('description')
                ->searchable()
                ->sortable()
                ->bodyAttribute('break-all'),

**Comment by ettiennelouw** [comment]
With a bit of digging i found the solution, Great package man.

->bodyAttribute('', 'white-space: normal;'),

**Comment by luanfreitasdev** [comment]
That's right!

Thanks
