### ISSUE TITLE
Publish Language files in laravel 9 causes validation error

### ISSUE THREAD

**Issue by gzai** [Power-Components/livewire-powergrid#372]
First of all, did you see if your problem has happened to other people before?
- [ ] Yes - I did not find it 
- [x] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**
I have error and test in this link https://laracasts.com/discuss/channels/laravel/laravel-9-validation-error, 
when publish Language files, it will create a ``lang vendor`` folder inside ``resource`` folder. 
based on https://laravel.com/docs/9.x/upgrade#the-lang-directory, laravel 9 create ``lang`` folder in root.
Looks like Laravel checks both locations ( ``lang`` folder in root and ``lang`` folder in ``resource`` folder ), but it will be prioritized if found ``lang`` folder in ``resources`` folder.
*

**To Reproduce**
Publis languange files livewire-powergrid, 
running this code in controller : 
```
dd(trans('validation.required'));
```
the result it will be ^ "validation.required"

**Laravel version (exactly)** 
Laravel 9.7.0
*

**Livewire version (exactly)**
Livewire 2.10.4
*

**AlpineJS:** 

*

**Theme:**
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [ ] Bootstrap - Version:        

**Screenshots** (***This helps to understand better***)

**Do you have any idea how we can fix it?**
publishing to app()->langPath()

**Put part of your code, an html screenshot of the problem element:**

**Comment by dansysanalyst** [comment]
Thanks for opening an issue @gzai! I have proposed a modification to the publishing command.

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/releases/tag/v2.4.4
