### ISSUE TITLE
InputDatePicker getting type "text"

### ISSUE THREAD

**Issue by Soletrar** [Power-Components/livewire-powergrid#373]
First of all, did you see if your problem has happened to other people before?
- [ ] Yes - I did not find it 
- [x] No

Did you read the [documentation](https://livewire-powergrid.com/) ?
- [x] Yes - I did not find it
- [ ] No

Is there an error in the console?
- [ ] Yes - I'll put a screenshot
- [x] No

**Describe the bug**
* Datepicker input is getting type "text" in html, not type "date", so we can't filter dates.

**To Reproduce**
* Use "makeInputDatePicker" to create a date filter and it will be of type text.

**Laravel version (exactly)** 
* 8.83.7

**Livewire version (exactly)**
* v2.10.5

**AlpineJS:** 
* 3.8.1

**Theme:**
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [x] Bootstrap - Version: 5       

**Screenshots** (***This helps to understand better***)
![image](https://user-images.githubusercontent.com/28328349/162429616-a99169fc-278b-4e7a-9e8e-302971693919.png)

**Do you have any idea how we can fix it?**
Change input type to date

**Put part of your code, an html screenshot of the problem element:**
![image](https://user-images.githubusercontent.com/28328349/162429721-43c2842c-3647-4996-af5f-b1c047b99736.png)
![image](https://user-images.githubusercontent.com/28328349/162429770-fea77557-d969-4053-b749-4ce0ee20e9ae.png)

**Comment by luanfreitasdev** [comment]
Hello.

The input type is correct, it has to be text.

Some checks:

- Did you get an error in the browser console?
- How are you using? via module or cdn?
- flatpicker is in window ? You can try like this: window.flatpickr

there is an example here with bootstrap:
https://github.com/Power-Components/powergrid-demo/tree/bs5-webpack

**Comment by Soletrar** [comment]
It's working now after I added flatpickr js/css into the blade.

But before it was working normally, using the flatpickr provided in powergrid config I suppose.

Either using cdn directly in blade the date is no longer in 'pt' locale/format as powergrid config.

Anyways, thank you!

**Comment by luanfreitasdev** [comment]
I believe you need to change this parameter to load by cdn
https://github.com/Power-Components/livewire-powergrid/releases/tag/v2.4.3
```php
 'plugins' => [
        // ...
        'flatpickr' => [
         // ...
```

**Comment by Soletrar** [comment]
This is why it wasn't inserting cdn, so many thanks bro!
