### ISSUE TITLE
Can I display icon on actions > buttons?

### ISSUE THREAD

**Issue by bfontanet** [Power-Components/livewire-powergrid#39]
I'd like display icon on action's buttons.
You have "caption" method but don't read HTML (to use fontawesome, for example).
Are any options for it?
Thanks!

![2021-08-06_6-51-41](https://user-images.githubusercontent.com/10600143/128457785-f545c23f-2436-45b5-8453-ea932eff0041.jpg)
![2021-08-06_6-51-04](https://user-images.githubusercontent.com/10600143/128457787-06226ead-a3e6-4a8c-b7e0-144d381ae556.jpg)

**Comment by bfontanet** [comment]
Sorry, I can see "i" method on Button class, but I cannot get how to watch the icon.
I have this code:
```
Button::add('synonyms')
  ->caption(__('Obtener sinónimos'))
  ->i('fas fa-cogs', __('Obtener sinónimos'), true)
  ->class('bg-purple-700 hover:bg-purple-900 text-white py-2 px-4 text-sm')
  ->route('entity.get-synonyms', ['entity' => 'id']),
```

I tried to get off "caption()" but don't work for me.
Can you help me?
![2021-08-06_7-10-37](https://user-images.githubusercontent.com/10600143/128459114-c55201e9-50cc-4782-9155-5f67a865cf68.jpg)

**Comment by luanfreitasdev** [comment]
Hello! @bfontanet ,

This method has been removed in this version and this weekend I will be releasing a new version where it will be possible to fix this problem. **You can call it this way:**

```
Button::add('synonyms')
  ->caption('<i class="fa-solid fa-info"></i>  '.__('Obtener sinónimos'))
  ->class('bg-purple-700 hover:bg-purple-900 text-white py-2 px-4 text-sm')
  ->route('entity.get-synonyms', ['entity' => 'id']),
```

**Comment by luanfreitasdev** [comment]
added into [v1.2](https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.2.0)

**Comment by bfontanet** [comment]
Thank you!!!
__________________
Bego Fontanet
***@***.***
