### ISSUE TITLE
breaking changes

### ISSUE THREAD

**Issue by jamesRUS52** [Power-Components/livewire-powergrid#390]
After update from 2.3.7 to 2.4.2 I have the error while use Select filter.
I think it may be issue for https://github.com/Power-Components/livewire-powergrid/pull/349

my config table is
```php
            Column::add()
                ->title('Статус')
                ->field('request_status')
                ->searchable()
                ->sortable()
                ->makeInputSelect(collect(RequestStatusEnum::cases())->map(fn ($item) =>['id' => $item->value, 'name' => $item->value]), 'name', 'status')
                ->bodyAttribute('text-center')
                ->visibleInExport(false),
            Column::add()
                ->title('Статус заявки')
                ->field('status')
                ->hidden()
                ->visibleInExport(true),
```

the error is 

![image](https://user-images.githubusercontent.com/39707635/162938966-0d0533be-e79c-4f18-90be-a5db4cfe45df.png)

**Comment by luanfreitasdev** [comment]
Hello. It's the same problem as this
https://github.com/Power-Components/livewire-powergrid/issues/374

**Comment by jamesRUS52** [comment]
Hi, 
I done
php artisan vendor:publish --tag=livewire-powergrid-views
and error is gone 
but
I have not done it before and doc says
[3. Publish files (OPTIONAL)](https://livewire-powergrid.com/#/get-started/install?id=_3-publish-files-optional)
Skip this step if you don’t need to customize views or language files.

I never published views, why must I publish views now ?

**Comment by jamesRUS52** [comment]
its not working without publish views

**Comment by luanfreitasdev** [comment]
I believe it may be in the cache in the view

**Comment by jamesRUS52** [comment]
Yes, you are right
php artisan optimize:clear 
solve my problem
It seems strange , but I don't use optimize before and all view should be recompile itself.
otherwise thanks a lot for your help
