### ISSUE TITLE
InputSelect error with join table

### ISSUE THREAD

**Issue by alexspi** [Power-Components/livewire-powergrid#393]
# PowerGrid Bug Report

Thank you for reporting a bug and helping us to improve PowerGrid!

## Guidelines

`   🐛 `   We use GitHub Issues exclusively for tracking bugs and unexpected software behavior. 

`   🙏 `  Please use the [Discussions](https://github.com/Power-Components/livewire-powergrid/discussions) tab for questions like _"How to...",_ "_how can I..."_ .

`   ✍️ `  Give this report a short but meaningful title. Make it easy to spot for others who might be facing the same issue.

`   ⚠️ `  Issues that do not describe a bug or do not follow the template will be closed.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [* ] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [* ] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [ ] Yes - I didn't work.
- [ *] No, this error is not related to views.

#### Is there an error in the console?
- [ ] Yes - I'll add a screenshot or report it below.
- [ *] No

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |    2.4.5               |
| Laravel   |        8.83.8           |
| Livewire  |         2.10.5          |
| Alpine JS  |                   |

### Theme
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [* ] Bootstrap - Version:        

---
### What happened?

I did FOO expecting BAR as a result. However, I received BAZ...

### To Reproduce...

First click on "FOO" then....

### Suggestions

(Do you have any idea how we can fix it?)

## Extra information

**Screenshots**

**Code snippet**

```php 
<?php
public function datasource(): ?Builder
    {
        return ClientVkReport::query()
            ->join('client_vk_campaigns', 'client_vk_reports.campaign_id', '=', 'client_vk_campaigns.campaign_id')
            ->join('client_vk_ads', 'client_vk_reports.ads_id', '=', 'client_vk_ads.ads_id')
            ->select(
                'client_vk_reports.*',
                'client_vk_campaigns.campaign_name as campaignName',
                'client_vk_ads.ads_name as adsName'
            );
           
    }
Column::add()
                ->title('Кампания')
                ->field('campaignName','client_vk_reports.campaign_id')
                ->makeInputSelect(ClientVkCampaign::where('client_id', $this->client->id)->get(), 'client_vk_campaigns.campaign_name', 'client_vk_reports.campaign_id')
                ->sortable(),





<div class="relative">
                <select id="input_" class="power_grid form-control shadow-none  " style="" wire:input.debounce.500ms="filterSelect('','Кампания')" wire:model.debounce.500ms="filters.select." data-live-search="">
                    <option value="">Все</option>
                                            <option value="1"></option>
                                            <option value="2"></option>
                                    </select>
                <div class="d-none">
                    <svg class="pointer-events-none w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
</svg>
                </div>
            </div>

````
SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'where clause' (SQL: select `client_vk_reports`.*, `client_vk_campaigns`.`campaign_name` as `campaignName`,......

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/issues/374

**Comment by alexspi** [comment]
with join, not work
work with relation
