### ISSUE TITLE
after updating the collection, does not update the table

### ISSUE THREAD

**Issue by alexspi** [Power-Components/livewire-powergrid#398]
# PowerGrid Bug Report

Thank you for reporting a bug and helping us to improve PowerGrid!

## Guidelines

`   🐛 `   We use GitHub Issues exclusively for tracking bugs and unexpected software behavior. 

`   🙏 `  Please use the [Discussions](https://github.com/Power-Components/livewire-powergrid/discussions) tab for questions like _"How to...",_ "_how can I..."_ .

`   ✍️ `  Give this report a short but meaningful title. Make it easy to spot for others who might be facing the same issue.

`   ⚠️ `  Issues that do not describe a bug or do not follow the template will be closed.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [ *] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [+ ] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [+ ] Yes - I didn't work.
- [ ] No, this error is not related to views.

#### Is there an error in the console?
- [+ ] Yes - I'll add a screenshot or report it below.
- [ ] No

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |         2.4.5          |
| Laravel   |            8.83       |
| Livewire  |       2.10            |
| Alpine JS  |                   |

### Theme
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [+ ] Bootstrap - Version:        

---
## Describe the bug
in datasource Collection ,after event d`not update table
### What happened?

I did FOO expecting BAR as a result. However, I received BAZ...

### To Reproduce...

First click on "FOO" then....

### Suggestions

(Do you have any idea how we can fix it?)

## Extra information

**Screenshots**

**Code snippet**

```php 
<?php
    protected function getListeners(): array
    {
        return array_merge(
            parent::getListeners(),
            [
                'refdatatable',

            ]);
    }
    public function refdatatable($start, $end)
    {
        $this->startDate = $start;
        $this->endDate = $end;
//        $this->fillData();
        $sd = $this->startDate;
        $ed = $this->endDate;
//dump($this->startDate);
//        dump($this->endDate);

        $after = array_filter($this->report, function ($value) use ($sd) {
            return ($value['daterep'] >= $sd);
        });
        $data = array_filter($after, function ($value) use ($ed) {
            return ($value['daterep'] <= $ed);
        });
        $this->fillData();
//        dd($data);
        return collect($data);
    }
//...
```

**Comment by luanfreitasdev** [comment]
Could you show the bug behavior in a video?

**Comment by alexspi** [comment]
https://user-images.githubusercontent.com/5305406/165403488-62605305-581f-4981-b719-e9d1c04ee982.mp4

**Comment by alexspi** [comment]
```
 public function mount(): void
    {
        parent::mount();
        $this->report = Cache::get('client.' . $this->client->id . '.table.main_table');


    }

    protected function getListeners(): array
    {
        return array_merge(
            parent::getListeners(),
            [
                'reftable',

            ]);
    }

    public function reftable($start, $end)
    {
        $this->startDate = $start;
        $this->endDate = $end;
        dump($start);
        dump($end);
        $sd = $this->startDate;
        $ed = $this->endDate;


        $after = array_filter($this->report, function ($value) use ($sd) {
            return ($value['daterep'] >= $sd);
        });
        $data = array_filter($after, function ($value) use ($ed) {
            return ($value['daterep'] <= $ed);
        });

        $this->fillData();

        return collect($data);
    }
```
it doesn't even hit the reftable event.
        dump($start);
        dump($end);
don't work.
if using
   public function datasource(): ?Builder
events fire

**Comment by luanfreitasdev** [comment]
Hi! I believe this is a standard behavior of powergrid as the data is loaded through the datasource.

What you can do is use the events to handle a variable and use the public variable inside the datasource method.
