### ISSUE TITLE
When user select "all" registers per page: "crash" or nothing is showed

### ISSUE THREAD

**Issue by bfontanet** [Power-Components/livewire-powergrid#40]
Hello,

In advance, thanks for your work. 
I want to report this issue: In my project, when the user select "ALL" registers (perPage), It's received this error:
![2021-08-09_7-06-08](https://user-images.githubusercontent.com/10600143/128662475-7adb86c2-e2ee-484f-adea-30249dcbf200.jpg)

And, if I try to do that in your "demo" project, nothing is showed (attach the screenshot):
![2021-08-09_7-00-28](https://user-images.githubusercontent.com/10600143/128662213-e3bb4fed-85ac-4105-8349-6f1d86974934.jpg)

Just I updated demo project and your component.
At demo project:
- Upgrading power-components/livewire-powergrid (v1.1.5 => **dev-main 02151e7**): Extracting archive)

At my project:
- Upgrading power-components/livewire-powergrid (v1.1.5 => **v1.2.0**): Extracting archive

Regards

**Comment by bfontanet** [comment]
One more detail, that I just see: I have 2 "all" (Todos) registers. Look at this:
![2021-08-09_7-27-29](https://user-images.githubusercontent.com/10600143/128663775-ce30dce4-7326-424d-b45a-c1e50c0967d3.jpg)

After the update I executed:
`λ npm install && npm run dev`
without errors >  `webpack compiled successfully`
and clear all items from cache:
```
Compiled views cleared!
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Files cached successfully!
```

Maybe I need to do another thing more ¿?
Because in my project the pagination looks different
![2021-08-09_7-34-30](https://user-images.githubusercontent.com/10600143/128664023-bbc8efb1-7a46-414b-a0fb-0952d9843751.jpg)

Here my "setUp" method:
```
public function setUp() {
  $this->showPerPage()
	  ->showToggleColumns()
	  ->showRecordCount('full')
	  ->showExportOption('download', ['excel', 'csv'])
	  ->showSearchInput();
}

```
Regards.

**Comment by luanfreitasdev** [comment]
@bfontanet 

I released an update that fixes this issue!, **thanks again.**

I will update the demo repo too

Hugs

**Comment by luanfreitasdev** [comment]
![image](https://user-images.githubusercontent.com/33601626/128703931-db2fa00e-fd39-4153-813e-5b494ffdf3af.png)


This difference from the demo repo is that I uploaded the version calling the bootstrap theme, and the main version is tailwind. so there is a difference
