### ISSUE TITLE
Livewire:powergrid not showing up the fields

### ISSUE THREAD

**Issue by chanduanupoju02git** [Power-Components/livewire-powergrid#408]
After on form submit missing the columns in PowerGrid datatable

[https://chandu-corephp.tinytake.com/msc/Njc3ODQ1MV8xOTQwMzk2MA](url)

- [ ] 

> Which version worked and which version did it start?
> 
> How do you call events for powergrid ?

Tnq for quick response 
currently iam using livewire-powergrid": "^2.4.6"
iam calling events like this 
 public function actions(): array
    {
        $edit_icon = config('constants.EDIT_ICON');
        $delete_icon = config('constants.DELETE_ICON');         
       return [
 
           Button::add('edit')
               ->caption('Pages')
               ->class('bg-green-500 cursor-pointer text-white px-3 py-1.5 m-1 rounded text-sm hover:no-underline')
               ->emit('pages', ['subtopic_id' => 'id']),
           Button::add('edit')
               ->caption($edit_icon)
               ->class('cursor-pointer px-3 py-2 m-1')
               ->emit('subTopicEdit', ['subtopic_id' => 'id']),               
           Button::add('destroy')
               ->caption($delete_icon)
               ->class('cursor-pointer px-3 py-2 m-1')
               ->emit('deleteSubTopic', ['subtopic_id' => 'id'])                                   
        ];
    }

**Comment by luanfreitasdev** [comment]
Hello, could you follow the issue template to help us with the information?

**Comment by luanfreitasdev** [comment]
Which version worked and which version did it start?

How do you call events for powergrid ?

**Comment by chanduanupoju02git** [comment]
Tnq for quick response
currently iam using livewire-powergrid": "^2.4.6"
iam calling events like this

    
        public function addColumns(): ?PowerGridEloquent
    {
        // return PowerGrid::eloquent();
        return PowerGrid::eloquent()
                ->addColumn('id')
                ->addColumn('st_no')
                ->addColumn('st_name') 
                ->addColumn('updated_by_formatted', function(MtsSubTopics $model) { 
                    return ((isset($model->getUpdatedUser->name) && !empty($model->getUpdatedUser->name))?$model->getUpdatedUser->name:'');
                })
                ->addColumn('created_at_formatted', function(MtsSubTopics $model) { 
                    return Carbon::parse($model->created_at)->format('d-M-Y');
                })
                ->addColumn('updated_at_formatted', function(MtsSubTopics $model) { 
                    return Carbon::parse($model->updated_at)->format('d-M-Y');
                });        
    }

    /*
    |--------------------------------------------------------------------------
    |  Include Columns
    |--------------------------------------------------------------------------
    | Include the columns added columns, making them visible on the Table.
    | Each column can be configured with properties, filters, actions...
    |
    */

     /**
     * PowerGrid Columns.
     *
     * @return array<int, Column>
     */
    public function columns(): array
    {
$canEdit  = true;   
        return [    
            Column::add()   
                ->title('ID')   
                ->field('id')
                ->searchable(),  
            Column::add()   
                ->title('SUB TOPIC NO') 
                ->field('st_no')
                ->searchable(),  
            Column::add()   
                ->title('SUB TOPIC NAME')   
                ->field('st_name')
                ->searchable(),  
            Column::add()   
                ->title('UPDATED BY')   
                ->field('updated_by_formatted', 'updated_by')   
                ->searchable(),                 
            Column::add()   
                ->title('CREATED AT')   
                ->field('created_at_formatted', 'created_at')   
                ->searchable(),    
            Column::add()   
                ->title('UPDATED AT')   
                ->field('updated_at_formatted', 'updated_at')   
                ->searchable(),    
        ]
;
    }

    /*
    |--------------------------------------------------------------------------
    | Actions Method
    |--------------------------------------------------------------------------
    | Enable this section only when you have defined routes for these actions.
    |
    */

     /**
     * PowerGrid subTopic action buttons.
     *
     * @return array<int, \PowerComponents\LivewirePowerGrid\Button>
     */

    public function actions(): array
    {
        $edit_icon = config('constants.EDIT_ICON');
        $delete_icon = config('constants.DELETE_ICON');         
       return [
 
           Button::add('edit')
               ->caption('Pages')
               ->class('bg-green-500 cursor-pointer text-white px-3 py-1.5 m-1 rounded text-sm hover:no-underline')
               ->emit('pages', ['subtopic_id' => 'id']),
           Button::add('edit')
               ->caption('<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="pencil-alt" class="svg-inline--fa fa-pencil-alt fa-w-16" style="width:1rem;" role="img" viewBox="0 0 512 512"><path fill="currentColor" d="M497.9 142.1l-46.1 46.1c-4.7 4.7-12.3 4.7-17 0l-111-111c-4.7-4.7-4.7-12.3 0-17l46.1-46.1c18.7-18.7 49.1-18.7 67.9 0l60.1 60.1c18.8 18.7 18.8 49.1 0 67.9zM284.2 99.8L21.6 362.4.4 483.9c-2.9 16.4 11.4 30.6 27.8 27.8l121.5-21.3 262.6-262.6c4.7-4.7 4.7-12.3 0-17l-111-111c-4.8-4.7-12.4-4.7-17.1 0zM124.1 339.9c-5.5-5.5-5.5-14.3 0-19.8l154-154c5.5-5.5 14.3-5.5 19.8 0s5.5 14.3 0 19.8l-154 154c-5.5 5.5-14.3 5.5-19.8 0zM88 424h48v36.3l-64.5 11.3-31.1-31.1L51.7 376H88v48z"></path></svg>')
               ->class('cursor-pointer px-3 py-2 m-1')
               ->emit('subTopicEdit', ['subtopic_id' => 'id']),               
           Button::add('destroy')
               ->caption('<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" data-prefix="far" data-icon="trash-alt" class="svg-inline--fa fa-trash-alt fa-w-14" style="width:1rem;" role="img" viewBox="0 0 448 512"><path fill="currentColor" d="M268 416h24a12 12 0 0 0 12-12V188a12 12 0 0 0-12-12h-24a12 12 0 0 0-12 12v216a12 12 0 0 0 12 12zM432 80h-82.41l-34-56.7A48 48 0 0 0 274.41 0H173.59a48 48 0 0 0-41.16 23.3L98.41 80H16A16 16 0 0 0 0 96v16a16 16 0 0 0 16 16h16v336a48 48 0 0 0 48 48h288a48 48 0 0 0 48-48V128h16a16 16 0 0 0 16-16V96a16 16 0 0 0-16-16zM171.84 50.91A6 6 0 0 1 177 48h94a6 6 0 0 1 5.15 2.91L293.61 80H154.39zM368 464H80V128h288zm-212-48h24a12 12 0 0 0 12-12V188a12 12 0 0 0-12-12h-24a12 12 0 0 0-12 12v216a12 12 0 0 0 12 12z"></path></svg>')
               ->class('cursor-pointer px-3 py-2 m-1')
               ->emit('deleteSubTopic', ['subtopic_id' => 'id'])                                   
        ];
    }
    /*
    |--------------------------------------------------------------------------
    | Edit Method
    |--------------------------------------------------------------------------
    | Enable this section to use editOnClick() or toggleable() methods.
    | Data must be validated and treated (see "Update Data" in PowerGrid doc).
    |
    */

     /**
     * PowerGrid subTopic Update.
     *
     * @param array<string,string> $data
     */

    
    public function update(array $data ): bool
    {
       try {
           $updated = MtsSubTopics::query()->findOrFail($data['id'])
                ->update([
                    $data['field'] => $data['value'],
                ]);
       } catch (QueryException $exception) {
           $updated = false;
       }
       return $updated;
    }

    public function updateMessages(string $status = 'error', string $field = '_default_message'): string
    {
        $updateMessages = [
            'success'   => [
                '_default_message' => __('Data has been updated successfully!'),
                //'custom_field'   => __('Custom Field updated successfully!'),
            ],
            'error' => [
                '_default_message' => __('Error updating the data.'),
                //'custom_field'   => __('Error updating custom field.'),
            ]
        ];

        $message = ($updateMessages[$status][$field] ?? $updateMessages[$status]['_default_message']);

        return (is_string($message)) ? $message : 'Error!';
    }


iam writing code like this

**Comment by chanduanupoju02git** [comment]
plz check this video for futher reference
[https://chandu-corephp.tinytake.com/msc/Njc3ODQ1MV8xOTQwMzk2MA](url)

**Comment by chanduanupoju02git** [comment]
plz check this video for futher reference
[https://chandu-corephp.tinytake.com/msc/Njc3ODQ1MV8xOTQwMzk2MA](url)

**Comment by luanfreitasdev** [comment]
I need to check the html of the row element next to the button
