### ISSUE TITLE
php artisan powergrid:create  >>  Class 'Composer\Factory' not found

### ISSUE THREAD

**Issue by bfontanet** [Power-Components/livewire-powergrid#41]
After update your component, the command powergrid:create doesn't work. 
Error:
```
λ php artisan powergrid:create
  Class 'Composer\Factory' not found

```
![2021-08-09_9-00-26](https://user-images.githubusercontent.com/10600143/128670283-75f8b9bb-ddf4-4760-bd79-bed0fa961863.jpg)

I try to execute composer dumpautoload and reisntall the component, but nothing work.
Version in my project: 
> power-components/livewire-powergrid v1.2.0   

I try to create a new laravel project and install your component and I get the same error.
> here the new project: [wetransfer](https://we.tl/t-mJTzLGkzAo)

Before the update, It was working fine.

At your demo-project, the command, work fine. In this, the component versión is:
> power-components/livewire-powergrid dev-main 02151e7

Can you help me to solve?? What I need to it does to work?

Sorry for inconvenience

Other info (but your demo is working, so I think is not the problem):
λ php artisan --version
Laravel Framework 8.53.1

λ composer --version
Composer version 2.0.12 2021-04-01 10:14:59

**Comment by luanfreitasdev** [comment]
hello @bfontanet 

Thank you very much for reporting, I have released an [update](https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.2.1) to fix this bug, temporarily removing the notify functionality.

**Comment by kasirye** [comment]
Same issue reoccuring

Composer version 2.1.11 2021-11-02 12:10:25
PHP 8.0.9
Laravel 8.65
power-components/livewire-powergrid": "^1.4"

**Comment by devsquad-luan-freitas** [comment]
Hi. did you install composer on the project?

**Comment by kasirye** [comment]
Yes I installed via composer
<img width="559" alt="Screenshot 2021-11-09 at 15 05 35" src="https://user-images.githubusercontent.com/11265554/140921415-58005a0c-339a-49a6-bc46-3e483fbb51fa.png">

**Comment by kasirye** [comment]
I referred to your documentation, installed  "composer require composer/composer --dev" and now its ok. Thanks
