### ISSUE TITLE
Powergrid Datatable datepicker translation

### ISSUE THREAD

**Issue by Lerma4** [Power-Components/livewire-powergrid#412]
Hello, I don't know if I'm doing something wrong, but the datepicker in the table remains with the months in English (my language is set in the app.php). Searching in the package files I found the list of months in Italian but I don't understand how to use them. I don't know if it's a function not yet implemented or an error on my part.

thanks in advance

**Comment by luanfreitasdev** [comment]
Hi! please consider the template given issue to help us with versions. Could you show the html of the datepiker component that was generated?

How is the language in the app?

**Comment by Lerma4** [comment]
The language in the app is Italian (other translations work correctly).

The code generated is this:

<div class="flatpickr-calendar rangeMode animate arrowTop arrowLeft open" tabindex="-1"
    style="top: 397.271px; left: 99.5px; right: auto;">
    <div class="flatpickr-months"><span class="flatpickr-prev-month"><svg version="1.1"
                xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 17 17">
                <g></g>
                <path d="M5.207 8.471l7.146 7.147-0.707 0.707-7.853-7.854 7.854-7.853 0.707 0.707-7.147 7.146z"></path>
            </svg></span>
        <div class="flatpickr-month">
            <div class="flatpickr-current-month"><select class="flatpickr-monthDropdown-months" aria-label="Month"
                    tabindex="-1">
                    <option class="flatpickr-monthDropdown-month" value="0" tabindex="-1">January</option>
                    <option class="flatpickr-monthDropdown-month" value="1" tabindex="-1">February</option>
                    <option class="flatpickr-monthDropdown-month" value="2" tabindex="-1">March</option>
                    <option class="flatpickr-monthDropdown-month" value="3" tabindex="-1">April</option>
                    <option class="flatpickr-monthDropdown-month" value="4" tabindex="-1">May</option>
                    <option class="flatpickr-monthDropdown-month" value="5" tabindex="-1">June</option>
                    <option class="flatpickr-monthDropdown-month" value="6" tabindex="-1">July</option>
                    <option class="flatpickr-monthDropdown-month" value="7" tabindex="-1">August</option>
                    <option class="flatpickr-monthDropdown-month" value="8" tabindex="-1">September</option>
                    <option class="flatpickr-monthDropdown-month" value="9" tabindex="-1">October</option>
                    <option class="flatpickr-monthDropdown-month" value="10" tabindex="-1">November</option>
                    <option class="flatpickr-monthDropdown-month" value="11" tabindex="-1">December</option>
                </select>
                <div class="numInputWrapper"><input class="numInput cur-year" type="number" tabindex="-1"
                        aria-label="Year"><span class="arrowUp"></span><span class="arrowDown"></span></div>
            </div>
        </div><span class="flatpickr-next-month"><svg version="1.1" xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 17 17">
                <g></g>
                <path d="M13.207 8.472l-7.854 7.854-0.707-0.707 7.146-7.146-7.146-7.148 0.707-0.707 7.854 7.854z">
                </path>
            </svg></span>
    </div>
    <div class="flatpickr-innerContainer">
        <div class="flatpickr-rContainer">
            <div class="flatpickr-weekdays">
                <div class="flatpickr-weekdaycontainer">
                    <span class="flatpickr-weekday">
                        Sun</span><span class="flatpickr-weekday">Mon</span><span
                        class="flatpickr-weekday">Tue</span><span class="flatpickr-weekday">Wed</span><span
                        class="flatpickr-weekday">Thu</span><span class="flatpickr-weekday">Fri</span><span
                        class="flatpickr-weekday">Sat
                    </span>
                </div>
            </div>
            <div class="flatpickr-days" tabindex="-1">
                <div class="dayContainer"><span class="flatpickr-day prevMonthDay" aria-label="March 27, 2022"
                        tabindex="-1">27</span><span class="flatpickr-day prevMonthDay" aria-label="March 28, 2022"
                        tabindex="-1">28</span><span class="flatpickr-day prevMonthDay" aria-label="March 29, 2022"
                        tabindex="-1">29</span><span class="flatpickr-day prevMonthDay" aria-label="March 30, 2022"
                        tabindex="-1">30</span><span class="flatpickr-day prevMonthDay" aria-label="March 31, 2022"
                        tabindex="-1">31</span><span class="flatpickr-day" aria-label="April 1, 2022"
                        tabindex="-1">1</span><span class="flatpickr-day" aria-label="April 2, 2022"
                        tabindex="-1">2</span><span class="flatpickr-day" aria-label="April 3, 2022"
                        tabindex="-1">3</span><span class="flatpickr-day" aria-label="April 4, 2022"
                        tabindex="-1">4</span><span class="flatpickr-day" aria-label="April 5, 2022"
                        tabindex="-1">5</span><span class="flatpickr-day" aria-label="April 6, 2022"
                        tabindex="-1">6</span><span class="flatpickr-day" aria-label="April 7, 2022"
                        tabindex="-1">7</span><span class="flatpickr-day" aria-label="April 8, 2022"
                        tabindex="-1">8</span><span class="flatpickr-day" aria-label="April 9, 2022"
                        tabindex="-1">9</span><span class="flatpickr-day" aria-label="April 10, 2022"
                        tabindex="-1">10</span><span class="flatpickr-day" aria-label="April 11, 2022"
                        tabindex="-1">11</span><span class="flatpickr-day" aria-label="April 12, 2022"
                        tabindex="-1">12</span><span class="flatpickr-day" aria-label="April 13, 2022"
                        tabindex="-1">13</span><span class="flatpickr-day" aria-label="April 14, 2022"
                        tabindex="-1">14</span><span class="flatpickr-day" aria-label="April 15, 2022"
                        tabindex="-1">15</span><span class="flatpickr-day" aria-label="April 16, 2022"
                        tabindex="-1">16</span><span class="flatpickr-day" aria-label="April 17, 2022"
                        tabindex="-1">17</span><span class="flatpickr-day" aria-label="April 18, 2022"
                        tabindex="-1">18</span><span class="flatpickr-day" aria-label="April 19, 2022"
                        tabindex="-1">19</span><span class="flatpickr-day" aria-label="April 20, 2022"
                        tabindex="-1">20</span><span class="flatpickr-day" aria-label="April 21, 2022"
                        tabindex="-1">21</span><span class="flatpickr-day" aria-label="April 22, 2022"
                        tabindex="-1">22</span><span class="flatpickr-day" aria-label="April 23, 2022"
                        tabindex="-1">23</span><span class="flatpickr-day" aria-label="April 24, 2022"
                        tabindex="-1">24</span><span class="flatpickr-day" aria-label="April 25, 2022"
                        tabindex="-1">25</span><span class="flatpickr-day" aria-label="April 26, 2022"
                        tabindex="-1">26</span><span class="flatpickr-day" aria-label="April 27, 2022"
                        tabindex="-1">27</span><span class="flatpickr-day" aria-label="April 28, 2022"
                        tabindex="-1">28</span><span class="flatpickr-day" aria-label="April 29, 2022"
                        tabindex="-1">29</span><span class="flatpickr-day today" aria-label="April 30, 2022"
                        aria-current="date" tabindex="-1">30</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 1, 2022" tabindex="-1">1</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 2, 2022" tabindex="-1">2</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 3, 2022" tabindex="-1">3</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 4, 2022" tabindex="-1">4</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 5, 2022" tabindex="-1">5</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 6, 2022" tabindex="-1">6</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 7, 2022" tabindex="-1">7</span></div>
            </div>
        </div>
    </div>
</div>

**Comment by Lerma4** [comment]
The set language is Italian (the other translations work correctly).

This is the generated code:

```
<div class="flatpickr-calendar rangeMode animate arrowTop arrowLeft open" tabindex="-1"
    style="top: 397.271px; left: 99.5px; right: auto;">
    <div class="flatpickr-months"><span class="flatpickr-prev-month"><svg version="1.1"
                xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 17 17">
                <g></g>
                <path d="M5.207 8.471l7.146 7.147-0.707 0.707-7.853-7.854 7.854-7.853 0.707 0.707-7.147 7.146z"></path>
            </svg></span>
        <div class="flatpickr-month">
            <div class="flatpickr-current-month"><select class="flatpickr-monthDropdown-months" aria-label="Month"
                    tabindex="-1">
                    <option class="flatpickr-monthDropdown-month" value="0" tabindex="-1">January</option>
                    <option class="flatpickr-monthDropdown-month" value="1" tabindex="-1">February</option>
                    <option class="flatpickr-monthDropdown-month" value="2" tabindex="-1">March</option>
                    <option class="flatpickr-monthDropdown-month" value="3" tabindex="-1">April</option>
                    <option class="flatpickr-monthDropdown-month" value="4" tabindex="-1">May</option>
                    <option class="flatpickr-monthDropdown-month" value="5" tabindex="-1">June</option>
                    <option class="flatpickr-monthDropdown-month" value="6" tabindex="-1">July</option>
                    <option class="flatpickr-monthDropdown-month" value="7" tabindex="-1">August</option>
                    <option class="flatpickr-monthDropdown-month" value="8" tabindex="-1">September</option>
                    <option class="flatpickr-monthDropdown-month" value="9" tabindex="-1">October</option>
                    <option class="flatpickr-monthDropdown-month" value="10" tabindex="-1">November</option>
                    <option class="flatpickr-monthDropdown-month" value="11" tabindex="-1">December</option>
                </select>
                <div class="numInputWrapper"><input class="numInput cur-year" type="number" tabindex="-1"
                        aria-label="Year"><span class="arrowUp"></span><span class="arrowDown"></span></div>
            </div>
        </div><span class="flatpickr-next-month"><svg version="1.1" xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 17 17">
                <g></g>
                <path d="M13.207 8.472l-7.854 7.854-0.707-0.707 7.146-7.146-7.146-7.148 0.707-0.707 7.854 7.854z">
                </path>
            </svg></span>
    </div>
    <div class="flatpickr-innerContainer">
        <div class="flatpickr-rContainer">
            <div class="flatpickr-weekdays">
                <div class="flatpickr-weekdaycontainer">
                    <span class="flatpickr-weekday">
                        Sun</span><span class="flatpickr-weekday">Mon</span><span
                        class="flatpickr-weekday">Tue</span><span class="flatpickr-weekday">Wed</span><span
                        class="flatpickr-weekday">Thu</span><span class="flatpickr-weekday">Fri</span><span
                        class="flatpickr-weekday">Sat
                    </span>
                </div>
            </div>
            <div class="flatpickr-days" tabindex="-1">
                <div class="dayContainer"><span class="flatpickr-day prevMonthDay" aria-label="March 27, 2022"
                        tabindex="-1">27</span><span class="flatpickr-day prevMonthDay" aria-label="March 28, 2022"
                        tabindex="-1">28</span><span class="flatpickr-day prevMonthDay" aria-label="March 29, 2022"
                        tabindex="-1">29</span><span class="flatpickr-day prevMonthDay" aria-label="March 30, 2022"
                        tabindex="-1">30</span><span class="flatpickr-day prevMonthDay" aria-label="March 31, 2022"
                        tabindex="-1">31</span><span class="flatpickr-day" aria-label="April 1, 2022"
                        tabindex="-1">1</span><span class="flatpickr-day" aria-label="April 2, 2022"
                        tabindex="-1">2</span><span class="flatpickr-day" aria-label="April 3, 2022"
                        tabindex="-1">3</span><span class="flatpickr-day" aria-label="April 4, 2022"
                        tabindex="-1">4</span><span class="flatpickr-day" aria-label="April 5, 2022"
                        tabindex="-1">5</span><span class="flatpickr-day" aria-label="April 6, 2022"
                        tabindex="-1">6</span><span class="flatpickr-day" aria-label="April 7, 2022"
                        tabindex="-1">7</span><span class="flatpickr-day" aria-label="April 8, 2022"
                        tabindex="-1">8</span><span class="flatpickr-day" aria-label="April 9, 2022"
                        tabindex="-1">9</span><span class="flatpickr-day" aria-label="April 10, 2022"
                        tabindex="-1">10</span><span class="flatpickr-day" aria-label="April 11, 2022"
                        tabindex="-1">11</span><span class="flatpickr-day" aria-label="April 12, 2022"
                        tabindex="-1">12</span><span class="flatpickr-day" aria-label="April 13, 2022"
                        tabindex="-1">13</span><span class="flatpickr-day" aria-label="April 14, 2022"
                        tabindex="-1">14</span><span class="flatpickr-day" aria-label="April 15, 2022"
                        tabindex="-1">15</span><span class="flatpickr-day" aria-label="April 16, 2022"
                        tabindex="-1">16</span><span class="flatpickr-day" aria-label="April 17, 2022"
                        tabindex="-1">17</span><span class="flatpickr-day" aria-label="April 18, 2022"
                        tabindex="-1">18</span><span class="flatpickr-day" aria-label="April 19, 2022"
                        tabindex="-1">19</span><span class="flatpickr-day" aria-label="April 20, 2022"
                        tabindex="-1">20</span><span class="flatpickr-day" aria-label="April 21, 2022"
                        tabindex="-1">21</span><span class="flatpickr-day" aria-label="April 22, 2022"
                        tabindex="-1">22</span><span class="flatpickr-day" aria-label="April 23, 2022"
                        tabindex="-1">23</span><span class="flatpickr-day" aria-label="April 24, 2022"
                        tabindex="-1">24</span><span class="flatpickr-day" aria-label="April 25, 2022"
                        tabindex="-1">25</span><span class="flatpickr-day" aria-label="April 26, 2022"
                        tabindex="-1">26</span><span class="flatpickr-day" aria-label="April 27, 2022"
                        tabindex="-1">27</span><span class="flatpickr-day" aria-label="April 28, 2022"
                        tabindex="-1">28</span><span class="flatpickr-day" aria-label="April 29, 2022"
                        tabindex="-1">29</span><span class="flatpickr-day today" aria-label="April 30, 2022"
                        aria-current="date" tabindex="-1">30</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 1, 2022" tabindex="-1">1</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 2, 2022" tabindex="-1">2</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 3, 2022" tabindex="-1">3</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 4, 2022" tabindex="-1">4</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 5, 2022" tabindex="-1">5</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 6, 2022" tabindex="-1">6</span><span class="flatpickr-day nextMonthDay"
                        aria-label="May 7, 2022" tabindex="-1">7</span></div>
            </div>
        </div>
    </div>
</div>
```

**Comment by luanfreitasdev** [comment]
how is your config file? You need to add your location key as in the example:

https://github.com/Power-Components/livewire-powergrid/issues/413#issuecomment-1117929805
