### ISSUE TITLE
Editable and togglable fields is not showing in initial request

### ISSUE THREAD

**Issue by Mo7sin** [Power-Components/livewire-powergrid#413]
## Information
I have some editable and togglable fields that don't appear until I do some action like changing the page or using the filters.

Here is a video for the issue.

[https://www.youtube.com/watch?v=1G1foOLa5wY](https://www.youtube.com/watch?v=1G1foOLa5wY)

#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [x] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [x] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

- [x ] Yes - I didn't work.
- [ ] No, this error is not related to views.

#### Is there an error in the console?
- [x] Yes - I'll add a screenshot or report it below.
- [ ] No

### Software Version

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |  v2.4.7                 |
| Laravel   |  v9.10.1                 |
| Livewire  | v2.10.5                  |
| Alpine JS  |  3.8.1                 |

### Theme
- [ ] Tailwind 2.x
- [x] Tailwind 3.x
  - [x] With tailwind/forms
- [ ] Bootstrap - Version:        

---
### What happened?

I have a typical table, it worked fine before I update to the latest version.

### To Reproduce...
I should change the page or do some filtering to get these fields to show in the table.

### Suggestions

(Do you have any idea how we can fix it?)
Unfortunately not.

## Extra information

**Screenshots**

Console error
![Console error](https://i.ibb.co/VjFfQqL/Screenshot-from-2022-04-29-23-56-59.png)

**Comment by CrazyBoy49z** [comment]
This bug in flatpickr, check file config/livewire-powergrid.php

```
'flat_piker' => [
...
  'locales'   => [
               'pt_BR' => [
                    'locale'     => 'pt',
                    'dateFormat' => 'd/m/Y H:i',
                    'enableTime' => true,
                    'time_24hr'  => true,
                ],
                ...
                'uk' => [
                    'locale'     => 'uk',
                    'dateFormat' => 'd/m/Y',
                    'enableTime' => false,
                    'time_24hr'  => true,
                ],
            ],
        ],
```

**Comment by Mo7sin** [comment]
@CrazyBoy49z  i have renamed flat_piker to flatpiker as documentation said.

**Comment by Mo7sin** [comment]
@luanfreitasdev is flatpicker issue related to the main problem this issue was opened for?

**Comment by luanfreitasdev** [comment]
> @luanfreitasdev is flatpicker issue related to the main problem this issue was opened for?

Yes, 

Take a look at this issue. If it doesn't work we will need to know if the flatpickr instance is global

https://github.com/Power-Components/livewire-powergrid/issues/365

**Comment by Mo7sin** [comment]
I did rename flat_picker to flatpicker, but still having flatpicker error.

**Comment by Mo7sin** [comment]
Here is what I have 

```
        'flatpickr' => [
            'js'      => 'https://cdn.jsdelivr.net/npm/flatpickr',
            'css'     => 'https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css',
            'locales' => [
                'en' => [
                    'locale'     => 'en',
                    'dateFormat' => 'd/m/Y H:i',
                    'enableTime' => true,
                    'time_24hr'  => true,
                ],
            ],
        ],
```

and I have the default `en` directory in `resources/lang/vendor/livewire-powergrid`

**Comment by luanfreitasdev** [comment]
This error happens when flatpickr is not being instantiated in the browser, there are two ways to do this, checking if the script was called correctly.

Did you insert the `@powerScript` tag before `</body>` ?

Was this script injected into the html?
`<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
`
Or you can call via module:

```js
import Alpine from 'alpinejs'
import flatpickr from "flatpickr";

window.Alpine = Alpine
window.flatpickr = flatpickr

require("./../../node_modules/flatpickr/dist/flatpickr.min.css");

import './../../vendor/power-components/livewire-powergrid/dist/powergrid'

Alpine.start()
```

Type in the browser console: window.flatpickr
![image](https://user-images.githubusercontent.com/33601626/167221521-0509edc2-8188-44d7-a752-4b78f9daa74a.png)

**Comment by Mo7sin** [comment]
@luanfreitasdev I use `@powerScript`, the problem was in both files `scripts.blade.php` and `styles.blade.php`

```
@if(filled(config('livewire-powergrid.plugins.flat_piker.js')))
    <script src="{{ config('livewire-powergrid.plugins.flat_piker.js') }}"></script>
@endif
```

```
<link rel="stylesheet" href="{{ config('livewire-powergrid.plugins.flat_piker.css') }}">
```

both snippets were not updated even after I republished the views files

```
php artisan vendor:publish --tag=livewire-powergrid-views && php artisan view:clear
```

So I manually modified both files and it's working fine now.

Thank you.

**Comment by luanfreitasdev** [comment]
Thanks!
