### ISSUE TITLE
Bug Report: ** short & meaningful title describing the bug ***

### ISSUE THREAD

**Issue by CrazyBoy49z** [Power-Components/livewire-powergrid#414]
# PowerGrid Bug Report

Thank you for reporting a bug and helping us to improve PowerGrid!

## Guidelines

`   🐛 `   We use GitHub Issues exclusively for tracking bugs and unexpected software behavior. 

`   🙏 `  Please use the [Discussions](https://github.com/Power-Components/livewire-powergrid/discussions) tab for questions like _"How to...",_ "_how can I..."_ .

`   ✍️ `  Give this report a short but meaningful title. Make it easy to spot for others who might be facing the same issue.

`   ⚠️ `  Issues that do not describe a bug or do not follow the template will be closed.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [X] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [X] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [ ] Yes - I didn't work.
- [X] No, this error is not related to views.

#### Is there an error in the console?
- [X] Yes - I'll add a screenshot or report it below.
- [ ] No

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |  v2.4.7                  |
| Laravel   |   8.83                |
| Livewire  |  v2.10.5                  |
| Alpine JS  | 3.9.1                  |

### Theme
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [X] Bootstrap - Version:        

---
### What happened?

Duplicate data source code

### To Reproduce...

Click show/hide column

## Extra information

**Screenshots**
![image](https://user-images.githubusercontent.com/3448603/167658613-f9a89308-2d4e-4246-a4ef-03024a5cc8c4.png)

**Comment by luanfreitasdev** [comment]
Thanks for report this bug!

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/releases/tag/v2.4.8
