### ISSUE TITLE
Bug Report: Action button disappears when table is updated and refreshed

### ISSUE THREAD

**Issue by Stridesdata** [Power-Components/livewire-powergrid#415]
# PowerGrid Bug Report

Thank you for reporting a bug and helping us to improve PowerGrid!

## Guidelines

`   🐛 `   We use GitHub Issues exclusively for tracking bugs and unexpected software behavior. 

`   🙏 `  Please use the [Discussions](https://github.com/Power-Components/livewire-powergrid/discussions) tab for questions like _"How to...",_ "_how can I..."_ .

`   ✍️ `  Give this report a short but meaningful title. Make it easy to spot for others who might be facing the same issue.

`   ⚠️ `  Issues that do not describe a bug or do not follow the template will be closed.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [X] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [X] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [X] Yes - I didn't work.
- [ ] No, this error is not related to views.

#### Is there an error in the console?
- [ ] Yes - I'll add a screenshot or report it below.
- [X] No

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |      2.2     |
| Laravel   |     8.83.0     |
| Livewire  |       2.6        |
| Alpine JS  |       3.0      |

### Theme
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [X] Bootstrap - Version:        

---
### What happened?

I deleted an item from the collection and used event listeners to refresh the table. When ever i do that the second to the last row does not show action buttons. It happens when I add an Item as well. It should be noted that this does not occur when updating the collection

## Extra information

**Screenshots**

**Code snippet**

```php 
<?php

//...
```

**Comment by Stridesdata** [comment]
https://user-images.githubusercontent.com/82326559/167861673-1896fade-9fc7-4589-8ab6-e1958ca8a416.mp4

**Comment by CrazyBoy49z** [comment]
Hmm, I do not use the buttons, because I have them used in view (blade). And there are no such problems (work fine), rather a problem that needs to be added wire:key

**Comment by luanfreitasdev** [comment]
I remember it was like this and I had to remove it for some reason. As much as I'm not having this kind of error

If you do put wire:key in your location does it work?

vendor/power-components/livewire-powergrid/resources/views/components/actions.blade.php

**Before**
```blade
@if(isset($actions) && count($actions) && $row !== '')
        @foreach($actions as $key => $action)
            <td class="pg-actions {{ $theme->table->tdBodyClass }}"
                style="{{ $theme->table->tdBodyStyle }}">
```

**After**
```blade
@if(isset($actions) && count($actions) && $row !== '')
        @foreach($actions as $key => $action)
            <td wire:key="{{ md5($action->action) }}" class="pg-actions {{ $theme->table->tdBodyClass }}"
                style="{{ $theme->table->tdBodyStyle }}">
```
