### ISSUE TITLE
"emitTo" action is being rendered as just "emit"

### ISSUE THREAD

**Issue by agharium** [Power-Components/livewire-powergrid#418]
#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [x] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [x] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [x] Yes - I didn't work.
- [ ] No, this error is not related to views.

#### Is there an error in the console?
- [ ] Yes - I'll add a screenshot or report it below.
- [x] No

### Software Version

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |    v2.4.7    |
| Laravel   |    v8.83.11    |
| Livewire  |   v2.10.5   |
| Alpine JS  |    v3.x.x     |

### Theme
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [x] Bootstrap - Version:  5

---
### What happened?

Trying to setup action with emitTo (open a bootstrap custom modal):

```
Button::add('edit')
    ->caption('Editar')
    ->tooltip('Editar')
    ->class('btn btn-warning round button-edit')
    ->emitTo('general-form-modal', 'toggle', ['model' => 'city', 'action' => 'edit'])
```

```
class GeneralFormModal extends Component
{
    public $listeners = [
        'toggle' => 'toggle',
    ];

	...

	public function toggle($model, $action, $id = null)
    {
        $this->_model = $model;
        $this->_action = $action;
        $this->_id = $id;
        
        $this->dispatchBrowserEvent('toggleGeneralFormModal');
    }

	... 
```

But the final render is..

![image](https://user-images.githubusercontent.com/28984633/168084117-3f39fb48-76f7-49e4-a9c6-4983f6229459.png)

As you can see, "emit" event instead of "emitTo" (the one I called for on the PHP).

Also, even with only "emit", it looks like the parameters aren't being treated correctly (even though the image shows that the rendered action has those parameters on it) when I click on the action button:

```
Illuminate\Contracts\Container\BindingResolutionException
Unable to resolve dependency [Parameter #1 [ <required> $action ]] in class App\Http\Livewire\GeneralFormModal
```

### To Reproduce...

Simply create a action with "emitTo" and parameters.

### Suggestions

No idea. I swear I've tried everything I could think of.

**Comment by luanfreitasdev** [comment]
Hello, thanks for report this bug

https://github.com/Power-Components/livewire-powergrid/releases/tag/v2.4.9
