### ISSUE TITLE
Datepickr dont open or triggered

### ISSUE THREAD

**Issue by pirex360** [Power-Components/livewire-powergrid#419]
Hello,

DatePicker, using ->makeInputDatePicker(), don't trigger... and no console error. The normal behaviour should trigger the datepickr, right ? I click and no action occurs, how could I fix this? Search and Sortable work well.

```
 public function columns(): array
    {
        return [
            Column::add()
                ->title('Início Produção')
                ->field('data_inicio')
                //->searchable()
                //->sortable()
                ->makeInputDatePicker('data_inicio'),
        ];
    }
```

![image](https://user-images.githubusercontent.com/17271768/168121511-17509e61-fb3a-4fc9-8376-7e4a7a6a9013.png)
![image](https://user-images.githubusercontent.com/17271768/168121739-07f9d3e6-3b22-400b-99c4-f3e5de445f84.png)

**Comment by luanfreitasdev** [comment]
Hello.

What versions are you using? Could you show a snippet of the html in datepicker and check if the datepicker script was instantiated by the browser or via module?

**Comment by pirex360** [comment]
Hi there, thanks for replying.

I figure out that the js of flatpickr isn't loaded in HTML, only CSS... but I hardcoded the `<script src="https://cdn.jsdelivr.net/npm/flatpickr" defer></script>` and the results are the same.

![2022-05-13_12-22](https://user-images.githubusercontent.com/17271768/168274756-0a0fb53b-431e-4d1e-bf82-59425563b0a0.png)

![2022-05-13_12-23](https://user-images.githubusercontent.com/17271768/168274767-ddcaaf48-8fa3-4895-b07a-f808315d8cb9.png)

**Comment by luanfreitasdev** [comment]
Can you show how close you are to x-data="pgFlatPickr" ?

![image](https://user-images.githubusercontent.com/33601626/168322327-b4b97b5b-4aee-4ab5-b64e-131a7562c658.png)

**Comment by pirex360** [comment]
![image](https://user-images.githubusercontent.com/17271768/168347607-9d5572ba-36a4-4e44-86d3-327162f35634.png)

**Comment by CrazyBoy49z** [comment]
Rather, you are having problems with js, or the data_inicio field does not exist in the database

**Comment by pirex360** [comment]
`data_inicio` is rendered in the table, as you can see in the screenshots...

**Comment by pirex360** [comment]
Ok, so there was a problem with bootstrap-select that was causing this issue.
In the webpack.mix.js I have the default laravel line : r`equire("bootstrap");` , change it to  `window.bootstrap = require("bootstrap");`

All works now.... the datepicker and the bootstrap-select

**Comment by pirex360** [comment]
Isn't it redundant to use both ? or the webpack.mix.js don't import 2x the library?

**Comment by luanfreitasdev** [comment]
did it work now?

**Comment by pirex360** [comment]
> did it work now?

Yeap, now it works...using the above hack
