### ISSUE TITLE
Dropdown is not showing all options

### ISSUE THREAD

**Issue by edwinheij** [Power-Components/livewire-powergrid#42]
while no results found and clicking a select input field with a couple of options in it, not all options are visible.

![image](https://user-images.githubusercontent.com/1799101/128680002-1c62f2d5-2f3c-4ff7-81fe-d58110bff056.png)

**Comment by luanfreitasdev** [comment]
hello @edwinheij

Thank you so much for reporting, I believe the [latest update](https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.2.1) fixes this issue
