### ISSUE TITLE
Bulk action button is not showing with boostrap 5

### ISSUE THREAD

**Issue by sampath-kumara-herath** [Power-Components/livewire-powergrid#421]
When I create the bulk action in power-grid table with bootstrap 5 , there is no button show as given name with given class for "Bulk Action" . But changed theme from bootstrap 5 to Tailwind it shows nicely.

**Comment by luanfreitasdev** [comment]
Hello. Unfortunately it is not available in v2, but in v3 it will be available.

Thanks
