### ISSUE TITLE
The published stub does not work

### ISSUE THREAD

**Issue by CrazyBoy49z** [Power-Components/livewire-powergrid#426]
# PowerGrid Bug Report

Thank you for reporting a bug and helping us to improve PowerGrid!

## Guidelines

`   🐛 `   We use GitHub Issues exclusively for tracking bugs and unexpected software behavior. 

`   🙏 `  Please use the [Discussions](https://github.com/Power-Components/livewire-powergrid/discussions) tab for questions like _"How to...",_ "_how can I..."_ .

`   ✍️ `  Give this report a short but meaningful title. Make it easy to spot for others who might be facing the same issue.

`   ⚠️ `  Issues that do not describe a bug or do not follow the template will be closed.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [X] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [X] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [ ] Yes - I didn't work.
- [X] No, this error is not related to views.

#### Is there an error in the console?
- [ ] Yes - I'll add a screenshot or report it below.
- [X] No

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |   v2.4.7                 |
| Laravel   |  v9.10.0                   |
| Livewire  |       v2.10.5              |
| Alpine JS  |  3.4.2                 |

### Theme
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [X] Bootstrap - Version:        

---
## Describe the bug
https://github.com/Power-Components/livewire-powergrid/blob/main/src/Commands/PublishCommand.php#L46-L48

1. Publish stub 
`php artisan powergrid:publish --type=stub`
2. Replace code
3. Create Table
`php artisan powergrid:create  `

The table created by default code

**Comment by luanfreitasdev** [comment]
Powergrid can have multiple stubs, so the correct flow would be:
* `php artisan powergrid:publish --type=stub`
* rename **stubs/table.model.stub** to **stubs/table1.stub**

* `php artisan powergrid:publish --type=stub`
* rename **stubs/table.model.stub** to **stubs/table2.stub**

And then you can do it:
```
php artisan powergrid:create --template=stubs/table1.stub
php artisan powergrid:create --template=stubs/table2.stub
```

This will be documented soon.

![image](https://user-images.githubusercontent.com/33601626/168399635-a21dfa44-410a-49c1-876b-bb4f7697e124.png)

**Comment by CrazyBoy49z** [comment]
Thanks
