### ISSUE TITLE
Date Picker Filter - Wrong Date ?!

### ISSUE THREAD

**Issue by pirex360** [Power-Components/livewire-powergrid#429]
I have a strange behaviour of filtering dates using flatpickr, (see video). I have records on 12/05/2022... when I choose the exact date on the picker: it returns zero rows.... but if I choose the next day 13/05/2022 all the records of 12/05/2022 are retrieved.

https://user-images.githubusercontent.com/17271768/168447958-377897ee-7809-4571-bb06-3aa0de8c6af9.mp4

 

So, my flatpickr in the config file is like this :

![image](https://user-images.githubusercontent.com/17271768/168447911-33361027-c569-4ab1-83d4-9b60ae7ddb43.png)

My component , in the addColumn() method
![image](https://user-images.githubusercontent.com/17271768/168447986-5437f523-be52-4f5b-8a8d-21e8a05f08b2.png)

My component, in the columns() method
![image](https://user-images.githubusercontent.com/17271768/168448000-2133a951-5665-4751-b3da-9e12231e074c.png)

So I think this is something regarding my Carbon transformation.... the data in the database is stored `Y-m-d H:I:s`, I use the callback to transform to locale date format `d/m/Y`

**Comment by luanfreitasdev** [comment]
This would be the best way:

```php
public function addColumns(): PowerGridEloquent
{
     return PowerGrid::eloquent()
         ->addColumn('data_inicio')
         ->addColumn('data_inicio_formatted', function ($entry) {
               return Carbon::parse($entry->data_inicio)->format('d/m/Y');
         });
}

public function columns(): array
   Column::add()
         ->title('Data Inicio')
         ->field('data_inicio_formatted')
         ->makeInputDatePicker('data_inicio'),

```

**Comment by pirex360** [comment]
Don't Work... I have the same behaviour.... 
The dates of 12/05/2022, only appear when I choose in the date picker 13/05/2022

maybe there is a flag for single date selection?

**Comment by luanfreitasdev** [comment]
Strange, here the filtering is returning correctly
![image](https://user-images.githubusercontent.com/33601626/168669407-69f227d2-31b4-482b-b29d-c26a22c09a71.png)

**Comment by pirex360** [comment]
Something wrong with my date... I choose a date between 15 and 16 of May... 

inspecting livewire filter date array ... is getting 14 to 15 (midnight) ....

![image](https://user-images.githubusercontent.com/17271768/168675648-afea4800-afe7-4281-abd6-d46f8250241a.png)

**Comment by luanfreitasdev** [comment]
Interesting. I'll see if I can find something around here. but feel free to correct and submit a PR!

**Comment by luanfreitasdev** [comment]
I believe these changes can resolve some of these issues. 

https://github.com/Power-Components/livewire-powergrid/pull/778
