### ISSUE TITLE
Toggleable value is reversed in v2.4.10

### ISSUE THREAD

**Issue by Mo7sin** [Power-Components/livewire-powergrid#437]
## Information

In [v2.4.10](https://github.com/Power-Components/livewire-powergrid/releases/tag/v2.4.10) when you click to toggle, the button works fine but when you refresh the page it resets back to default.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [x] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [x] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

- [x] Yes - I didn't work.
- [ ] No, this error is not related to views.

#### Is there an error in the console?
- [ ] Yes - I'll add a screenshot or report it below.
- [x] No

### Software Version

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |  v2.4.10                 |
| Laravel   |  v9.13.0                  |
| Livewire  |  v2.10.5                 |
| Alpine JS  |   3.8.1                |

### Theme
- [ ] Tailwind 2.x
- [x] Tailwind 3.x
  - [x] With tailwind/forms
- [ ] Bootstrap - Version:        

---

### What happened?

I `dd($data)` in the `update` method and I got

```
array:3 [▼
  "id" => "18232"
  "field" => "order_status"
  "value" => 0
]
```

`value` should be `1` at this point, but it's reversed, 

meaning if the toggle was active and I switch it to be off, the `value` now is `1`

Note: This issue doesn't exists is `v2.4.9`

**Comment by luanfreitasdev** [comment]
Thanks for reporting this bug, it was fixed in v2.4.11
