### ISSUE TITLE
Return type of dataSource() error

### ISSUE THREAD

**Issue by edwinheij** [Power-Components/livewire-powergrid#44]
Return value of App\Http\Livewire\ProductTable::dataSource() must be an instance of App\Http\Livewire\Collection, instance of Illuminate\Database\Eloquent\Collection returned

**Comment by luanfreitasdev** [comment]
Hi @edwinheij 

I couldn't reproduce the same error. Can you specify the situation better?

I will close the issue, but if it happens again, you can reopen it again.

Hug.
