### ISSUE TITLE
Bug Report: search for formatted date

### ISSUE THREAD

**Issue by agharium** [Power-Components/livewire-powergrid#443]
# PowerGrid Bug Report

Thank you for reporting a bug and helping us to improve PowerGrid!

## Guidelines

`   🐛 `   We use GitHub Issues exclusively for tracking bugs and unexpected software behavior. 

`   🙏 `  Please use the [Discussions](https://github.com/Power-Components/livewire-powergrid/discussions) tab for questions like _"How to...",_ "_how can I..."_ .

`   ✍️ `  Give this report a short but meaningful title. Make it easy to spot for others who might be facing the same issue.

`   ⚠️ `  Issues that do not describe a bug or do not follow the template will be closed.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [ x ] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [ x ] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [ ] Yes - I didn't work.
- [ x ] No, this error is not related to views.

#### Is there an error in the console?
- [ ] Yes - I'll add a screenshot or report it below.
- [ x ] No

### Software Version

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |    v2.4.8    |
| Laravel   |    v8.83.11    |
| Livewire  |   v2.10.5   |
| Alpine JS  |    v3.x.x     |

### Theme
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [x] Bootstrap - Version:  5

---
### What happened?

Search for the formatted date (d/m/Y, for instance) on table's search box doesn't work.

### To Reproduce...

Insert d/m/Y date into search box.

### Suggestions

Maybe a way to intercept search input value and format it back to SQL format. Maybe.

## Extra information

**Screenshots**

When I insert the formatted date on search box, it doesn't find anything:

![image](https://user-images.githubusercontent.com/28984633/169530478-ecb1a103-b994-4270-b7a2-932d68fc1661.png)

But when I insert a SQL date format, it works:

![image](https://user-images.githubusercontent.com/28984633/169530291-c4a92a34-e8f7-4d5c-9f33-57128358da28.png)

**Code snippet**

```php 
    public function addColumns(): ?PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ...
            ->addColumn('updated_at_formatted', function(City $model) { 
                return Carbon::parse($model->updated_at)->format('d/m/Y');
            });
    }
```

**Comment by luanfreitasdev** [comment]
Hi!. This would not be possible currently.

What I've been thinking about this would be to have a `searchableRaw` where you could put a `sql` string that would turn into a column:

```php
public function datasource()
{
     return Dish::query()
         ->join('categories', function ($categories) {
              $categories->on('dishes.category_id', '=', 'categories.id');
         })
          ->join('kitchens', function ($categories) {
              $categories->on('dishes.kitchen_id', '=', 'kitchens.id');
         })
         ->select('dishes.*', 'categories.name as category_name', DB::raw('DATE_FORMAT(dishes.produced_at, "%d/%m/%Y") as produced_at'));
}

 /// ...
public function columns(): array
    {
        return [
            Column::add()
                ->title('Craeted At PT')
                ->field('created_at2', 'created_at2')
                ->searchableRaw('DATE_FORMAT(dishes.produced_at, "%d/%m/%Y")')
                ->sortable(),
        ];
}
```

What do you say?

**Comment by agharium** [comment]
That would be perfect!

Meio estranho a gente ficar conversando em inglês, não é? hehe

Valeu pelo componente, top demais ❤️

**Comment by luanfreitasdev** [comment]
Vlw!, 

Let's add in v3
