### ISSUE TITLE
No Numeric Formatting in Excel?

### ISSUE THREAD

**Issue by saezels** [Power-Components/livewire-powergrid#447]
# PowerGrid Bug Report

Thank you for reporting a bug and helping us to improve PowerGrid!

## Guidelines

`   🐛 `   We use GitHub Issues exclusively for tracking bugs and unexpected software behavior. 

`   🙏 `  Please use the [Discussions](https://github.com/Power-Components/livewire-powergrid/discussions) tab for questions like _"How to...",_ "_how can I..."_ .

`   ✍️ `  Give this report a short but meaningful title. Make it easy to spot for others who might be facing the same issue.

`   ⚠️ `  Issues that do not describe a bug or do not follow the template will be closed.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [x] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [x] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [x] Yes - I didn't work.
- [ ] No, this error is not related to views.

#### Is there an error in the console?
- [ ] Yes - I'll add a screenshot or report it below.
- [x] No

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |      v3.0.1             |
| Laravel   |      v9.0.2             |
| Livewire  |      v2.10.2             |
| Alpine JS  |        3.9.0           |

### Theme
- [ ] Tailwind 2.x
- [x] Tailwind 3.x
  - [x] With tailwind/forms
- [ ] Bootstrap - Version:        

---
## Describe the bug
When Using Export, every Numeric Column is formatted as Text in Excel besides the Id
### What happened?
Every Cell is formatted as Text and has to be converted to Numbers in Excel.

### To Reproduce...

Klick "Export Excel"

### Suggestions

(Do you have any idea how we can fix it?)

## Extra information

**Screenshots**

**Code snippet**

```php 
<?php

//...
```

**Comment by luanfreitasdev** [comment]
Hi, I believe this is the best solution. 👍

**Comment by ashek1412** [comment]
I tired the solution provided by @saezels , but not working. Even ID field shows as text in excel.
I am using livewire-powergrid: "4.9.8"
