### ISSUE TITLE
makeInputSelect doesn't show an 'All' option

### ISSUE THREAD

**Issue by mcouvreur** [Power-Components/livewire-powergrid#455]
After updating to Powergrid 3.0.2 from 2.4.13 the makeInputSelect doesn't show an 'All' option anymore.

This is the example code:
Column::add()
                ->title(__('Kitchen'))
                ->field('kitchen_name', 'kitchens.name')
                ->sortable('kitchens.name')
                ->makeInputSelect(Kitchen::all(), 'name', 'kitchen_id'),

Version 2.4.13 results in:
<img width="100" alt="image" src="https://user-images.githubusercontent.com/5759400/170991608-141a3fd9-f06f-4212-aa15-5a83723b1db6.png">

Version 3.0.2 results in:
<img width="96" alt="image" src="https://user-images.githubusercontent.com/5759400/170990462-771d72ec-df68-480a-93de-805b0bb16d54.png">

**Comment by luanfreitasdev** [comment]
Thanks for reporting this bug, I'm fixing it in v3.0.3
