### ISSUE TITLE
livewire powergrid pagination button not styled

### ISSUE THREAD

**Issue by winryesforty** [Power-Components/livewire-powergrid#458]
Hello everyone,

Im new to laravel and livewire, this powergrid looks awesome but i dont know why the pagination button is not showing a style,  i followed the Powergrid demo and didnt change any from the file pwergrid-demo. what seems to be the problem here? tnx in advance

![livewire powergrid not styled](https://user-images.githubusercontent.com/20971501/171469986-1eb1fb0b-223f-48f4-bb90-da9e7ac74080.png)

# PowerGrid Bug Report

**Comment by luanfreitasdev** [comment]
Hello!. could you post your solution? Maybe it will help others with the same problem. Thanks

**Comment by JoshPJackson** [comment]
I am now getting this with v5. Can you help me with a solution?
