### ISSUE TITLE
After searching in search for full text of first row, then remove it. This action hides the first row

### ISSUE THREAD

**Issue by SushilMore1988** [Power-Components/livewire-powergrid#465]
To generate above bug.
create simple data table add one row with title "something"
after this
in powergrid search for keyword "something"
after search result populated remove "something" keyword from search
then you will see a blank row.

It only happens for first row. all other rows are working fine.
<img width="1357" alt="Screenshot 2022-06-03 at 4 06 33 PM" src="https://user-images.githubusercontent.com/47495634/171838528-e9026e10-39e1-4e1a-bf7b-ac2fe3ae4af8.png">
<img width="1357" alt="Screenshot 2022-06-03 at 4 06 47 PM" src="https://user-images.githubusercontent.com/47495634/171838551-39479fb5-ff6a-4578-a5b9-40b933155ef2.png">
<img width="1357" alt="Screenshot 2022-06-03 at 4 06 56 PM" src="https://user-images.githubusercontent.com/47495634/171838578-0ecfa077-6ffe-4268-bf89-4da1293d69dd.png">

**Comment by luanfreitasdev** [comment]
Unfortunately I couldn't reproduce

**Comment by Unisolgr14** [comment]
In my case it occured when i have whereor in the query
