### ISSUE TITLE
Detail Row Throws an Error 

### ISSUE THREAD

**Issue by ceh137** [Power-Components/livewire-powergrid#466]
Hello!
I'm struggling with the following error that appears when Im trying to expand detail view.
<img width="1347" alt="Screenshot 2022-06-03 at 15 17 04" src="https://user-images.githubusercontent.com/72025738/171851987-c0977afe-114d-4a31-aa18-daf60078a2f7.png">
I have made a powergrid table and a detail view 
<img width="588" alt="Screenshot 2022-06-03 at 15 18 42" src="https://user-images.githubusercontent.com/72025738/171852148-666d1e9c-e6e6-40b0-8784-854d4961fb4e.png">
Here is the detail view (nothing important just testing without variables), but the same happens when Im trying to put some variables.
<img width="539" alt="Screenshot 2022-06-03 at 15 19 05" src="https://user-images.githubusercontent.com/72025738/171852465-bc9d4148-fe5f-474c-bb1b-0a123e719ae3.png">

Any help will be highly appreciated.
Thank you in advance!

**Comment by cddoma** [comment]
I'm also experiencing the same problem.

**Comment by luanfreitasdev** [comment]
Hello This is weird. Can you reproduce the error in the power-demo-misc repo?

**Comment by ceh137** [comment]
I will try to do so!

**Comment by ceh137** [comment]
Unfortunately, I wasn't able to reproduce that error. I have no idea why this is happening. I came up with an idea and it helped... there is no such an error now. I just put orderBy() after the select in the builder. 
<img width="872" alt="Screenshot 2022-06-06 at 12 38 13" src="https://user-images.githubusercontent.com/72025738/172136707-8170d1f5-309c-4a0d-936a-e46d44bb1d06.png">
But the other problem appeared.

https://user-images.githubusercontent.com/72025738/172137750-7500fb70-aaad-4ce9-a641-b698db7e9f08.mp4

Really weird...

**Comment by ceh137** [comment]
So, I got a solution. 
Firstly, I had
`public string $primary key = 'orders.id'` 
and 
`select('orders.*')` in builder

And when I changed it to
`public string $primary key = 'id'`
and
`select('orders.id as id')` 
it worked
