### ISSUE TITLE
editOnClick not working

### ISSUE THREAD

**Issue by Ahsan-Sarbaz** [Power-Components/livewire-powergrid#478]
```
 Column::make('Name', 'name')
                ->searchable()
                ->editOnClick()
                ->makeInputText('name')
                ->sortable(),
```
**gives error Property [$name] not found on component: [customer-table]**

**Comment by luanfreitasdev** [comment]
Hi! Thanks for reporting.

Actually this is caused by not having the public property on the component.
I made an improvement in the documentation on this

https://livewire-powergrid.com/#/table/cell-actions-buttons?id=editonclickbool-iseditable

**Comment by macCesar** [comment]
Where do I need to put the `onUpdatedEditable` method ??

I've put it in the component `app/Http/Livewire/MaterialsTable`

```javascript
public ?string $name = null;

public function onUpdatedEditable($id, $field, $value): void
{   
    Material::query()->find($id)->update([
            $field => $value,
    );
}
```

But its trowing this errror:

**`Cannot auto-initialize an array inside property App\Http\Livewire\MaterialsTable::$name of type ?string`**

**Comment by macCesar** [comment]
The only way to make it work is to remove `?string` from the variable name.

Tested on Laravel v9.17.0 and PHP v8.1.6.

**Comment by macCesar** [comment]
**One more thing...**

What's the difference between `Column::add()` and `Column::make()` ??

The docs shows this code?

```php
$canEdit = true; //User has edit permission

Column::add()
  ->title('Name')
  ->field('name'),
  ->editOnClick($canEdit),
```

But the generated component has the `make()` method:

```php
public function columns(): array
{
  return [
    Column::make('NAME', 'name')
      ->sortable()
      ->searchable()
      ->editOnClick(true)
  ];
}
```

I just added the `editOnClick(true)` and the recommended method `onUpdatedEditable` ( minus the `?string` declaration 😉 ) to edit the content inline!! 😀

**Comment by luanfreitasdev** [comment]
Somewhere the variable is counting an array...

**Comment by luanfreitasdev** [comment]
> **One more thing...**
> 
> What's the difference between `Column::add()` and `Column::make()` ??
> 
> The docs shows this code?
> 
> ```
> $canEdit = true; //User has edit permission
> 
> Column::add()
>   ->title('Name')
>   ->field('name'),
>   ->editOnClick($canEdit),
> ```
> 
> But the generated component has the `make()` method:
> 
> ```
> public function columns(): array
> {
>   return [
>     Column::make('NAME', 'name')
>       ->sortable()
>       ->searchable()
>       ->editOnClick(true)
>   ];
> }
> ```
> 
> I just added the `editOnClick(true)` and the recommended method `onUpdatedEditable` ( minus the `?string` declaration 😉 ) to edit the content inline!! 😀

less code only

**Comment by muhammadessam** [comment]
Same here, I can't get it working, for me the column is just a JSON  stored in the database
any help.
@msdos2 
@luanfreitasdev 
@macCesar

**Comment by muhammadessam** [comment]
For me it only worked after I added the array type to the property name in the component
thanks.
