### ISSUE TITLE
Why the need to import Alpine JS?

### ISSUE THREAD

**Issue by jiaoliness** [Power-Components/livewire-powergrid#482]
Livewire itself uses alpine JS to function,  it is included in the compiled scripts and importing alpine again from CDN causes issues. Of course, you can fix it by doing this in the config

`  /*
    |--------------------------------------------------------------------------
    | AlpineJS CDN
    |--------------------------------------------------------------------------
    |
    | Define here the CDN source for imported AlpineJS
    |
    */

    'alpinejs_cdn' => '',`

**Comment by luanfreitasdev** [comment]
Alpine and Livewire are distinct

https://laravel-livewire.com/docs/2.x/alpine-js#installation
