### ISSUE TITLE
Add minimum width to Filter

### ISSUE THREAD

**Issue by thetwopct** [Power-Components/livewire-powergrid#49]
I've noticed that on smaller screens there is no minimum width on filter selects, so they can look like this:

![2021-08-12-134939](https://user-images.githubusercontent.com/10615884/129150847-62d01d10-798b-4a8a-ae95-7863526123a4.jpg)

and on a wider screen:

![2021-08-12-135002@2x](https://user-images.githubusercontent.com/10615884/129150928-ad43bf11-e69a-4848-8702-7211d422b2ec.jpg)

**Comment by luanfreitasdev** [comment]
This solves: `->headerAttribute('class', 'style')`

```
Column::add()
       ->title(__('Em Estoque'))
       ->headerAttribute('', 'min-width: 130px')
       ->toggleable(true, 'sim', 'não')
       ->makeBooleanFilter('in_stock', 'sim', 'não')
       ->field('in_stock'),
```

Result:

![image](https://user-images.githubusercontent.com/33601626/129424061-f227b7c7-c357-4751-8a5f-06c397ce4081.png)
