### ISSUE TITLE
Keep table ID ordered instead of DB record ID

### ISSUE THREAD

**Issue by gopalwebdev** [Power-Components/livewire-powergrid#496]
Hello, In my project, PG Table IDs are displayed as per DB record id . It would be better, if you add a setup function that resets all the IDs and orders from 1. For example, I've 4 record in table. PG Table displays ID like 123, 1999, 2422, 5690. They are actual record ID coming from DB. This is not looking good as an end user perspective. It would be cool, if it's like 1, 2, 3, 4. We don't wanna reveal record ID to end user. Kindly help me to solve this issue. Thank you!
![Screenshot from 2022-07-08 12-37-51](https://user-images.githubusercontent.com/78777044/177937943-1ffc4a66-40d6-4dd5-be8e-768917f123f5.png)

**Comment by luanfreitasdev** [comment]
Hello.

This is currently not possible as powergrid needs an ID for each row to send requests coming from `action buttons, detailRow, actionRules, editOnClick and toggleable.`

Maybe the ideal would be to make a hidden() in the column and show another fake id
```php
public function addColumns(): PowerGridEloquent
{
      return PowerGrid::eloquent()
        ->addColumn('id')
        ->addColumn('fake_id', function () {
           return '...';
        });
}

public function columns(): array
 {
     return [
          Column::add()
              ->title(__('ID'))
               ->field('id')
              ->hidden(),

          Column::add()
              ->title(__('Id'))
              ->field('fake_id'),
        ];
}

```
