### ISSUE TITLE
Toggle button is showing wrong

### ISSUE THREAD

**Issue by joaonivaldo** [Power-Components/livewire-powergrid#497]
#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [X] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [X] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [ ] Yes - I didn't work.
- [X] No, this error is not related to views.

#### Is there an error in the console?
- [ ] Yes - I'll add a screenshot or report it below.
- [X] No

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |       3.2.1            |
| Laravel   |         9.19          |
| Livewire  |          2.10.6         |
| Alpine JS  |         3.10.2          |

### Theme
- [ ] Tailwind 2.x
- [X] Tailwind 3.x
  - [X] With tailwind/forms
- [ ] Bootstrap - Version:        

---
## Describe the bug
The toggle button in the Status column has suddenly changed to this box with YES inside.

**Screenshots**
![image](https://user-images.githubusercontent.com/4040086/178119296-56b6a31e-a347-4178-886a-837e9a341b81.png)

**Comment by luanfreitasdev** [comment]
Hi @joaonivaldo , This happens because powergrid can't toggle a related field, for example categories.name.
