### ISSUE TITLE
Inline editing shows old value when editing for a second time

### ISSUE THREAD

**Issue by thetwopct** [Power-Components/livewire-powergrid#50]
I'm experiencing an issue with inline editing. When editing a value and saving it, then re-editing the value, the original value is shown. Here's a video:

https://user-images.githubusercontent.com/10615884/129152244-8cd4ca67-fdf6-4012-b327-9fb0e317dbf6.mp4

**Comment by luanfreitasdev** [comment]
Hi, it may have to do with alpinejs version. At the moment it doesn't support ^3

**Comment by luanfreitasdev** [comment]
Really this is a problem that I am not able to find the solution with Alpine, even knowing that it is updated with the new value, if you click back to edit it will return the old value in the view.
