### ISSUE TITLE
Bug Report: dropdown css causes offset in BS5 navbar

### ISSUE THREAD

**Issue by akulmehta** [Power-Components/livewire-powergrid#507]
# PowerGrid Bug Report

#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [X] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [X] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [X] Yes - I didn't work.
- [ ] No, this error is not related to views.

#### Is there an error in the console?
- [ ] Yes - I'll add a screenshot or report it below.
- [X] No

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |         V3.2.2          |
| Laravel   |         V9.19.0          |
| Livewire  |        V2.10.6           |
| Alpine JS  |           CDN        |

### Theme
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [X] Bootstrap - Version:        5.1.3

---
## Describe the bug
The dropdown styles is affecting the styling of Bootstrap5 navbar styles. It is causing the line height to become higher. 
See screenshot below.

### What happened?

I expected the navbar to remain in line, but dropdown links were raised higher that the rest.

### To Reproduce...

Create a page with BS5 navbar on the top.

### Suggestions

Change CSS style - I will create a PR for this.

## Extra information

**Screenshots**

![image](https://user-images.githubusercontent.com/42812604/179084868-bd3697c6-ed5d-4546-8f61-f5f899c1071c.png)

As you can see the `Menu` link is higher

**Code snippet**
None

**Comment by luanfreitasdev** [comment]
Thanks!
