### ISSUE TITLE
Composer.lock Issue, Packages Lock with wrong Verion, and not able to install other packges.

### ISSUE THREAD

**Issue by shakeel2717** [Power-Components/livewire-powergrid#515]
# PowerGrid Bug Report

Thank you for reporting a bug and helping us to improve PowerGrid!

## Guidelines

`   🐛 `   We use GitHub Issues exclusively for tracking bugs and unexpected software behavior. 

`   🙏 `  Please use the [Discussions](https://github.com/Power-Components/livewire-powergrid/discussions) tab for questions like _"How to...",_ "_how can I..."_ .

`   ✍️ `  Give this report a short but meaningful title. Make it easy to spot for others who might be facing the same issue.

`   ⚠️ `  Issues that do not describe a bug or do not follow the template will be closed.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [ ] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [1 ] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [ 1] Yes - I didn't work.
- [ ] No, this error is not related to views.

#### Is there an error in the console?
- [1 ] Yes - I'll add a screenshot or report it below.
- [ ] No

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |                   |
| Laravel   |                   |
| Livewire  |                   |
| Alpine JS  |                   |

### Theme
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [ ] Bootstrap - Version:        

---
### What happened?

After Installing Powergird Livewire, everything working fine. but the problem is that i can't install any Excel Import Export Packages. because the composer.lock lock wrong veriosn of some packages.
Laravel Spaite
Problem 1
    - Root composer.json requires spatie/simple-excel ^2.1 -> satisfiable by spatie/simple-excel[2.1.0].
    - spatie/simple-excel 2.1.0 requires openspout/openspout ^3.0 -> found openspout/openspout[v3.4.0, ..., 3.x-dev] but the package is fixed to v4.6.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
Laravel Excel
Problem 1
    - Root composer.json requires phpoffice/phpspreadsheet ^1.24 -> satisfiable by phpoffice/phpspreadsheet[1.24.0, 1.24.1].
    - phpoffice/phpspreadsheet[1.24.0, ..., 1.24.1] require psr/simple-cache ^1.0 || ^2.0 -> found psr/simple-cache[1.0.0, 1.0.1, 2.0.0, 2.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
Problem 1
    - Root composer.json requires rap2hpoutre/fast-excel ^4.0 -> satisfiable by rap2hpoutre/fast-excel[v4.0.0].
    - rap2hpoutre/fast-excel v4.0.0 requires openspout/openspout ^3 -> found openspout/openspout[v3.4.0, ..., 3.x-dev] but the package is fixed to v4.6.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

### To Reproduce...

First click on "FOO" then....

### Suggestions

Do you have any idea how we can fix it?

## Extra information

**Screenshots**

**Code snippet**

```php 
![Screenshot 2022-07-20 012040](https://user-images.githubusercontent.com/79254929/179933642-5d8fdd3f-b681-4cf8-966e-4f83ee258323.jpg)

<?php

//...
```

**Comment by akulmehta** [comment]
Have you tried running `composer require` with the `--with-all-dependencies` option?

**Comment by luanfreitasdev** [comment]
I think the only solution would be fast-excel and simple-excel to support openspout version 4.0 (but this version requires php 8.0).

You can't use openspout to export or do you need to repurpose from other packages?

**Comment by shakeel2717** [comment]
I Just need to import data from Simple:excel, but i can't install any of that package. because powergrid not have import functionality...

**Comment by luanfreitasdev** [comment]
You can use openspout's own layer to import as well, (it's the same as what fast-excel uses) while it's not supported.
