### ISSUE TITLE
View [components\frameworks\tailwind\table-base] not found. 

### ISSUE THREAD

**Issue by andruu** [Power-Components/livewire-powergrid#52]
Can't find the vendor specific files

**Comment by luanfreitasdev** [comment]
Hello, which version are you using?

**Comment by andruu** [comment]
Latest version from composer. Followed the install instructions

**Comment by luanfreitasdev** [comment]
Is the version 1.1.7?
can you send me a screenshot with this error?

**Comment by luanfreitasdev** [comment]
Fix - [v1.2.2](https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.2.2)
