### ISSUE TITLE
Call to undefined method PowerComponents\LivewirePowerGrid\Helpers\Helpers::makeActionRules()

### ISSUE THREAD

**Issue by SushilMore1988** [Power-Components/livewire-powergrid#526]
I have update powergrid to latest version 3.2.3 and I got the above error.
<img width="1440" alt="Screenshot 2022-07-28 at 9 43 13 AM" src="https://user-images.githubusercontent.com/47495634/181418827-da04a55a-ee48-4631-89f8-2329d479de9a.png">

**Comment by Mutembeijoe** [comment]
You have to clear cache `php artisan view:clear`

**Comment by SushilMore1988** [comment]
> You have to clear cache `php artisan view:clear`

No it still shows same error.

**Comment by luanfreitasdev** [comment]
Hello, you have the package published in the resources/views directory, so it doesn't work. Delete the published directory it will work.

**Comment by SushilMore1988** [comment]
> Hello, you have the package published in the resources/views directory, so it doesn't work. Delete the published directory it will work.

Yes it worked. Thank You.

**Comment by Danss0** [comment]
> 

delete what in resources/view ? please help me
