### ISSUE TITLE
Bug Report: Error while opening excel Files- File Damaged

### ISSUE THREAD

**Issue by Stridesdata** [Power-Components/livewire-powergrid#537]
# PowerGrid Bug Report

Thank you for reporting a bug and helping us to improve PowerGrid!

## Guidelines

`   🐛 `   We use GitHub Issues exclusively for tracking bugs and unexpected software behavior. 

`   🙏 `  Please use the [Discussions](https://github.com/Power-Components/livewire-powergrid/discussions) tab for questions like _"How to...",_ "_how can I..."_ .

`   ✍️ `  Give this report a short but meaningful title. Make it easy to spot for others who might be facing the same issue.

`   ⚠️ `  Issues that do not describe a bug or do not follow the template will be closed.

#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [x] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [x] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [ ] Yes - I didn't work.
- [x] No, this error is not related to views.

#### Is there an error in the console?
- [x] Yes - I'll add a screenshot or report it below.
- [ ] No

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |   3.2.5          |
| Laravel   |    8.83.0          |
| Livewire  |      2.10.1       |
| Alpine JS  |       3.16      |
| maatwebsite/excel |   3.1.36 |

### Theme
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [x] Bootstrap - Version:        

---
## Describe the bug

Error while opening excel Files- File Damaged

### What happened?

Good Day,
I upgraded to the latest version and noticed that exported Excel files throws an error when trying to open.

![image](https://user-images.githubusercontent.com/82326559/182291348-0880ef67-7ff3-4728-bcfc-c0f2f598ddb2.png)

. It worked well before the upgrad. Going through your release note, I discovered that you make use of "Export using openspout/openspout". 
I noticed that my issue has a similar open issue in the Openspout repository(see link)
https://github.com/openspout/openspout/issues/90#issue-1291135274.

I dont know if I am missing something. Note CSV works and opens fine, the issue is just with XLSX files

I did FOO expecting BAR as a result. However, I received BAZ...

### To Reproduce...

First click on "FOO" then....

### Suggestions

(Do you have any idea how we can fix it?)

## Extra information

![image](https://user-images.githubusercontent.com/82326559/182291634-ee3f6d29-ab4d-49b4-bf7a-ec385f78b81e.png)

**Code snippet**

```php 
<?php

//...
```

**Comment by luanfreitasdev** [comment]
I don't think there is a solution in the powergrid part for this initially.

openspout v3 would it work?

Maybe we can release a v3-supported version of openspout without necessarily being installed. But this requires a major version .

**Comment by shakeel2717** [comment]
I'm facing same issues since few weeks

**Comment by akulmehta** [comment]
Could you share the version of Excel you are using to open the file, just to check if it is related?

**Comment by Stridesdata** [comment]
Office professional plus 2016

**Comment by luanfreitasdev** [comment]
I'll close this for now as at the moment I can't support two different versions for the same package. Maybe this works in v4
