### ISSUE TITLE
Bug Report: Duplicate SQL queries when many columns searchable within single table

### ISSUE THREAD

**Issue by akulmehta** [Power-Components/livewire-powergrid#538]
#### Have you searched through other issues to see if your problem is already reported or has been fixed?
- [x] Yes - I did not find it.
- [ ] No

#### Did you read the [documentation](https://livewire-powergrid.com/)?
- [x] Yes - I did not find it.
- [ ] No

#### Have you tried to publish the views?

You can publish the views to make sure there is no "old code" trapped in views which are not up-to-date.

To publish, run: `php artisan vendor:publish --tag=livewire-powergrid-views`

- [ ] Yes - I didn't work.
- [x] No, this error is not related to views.

#### Is there an error in the console?
- [ ] Yes - I'll add a screenshot or report it below.
- [x] No

### Software Version

You can run `composer show -i` and `npm list` to list installed package with their versions.

| Software  | Version (exactly) |
|-----------|-------------------|
| PowerGrid |       v3.2.5            |
| Laravel   |        v9.23.0           |
| Livewire  |         v2.10.6          |
| Alpine JS  |          CDN         |

### Theme
- [ ] Tailwind 2.x
- [ ] Tailwind 3.x
  - [ ] With tailwind/forms
- [X] Bootstrap - Version:     5.2.0   

---
## Describe the bug

When several columns are searchable, the package produces duplicate queries to check if the table has columns. 

### What happened?

For each of the columns which are searchable, the package runs a sql query to check if the table has the column similar to 

```
select column_name from information_schema.columns where table_catalog = 'dbname' and table_schema = 'public' and table_name = 'users'
```

I used laravel debugbar to check the number of queries and noticed that this query was being run multiple number of times. This can slow down search performance.

### To Reproduce...

Create a table with many columns searchable. The more the number of columns which are searchable the more queries will be run. 
Use laravel debugbar or other packages to check the number of queries.

### Suggestions

I believe it is the `Model.php` helper file which checks the table has columns within a `for` loop. 

```php
//src>Helpers>Model.php: line 279
                        $hasColumn = Schema::hasColumn($table, $field);
```

Instead of `hasColumn`, maybe  use `Schema::getColumnListing($table)` --> cache this result and reuse it. 

I can make a PR for this.

## Extra information

**Screenshots**

**Code snippet**

```php 
<?php

//...
```

**Comment by luanfreitasdev** [comment]
Hello @akulmehta , this is very useful and seems to solve a search performance issue. 
I will review these days.

Thanks!

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/releases/tag/v3.2.6
