### ISSUE TITLE
Livewire Powergrid : field values  misplaced after search

### ISSUE THREAD

**Issue by punna1138** [Power-Components/livewire-powergrid#548]
"livewire/livewire": "^2.5",
 "power-components/livewire-powergrid": "^2.2",
"laravel/framework": "^9.0",

those are the versions we are using.
![Capture1](https://user-images.githubusercontent.com/16316372/183395196-b99d5d0a-64c2-4eb9-9dd5-601f834f8e12.PNG)

**Comment by akulmehta** [comment]
Have you tried upgrading powergrid to latest release?

**Comment by punna1138** [comment]
yes tried! no luck

**Comment by akulmehta** [comment]
@punna1138 

- what is the version of powergrid you now have?

- could you share more code about how you generate the table and what is the data structure of the table?

**Comment by punna1138** [comment]
-> powergrid version is 2.4.6

 public function datasource(): ?Builder
    {
        return $query = Question::query()->with('type', 'questionCategory')->latest();
    }

public function addColumns(): ?PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ->addColumn('id')
            ->addColumn('question_name', function (Question $model) {
                return Str::words($model->question_name, 7);
            })
            //->addColumn('question_name')
            ->addColumn('question_type', function (Question $model) {
                    return $model->type->name;
            })
            ->addColumn('question_category', function (Question $model) {
                    return $model->questionCategory->category_name;
            })
            ->addColumn('created_at_formatted', function (Question $model) {
                return Carbon::parse($model->created_at)->format('d/m/Y');
            });
    }

**Comment by akulmehta** [comment]
Latest release is on version 3.x. Please see upgrade guide https://livewire-powergrid.com/#/get-started/upgrade-guide

**Comment by luanfreitasdev** [comment]
@punna1138 , Can you update to the latest version and test it?

**Comment by luanfreitasdev** [comment]
closed due to inactivity

**Comment by punna1138** [comment]
working fine with latest updates.
