### ISSUE TITLE
Bug when delete search input text

### ISSUE THREAD

**Issue by nguyentranchung** [Power-Components/livewire-powergrid#56]
![image](https://user-images.githubusercontent.com/9611224/131201328-a12f7e18-819f-4a53-b823-3f24e23417bf.png)

in the status search i will delete

Normal working
ERROR -> ERRO -> ERR -> ER ->  E -> blank

Current working
ERROR -> ERRO -> ERR -> ER ->  blank

 (It doesn't delete 1 character, it deletes 2 characters)

**Comment by luanfreitasdev** [comment]
Can you record a video with the problem?

**Comment by luanfreitasdev** [comment]
This bug has to do with another issue [issue 57](https://github.com/Power-Components/livewire-powergrid/issues/57)
