### ISSUE TITLE
Customize searchbar

### ISSUE THREAD

**Issue by Naagarjunaa** [Power-Components/livewire-powergrid#566]
### Discussed in https://github.com/Power-Components/livewire-powergrid/discussions/565

<div type='discussions-op-text'>

<sup>Originally posted by **Naagarjunaa** August 18, 2022</sup>
Hi Team,
How can I customize the global search bar like added classes to its input and all sort of things..i would like to move toward the right side.

![image](https://user-images.githubusercontent.com/46925151/185271963-5fcfc476-15a5-4648-9946-3a1673a7f77d.png)

Similarly i need to add classes for row count select... kindly help me to achieve that
![image](https://user-images.githubusercontent.com/46925151/185272205-f929b406-1397-4486-b275-6c1546292a88.png)

Thanks for the Lovely Package!!!</div>

**Comment by luanfreitasdev** [comment]
Hello !. I believe you are using an unsupported version of bootstrap.

By default, powergrid is supported in bootstrap 5.0 and is already right aligned.
