### ISSUE TITLE
Search input debounce

### ISSUE THREAD

**Issue by nguyentranchung** [Power-Components/livewire-powergrid#57]
![image](https://user-images.githubusercontent.com/9611224/131201407-d3b87f91-6140-4c9c-80d8-908fb383ef90.png)

For every character I type, a request is sent. it doesn't seem very good in terms of performance

https://laravel-livewire.com/docs/2.x/properties#debouncing-input

**Comment by luanfreitasdev** [comment]
I fixed this and it got better, [v1.2.5](https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.2.5)

Thanks for using PowerGrid
