### ISSUE TITLE
Show Per Page - Não está sendo possível customizar

### ISSUE THREAD

**Issue by gonribeiro** [Power-Components/livewire-powergrid#573]
Olá!

Estou utilizando a ultima versão do Livewire Powergrid.

Ao tentar customizar as opções do ShowPerPage utilizando essa forma:
https://livewire-powergrid.com/#/table/features-setup?id=showperpage
```
class DishesTable extends PowerGridComponent
{
    //Custom per page values
    public array $perPageValues = [10, 50, 100, 1000];

    public function setUp(): array
    {
...
```
Mas não funciona. Simplesmente ele não altera e mantém o padrão já conhecido.

**Comment by akulmehta** [comment]
@luanfreitasdev the docs need to be updated - I have a PR for this

```
class DishesTable extends PowerGridComponent
{
    //Custom per page
    public int $perPage = 5;
    
    //Custom per page values
    public array $perPageValues = [0, 5, 10, 20, 50];

    public function setUp(): array
    {
        return [
            Footer::make()
                ->showPerPage($this->perPage, $this->perPageValues)
        ]   
    }

   ...
```

**Comment by luanfreitasdev** [comment]
Thanks @akulmehta , @gonribeiro now the documentation is fixed!

https://livewire-powergrid.com/#/table/features-setup?id=showperpage
