### ISSUE TITLE
Default makeInputText condition for textFieldOperator

### ISSUE THREAD

**Issue by hemant17** [Power-Components/livewire-powergrid#577]
# ⚡ PowerGrid ⚡ Feature Request

## Summary

while using makeInputText comes with two inputs first Select that contains textFieldOperator switch case which is good but what when we want a single search box without giving the option to select textFieldOperator  like ' Contain, Link etc..'

### Why is this needed?

Single search box for column with textFieldOperator  param so we can search the column without validateInputTextOptions 

### Suggested Solution(s)
replace the 'contains' with a variable that we can pass makeInputText(), which will overwrite the condition or even $this->filters, "input_text_options.$field" set a default for the option
`$textFieldOperator = (validateInputTextOptions($this->filters, $field) ? strtolower(strval(data_get($this->filters, "input_text_options.$field"))) : 'contains');`

### Related issue(s)/PR(s)

NO

**Comment by luanfreitasdev** [comment]
I think this is a nice addition.

**Comment by thanjeys** [comment]
> 

Can you tell me where can i use this ? Mean Files and location Pls ? 

Thanks

**Comment by luanfreitasdev** [comment]
Hello!.

We're thinking about the current structure of filters, maybe there's a big refactoring to allow this. But I already left it in the backlog for version 4. Any PR should be directed to the v4 branch

**Comment by luanfreitasdev** [comment]
Working on this feature. Will be available in version 4

https://github.com/Power-Components/livewire-powergrid/pull/779
