### ISSUE TITLE
[Bug]: xxs problem 

### ISSUE THREAD

**Issue by markgoedegebure** [Power-Components/livewire-powergrid#584]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

No

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

v3.2.6

### Laravel

9.24.0

### Livewire

2.10.7

### Alpine JS

3.10.3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When loading the table with database data xxs is not prevented

### To Reproduce...

Load a table with items where a row value is `<button type=button x-on:click="alert('Hi!');">Click me!</button>`. This gets rendered in the table as a button, which alerts 'Hi!' when clicked. 
![image](https://user-images.githubusercontent.com/44771394/186604927-7585e9c0-0915-4c9c-a433-668ca9385518.png)
![image](https://user-images.githubusercontent.com/44771394/186605146-59a768f9-f802-42ad-bf65-d3a4ea1e733f.png)
![image](https://user-images.githubusercontent.com/44771394/186605327-4d520d92-15b9-42eb-aada-c0a84e2484c5.png)

**Comment by akulmehta** [comment]
@luanfreitasdev I can confirm that this is a security issue xss.

**Comment by akulmehta** [comment]
This happens because values passed in closures are not escaped. We would need to manually escape the strings using laravel `e` helper https://laravel.com/docs/9.x/helpers#method-e

For example:
```php
public function addColumns(): PowerGridEloquent
{
  return PowerGrid::eloquent()
    ->addColumn('location_link', function (Dish $model) {
      return '<a href="https://www.google.com/maps/search/' . e($model->lat_long) . '">'. e($model->location_name) .'</a>'; 
    });
}
```

@luanfreitasdev maybe it is best to update the docs to reflect this requirement and add a security note?

**Comment by luanfreitasdev** [comment]
I remember discussing this some time ago in issue #173 , but it hasn't been documented.

I think it's interesting to include this in the doc since on the powergrid side it can't be done internally because it's dynamic.

@akulmehta , I agree with you.

**Comment by akulmehta** [comment]
@luanfreitasdev created a PR for the docs. But maybe some thought needs to go into a more elegant solution for this for version 4?

**Comment by luanfreitasdev** [comment]
Thanks for the PR, I've merged it. 

I don't have an idea at the moment, but if you have something similar it will definitely go into v4.
