### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rosolovsky** [Power-Components/livewire-powergrid#588]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### PowerGrid

3.2.7

### Laravel

9.26.1

### Livewire

2.10.7

### Alpine JS

3.10.3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

This code generate a link, not a button!

public function header(): array
{
    return [
        Button::add('new-modal')
            ->caption('New window')
            ->class('bg-gray-300')
            ->openModal('new', []),
            
        //...
    ];
}

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v3.2.8
