### ISSUE TITLE
[Bug]: EmitTo Events is not triggered

### ISSUE THREAD

**Issue by thanjeys** [Power-Components/livewire-powergrid#601]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

3.2

### Laravel

8.75

### Livewire

2.5

### Alpine JS

3.0.6

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

Emito Event is not triggering on Action Buttons 

Component File : 
![image](https://user-images.githubusercontent.com/5894531/187435732-ed2ee528-bb09-453e-984a-450797e72349.png)

### To Reproduce...

Pls help me. Thanks 

### Extra information

```markdown
public function actions(): array
    {
       return [
           Button::add('view')
                    ->caption('View')
                    ->class('btn btn-primary')
                    ->emitTo('delivered-items-modal', 'deliveredItems', ['key' => 'id']),

            //    ->class('bg-indigo-500 cursor-pointer text-white px-3 py-2.5 m-1 rounded text-sm')
            //    ->route('', ['deliver' => 'id']),


        //    Button::make('destroy', 'Delete')
        //        ->class('bg-red-500 cursor-pointer text-white px-3 py-2 m-1 rounded text-sm')
        //        ->route('', ['deliver' => 'id'])
        //        ->method('delete')
        ];
    }
```

**Comment by akulmehta** [comment]
Could you right click on the button and inspect the element and share what you are seeing?

**Comment by luanfreitasdev** [comment]
Hello!. Please take a look at this:

https://livewire-powergrid.com/#/table/component-settings?id=event-listeners

**Comment by thanjeys** [comment]
> Could you right click on the button and inspect the element and share what you are seeing?

Hi, 
I am getting this.

<button class="btn btn-primary" title="" wire:click="$emitTo(&quot;delivered-items-modal&quot;, &quot;deliveredItems&quot;, {&quot;key&quot;:1})">
                            View
                        </button>

**Comment by thanjeys** [comment]
> Could you right click on the button and inspect the element and share what you are seeing?

Hi, I am getting this.

`<button class="btn btn-primary" title="" wire:click="$emitTo(&quot;delivered-items-modal&quot;, &quot;deliveredItems&quot;, {&quot;key&quot;:1})">
                            View
                        </button>`

**Comment by dansysanalyst** [comment]
@thanjeys could you please confirm that your characters are not being escaped in your page HTML source?

In other words, when you inspect your page, you see 

`$emitTo("delivered-items-modal"...` 

instead of 

`wire:click="$emitTo(&quot;delivered-items-modal&quot;...`.

--- 

I think your feedback is based on the browser inspection tool copy HTML:
 
<img width="962" alt="CleanShot 2022-09-03 at 15 48 43@2x" src="https://user-images.githubusercontent.com/79267265/188273384-9f9259f9-601f-4716-8210-8745223525d2.png">

which results in :

<img width="701" alt="CleanShot 2022-09-03 at 15 45 49@2x" src="https://user-images.githubusercontent.com/79267265/188273319-966c6be4-6707-46aa-b124-ec3a092b400f.png">

**Comment by dansysanalyst** [comment]
👉 I suggest you to try [LaraDumps](https://github.com/laradumps/laradumps) for a more convenient way to debug Livewire components.


A simple component:

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class DeliveredItemsModal extends Component
{
    protected $listeners = [ 'deliveredItems' ];

    public int $deliveryId = 0;

    public function deliveredItems($data)
    {
        $this->deliveryId = $data['id'];
    }

    public function render()
    {
        return view('livewire.delivered-items-modal');
    }
}
```

Your PowerGrid table:


```php 
<?php 

final class UserTable extends PowerGridComponent
{
    use ActionButton;

    protected function getListeners(): array
    {
        return array_merge(
            parent::getListeners(),
            [
                'deliveredItems',
            ]
        );
    }

//...

    public function actions(): array
    {
        return [
            Button::add('view')
                ->caption('View')
                ->emitTo('delivered-items-modal', 'deliveredItems', ['id' => 'id']),
         ];
    }
```

I've clicked on the "View" button at row ID #1 and as you can see on LaraDumps debug, the component has received this event and data:
 
![CleanShot 2022-09-03 at 18 13 38@2x](https://user-images.githubusercontent.com/79267265/188279252-776318ed-e042-4578-a5ef-6a0f0175c71a.png)

**Comment by thanjeys** [comment]
Hi Dan Ang, 

Thanks for your reply. I did it what you given. But i couldnt find where i am doing mistake. Still its not working. 

![image](https://user-images.githubusercontent.com/5894531/188365912-db107cb2-f585-43e0-81ba-973c546f11bd.png)

`<?php

namespace App\Http\Livewire;

use Livewire\Component;

class DeliveredItemsModal extends Component
{
    public $deliveredId;

    protected $listeners  = ['deliveredItems'];


    function deliveredItems($data)
    {
        ds('hello calling', $data);
    }


    public function render()
    {
        return view('livewire.delivered-items-modal');
    }
}
`
Datatable.php

` protected function getListeners(): array
    {
        return array_merge(
            parent::getListeners(),
            [
                'delivered-items' => 'deliveredItems'
            ]);
    }`

` public function actions(): array
    {
       return [
           Button::add('view')
                    ->caption('View')
                    ->class('btn btn-primary')
                    ->emitTo('delivered-items-modal', 'delivered-items', ['id' => 'id']),
        ];
    }`

Thanks

**Comment by dansysanalyst** [comment]
Hi @thanjeys 

Change `delivered-items` to `deliveredItems` in `emitTo`:

```php 

Button::add('view')
    ->caption('View')
    ->emitTo('delivered-items-modal', 'deliveredItems', ['id' => 'id']), //✅

Button::add('view')
    ->caption('View') 
    ->class('btn btn-primary')
    ->emitTo('delivered-items-modal', 'delivered-items', ['id' => 'id']),  //❌
```

**Comment by thanjeys** [comment]
Hi Dan Ang,

Now it working perfectly. Thank you very much for your effort.

**Comment by dansysanalyst** [comment]
Fantastic! Thank you for using PowerGrid!

Please consider staring ⭐ [PowerGrid](https://github.com/Power-Components/livewire-powergrid) and [LaraDumps](https://github.com/laradumps/laradumps) repositories!

**Comment by thanjeys** [comment]
DONE !!!
