### ISSUE TITLE
QueryBuilder Limit not working

### ISSUE THREAD

**Issue by nguyentranchung** [Power-Components/livewire-powergrid#61]
```php
    public function dataSource()
    {
        return Event::query()->with(['server:id,name', 'user:id,name'])->latest()->limit(1);
    }
```

![image](https://user-images.githubusercontent.com/9611224/131435265-8a36413d-1fd1-461b-8489-65ceba276e7d.png)

**Comment by luanfreitasdev** [comment]
Hello. 

I'll investigate further, and if everything works out, I'll submit a PR

Thanks

**Comment by luanfreitasdev** [comment]
Hi. I see this is a problem related to eloquent itself.

https://github.com/laravel/framework/pull/21984/files

**Comment by Furentes** [comment]
Since the pull request was rejected, what is the solution if one wants to limit the data shown in the table?
