### ISSUE TITLE
Add cursor pointer by default to button in header() method. Now this button without cursor pointer.

### ISSUE THREAD

**Issue by rosolovsky** [Power-Components/livewire-powergrid#611]
# ⚡ PowerGrid ⚡ Feature Request

## Summary

Brief description of what is at stake.

### Why is this needed?

A clear and concise description of the problem.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/request

**Comment by akulmehta** [comment]
Please fill out the subsections in the Feature Request. It is difficult to understand what you are asking to be done.
