### ISSUE TITLE
how to do without the id but another primary key

### ISSUE THREAD

**Issue by Unisolgr14** [Power-Components/livewire-powergrid#615]
### Discussed in https://github.com/Power-Components/livewire-powergrid/discussions/613

<div type='discussions-op-text'>

<sup>Originally posted by **Unisolgr14** September  7, 2022</sup>
Greetings! your team is doing a great job. Powergrid is a fantastic package which makes the work of a coder much easier.while,I have a very small issue: I have my tables without id but with like member_id as an example. so without this id filed Iam unable to use the powergrid as id is use in the order by clause by default.how do I use poweergrid with my own primary key with the id field?</div>

**Comment by dansysanalyst** [comment]
Read guidelines.
