### ISSUE TITLE
Question: why search input always uppercase

### ISSUE THREAD

**Issue by nguyentranchung** [Power-Components/livewire-powergrid#62]
![Screenshot from 2021-09-07 12-28-41](https://user-images.githubusercontent.com/9611224/132280165-4b6664bf-a56e-471a-8910-aebc546dd5ee.png)

**Comment by luanfreitasdev** [comment]
Hi, @nguyentranchung .

By default, all filter fields will come with capital letters, but you can change it using css

Thanks for using powergrid ⚡
