### ISSUE TITLE
Unable to find component: [dish-table]

### ISSUE THREAD

**Issue by codenashwan** [Power-Components/livewire-powergrid#63]
i'm usign laravel 8.x and livewire 2.x 

when i installed livewire in my project i changed `class_namespace` and `view_path` in `config/livewire.php`
by default value on livewire is : 
 
**/config/livewire.php**
```
'class_namespace' => 'App\\Http\\Livewire',
'view_path' => resource_path('views\livewire'),
```

**I've changed to this.** 

```
 'class_namespace' => 'App\\Http\\Controllers',
 'view_path' => resource_path('views'),
```

now when i installed livewire-powergrid ,it gave me a error that it says. `Unable to find component: [dish-table]`

<hr>

### I tested these commands to create
Component Name:
> DishTable

[M]odel or [C]ollection? (default: M):
> M

Model (ex: App\Models\User):
> App\Models\User

Use the based on fillable ? (yes/no) [no]:
> yes

<hr>

### this is my layout : 
![image](https://user-images.githubusercontent.com/35005761/134351007-3b3ebff2-b34a-460f-b8d5-04bac82c5f8a.png)

**Comment by luanfreitasdev** [comment]
* Change to @powerGridStyles
![image](https://user-images.githubusercontent.com/33601626/134421137-84cbf9e9-9965-41e0-b0ae-0c7574c12720.png)

* Try run: php artisan livewire:discover

thanks
