### ISSUE TITLE
[Bug]:  editOnClick does not work if cell is empty

### ISSUE THREAD

**Issue by jpaav** [Power-Components/livewire-powergrid#649]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

v3.4.1

### Laravel

v9.32.0

### Livewire

v2.10.7

### Alpine JS

3.10.3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

I have several records in the table that have certain cells not filled out. In the database they are empty strings. I want to be able to edit these using the editonClick functionality, but because there is no text in the cell it does not open the edit interface when clicked. Other cells in the same column that have text in them already are editable as desired.

### To Reproduce...

Make a table for an eloquent model that has a string field, and make sure that the column is marked editable. Make a model instance with an empty string in that field. That instance's row will not let you edit the empty field. 

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/releases/tag/v3.5.0

**Comment by jpaav** [comment]
Wow! Thank you so much for the extremely quick turnaround on this!
