### ISSUE TITLE
[Bug]: Detail Row entangle error with property 'setUp.detail.state' cannot be found 

### ISSUE THREAD

**Issue by felixmpa** [Power-Components/livewire-powergrid#650]
I am using Laravel 9, Tailwind 3.x. and, get error trying to use Detail Row.

Detail class is already imported in my livewire:

`use PowerComponents\LivewirePowerGrid\Detail;
`

My livewire class with the setUp function:

```
public function setUp(): array
{ 
    return [
        Detail::make()
            ->view('components.detail') //File created in: resources/views/components/detail.blade.php 
            ->options(['name' => 'Luan'])
            ->showCollapseIcon(),
    ];
}
```

Console error browser:

`SupportAlpine.js:175 Livewire Entangle Error: Livewire property 'setUp.detail.state.' cannot be found`

**Comment by luanfreitasdev** [comment]
Please read issue guidelines.

**Comment by felixmpa** [comment]
Updated, please could you give me any idea to solve it?

**Comment by luanfreitasdev** [comment]
How is $primaryKey defined?

**Comment by felixmpa** [comment]
Yes, thank you very much.! 

You are right I was calling my $primaryKey as 'TableA.ID to avoid ambiguous select **Id** with the inner join on TableB.

So, the error stop after removed **$primaryKey = "TableA.id"** to **$primaryKey = ".id"**

```
public string $primaryKey = "id"; 
public string $sortField = "id";
```

The datasources:

```
public function datasource(): Builder { 
 $data = TablaA::query();
 $data = $data->select('TableA.id', 'TableA.name', 'TableB.id as table_id');
 $data = $data->join('TableB', function($relation) {
       $relation->on('TablaA.id', '=', 'TableB.id');
 };
return $data; 
}
```
