### ISSUE TITLE
[Bug]: export option is not working

### ISSUE THREAD

**Issue by MuhammadTanvir** [Power-Components/livewire-powergrid#654]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

![image](https://user-images.githubusercontent.com/16465865/194281026-6732a5b5-81a4-44ef-91f9-da900c358683.png)

### PowerGrid

3.x

### Laravel

8.x.x

### Livewire

2.x.x

### Alpine JS

3.x.x

### Theme

Bootstrap

### Describe the bug.

I have more than 1400000 data. When I tried to export all the data, the export is not working and find a blank window with the error message` Failed to load resource: the server responded with a status of 500 ()`  on the console but actaully  I found there is no details of that message  on the network dev tool of the browser. And when I tried to export only selected data I found an empty file as an exported document

**Comment by luanfreitasdev** [comment]
Hello, we suggest using queues to export this amount of data.
Also check if the server can handle it, amount of php memory

https://livewire-powergrid.com/#/table/queue-export
