### ISSUE TITLE
[Bug]: Getting Error on inputMultiselect

### ISSUE THREAD

**Issue by thanjeys** [Power-Components/livewire-powergrid#659]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes
![image](https://user-images.githubusercontent.com/5894531/194559410-aa17bb2a-1534-4592-ad26-53f945a27fed.png)

### PowerGrid

3.2

### Laravel

8.75

### Livewire

2.5

### Alpine JS

3.0.6

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

Hi, 

I have included MakeinputMultiselect option. When i select Text box, i am getting error  on console log. 

Thanks 

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello.

I believe we've seen this kind of problem, are you using alpine import inside the config ? Maybe it's duplicating Alpine calls
