### ISSUE TITLE
Undefined array key when using withSum, withCount, withAvg, withMax or withMin

### ISSUE THREAD

**Issue by markgoedegebure** [Power-Components/livewire-powergrid#667]
When using any of the functions: withSum, withCount, withAvg, withMax or withMin, an error occurs saying undefined array key. The undefined key is the given name of the field specified for the column. 

These functions also seems to lack an option to format the sum result with a callback function as possible in the addColumns() function.

**Comment by luanfreitasdev** [comment]
Hello. This doesn't seem to be common. Can you show a screenshot of the error version you are using following the issue opening guide?
