### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by apt42541** [Power-Components/livewire-powergrid#672]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

No

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### PowerGrid

power-components/livewire-powergrid  v2.4.13

### Laravel

laravel/framework                    v8.83.23 

### Livewire

livewire/livewire                    v2.10.7  

### Alpine JS

-

### Theme

Tailwind 3.x

### Describe the bug.

i can't find ways to make action button in same td 
![image](https://user-images.githubusercontent.com/12625408/196931143-f6fbda61-762b-4dd6-818f-b07af2d888a1.png)

### To Reproduce...

![image](https://user-images.githubusercontent.com/12625408/196931201-f5455a76-c58b-4cc3-8cde-dd55cde4f9b0.png)

### Extra information

```markdown
public function actions(): array
    {
       return [
           Button::add('info')
               ->caption(__('Click me'))
               ->class('bg-indigo-500 hover:bg-indigo-600 cursor-pointer text-white px-3 py-2 text-sm rounded-md')
               ->emit('rowActionEvent', ['id' => 'id']),
           Button::add('info')
               ->caption(__('Click me'))
               ->class('bg-indigo-500 hover:bg-indigo-600 cursor-pointer text-white px-3 py-2 text-sm rounded-md')
               ->emit('rowActionEvent', ['id' => 'id']),
        ];
    }
```

**Comment by luanfreitasdev** [comment]
In the last version the buttons are in the same td

![image](https://user-images.githubusercontent.com/33601626/197349745-6f03189d-2efc-4ce3-97b1-2b48225b27f9.png)
