### ISSUE TITLE
[Bug]: duplicate query when changing showPerPage

### ISSUE THREAD

**Issue by damaskus92** [Power-Components/livewire-powergrid#677]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### Theme

Tailwind 3.x

### Describe the bug.

I apologize for the English I use.

The problem I'm having right now is that when I set `showPerPage()` to `showPerPage(0)`, I get duplicate queries. But when I revert back to `showPerPage()` it's back to normal.

![Screenshot from 2022-10-26 13-25-13](https://user-images.githubusercontent.com/53900364/197953332-398c9ebd-a86b-44de-83e6-e0c2274a1d3c.png)

![Screenshot from 2022-10-26 13-24-44](https://user-images.githubusercontent.com/53900364/197953328-326e4c54-8081-4d66-a959-68034694f8c0.png)

**Comment by luanfreitasdev** [comment]
Hello. I tried to simulate here but I couldn't reproduce the problem

![image](https://user-images.githubusercontent.com/33601626/198830679-f1d48163-6136-4ed8-a550-67bb39beb4cf.png)
