### ISSUE TITLE
min and max

### ISSUE THREAD

**Issue by riyasmuviereck** [Power-Components/livewire-powergrid#695]
# ⚡ PowerGrid ⚡ Feature Request

## Summary

Brief description of what is at stake.

### Why is this needed?

A clear and concise description of the problem.

### Related issue(s)/PR(s)

Let us know if this is related to any issue/request

**Comment by luanfreitasdev** [comment]
Issue without description

**Comment by riyasmuviereck** [comment]
my issue was min and max search and datepicker filters was not working in powergrid. for me

**Comment by luanfreitasdev** [comment]
Can you open a new issue showing more details, what errors appear and screenshots if possible?
