### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by riyasmuviereck** [Power-Components/livewire-powergrid#696]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No errors in console

### PowerGrid

3.5.8

### Laravel

9.37.0

### Livewire

2.10.7

### Theme

Bootstrap

### Describe the bug.

I had done join in query in powergrid ,thats why searches and filter were not working in my powergrid table like min and max,datepicker search and general search also not working.in debugbar query was executing which was getting correctly values in phpmyadmin I upgraded powergrid till not working pls help me to solve the issue

### To Reproduce...

First click on "FOO" then.... 
![Screenshot (83) (1)](https://user-images.githubusercontent.com/107984420/199035252-b32277c8-21b7-4a2a-84dd-715ecd553d54.png)
![Screenshot (84) (1)](https://user-images.githubusercontent.com/107984420/199035258-6e7c5817-e3b6-4a0a-bef3-f63f49781310.png)
![Screenshot (82) (1)](https://user-images.githubusercontent.com/107984420/199035263-379ab0bf-7819-40db-8425-0789f301b666.png)
![Screenshot (79) (1)](https://user-images.githubusercontent.com/107984420/199035266-14fc078a-a540-4c7c-801e-741ba33815c6.png)
![Screenshot (80) (1)](https://user-images.githubusercontent.com/107984420/199035268-a7f679a8-dba8-4ede-83c7-d49c71ba32eb.png)
![Screenshot (81) (1)](https://user-images.githubusercontent.com/107984420/199035274-e3752291-30c4-4441-bd96-6e62d3eade1a.png)

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello. I still haven't been able to reproduce this problem.

**Comment by riyasmuviereck** [comment]
thanks i sorted out that problem

**Comment by luanfreitasdev** [comment]
Hello. Can you share the solution?
