### ISSUE TITLE
[Bug]: error editonclick

### ISSUE THREAD

**Issue by alexandergziresis** [Power-Components/livewire-powergrid#699]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### PowerGrid

3.5.9

### Livewire

9.38

### Theme

Tailwind 3.x

### Describe the bug.

I install demo app, when i try to edit price a get error:  Property [$price] not found on component: [dishes-table]

### To Reproduce...

Click and edit price from demo app

### Extra information

```markdown
public function inputTextChanged(array $data = []): void
    {
        $id         = $data['id'];
        $field      = $data['field'];
        $this->{$field}[$id] = $data['value'];
        $this->onUpdatedEditable($id, $field, $data['value']);
        $this->dispatchBrowserEvent('pg:editable-close-' . $id);

    }
```

**Comment by luanfreitasdev** [comment]
You need to define a public property of type array in your component with the name $price

https://livewire-powergrid.com/#/table/cell-actions-buttons?id=editonclickhaspermission-true-fallback-type-here-saveonmouseout-false

![image](https://user-images.githubusercontent.com/33601626/199445570-fa5f70f4-9b06-482b-87b8-c7f65234ac4c.png)
