### ISSUE TITLE
[Bug]: Exporting collection ( Call to undefined method stdClass::withoutRelations() )

### ISSUE THREAD

**Issue by mukize** [Power-Components/livewire-powergrid#702]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes - I'll add a screenshot or report it below.

### PowerGrid

v3.5.9

### Laravel

8.83.25

### Livewire

2.10

### Alpine JS

3.x.x

### Theme

Tailwind 3.x

### Describe the bug.

Tried to export-all the table. Threw back this error. Thought it was only an issue with my custom table until I tried it again with the default created one. Theses were both tables made using collections.

Error: Call to undefined method stdClass::withoutRelations();
power-components\livewire-powergrid\src\Services\Export.php on line 59

### To Reproduce...

create a powergrid table via the console with a collection datasource. Add the table to a blade and try to export-excel-all

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/releases/tag/v3.5.10
