### ISSUE TITLE
[Bug]: htmlspecialchars(): Argument #1 ($string) must be of type string, array given

### ISSUE THREAD

**Issue by aymanalhattami** [Power-Components/livewire-powergrid#708]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### PowerGrid

3.5

### Laravel

9.0

### Livewire

3.10

### Alpine JS

3.10.3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

I am using [Spatie transalation package](https://spatie.be/docs/laravel-translatable/v6/introduction) for supporting multi-language. 
This package make value of column as json like this 👇
![image](https://user-images.githubusercontent.com/34315778/200060035-780f5d8e-ad3a-4df9-a395-963f6c5aa121.png)

When filtering by this columns, I got this error 👇
![image](https://user-images.githubusercontent.com/34315778/200059488-9145cbba-136b-44be-ac21-fa527ee07a16.png)

**Comment by luanfreitasdev** [comment]
Maybe in that case you can remove the e() function inside addColumn

```php
->addColumn('dish_name', function (Dish $dish) {
    return e($dish->name);
})
```
To:
```php
->addColumn('dish_name', function (Dish $dish) {
    return $dish->name;
})
```

**Comment by luanfreitasdev** [comment]
Closed for lack of response. Please if the problem persists, open another Issue
