### ISSUE TITLE
Create blade file for each component created by PowerGrid

### ISSUE THREAD

**Issue by aymanalhattami** [Power-Components/livewire-powergrid#709]
# ⚡ PowerGrid ⚡ Feature Request

## Summary

It's better that each component created by powergrid has its own blade file

### Why is this needed?

It will be good for customizing each component independent of other components

### Suggested Solution(s)

When creating new component by powergird, create two files, php file and blade file

**Comment by luanfreitasdev** [comment]
Hello. Thanks for the suggestion. But this would add more complexity to the developer and possibly break between an updated version in the package and the installed version.

Today it is possible to change some things like theme and add components between the layout

- https://livewire-powergrid.com/#/custom-theme
- https://livewire-powergrid.com/#/table/features-setup?id=includeviewontop
- https://livewire-powergrid.com/#/table/features-setup?id=includeviewonbottom
- https://livewire-powergrid.com/#/table/features-setup?id=includeviewontop-1
- https://livewire-powergrid.com/#/table/features-setup?id=includeviewonbottom-1
