### ISSUE TITLE
[Bug]: Theme actions tdBodyClass/tdBodyStyle is not being utilized in the actions.blade.php

### ISSUE THREAD

**Issue by illia-sapryga** [Power-Components/livewire-powergrid#724]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

3.5.1

### Laravel

9.40.1

### Livewire

2.10.7

### Alpine JS

3.10.5

### Theme

Tailwind 3.x

### Describe the bug.

Theme actions tdBodyClass/tdBodyStyle is not being utilized in the actions.blade.php. It is pretty straight forward if you go to the Actions.php class you will see there is tdBody function so I am assuming that is to style the actions td. Once you open actions.blade.php you will see there is a line `<td class="pg-actions {{ $theme->table->tdBodyClass }}"` which does not utilize actions td styles, but it uses regular table styles.

### To Reproduce...

Go to Actions.php class and go to actions.blade.php and you will quickly understand.

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello!. Sorry but I don't understand the problem
