### ISSUE TITLE
[Bug]: Deleting a row on the last page where theres only 1 row makes the pagination dissapear and you are forced to refresh page to get the other DATA

### ISSUE THREAD

**Issue by BenOussama180** [Power-Components/livewire-powergrid#727]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### PowerGrid

v3.2.7

### Laravel

v9.6.0

### Livewire

v2.10.5

### Alpine JS

3.9.5

### Theme

Tailwind 3.x, Tailwind 3.x with tailwind/forms

### Describe the bug.

i had the last page in my powergrid table where was only 1 row appearing in that last page, when i deleted that row using the action button, the table became empty, no paginationn buttoon  to go back to page 1 , nnothing to do , the onnly way to see the left data is to refresh page

### To Reproduce...

make sexeral pages in poowergrid, having only 1 row shown in the last page , delete that row using actionn button nothing will be shown in the table nor pagination buttons

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello!. Do you have any idea how to fix this situation?

**Comment by BenOussama180** [comment]
it is the same bug that happens when you are on page 3 for example and you change per page values to 100 for example , everything gets lost , and no i havent went deep in the source code to see how it could fixed

**Comment by BenOussama180** [comment]
@luanfreitasdev why not hide the show per page dropdown when changing page ? and only showing it at the first page of the table

**Comment by luanfreitasdev** [comment]
@BenOussama180 , can you test this branch ?
https://github.com/Power-Components/livewire-powergrid/pull/751

**Comment by BenOussama180** [comment]
> @BenOussama180 , can you test this branch ? #751

i didnt get how to composer install that specific branch , how can i do it so ican test ?

**Comment by luanfreitasdev** [comment]
Can you copy the changes inside the vendor?

**Comment by BenOussama180** [comment]
> Can you copy the changes inside the vendor?

i tried  that yesterday i encoutered some issues i'll expirement with it more this night after work
