### ISSUE TITLE
[Bug]: When using "Detail Row", and sorting, get error: "Livewire encountered corrupt data when trying to hydrate"

### ISSUE THREAD

**Issue by mariusdatakrag** [Power-Components/livewire-powergrid#733]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes, 500 error on post when you click on die view details arrow

### PowerGrid

3.5.3

### Laravel

9.36.4

### Livewire

2.10.7

### Alpine JS

^3.10.2

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

I clicked on the "View details" chevron arrow and expect to view the details of the row.  I got the following error "Livewire encountered corrupt data when trying to hydrate the component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests."

When I removed the order By either from the "datasource" or from 
 defining the sort
    public string $sortField = 'name';    
    public string $sortDirection = 'desc';

Then it works, as soon as I add on the orderBy back it gives me the error

### To Reproduce...

--Add sort columns:
    public string $sortField = 'name';
    public string $sortDirection = 'desc';

--Add Detail to the power grid
    public function setUp(): array
    {
             return [
            Detail::make()
                ->view('livewire.view-detail')
                ->showCollapseIcon(),
            Header::make()
                ->showToggleColumns()
                ->showSearchInput(),
            Footer::make()
                ->showPerPage()
                ->showRecordCount(),
        ];
    }

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
hello, This problem has been fixed

https://github.com/Power-Components/livewire-powergrid/pull/716

**Comment by mariusdatakrag** [comment]
Thanks
