### ISSUE TITLE
Easy way to make a button icon

### ISSUE THREAD

**Issue by marccoadou** [Power-Components/livewire-powergrid#741]
# ⚡ PowerGrid ⚡ Feature Request

## Summary

This would make adding an icon to a button a simple task

### Why is this needed?

It would make the syntax cleaner

### Suggested Solution(s)

Add a 3rd parameter to the make method that defaults to null
`public static function make(string $action, string $caption, string $icon = null): self`

**Comment by luanfreitasdev** [comment]
Hello!, I don't think it makes much sense because the buttons are dynamic and don't depend on a icon
