### ISSUE TITLE
html_entity_decode(): Passing null to parameter #1

### ISSUE THREAD

**Issue by abdop** [Power-Components/livewire-powergrid#745]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

![image](https://user-images.githubusercontent.com/46269677/204991018-fd02f907-1ded-403c-868a-e6c5cb7914ef.png)
LOG.warning: html_entity_decode(): Passing null to parameter #1 ($string) of type string is deprecated

### PowerGrid

3.5.12

### Laravel

9.21.6

### Livewire

2.10.7

### Alpine JS

3.10.15

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

I'm using php version 8.1.8, and I'm receiving a log warning 
**LOG.warning: html_entity_decode(): Passing null to parameter 1 ($string) of type string is deprecated**
even when using the demo project. 
This warning comes from the usage of html_entity_decode() function in php version above 8.1 with a null parameter. 
This function is used [here](https://github.com/Power-Components/livewire-powergrid/blob/e3748a23f639e091357220cec639de782a853d0a/resources/views/components/editable.blade.php#L14) https://github.com/Power-Components/livewire-powergrid/blob/e3748a23f639e091357220cec639de782a853d0a/resources/views/components/editable.blade.php#L14
  

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by abdop** [comment]
the [Durpal](https://www.drupal.org/project/csv_serialization/issues/3272884) team has encoutered the same issue, and they choose to cast variable to string to ensure a valid type.
https://www.drupal.org/project/csv_serialization/issues/3272884

**Comment by luanfreitasdev** [comment]
Thanks for the report. Fixed, awaiting bugfix release
