### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by nurizzatie** [Power-Components/livewire-powergrid#784]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

3.5

### Laravel

9.11

### Livewire

2.10

### Alpine JS

3

### Theme

Bootstrap

### Describe the bug.

![Screenshot (2)](https://user-images.githubusercontent.com/89720559/210031187-c5853a5b-8cc0-4fc6-bf31-49be83eca4f2.png)

Hye, I'm having a problem to export selected excel/csv since I'm joining with another table call Item. The error show as above. Hope you can help me how to resolve this problem. Thank you. 

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
Here is my datasource declaration:

public function datasource(): Builder
    {
        return Record::query()
            ->join('items', function ($items) {
                $items->on('records.item_id', '=', 'items.id');
            })
            ->select([
                'records.*',
                'items.description as item_name',
                'items.item_code as item_code'
            ]);
    }
```

**Comment by quaxxon** [comment]
This is an SQL error and not powergrid as such.

Because your joining 2 tables, there are 2 tables with ID columns and powergrid doesn't know which one to use.

I solved this for myself just by selecting every column I needed

<code>
->select([
                'records.id',
                'records.something',
</code>

**Comment by nurizzatie** [comment]
Thank you for replaying. I have found the solution which is we need to add this to avoid key conflict as said in documentation like this:

public string $primaryKey = 'records.id';

Thank you. I will close the issues.
