### ISSUE TITLE
[Bug]: Responsive Text Edit

### ISSUE THREAD

**Issue by ipeterlow** [Power-Components/livewire-powergrid#804]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

No

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

last version

### Laravel

8.83.27

### Theme

Tailwind 3.x

### Describe the bug.

Fields that are active for editing are not responsive to "dots". I have checked the documentation but it does not appear how to solve it. I'm with the Tailwind theme.

<img width="726" alt="Captura de pantalla 2023-01-11 a la(s) 11 33 43" src="https://user-images.githubusercontent.com/38480397/211833962-67555444-c379-46e7-9f97-b97d7daced19.png">

I am looking for the points to be responsive to the text

<img width="671" alt="Captura de pantalla 2023-01-11 a la(s) 11 38 24" src="https://user-images.githubusercontent.com/38480397/211834492-e57ac693-cec5-4203-80ec-c2e736ffc667.png">

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Thank you for reporting the issue!

Fixed in version 3.6.1

**Comment by ipeterlow** [comment]
Hello @luanfreitasdev , Update to the new version 3.6.1. solving the problem that I left in the post but a new one appeared. where a double entry box appears when editing the fields I opened a new post

https://github.com/Power-Components/livewire-powergrid/issues/811
