### ISSUE TITLE
[Bug]: When remove filter date, flatpickr not reset

### ISSUE THREAD

**Issue by zamcoder** [Power-Components/livewire-powergrid#808]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

v3.6.1

### Laravel

v9.47.0 

### Livewire

v2.10.8

### Alpine JS

3.10.3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

when i use date pickr filter , after remove filter flatpickr won't reset

here i attachted the video

sorry for my bad english

https://user-images.githubusercontent.com/76896394/212266908-1a07869f-d82d-4861-bb84-599173d988cc.mp4

### To Reproduce...

use filter date and remove filter

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Fixed on [v4](https://github.com/Power-Components/livewire-powergrid/pull/825)
