### ISSUE TITLE
[Bug]: Clear range input not working with column ID with joins

### ISSUE THREAD

**Issue by edux04** [Power-Components/livewire-powergrid#809]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

3.5.13

### Laravel

9.46.0

### Livewire

2.10.8

### Alpine JS

3.10.3

### Theme

Tailwind 3.x

### Describe the bug.

First of all, thank you for this wonderful package,

I am facing a problem when I want to clean the filter of a "makeInputRange"), after making a filter and wanting to clean it, the table remains with the filter applied and I have to reload the page to delete it, this does not happen to me with another filter of this one type on other fields, only on the id field of all tables.

### To Reproduce...

Create a table with inner join like the second image and add a "makeInputRange" filter to the id column, then try to clear the filter like the first image, the filter will be removed visually but the table still shows only the filtered fields

![imagen](https://user-images.githubusercontent.com/73184362/212318794-28706649-4b1e-46f8-b395-9852e2766321.png)
![imagen](https://user-images.githubusercontent.com/73184362/212319493-78f9cf92-ae46-4c6d-95a3-0287a9fe24ee.png)

![imagen](https://user-images.githubusercontent.com/73184362/212319415-0b1fd12a-ecc6-4694-9b12-0ec505559ee0.png)

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Fixed on v3.7.2
