### ISSUE TITLE
Class "Composer\Factory" not found

### ISSUE THREAD

**Issue by bounty12** [Power-Components/livewire-powergrid#810]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes

     __     ____                          ______     _     __
    / /_,  / __ \____ _      _____  _____/ ____/____(_)___/ /
    /_ ,' / /_/ / __ \ | /| / / _ \/ ___/ / __/ ___/ / __  / 
    /'   / ____/ /_/ / |/ |/ /  __/ /  / /_/ / /  / / /_/ /  
        /_/    \____/|__/|__/\___/_/   \____/_/  /_/\__,_/     

   Error 

  Class "Composer\Factory" not found

  at E:\wamp64\www\Voice4u\root\vendor\power-components\livewire-powergrid\src\Helpers\InteractsWithVersions.php:28
     24▕      * @return array
     25▕      */
     26▕     public function ensureLatestVersion(): array
     27▕     {
  ➜  28▕         $composer  = Factory::create(new NullIo(), null, false);
     29▕         $localRepo = $composer->getRepositoryManager()->getLocalRepository();
     30▕ 
     31▕         return $this->searchPackage($localRepo);
     32▕     }

### PowerGrid

3.5

### Laravel

9.19

### Livewire

2.5

### Alpine JS

3.0.6

### Theme

Bootstrap

### Describe the bug.

when running
php artisan powergrid:create
console show error

### To Reproduce...

after Installing and configuring powergrid
set
'check_version' => true,
in config/livewire-powergrid.php

then run
php artisan powergrid:create
you will get the error

### Extra information

```markdown
if it is set to false it works fine
'check_version' => false,
```
And lastly thanks a lot for this wonderfull package

**Comment by dansysanalyst** [comment]
Hi @bounty12,

You need to require composer as a developer dependency as indicated in the [documentation](https://livewire-powergrid.com/get-started/configure.html#_7-filters).

Run the command below and try again:   

```shell
composer require composer/composer --dev
```

It should solve the problem! 🙂

________
⭐ Enjoying PowerGrid? Please consider Starring the repository!
📢 Share PowerGrid with your dev-community, friends and colleagues: Tweet, write a blog, record review video. 
👥 PowerGrid is open-source, entirely developed and maintained by the author and the contributors.
