### ISSUE TITLE
[Bug]: Doble input updateedit

### ISSUE THREAD

**Issue by ipeterlow** [Power-Components/livewire-powergrid#811]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

3.6.1

### Theme

Tailwind 3.x

### Describe the bug.

Hello Luan, After the new update of the fixed problem of the responsive points. I got the following bug.

when clicking to edit two input cells appear. being that only one should appear.

I stay tuned if there is a new configuration that can fix this problem or with a new version solving this problem.

<img width="733" alt="Captura de pantalla 2023-01-15 a la(s) 19 03 55" src="https://user-images.githubusercontent.com/38480397/212569584-eb0b1032-950c-4cad-b951-8222b4446560.png">

**Comment by luanfreitasdev** [comment]
Fixed: https://github.com/Power-Components/livewire-powergrid/releases/tag/v3.6.2
