### ISSUE TITLE
[Bug]: When Enter on 2nd page and change number of rows displays nothing

### ISSUE THREAD

**Issue by peroxovy** [Power-Components/livewire-powergrid#818]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

3.5.3 

### Laravel

9.36.4

### Livewire

2.10.7

### Theme

Tailwind 3.x

### Describe the bug.

When displaying data in your datatable, which is paginated ( limit 10 per page), when I go into f.e. 2nd page of datatable and select amount of showed records to all or other number, datatable becames empty and shows `No records found`.

Also the footer dissappears, and there's no possibility to switch the pagination.

Please check the issue, I've published the vendors while installation of your library.

**Comment by luanfreitasdev** [comment]
I don't understand the problem, can you record a video?

**Comment by tahaRazaTalibi** [comment]
On 2nd page of pagination when we select to show all items it shows nothing.
![image](https://github.com/Power-Components/livewire-powergrid/assets/22843226/a696732b-304e-4f6d-bf06-625868dd299c)
![image](https://github.com/Power-Components/livewire-powergrid/assets/22843226/648ee95e-9b8d-4341-a52c-26f2a925ee4e)
![image](https://github.com/Power-Components/livewire-powergrid/assets/22843226/0b0adda4-e986-4756-ab06-9d9095c990d1)
![image](https://github.com/Power-Components/livewire-powergrid/assets/22843226/8531901e-d0d2-4af5-95ac-37f0e9ad5310)
