### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Unisolgr14** [Power-Components/livewire-powergrid#823]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

3.2

### Laravel

9.19

### Livewire

2.5

### Alpine JS

3.0.6

### Theme

Tailwind 2.x

### Describe the bug.

The pagination are not working. neither the dropdown or the page number buttons are not working. The show/hide columns button are also not working. It use to work well before 1 month ago. The project was running fine but today when I check it is not working

### To Reproduce...

To reproduce I actually do not know what and where it is wrong as it was working fine and it is not working now. Sorry for this.
This is powergrid file
`<?php

namespace App\Http\Livewire;
use App\Http\Controllers\Approvals\MemApprovalController as memApproval;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Auth;
use App\Models\Member;
use App\Models\Parameter;
use Illuminate\Support\Carbon;
use Illuminate\Database\Eloquent\Builder;
use PowerComponents\LivewirePowerGrid\Rules\{Rule, RuleActions};
use PowerComponents\LivewirePowerGrid\Traits\ActionButton;
use PowerComponents\LivewirePowerGrid\{Button, Column, Exportable, Footer, Header, PowerGrid, PowerGridComponent, PowerGridEloquent};

final class MemberList extends PowerGridComponent
{
    use ActionButton;

    /*
    |--------------------------------------------------------------------------
    |  Features Setup
    |--------------------------------------------------------------------------
    | Setup Table's general features
    |
    */
    public int $perPage = 20;
    public array $perPageValues = [0, 5, 10,15, 20,25, 50,100];

    public string $primaryKey = 'members.member_id';

    public string $sortField = 'members.member_id';

    public function setUp(): array
    {
        // $this->showCheckBox();

        return [
            Exportable::make('MemberList_'.date('Ymdhhmm').'_by_'.Auth::user()->display_as)
                // ->striped()
                ->type(Exportable::TYPE_XLS, Exportable::TYPE_CSV),
            Header::make()
                ->showSearchInput()
            ->showToggleColumns()
            ->includeViewOnTop('components.datatable.header-top')
            ,
            Footer::make()
                ->showPerPage($this->perPage,$this->perPageValues)
                ->showRecordCount()
                ,
        ];
    }

    /*
    |--------------------------------------------------------------------------
    |  Datasource
    |--------------------------------------------------------------------------
    | Provides data to your Table using a Model or Collection
    |
    */

    /**
    * PowerGrid datasource.
    *
    * @return Builder<\App\Models\Member>
    */
    public function datasource(): Builder
    {
        //dd(Member::query());
        //Member::refresh();
        return Member::query()
        ->select(
            'members.*',
          DB::raw("  CONCAT(
    `first_name`,
    if(trim(`middle_name`) = ''or isnull(`middle_name`), '', concat(' ', `middle_name`)),
    if(trim(`last_name`) = '' or isnull(`last_name`), '', concat(' ', `last_name`))
  ) as full_name"),
          )
        ->addselect(['qualification1'=>Parameter::select('para_name')
    ->whereColumn('para_id','members.qualification')
    ->where('para_type','=','qualification')])
    ->addselect(['income'=>Parameter::select('para_name')
    ->whereColumn('para_id','members.income')
    ->where('para_type','=','income')])
    ->addselect(['marital_status'=>Parameter::select('para_name')
    ->whereColumn('para_id','members.marital_status')
    ->where('para_type','=','marital')])
    ->addselect(['occupation'=>Parameter::select('para_name')
    ->whereColumn('para_id','members.occupation')
    ->where('para_type','=','occupation')])
    ->addselect(['care_of_rel'=>Parameter::select('para_name')
    ->whereColumn('para_id','members.care_of_rel')
    ->where('para_type','=','relationship')])
    ->addselect(['nominee_rel'=>Parameter::select('para_name')
    ->whereColumn('para_id','members.nominee_rel')
    ->where('para_type','=','relationship')])
        ->orderBy('member_id')
        ->wherein('status',['1','2'])

        // ->where('first_name','like','Lai')
        // ->orwhere('status','=','2')
        
    ;
    }

    /*
    |--------------------------------------------------------------------------
    |  Relationship Search
    |--------------------------------------------------------------------------
    | Configure here relationships to be used by the Search and Table Filters.
    |
    */

    /**
     * Relationship search.
     *
     * @return array<string, array<int, string>>
     */
    public function relationSearch(): array
    {
        return [];
    }

    /*
    |--------------------------------------------------------------------------
    |  Add Column
    |--------------------------------------------------------------------------
    | Make Datasource fields available to be used as columns.
    | You can pass a closure to transform/modify the data.
    |
    */
    public function addColumns(): PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ->addColumn('id')
            ->addColumn('member_id')
             ->addColumn('meeting_id')
            ->addColumn('first_name')
            ->addColumn('middle_name')
            ->addColumn('last_name')
            ->addColumn('full_name')
            ->addColumn('dob_formatted', fn (Member $model) => Carbon::parse($model->dob)->format('d/m/Y H:i:s'))
            ->addColumn('mobile')
             ->addColumn('alt_mobile')
            ->addColumn('aadhaar_no')
            ->addColumn('marital_status')
            ->addColumn('qualification')
            ->addColumn('occupation')
            ->addColumn('income')
            ->addColumn('doj_formatted', fn (Member $model) => Carbon::parse($model->doj)->format('d/m/Y H:i:s'))
           
            ->addColumn('address_formated',function(Member $model){
            return Str::words(e($model->address),4);
           })
           ->addColumn('Pincode')
            ->addColumn('post_office')
            ->addColumn('district')
            ->addColumn('no_of_dependents')
            ->addColumn('police_station')
            ->addColumn('care_of')
            ->addColumn('care_of_rel')
            ->addColumn('nominee')
            ->addColumn('nominee_address')
            ->addColumn('nominee_rel')
            ->addColumn('photo')
            ->addColumn('signature1')
            ->addColumn('signature2')
            ->addColumn('signature3')
            ->addColumn('intro_by')
            // ->addColumn('status')
            ->addColumn('approved_date_formatted', fn (Member $model) => Carbon::parse($model->approved_date)->format('d/m/Y H:i:s'))
            ->addColumn('approved_by')
            ->addColumn('created_by')
            ->addColumn('created_date_formatted', fn (Member $model) => Carbon::parse($model->created_date)->format('d/m/Y H:i:s'))
            // ->addColumn('updated_by')
            // ->addColumn('updated_date_formatted', fn (Member $model) => Carbon::parse($model->updated_date)->format('d/m/Y H:i:s'))
            ;
    }

    /*
    |--------------------------------------------------------------------------
    |  Include Columns
    |--------------------------------------------------------------------------
    | Include the columns added columns, making them visible on the Table.
    | Each column can be configured with properties, filters, actions...
    |
    */

     /**
     * PowerGrid Columns.
     *
     * @return array<int, Column>
     */
    public function columns(): array
    {
        return [
          
            Column::make('MEMBER ID', 'member_id')
            ->searchable()
            
            // ->makeInputText()
            ,

            // Column::make('MEETING ID', 'meeting_id')
            //     ->makeInputRange(),
            Column::make('Full NAME', 'full_name')
            ->bodyAttribute('any-class','min-width: 20 vw;max-width:20 vw')
                ->sortable()
                ->searchable()
                // ->makeInputText()
                ,
            Column::make('FIRST NAME', 'first_name')
            ->bodyAttribute('any-class','min-width: 25vw;max-width:25vw')
                ->sortable()
                ->searchable()
                // ->makeInputText()
                ->hidden(),

            Column::make('MIDDLE NAME', 'middle_name')
                ->sortable()
                ->searchable()
                // ->makeInputText()
                ->hidden(),

            Column::make('LAST NAME', 'last_name')
                ->sortable()
                ->searchable()
                // ->makeInputText()
                ->hidden(),

            Column::make('Date of Birth', 'dob_formatted', 'dob')
                ->searchable()
                // ->sortable()
                // ->makeInputDatePicker()
                ,

            Column::make('MOBILE', 'mobile')
                // ->sortable()
                ->searchable()
                // ->makeInputText()
                ,

            Column::make('Alternate MOBILE', 'alt_mobile')
                // ->sortable()
                ->searchable()
                ->hidden(true,false)
                // ->makeInputText()
                ,

            Column::make('AADHAAR NO', 'aadhaar_no')
                // ->sortable()
                // ->hidden(true,false)
                ->searchable()
                // ->makeInputText()
                ,

            Column::make('MARITAL STATUS', 'marital_status')
                ->hidden(true,false)
                // ->sortable()
                ->searchable()
                // ->makeInputText()
                ,

            Column::make('QUALIFICATION', 'qualification1')
                // ->sortable()
               // ->searchable()
                ->hidden(true,false)
               // ->makeInputText()
               ,

                Column::make('PIN CODE', 'pincode')
                // ->sortable()
                // ->searchable()
                ->hidden(true,false)
                // ->makeInputText()
                ,
            Column::make('OCCUPATION', 'occupation')
                ->hidden(true,false)
                // ->sortable()
                // ->searchable()
                // ->makeInputText()
                ,

            Column::make('INCOME', 'income')
                ->hidden(true,false)
               // ->makeInputRange()
               ,

            Column::make('Date of Joining', 'doj_formatted', 'doj')
               // ->searchable()
                // ->hidden(true,false)
                // ->sortable()
               // ->makeInputDatePicker()
               ,

            Column::make('ADDRESS', 'address_formated','address')
                ->hidden(true,false)
                // ->sortable()
                ->searchable()
                // ->makeInputText()
                ,

            Column::make('POST OFFICE', 'post_office')
                // ->sortable()
                ->searchable()
                ->hidden(true,false)
                // ->makeInputText()
                ,

            Column::make('DISTRICT', 'district')
                // ->sortable()
                ->searchable()
                ->hidden(true,false)
                // ->makeInputText()
                ,

            Column::make('NO OF DEPENDENTS', 'no_of_dependents')
                ->hidden(true,false)
                // ->toggleable()
                ,

            Column::make('POLICE STATION', 'police_station')
                // ->sortable()
                ->searchable()
                ->hidden(true,false)
                // ->makeInputText()
                ,

            Column::make('CARE OF', 'care_of')
                // ->sortable()
                ->searchable()
                ->hidden(true,false)
                // ->makeInputText()
                ,

            Column::make('CARE OF Relationship', 'care_of_rel')
                // ->sortable()
                //->searchable()
                ->hidden(true,false)
                //->makeInputText()
                ,

            Column::make('NOMINEE', 'nominee')
                // ->sortable()
                ->searchable()
            // ->makeInputText()
            ,

            Column::make('NOMINEE ADDRESS', 'nominee_address')
                // ->sortable()
                ->searchable()
                ->hidden(true,false)
                // ->makeInputText()
                ,

            Column::make('NOMINEE Relationship', 'nominee_rel')
                ->hidden(true,false)
                // ->sortable()
                // ->searchable()
                // ->makeInputText()
                ,

            Column::make('PHOTO', 'photo')
                ->hidden(true,false)
                // ->sortable()
                // ->searchable()
                // ->makeInputText()
                ,

            Column::make('SIGNATURE1', 'signature1')
                ->hidden(true,false)
                // ->sortable()
                // ->searchable()
                // ->makeInputText()
                ,

            Column::make('SIGNATURE2', 'signature2')
                ->hidden(true,false)
                // ->sortable()
                // ->searchable()
                // ->makeInputText()
                ,

            Column::make('SIGNATURE3', 'signature3')
                ->hidden(true,false)
                // ->sortable()
                // ->searchable()
                // ->makeInputText()
                ,

            Column::make('Introduced BY', 'intro_by')
                ->hidden(true,false)
                //->makeInputRange()
                ,

            Column::make('STATUS', 'status')
                ->hidden(true,false)
            //     ->sortable()
            //     ->searchable()
            //     ->makeInputText()
            ,

            Column::make('APPROVED DATE', 'approved_date_formatted', 'approved_date')
                ->hidden(true,false)
                // ->searchable()
                // ->sortable()
                // ->makeInputDatePicker()
                ,

            Column::make('APPROVED BY', 'approved_by')
                ->hidden(true,false)
                // ->sortable()
                // ->searchable()
                // ->makeInputText()
                ,

            Column::make('CREATED BY', 'created_by')
                ->hidden(true,false)
                // ->sortable()
                // ->searchable()
                // ->makeInputText()
                ,

            Column::make('CREATED DATE', 'created_date_formatted', 'created_date')
                ->hidden(true,false)
                // ->searchable()
                // ->sortable()
                // ->makeInputDatePicker()
                ,

            Column::make('UPDATED BY', 'updated_by')
                ->hidden(true,false)
                // ->sortable()
                // ->searchable()
                // ->makeInputText()
                ,

            Column::make('UPDATED DATE', 'updated_date_formatted', 'updated_date')
                ->hidden(true,false)
                // ->searchable()
                // ->sortable()
                // ->makeInputDatePicker()
                ,

        ]
;
    }

    /*
    |--------------------------------------------------------------------------
    | Actions Method
    |--------------------------------------------------------------------------
    | Enable the method below only if the Routes below are defined in your app.
    |
    */

     /**
     * PowerGrid Member Action Buttons.
     *
     * @return array<int, Button>
     */

    
    public function actions(): array
    {
       return [
           Button::make('edit', 'Edit')
               ->class('bg-success bg-gradient btn cursor-pointer text-white px-3 py-1 border border-white text-sm')              
               ->route('members.member.edit', ['member' => 'member_id'])
               ->target('_self')
               ->method('get'),
               Button::make('view', 'View')
               ->class('bg-success btn bg-blue-700 hover:bg-blue-900 cursor-pointer text-white px-3 py-1 border border-white text-sm')              
               ->route('members.member.show', ['member' => 'member_id'])
               ->target('_self')
               ->method('get'),  

        //    Button::make('destroy', 'Delete')
        //        ->class('bg-red-500 cursor-pointer text-white px-2 py-2 m-1 rounded text-sm')
        //        ->route('members.member.destroy', ['member' => 'id'])
        //        ->method('delete'),
        ];
    }
   

    /*
    |--------------------------------------------------------------------------
    | Actions Rules
    |--------------------------------------------------------------------------
    | Enable the method below to configure Rules for your Table and Action Buttons.
    |
    */

     /**
     * PowerGrid Member Action Rules.
     *
     * @return array<int, RuleActions>
     */

    
    public function actionRules(): array
    {
       return [

           //Hide button edit for ID 1
            Rule::button('edit')
                ->when(fn($member) => $member->status === '1')
                
                ->hide(),
            Rule::button('edit')
            ->when(function () { 
                return !memApproval::UserMemberEditRights() ;
            })              
                ->hide(),
            Rule::button('view')
            ->when(function () { 
                return !memApproval::UserMemberViewRights() ;
            })
                ->hide(),

            // Rule::rows()
            //     ->when(function ($member) { 
            //         return $member->status == '2' ;
            //     })
                
            //     ->setAttribute('class', 'bg-secondary'),
        ];
    }
   
}
`

### Extra information

```markdown
I had been using this versions of Tailwind
"@tailwindcss/forms": "^0.5.2",
"@tailwindcss/typography": "^0.5.0",
```

**Comment by luanfreitasdev** [comment]
Hi!. Can you do these steps to try to identify the problem?

Install a previous version

If does not work. Delete the vendor folder and install everything again.

Check app and browser cache.

If possible record a video with the console open.

**Comment by Unisolgr14** [comment]
It is working after I restart my system(local server thank god it is not the production server). But I had already tried the above mentions steps and it did not fix the problem. Thank you Sir for your reply.
