### ISSUE TITLE
[Bug]: modal functionality breaks the PowerGrid table

### ISSUE THREAD

**Issue by alexchirolde** [Power-Components/livewire-powergrid#829]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

yes

### PowerGrid

v3.5.13

### Laravel

 v9.46.0

### Livewire

v2.10.8 

### Alpine JS

v3.11.1

### Theme

Tailwind 3.x

### Describe the bug.

I added a button to open a modal in the actions column, like [here](https://livewire-powergrid.com/table/row-actions-buttons.html#openmodal).
The idea of the modal is to update a record. Everything works as expected, the modal is shown, the records is properly updated after I click the update button in the modal, but after the modal is closed, this error in the console appears and nothing works on the page. Not even the links on the top menu which has nothing to do with the table.

<img width="1679" alt="Screenshot 2023-01-21 at 3 27 30 PM" src="https://user-images.githubusercontent.com/48970517/213886173-16bca017-a4c0-4e5d-94fa-bf287223f615.png">

It doesn't matter how the modal is closed; clicking outside, or clicking the cancel button in the modal with this code 

`wire:click="$emit('closeModal')"`

The page just breaks.

I tested and added the same modal on another page with no PowerGrid table and everything works fine, not even an error on the console.

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
this is the livewire component:

class EditOperationModal extends ModalComponent
{
    public Operation $operation;

    public int $status_selected;

    public function mount(int $operationId)
    {
        $this->operation = Operation::find($operationId);
    }


    public function submit(): void
    {
        $validatedData = $this->validate([
            "status_selected" => ["integer"],
        ]);
        $this->operation->update([
            'status' => $validatedData['status_selected'],
        ]);

        $this->closeModal();
    }


    public function render()
    {
        $statusEnums = OperationStateEnums::cases();
        $status = [];
        foreach ($statusEnums as $enum) {
            $status[$enum->value] = $enum->getTranslation();
        }
        $this->status_selected = $this->operation->status->value;

        return view('livewire.edit-operation-modal', [
            "status" => $status,
            "status_selected" => $this->status_selected
        ]);
    }

 ```
```

**Comment by luanfreitasdev** [comment]
Hi!. Please believe this issue is because you have two instances of Alpine in the browser.

Be sure to leave null in config/livewire-powergrid.php
```php
'alpinejs_cdn'  => 'https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js',
```
To
```php
'alpinejs_cdn'  => null,
```

**Comment by alexchirolde** [comment]
You were absolutely right!!! Thanks

**Comment by MaxBernasconiCodes** [comment]
> Hi!. Please believe this issue is because you have two instances of Alpine in the browser.
> 
> Be sure to leave null in config/livewire-powergrid.php
> 
> ```
> 'alpinejs_cdn'  => 'https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js',
> ```
> 
> To
> 
> ```
> 'alpinejs_cdn'  => null,
> ```

Tyvm, i had the same problem
