### ISSUE TITLE
Missused Documentation 

### ISSUE THREAD

**Issue by muhammadnan** [Power-Components/livewire-powergrid#83]
in this [documentation](https://livewire-powergrid.docsforge.com/main/configure/#2-alpine-js), instruction directs to replace 'alpinejs' to null without quote like a 'null', this doesn't seem to match [functions.php line 28](https://github.com/muhammadnan/livewire-powergrid/blob/main/src/functions.php#L28) which generates the string.. looks like there needs to be a change in documentation or functions.php

![Screenshot 2021-10-16 at 19-18-59 🧨 powerGridJsFramework() Return value must be of type string, null returned (View home a](https://user-images.githubusercontent.com/30528814/137587078-8da6c4e6-432e-4150-9803-b64857f4e74b.png)

**Comment by luanfreitasdev** [comment]
Hi, thanks for letting us know! I've already corrected the main
