### ISSUE TITLE
[Bug]: crash on resolveContent helper when using Collections

### ISSUE THREAD

**Issue by frontalnugity** [Power-Components/livewire-powergrid#844]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### PowerGrid

3.7.2

### Laravel

9.51.0

### Livewire

2.11.2

### Alpine JS

3.11.1

### Theme

Tailwind 3.x

### Describe the bug.

I set up a new instance of a power grid, following the install instructions to the letter. As soon as I attempted to enable the editOnClick() method on the test table (and all subsequent tests), I was presented with the following error:

![pg_error](https://user-images.githubusercontent.com/12880595/217682717-ea9d46a9-44fb-4ed9-89dc-a2071aec3be3.png)

I was able to bypass this by removing the `Model` typing in the Helpers.php file (line 30), and I suspect this is because I'm populating my table using a collection.

### To Reproduce...

- New Laravel project
- install power grid and dependencies
- create a new Powergrid component and add a related page

In your newly created component class, under the Columns function, add editOnClick() to one of the demo columns - ie:

```php
 Column::make('Name', 'name')
                ->searchable()
                ->makeInputText('name')
                ->editOnClick(true)
                ->sortable(),

```

### Extra information

```markdown
- I did ensure to set the private key property as outlined in the docs:

    public string $primaryKey = 'id';
    public string $sortField = "id";


- Removing the editOnClick method restores functionality (but not editability)

- Was able to bypass the error (but not fully aware of any side effects but changing the helpers.php in the package as follows:

```php
    public function resolveContent(string $currentTable, string $field, Model $row): ?string

```
to

```php
    public function resolveContent(string $currentTable, string $field, $row): ?string

```

I believe this to be a bug or perhaps a side-effect of new typing syntax in recent PHP installs (I'm running 8.2) and would appreciate any info on if this requires a fix or if there are serious side effects from my suggested change.
```

**Comment by dansysanalyst** [comment]
Hi @frontalnugity,

Currently, the editOnClick() feature only works on Models.

I will make sure to update the documentation, making it clear.

There are no plans to implement this functionality, but we are open for a Pull Request!

**Comment by frontalnugity** [comment]
@dansysanalyst, thanks for clarifying the current state!
