### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by rootuser** [Power-Components/livewire-powergrid#845]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

1.17.9

### Laravel

9

### Livewire

2.11.2

### Alpine JS

3.11.1

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

Hello,

sorry I have to report the error here, but in the documentation repository (https://github.com/Power-Components/powergrid-doc) issues are not activated.

The documentation of Themes is broken/missing (see: https://livewire-powergrid.com/get-started/configure.html#_3-choose-your-theme)
In that paragraph there is an info box with a link for 'Theme'. The link points to https://livewire-powergrid.com/table/custom-theme, but that page does not exist.

Looking into the files of the documentation repository, this file is also missing (see: https://github.com/Power-Components/powergrid-doc/tree/main/docs/table)

It would be great if you could provide the missing information.

Thank you very much!
Kind regards, Tom

**Comment by dansysanalyst** [comment]
Hi @rootuser,

Thank you for reporting the problem. 

You have opened the issue in the right place, we just find it easier to center everything in this repository. 🙂 

I will verify the broken link and update it as soon as possible!

**Comment by dansysanalyst** [comment]
Documentation added:

https://livewire-powergrid.com/table/custom-theme.html
