### ISSUE TITLE
Show All Record Issue

### ISSUE THREAD

**Issue by abhaypithadiya** [Power-Components/livewire-powergrid#851]
### Discussed in https://github.com/Power-Components/livewire-powergrid/discussions/849

<div type='discussions-op-text'>

<sup>Originally posted by **abhaypithadiya** February 13, 2023</sup>
I have 100 records in the table. When I change the show record to "All". The query sets the limit to 1 so it shows one record and other records are paginated. Not sure why this happened.

Around 100 records
![chrome_gfcyJf884l](https://user-images.githubusercontent.com/107384999/218365588-878f0305-e7c4-46b5-aa04-b6f98a86e478.png)

When selected "All"
![chrome_rMVzrRm9hV](https://user-images.githubusercontent.com/107384999/218365633-fbf8b7c4-bc73-45e3-aa43-a30be97f1e4f.png)

How to solve this? Thanks</div>

**Comment by abhaypithadiya** [comment]
Hello! Yes , still the same problem, I have cleared all the caches as well.

I am currently using Powergrid version 3.5.

**Comment by ssenoga** [comment]
I am also experiencing the same issue.

**Comment by luanfreitasdev** [comment]
Does this happen because there are exactly 100 records? What happens if you have more or less?

**Comment by abhaypithadiya** [comment]
Hey! No for me even if there are 5 records or 2 records. It gets paginated with the limit of 1.

**Comment by luanfreitasdev** [comment]
Hello!. Let me know if this is resolved, as I have not been able to reproduce this issue

**Comment by abhaypithadiya** [comment]
Hi! Any update on this issue?

**Comment by luanfreitasdev** [comment]
I still haven't been able to reproduce the error. Could you send a public repository so we can analyze it together. ?

**Comment by abhaypithadiya** [comment]
> I still haven't been able to reproduce the error. Could you send a public repository so we can analyze it together. ?

Hey! Sorry I am unable to reproduce the error in a new public repository, everything works properly there. I am not sure why this is happening. Any other way I could share it with you?

**Comment by luanfreitasdev** [comment]
Hello. You can add me to a private repository if you want
