### ISSUE TITLE
[Bug]: Custom attribute from models is not working on sortable() but detectable on addColumns()

### ISSUE THREAD

**Issue by roeiboribor** [Power-Components/livewire-powergrid#852]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

![image](https://user-images.githubusercontent.com/23719322/218911518-f174f436-eda8-4374-8313-2bc3f4478ed7.png)

### PowerGrid

v3.7.2

### Laravel

v8.83.27

### Livewire

v2.10.7

### Alpine JS

3.10.5

### Theme

Tailwind 3.x, Tailwind 3.x with tailwind/forms

### Describe the bug.

When I use the custom attribute from model It doesn't recognize even if I add the table name without the join. "applicants.full_name"

### To Reproduce...

click the sort or search function inside the table. then the error will show saying that the column name is not recognized.

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello!

This is not possible because the full_name column does not exist in the database. You can achieve this if you include [selectRaw](https://laravel.com/docs/9.x/queries#selectraw) in your query.
