### ISSUE TITLE
hiding filterInputTextOptions, and Showing only search box for a column

### ISSUE THREAD

**Issue by rpanda-dot** [Power-Components/livewire-powergrid#858]
# ⚡ PowerGrid ⚡ Feature Request

## Summary

I am creating a table in using powergrid livewire in a laravel project, I am using  **makeInputText()** to search inside a column. When I am using this function a textbox for search along with a select box with possible searchin parameters are showing like _**Is/Is not, Contains/Does not contain, Starts with/Ends with, etc**_. But I only want to show the search box with a default filter option selected,

### Why is this needed?

When showing two input boxes there (textbox,select box) the header area is taking more place, and for a normal user its also confusing because a normal user is going to simply match with the stirng most of the time. 

### Suggested Solution(s)

I am not able to find any solutions for the specific portion to enable or disable.

**Comment by luanfreitasdev** [comment]
Hello. Thanks for reporting this feature, but I can tell you that it's already done in the next version (v4).  Which very soon will be officially launched.

https://v4.livewire-powergrid.com/table/column-filters.html#filter-inputtext
