### ISSUE TITLE
[Bug]:  modals with alerts

### ISSUE THREAD

**Issue by medilyassg** [Power-Components/livewire-powergrid#874]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

2

### Laravel

10

### Livewire

1

### Alpine JS

1

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

the modals with power grid not allowed

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello!, powergrid does not support version 1 of livewire and Alpine.

**Comment by medilyassg** [comment]
thanks you bro
