### ISSUE TITLE
[Bug]: Date picker wrong date, already installed latest version

### ISSUE THREAD

**Issue by zamcoder** [Power-Components/livewire-powergrid#889]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

v3.7.5

### Laravel

v9.52.4

### Livewire

v2.12.3

### Alpine JS

v3.4.2

### Theme

Tailwind 3.x, Tailwind 3.x with tailwind/forms

### Describe the bug.

still being bugs until now, i already update to the latest version

but my choices date still make different ouput in queries 

![image](https://user-images.githubusercontent.com/76896394/227464044-b4607d50-0256-4fbf-a7a9-b7a171288d35.png)

### To Reproduce...

just click date picker

### Extra information

```markdown
no extra info, the code still as is
```

**Comment by luanfreitasdev** [comment]
Hello!, can you run other tests with other dates?

Can you debug the variables inside that function and see how it's coming along? I didn't have this problem here
```php

// vendor/power-components/livewire-powergrid/src/Traits/Filter.php

public function datePickerChanged(array $data): void
{
   // $debug variables
}
```

**Comment by zamcoder** [comment]
![image](https://user-images.githubusercontent.com/76896394/227686923-301dcda7-4414-446c-9334-da5823b879fb.png)

still same, its bug, but when i debug like your said

the result is correct

![image](https://user-images.githubusercontent.com/76896394/227687035-2d5623aa-a8d8-41e4-8d28-384839fece61.png)

@luanfreitasdev

**Comment by zamcoder** [comment]
![image](https://user-images.githubusercontent.com/76896394/227687362-5bece41b-f1da-4b8a-ab13-d67fa2d2c8a9.png)


but when i debug only startDate & endDate

the result is wrong

@luanfreitasdev

**Comment by zamcoder** [comment]
![image](https://user-images.githubusercontent.com/76896394/227687930-8fae0d4d-e059-4098-bb41-e268103f7512.png)


i try like this, the result is correct

**Comment by luanfreitasdev** [comment]
I see that this is a problem with the flatpickr package according to several issues it has. (the selected date always comes from the computer and in the database we use UTC, that's why the difference).

https://github.com/flatpickr/flatpickr/issues/1532

I believe that getting around this with explode "to" may work for you, but in other languages this is not possible.

With that in mind, I think we can create a standard browser date filter and maybe put another similar one in place of flatpickr. What do you think ?

**Comment by zamcoder** [comment]
I think we can use https://flowbite.com/docs/plugins/datepicker/

Instead flatpickr , because I use this flowbite datepicker and it's goes
well

**Comment by zamcoder** [comment]
how ? @luanfreitasdev

**Comment by luanfreitasdev** [comment]
@zamcoder  can you send a PR for version 4?

**Comment by zamcoder** [comment]
Sorry I can't , because I use that datepicker not in Livewire powergrid

**Comment by zamcoder** [comment]
when will it fix? @luanfreitasdev

**Comment by luanfreitasdev** [comment]
Hello, please take a look at this pr

https://github.com/Power-Components/livewire-powergrid/pull/891

**Comment by luanfreitasdev** [comment]
https://github.com/Power-Components/livewire-powergrid/releases/tag/v3.7.6

**Comment by zamcoder** [comment]
still bug @luanfreitasdev 
![image](https://user-images.githubusercontent.com/76896394/228728601-5e4cdb55-a03b-41b7-ad60-efe38bf6cb1f.png)

already updated 
![image](https://user-images.githubusercontent.com/76896394/228728646-e04ea3e4-aa87-4e34-8b1b-4dc6f5d9cdb3.png)

![image](https://user-images.githubusercontent.com/76896394/228728678-0551f2cb-17d2-41fd-a46a-c0261f57c215.png)

**Comment by luanfreitasdev** [comment]
I think this is not a bug.

We have to understand now that all dates must have a timezone value set correctly. Also, every powergrid update must happen npm run dev/build to work correctly.

We must take this into account:
* local timezone
* app timezone
* timezone of the dates that are being displayed in the powergrid date column
* database timezone (with time).
