### ISSUE TITLE
After editing data in a modal window using openModal all changed data is updated in the grid except toggleable column.

### ISSUE THREAD

**Issue by rosolovsky** [Power-Components/livewire-powergrid#899]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

3.7.6

### Laravel

9.52.5

### Livewire

2.12.3

### Alpine JS

3.10.3

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

After editing data in a modal window using openModal all changed data is updated in the grid except toggleable column.
In modal componen i use this
```
public function update() {
        $this->validate();
        $this->product->save();
        $this->closeModalWithEvents([
            $this->emit('pg:eventRefresh-default')
        ]);
    }
```
But toggleable column not refreshed. Only reloading page browser refreshed toggleable column in grid!
How can i fix it?

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by rosolovsky** [comment]
What is? Is this a bug?
![bug](https://user-images.githubusercontent.com/5950382/229808634-ee9e3ddd-608a-4eb7-ac6c-c4e3838b0416.png)

**Comment by luanfreitasdev** [comment]
Hello!. This is strange, all the tests I did worked correctly. Can you take a look here?

https://github.com/Power-Components/powergrid-demo-misc/blob/main/app/Http/Livewire/EditStock.php#L63

**Comment by rosolovsky** [comment]
I do not know
In my modal component 
```
  public function update() {
        $this->validate();
        $this->product->save();
        $this->closeModalWithEvents([
            ProductTable::getName() => 'refreshGrid'
        ]);
    }
```
In ProductTable component

```
protected function getListeners(): array
    {
        return array_merge(
            parent::getListeners(), 
            [
                'refreshGrid'   => 'refreshGrid'
            ]);
    }

    public function refreshGrid() 
    {
        $this->emit('pg:eventRefresh-default');
    }
```
After editing in the modal I get this: 

![bug1](https://user-images.githubusercontent.com/5950382/229814150-dace936a-c013-49b3-8242-664afe3777d8.png)

After reload page browser  I get this: 

![bug2](https://user-images.githubusercontent.com/5950382/229814441-4652e4ec-0487-4b75-9d56-051b616a5b4d.png)
