### ISSUE TITLE
[Bug]: Button for clear filter has a field/column name, not a column title

### ISSUE THREAD

**Issue by jamesRUS52** [Power-Components/livewire-powergrid#917]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

4

### Laravel

10

### Theme

Bootstrap

### Describe the bug.

Button for clear filter has a field/column name, not a column title

### To Reproduce...

input some thing into filter field

**Comment by luanfreitasdev** [comment]
Thanks @jamesRUS52 , fixed on : https://github.com/Power-Components/livewire-powergrid/releases/tag/v4.3.1
