### ISSUE TITLE
Using editOnclick() function

### ISSUE THREAD

**Issue by Chirroc** [Power-Components/livewire-powergrid#93]
Im using the editonClick function for my crud, as I edit the wanted cell, it saves the update but i have to refresh the page for me to be able to see the update.

Is there a way can be able to fix this ?

![image](https://user-images.githubusercontent.com/79195552/139828211-8bf225d0-3f84-45df-9054-afe70c1db834.png)

Doing the edit 

![image](https://user-images.githubusercontent.com/79195552/139828395-a2ac4b1e-4cbc-417d-966c-209159f90e28.png)

After i've done the edit 

![image](https://user-images.githubusercontent.com/79195552/139828493-1635d0c2-3522-4bf5-9255-5f8f5edefe08.png)

After resfresh, is it possible to have have the edited cell without refreshing?
![image](https://user-images.githubusercontent.com/79195552/139828773-5aff86ae-106c-4501-8695-c3a847391097.png)

**Comment by luanfreitasdev** [comment]
Hello

Thanks for using Powergrid. This issue has been fixed and will be released in the next release soon!

[issue 50](https://github.com/Power-Components/livewire-powergrid/issues/50)

**Comment by vs0uz4** [comment]
This issue has been fixed and will be released in the next release soon!
![auto_refresh_after_editonclick](https://user-images.githubusercontent.com/2080547/139909393-a668a349-dfa8-42b5-8a33-98fcd221f172.gif)

**Comment by luanfreitasdev** [comment]
Fixes in v1.4 - https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.4.0
