### ISSUE TITLE
[Bug]: Export selected ambiguois id error for tables with relations

### ISSUE THREAD

**Issue by uqjohart** [Power-Components/livewire-powergrid#931]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes - I'll add a screenshot or report it below.
![error](https://user-images.githubusercontent.com/85085437/232642526-516f8d53-0c02-4d45-9163-370d62ff1f10.png)

### PowerGrid

3.7

### Laravel

9.19

### Livewire

2.10

### Alpine JS

3.2.4

### Theme

Tailwind 3.x

### Describe the bug.

If you have a powertable with a related (joined) table, you cant select records to selectively export.

My example:
- Assets have a related Type
- Type has a name field
- AssetsTable shows the asset.id and assets.types.name fields (to keep it simple. 

Have I borked something or is that broken? I tried using  Asset::query().with('types') which fixes the export issue, but I couldn't get the column sorting to work with that. 

I'm super close to finishing this project so I really don't want to replace this awesome library at such a late stage :c

### To Reproduce...

Select a few records, then click export -> selected
![asset powertable](https://user-images.githubusercontent.com/85085437/232642974-0a137669-ca57-4b55-b560-0bbbeb49aca0.png)

[AssetsTable.txt](https://github.com/Power-Components/livewire-powergrid/files/11257016/AssetsTable.txt)

### Extra information

```markdown
The AssetsTable relevant chunks of code:

1. Export setup partial
$this->showCheckBox();
  return [
    Exportable::make('export')
      ->striped()
      ->csvDelimiter("\t")
      ->type(Exportable::TYPE_XLS, Exportable::TYPE_CSV),

2. Datasource
return Asset::query()
  ->join('types', 'assets.type_id', '=', 'types.id')
  ->select('assets.*','types.name as types_name',)
  ->groupBy('assets.id');

3. addColumn function
  ->addColumn('id')
  ->addColumn('type_name', function (Asset $asset) {return e($asset->type->name);

4. columns function
Column::make('ID', 'assets.id'),
Column::make('TYPE', 'type_name', 'types.name')
  ->makeInputSelect(Type::all(), 'name', 'type_id')
  ->sortable(),
```

**Comment by akamasAT** [comment]
see https://v4.livewire-powergrid.com/table/datasource.html#keys-conflict
just had the same issue and `public string $primaryKey = 'your_table.id';` fixed it

**Comment by luanfreitasdev** [comment]
Hello, I think this is a problem in your table join, you can select only one id and rename it. Try using this, if that doesn't work it may reopen the same issue

```php
public function datasource(): Builder
{
     return Asset::query()
        ->join('types', 'assets.type_id', '=', 'types.id')
        ->select([
            'assets.id as assets_id',
            'assets.description as assets_description',
            'types.name as types_name'
       ])
        ->groupBy('assets.id');
 }
```

**Comment by uqjohart** [comment]
> see https://v4.livewire-powergrid.com/table/datasource.html#keys-conflict just had the same issue and `public string $primaryKey = 'your_table.id';` fixed it

This fixed it! You absolutely awesome person you!!
(Hopefully this wont reopen the ticket, if so please feel free to close it)
