### ISSUE TITLE
[Bug]: Export button not visible due to x-cloak attribute

### ISSUE THREAD

**Issue by tek2991** [Power-Components/livewire-powergrid#933]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

4.3

### Laravel

10.0

### Livewire

2.11

### Alpine JS

3.0.6

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

The export button is not visible.

### To Reproduce...

1. Create a fresh Laravel Project.
2. Install Laravel Jetstream to fast-track the installation of "Livewire", "Tailwind", "Alpine JS".
3. Install powergrid, flatpickr, openspout.
4. Seed 100 users and create a simple Users Table.

### Extra information

```markdown
The issue seems to be because of "x-cloak" attribute in the "header.blade.php" file inside the tailwind folder. I have not tested with Bootstrap5.

For now, publishing the views and removing the "x-cloak" attribute from the header.blade.php seems to bring back the export button.

Any comment is welcome.
```

**Comment by luanfreitasdev** [comment]
Hello!, can you send a PR?

**Comment by luanfreitasdev** [comment]
Done #934

**Comment by tek2991** [comment]
Thank you.
