### ISSUE TITLE
[Bug]: addColumn in PG 4.x Cannot Use Carbon Formatted Date

### ISSUE THREAD

**Issue by GBry** [Power-Components/livewire-powergrid#939]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

4.3.3

### Laravel

10.8.0

### Livewire

2.12.3

### Alpine JS

3.12.0

### Theme

Tailwind 3.x

### Describe the bug.

I used the addColumn function like
`
->addColumn('LogDate', function (afml_model $model) {
                return Carbon::parse($model->LogDate)->format('d M Y');
})
`
But the column still returns
2023-04-20 00:00:00

Yes I also included
Column::make('Log Date','LogDate'),

### To Reproduce...

Try to addColumn and format it

### Extra information

```markdown
I did try to dd the object and it returns a valid d M Y string
```

**Comment by dansysanalyst** [comment]
See below, I've created a custom column with the formatted date.

```php
 public function addColumns(): PowerGridEloquent
 {
        return PowerGrid::eloquent()
            ->addColumn('id')
             //...
            ->addColumn('produced_at')
            ->addColumn('produced_at_formatted', function (Dish $dish) {
                return Carbon::parse($dish->produced_at)->format('d M Y');
            });
 }

 public function columns(): array
  {
        return [
            //...
            Column::make(__('Production date'), 'produced_at_formatted'),
        ];
  }
```

Results in:


<img width="802" alt="CleanShot 2023-04-25 at 10 37 47@2x" src="https://user-images.githubusercontent.com/79267265/234221931-bd9c7351-1629-465c-996f-761512c35d95.png">

**Comment by GBry** [comment]
Apparently my column name was conflicting with the model column. I think the PG Column is taking the pre-processed value from the model directly.

Thanks for the insight!
