### ISSUE TITLE
Create a report to help us improve

### ISSUE THREAD

**Issue by mehmetakifozkaya** [Power-Components/livewire-powergrid#94]
Default Primary key

* I have defined the primary key in the model but it gives the error: "Column not found: 1054 Unknown column 'id' in 'order clause' ...order by `id`"
How can I identify the primary key other than "id"?

**Comment by luanfreitasdev** [comment]
Hello

Did you try to set a value in the public variable `$primaryKey`?

thanks for using the powergrid!
