### ISSUE TITLE
Undefined property: PowerComponents\LivewirePowerGrid\Button::$param

### ISSUE THREAD

**Issue by ndarproj** [Power-Components/livewire-powergrid#940]
Im getting an error whenever i view the page after adding the bulk actions. I am using powergrid 3.7.8 PHP 8.1.16 Laravel 10.1.4

ErrorException
PHP 8.1.16
10.1.4
Undefined property: PowerComponents\LivewirePowerGrid\Button::$param

`<?php

namespace App\Http\Livewire\DataTables;

use App\Models\TempUser;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Validator;
use Illuminate\Database\Eloquent\Builder;
use PowerComponents\LivewirePowerGrid\Rules\{Rule, RuleActions};
use PowerComponents\LivewirePowerGrid\Traits\ActionButton;
use PowerComponents\LivewirePowerGrid\{Button, Column, Exportable, Footer, Header, PowerGrid, PowerGridComponent, PowerGridEloquent};

final class TempUserTable extends PowerGridComponent
{
    use ActionButton;
    public $error;
    public $success;
    public $email;
    public $mobile;
    public $timezone;

    //Table sort field
    public string $sortField = 'temp_users.id';

    /*
    |--------------------------------------------------------------------------
    |  Event listeners
    |--------------------------------------------------------------------------
    | Add custom events to DishesTable
    |
    */
    protected function getListeners(): array
    {
        return array_merge(
            parent::getListeners(),
            [
                'edit-dish' => 'editDish',
                'bulkDelete',
            ]
        );
    }

    /*
    |--------------------------------------------------------------------------
    |  Bulk delete button
    |--------------------------------------------------------------------------
    */
    public function bulkDelete(): void
    {
        $this->emit('openModal', 'delete-dish', [
            'dishIds'                 => $this->checkboxValues,
            'confirmationTitle'       => 'Delete dish',
            'confirmationDescription' => 'Are you sure you want to delete this dish?',
        ]);
    }
    /*
    |--------------------------------------------------------------------------
    |  Features Setup
    |--------------------------------------------------------------------------
    | Setup Table's general features
    |
    */
    public function setUp(): array
    {
        $this->showCheckBox();

        return [
            // Exportable::make('export')
            //     ->striped()
            //     ->type(Exportable::TYPE_XLS, Exportable::TYPE_CSV),
            Header::make()->showSearchInput(),
            Footer::make()
                ->showPerPage()
                ->showRecordCount(),
        ];
    }

    /*
    |--------------------------------------------------------------------------
    |  Datasource
    |--------------------------------------------------------------------------
    | Provides data to your Table using a Model or Collection
    |
    */

    /**
     * PowerGrid datasource.
     *
     * @return Builder<\App\Models\TempUser>
     */
    public function datasource(): Builder
    {
        return TempUser::where('company_id', \Session::get('defaultCompany')->id);
    }

    /*
    |--------------------------------------------------------------------------
    |  Relationship Search
    |--------------------------------------------------------------------------
    | Configure here relationships to be used by the Search and Table Filters.
    |
    */

    /**
     * Relationship search.
     *
     * @return array<string, array<int, string>>
     */
    public function relationSearch(): array
    {
        return [];
    }

    /*
    |--------------------------------------------------------------------------
    |  Add Column
    |--------------------------------------------------------------------------
    | Make Datasource fields available to be used as columns.
    | You can pass a closure to transform/modify the data.
    |
    */
    public function addColumns(): PowerGridEloquent
    {
        return PowerGrid::eloquent()
            // ->addColumn('id')
            ->addColumn('name')
            ->addColumn('email')
            ->addColumn('mobile')
            ->addColumn('timezone')
            ->addColumn('team_name')
            ->addColumn('status')
            ->addColumn('meta');
    }

    /*
    |--------------------------------------------------------------------------
    |  Include Columns
    |--------------------------------------------------------------------------
    | Include the columns added columns, making them visible on the Table.
    | Each column can be configured with properties, filters, actions...
    |
    */

    /**
     * PowerGrid Columns.
     *
     * @return array<int, Column>
     */
    public function columns(): array
    {
        return [

            // Column::make('ID', 'id'),
            Column::make('NAME', 'name')
                ->sortable()
                ->searchable()
                ->makeInputText(),

            Column::make('EMAIL', 'email')
                ->sortable()
                ->searchable()
                ->makeInputText()
                ->editOnClick(true),

            Column::make('MOBILE', 'mobile')
                ->sortable()
                ->searchable()
                ->makeInputText()
                ->editOnClick(true),

            Column::make('TIMEZONE', 'timezone')
                ->sortable()
                ->searchable()
                ->makeInputText()
                ->editOnClick(true),

            Column::make('TEAM NAME', 'team_name')
                ->sortable()
                ->searchable()
                ->makeInputText()
                ->editOnClick(true),

            Column::make('META DATA', 'meta')
                ->sortable()
                ->searchable()
                ->makeInputText(),

            Column::make('STATUS', 'status'),
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | Actions Method
    |--------------------------------------------------------------------------
    | Enable the method below only if the Routes below are defined in your app.
    |
    */

    /**
     * PowerGrid TempUser Action Buttons.
     *
     * @return array<int, Button>
     */

    public function actions(): array
    {
        return [
            Button::make('destroy', 'Delete')
                ->target('_self')
                ->class('js-alertOnSubmit text-danger-600 hover:underline')
                ->route('temp_users.destroy', ['temp_user' => 'id'])
                ->method('delete'),
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | Header Action Buttons
    |--------------------------------------------------------------------------
    */

    public function header(): array
    {
        return [
            Button::add('bulk-delete')
                ->caption(__('Bulk delete'))
                ->class('cursor-pointer block bg-white-200 text-gray-700 border border-gray-300 rounded py-2 px-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-600 dark:border-gray-500 dark:bg-gray-500 2xl:dark:placeholder-gray-300 dark:text-gray-200 dark:text-gray-300')
                ->emit('bulkDelete', [])
        ];
    }
}
`

**Comment by abhaypithadiya** [comment]
Hey! Check this similar issue: https://github.com/Power-Components/livewire-powergrid/discussions/707#discussion-4539438

**Comment by luanfreitasdev** [comment]
Hello!. I tried to reproduce this problem, but I didn't have the same result.

![image](https://user-images.githubusercontent.com/33601626/234001467-f2e5d0b2-efd1-44f3-8732-49807791da00.png)

![image](https://user-images.githubusercontent.com/33601626/234001246-a018e6bb-689f-46c6-b984-f9de48f6e908.png)

```php
  Button::make('destroy', 'Delete')
          ->target('_self')
          ->class('js-alertOnSubmit text-danger-600 hover:underline')
           ->route('dish.destroy', ['dish' => 'id'])
           ->method('delete'),
``
