### ISSUE TITLE
[Bug]: Alpine Expression Error: pgFlatPickr is not defined

### ISSUE THREAD

**Issue by peroxovy** [Power-Components/livewire-powergrid#941]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

```
Alpine Expression Error: pgFlatPickr is not defined

Expression: "pgFlatPickr({
        dataField: 'created_at',
        tableName: 'default',
        filterKey: 'enabledFilters.date_picker.created_at',
        label: 'CREATED AT',
        locale: {"locale":"en","dateFormat":"d\/m\/Y H:i","enableTime":true,"time_24hr":true},
        onlyFuture: false,
        noWeekEnds: false,
        customConfig: []
    })"

Uncaught ReferenceError: pgFlatPickr is not defined
    at eval (eval at <anonymous> (app.ab93cf8a.js:32:653), <anonymous>:3:16)
    at app.ab93cf8a.js:32:992
    at ow (app.ab93cf8a.js:28:16989)
    at vn (app.ab93cf8a.js:32:130)
    at app.ab93cf8a.js:32:29415
    at Function.<anonymous> (app.ab93cf8a.js:32:10615)
    at i (app.ab93cf8a.js:32:1936)
    at s (app.ab93cf8a.js:32:1966)
    at dw (app.ab93cf8a.js:32:1976)
    at Mt (app.ab93cf8a.js:32:4732)
```

### PowerGrid

3.7.8

### Laravel

9.5..5

### Livewire

2.13.3

### Theme

Tailwind 3.x

### Describe the bug.

I've cloned application to another test VM and error is visible.
I've changed default lang "pt_PT" to "en". Issue is still visible.
Therefore inside `app.js` I haven't imported `flatpicker` and it works without any problem. 
Any thoughts? I was trying reproducing all stuff from the git issue pages but no result.. :/

### To Reproduce...

...

### Extra information

```markdown
...
```

**Comment by luanfreitasdev** [comment]
This really is weird. I just downloaded this [source](https://github.com/power-Components/powergrid-demo) where the 3.7 version is and I didn't have the same result.

I think I'm missing importing `@powerGridScripts`

https://v3.livewire-powergrid.com/get-started/configure.html#_1-include-scripts-and-styles

**Comment by peroxovy** [comment]
Just before `</body>` I have `@powerGridScripts`. 

I have app hosted inside `/var/www/html/pg-app` and also inside `livewire.cfg` I've set ` "asset_url" => "/pg-app"`.

All other functions including sorting/filtering are working properly. Assets and files were published.

**Comment by peroxovy** [comment]
I've found that on both servers I've got PHP in version 8.0.20 but on previous server I've got v3.5.3 of PowerGrid... this could cause a problem, because currently I've got 3.7.* Is there any possibility to downgrade it?

**Comment by eafarooqi** [comment]
i also have the same issue with the latest release. date filters are not working
