### ISSUE TITLE
Adding new field inside Bug form

### ISSUE THREAD

**Issue by peroxovy** [Power-Components/livewire-powergrid#943]
I wanted to ask for adding new field inside Bug report form which is PHP Version.

I was recently adding new topic, but I've found that my PHP Version don't match the library and it wasn't mentioned.

**Comment by dansysanalyst** [comment]
Hi @peroxovy,

Would you consider pull requesting it?

https://github.com/Power-Components/livewire-powergrid/blob/4.x/.github/ISSUE_TEMPLATE/bug.yml
