### ISSUE TITLE
[Bug]: package scripts and styles without npm

### ISSUE THREAD

**Issue by eafarooqi** [Power-Components/livewire-powergrid#944]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

No, this error is not related to views.

### Is there an error in the console?

No

### PowerGrid

4.3.4

### Laravel

10.8.0

### Livewire

2.12.3

### Theme

Bootstrap

### Describe the bug.

Hi, 
for the V4 @powerGridStyles and @powerGridScripts are deprecated, how can we include scripts and styles without npm. 

unfortunately npm modules are not an option on this project. is there any other way ?
The plugins are also not working like datepicker and multi select.

### To Reproduce...

without npm

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello!. Unfortunately, we no longer use this functionality.

However, you can make a custom directive as was previously done in version 3

https://github.com/Power-Components/livewire-powergrid/blob/3.x/src/Providers/PowerGridServiceProvider.php#L79
