### ISSUE TITLE
[Bug]: Relation search causes query to be out of range

### ISSUE THREAD

**Issue by martynaskre** [Power-Components/livewire-powergrid#947]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

3.7.8

### Laravel

9.52.6

### Livewire

2.12.3

### Alpine JS

3.10.3

### Theme

Tailwind 3.x

### Describe the bug.

By enabling the date filter alongside the text search in the Livewire PowerGrid's `relationSearch` method, the resulting query "goes out of scope". In order to avoid this issue, it is necessary to wrap relation search into separate `where` query.

This is what generated in **PowerGrid 3.x**:

```sql
select * from `table` where (exists (SOME QUERY) or exists (SOME QUERY) and (`table`.`created_at` between '2023-04-24 00:00:00' and '2023-04-24 23:59:59')) and `table`.`deleted_at` is null order by `id` asc limit 50 offset 0
```

In order to prevent this issue, we must wrap exists queries into separate where, e.g.:
```sql
select * from `table` where ((exists (SOME QUERY) or exists (SOME QUERY)) and (`table`.`created_at` between '2023-04-24 00:00:00' and '2023-04-24 23:59:59')) and `table`.`deleted_at` is null order by `id` asc limit 50 offset 0
```

### To Reproduce...

Steps to reproduce:

- Add relation search entry
- Setup column with `makeInputDatePicker`
- Select specific date range
- Enter text search

**Comment by luanfreitasdev** [comment]
thanks for checking this
