### ISSUE TITLE
ToggleColumn and Download buttons not vissable and working.

### ISSUE THREAD

**Issue by kmiesen** [Power-Components/livewire-powergrid#95]
**Describe the bug**

* After loading the table the button to toggle fields or download a file are hidden.

**To Reproduce**
* Got to any form and see if the buttons are there.

**Laravel version (exactly):**
* 8.60.0 
 
**Alpine version:**
* 3.4.2 

**Theme:**
- [X] Tailwind 
   - Version:  4.3      

**Screenshots** (***This helps to understand better***) (Redacted since private data)

![screen](https://user-images.githubusercontent.com/92785874/139857398-1bce9022-5e95-4ec3-af48-2c67172e2c18.png)

**Do you have any idea how we can fix it?**
For some reason the x-cloak works but it doesnt update to being visable.

This might be an error on my part but its weird that it doesnt work out of the box if thats the case.

**Comment by kmiesen** [comment]
Thanks for the package btw! I love it.

**Comment by luanfreitasdev** [comment]
Temporarily removed in the version v1.4 - https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.4.0.

Thank you so much for using power grid!
