### ISSUE TITLE
[Bug]: Flatpickr bug with selected range date

### ISSUE THREAD

**Issue by rosolovsky** [Power-Components/livewire-powergrid#951]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1.17

### PowerGrid

4.4.2

### Laravel

10.9.0

### Livewire

2.12.3

### Alpine JS

3.12.0

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

After select date range in Flatpickr filter (e.g. 01.04.2013 - 01.04.2013) i get wrong start and end range. My timezone Europe/Kiev.
In Chrome console log i get:

![pic1](https://user-images.githubusercontent.com/5950382/234809436-7fb78df1-b5c8-4425-85ab-a617240caff5.png)

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
From what I understand, the selecteddates is already coming wrong?

**Comment by luanfreitasdev** [comment]
As data that the query is doing is not in UTC?

Ideally, the user enters a data interval and the flatpickr sends the timezone of the user. We do not convert backend or schedule to UTC na search

**Comment by rosolovsky** [comment]
I'm not talking about time. What I'm talking about is that when I select the period of April 1st to filter, I get March 31st. That is, 1 day ago. Why so? Even in your GitHub demo this happens. Thanks for understanding.

**Comment by luanfreitasdev** [comment]
But it needs to count the time in UTC otherwise it filters based on the timezone

**Comment by rosolovsky** [comment]
And why does it count and filter incorrectly? After all, I specified the timezone in all the necessary configs.

**Comment by luanfreitasdev** [comment]
How is the timezone in app.config?

**Comment by rosolovsky** [comment]
I changed different time zones. UTC and Europe/Kiev in config app and php.ini. But the result is the same. Filters 1 day ago from the selected range.

**Comment by rosolovsky** [comment]
I also used Flatpickr in pure html and js. And there the plugin gives the start and end date of the selected period correctly.

**Comment by luanfreitasdev** [comment]
Strange . Can you record a video with the date, showing how it is in the bank, how it is filtering and showing some debugs?

**Comment by rosolovsky** [comment]
Yes!

https://user-images.githubusercontent.com/5950382/234949901-03a1b014-5653-4574-9dfa-341a8b0e84d1.mp4

**Comment by rosolovsky** [comment]
Of course.


https://user-images.githubusercontent.com/5950382/234951785-2e3e916e-2974-41e5-8371-07aa58fb7b19.mp4

**Comment by alexchirolde** [comment]
I was about to open a new issue when I found this one, in my case, I cannot even select a range of dates. I created a default table component using the terminal command artisan powergrip:create, no configurations at all, and I got this console error.
```
module.esm.js:416 Alpine Expression Error: pgFlatPickr is not defined

Expression: "pgFlatPickr({
        dataField: 'created_at',
        tableName: 'default',
        filterKey: 'enabledFilters.date_picker.created_at',
        label: 'Created at',
        locale: null,
        onlyFuture: false,
        noWeekEnds: false,
        customConfig: []
    })"
```
A picker opens when I click on the input, but is a single selection picker and doesn't work, the results are not even filtered.

this is how it looks

<img width="1256" alt="Screenshot 2023-05-06 at 7 54 10 PM" src="https://user-images.githubusercontent.com/48970517/236650952-d0318835-36c1-4fd0-a5fc-c02ca373237a.png">

**Comment by luanfreitasdev** [comment]
@martynaskre , can you try again with v4.4.3?

**Comment by martynaskre** [comment]
> @martynaskre , can you try again with v4.4.3?

Just tried this with `v4.4.3` and I can say that it works as expected.

**Comment by rosolovsky** [comment]
> @martynaskre , can you try again with v4.4.3?

Does not work correctly!!! 
If i select on day 01.04.2023 i get 01.04.2023 00:00:00 - 01.04.2023 00:00:00
It is wrong!
It should be so 01.04.2023 00:00:00 - 01.04.2023 23:59:59

![pic1](https://github.com/Power-Components/livewire-powergrid/assets/5950382/f6267aa4-0f56-4522-a5bb-834e658e349c)

**Comment by luanfreitasdev** [comment]
This is really weird. I still haven't been able to reproduce this bug

**Comment by rosolovsky** [comment]
:) Yes, let it be

**Comment by luanfreitasdev** [comment]
Can you try again using latest version ?

**Comment by rosolovsky** [comment]
> Can you try again using latest version ?

There are features of use Flatpickr with option enableTime = false. For me it was necessary to use enableTime = true
Flatpick now it works correctly.

**Comment by rosolovsky** [comment]
In my opinion, this is a bug. Because when I select only 1 day for filtering without specifying the time, then by default the time should be 00:00:00 - 23:59:59 (This is absolutely logical). Instead I get 00:00:00 - 00:00:00. Fix this problem.

**Comment by luanfreitasdev** [comment]
The time to filter on the database must not be 00:00 until 23:59. It should be based on UTC time.

**Comment by rosolovsky** [comment]
Perfectly!!! Everything works correctly in 4.4.4. Thank you!!!
