### ISSUE TITLE
[Bug]: Filters outside not working

### ISSUE THREAD

**Issue by JACarrasco7** [Power-Components/livewire-powergrid#955]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

Hi, I when click filter button for filter outside, i can´t see the filter inputs. I can configure filters inline, i can see the inputs filters

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Can you provide more information about the issue?

**Comment by JACarrasco7** [comment]
If I set the filters to "outside", when I click on the button the filters are not shown, it does nothing. but when I set them inline if I can work with them

**Comment by JACarrasco7** [comment]
I have this versions 

"laravel/framework": "^9.19",  
"wireui/wireui": "^1.17",
"power-components/livewire-powergrid": "^4.4",
 "livewire/livewire": "^2.12"

**Comment by luanfreitasdev** [comment]
Can you check if there is any log when you click on show filters?
If you want to send a video please

**Comment by JACarrasco7** [comment]
https://user-images.githubusercontent.com/45757951/236755649-9ca926b1-57c1-4051-8307-e9e07a7d928b.mp4

**Comment by luanfreitasdev** [comment]
Unfortunately, I haven't been able to reproduce this problem yet.

**Comment by hitaloramon** [comment]
This same problem happens here

**Comment by 8888post** [comment]
Probably you publish views.
To solve problem remove  or rename (Backup if you customize views) this folder `resources\views\vendor\livewire-powergrid`

**Comment by marineusde** [comment]
> Unfortunately, I haven't been able to reproduce this problem yet.

Maybe its the same problem with the "field" in the Filter-Class, in this thread I can reproduce the problem: https://github.com/Power-Components/livewire-powergrid/issues/971

**Comment by marineusde** [comment]
I fixed two problems in the builder class in the latest version 4.5.2, can you update please and tell us if your problem is fixed too?

**Comment by hitaloramon** [comment]
@zwhhz Now it worked. Problem solved!

**Comment by marineusde** [comment]
Fixed in Branch https://github.com/Power-Components/livewire-powergrid/pull/992

Done in v4.5.2

@JACarrasco7 please close
