### ISSUE TITLE
[Bug]: Too few arguments to function PowerComponents\LivewirePowerGrid\Filters\FilterInputText::getWireAttributes()

### ISSUE THREAD

**Issue by imfaisii** [Power-Components/livewire-powergrid#958]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### Theme

Bootstrap

### Describe the bug.

I have added filters:

Filter::inputText('column_name')->operators(['contains']),

But it throws the above exception

### To Reproduce...

Add custom input text filter

**Comment by abhaypithadiya** [comment]
Hey! 

I think you need to pass the database column name from which the data is filtered. So something like this: 

```
public function filters(): array
{
    return [
       Filter::inputText('column_name', 'db_column_name')
          ->operators(['contains']),
    ];
}
```

**Comment by 8888post** [comment]
Probably you publish views.
To solve the problem remove  or rename (Backup if you customize views) this folder `resources\views\vendor\livewire-powergrid`
