### ISSUE TITLE
Undefined variable: searchInput when using 'outside' filters

### ISSUE THREAD

**Issue by owf18916** [Power-Components/livewire-powergrid#96]
**Describe the bug**

*  When using 'filter' => 'outside', the Undefined variable: searchInput occured

**To Reproduce**
* Got to change the inline filter to outside

**Laravel version (exactly):**
* 8.68.1 ?
 
**Alpine version:**
* 3.x.x ?

**Theme:**

- [x] Bootstrap
   - Version: 5.1.3        

**Screenshots** (***This helps to understand better***)
![image](https://user-images.githubusercontent.com/55745878/139862613-2e32c7b6-3ada-4703-ba10-62d9162f3c88.png)

**Do you have any idea how we can fix it?**

**Comment by luanfreitasdev** [comment]
Hello @owf18916 , 

Unfortunately the 'outside' filtering option is not yet available in the bootstrap5 version

If you want to send a PR, you could use tailwind as a base.

**Comment by NetRally** [comment]
Hello unfortunetly the tailwind version also throw error Invalid argument supplied for foreach()

**Comment by owf18916** [comment]
> Hello unfortunetly the tailwind version also throw error Invalid argument supplied for foreach()

Yep, i also experienced the same issues with the tailwindcss

**Comment by luanfreitasdev** [comment]
For me it's working normally in tailwind

Could you run composer dump-autoload?

![image](https://user-images.githubusercontent.com/33601626/139953945-6455d7b7-ef6c-4079-9407-f97f79f19b8b.png)

**Comment by NetRally** [comment]
Hello, I did it but the same error
![image](https://user-images.githubusercontent.com/12120871/140036843-39db787c-59e2-4a7a-80f2-b5809e490e92.png)

**Comment by luanfreitasdev** [comment]
Could it show the error itself? There it's just showing the error line

**Comment by NetRally** [comment]
ErrorException
Invalid argument supplied for foreach() in filter blade

**Comment by luanfreitasdev** [comment]
Can you post how the component was assembled for me to try to play?
