### ISSUE TITLE
[Bug]:  Class "OpenSpout\Writer\CSV\Options" not found | Class "OpenSpout\Writer\XLSX\Options" not found

### ISSUE THREAD

**Issue by abhaypithadiya** [Power-Components/livewire-powergrid#962]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1

### PowerGrid

v4.4.2

### Laravel

v10.9.0

### Livewire

v2.12.3

### Alpine JS

3.12.0

### Theme

Bootstrap

### Describe the bug.

When exporting data I come across this error. This happens in both CSV and XLXS.

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
This happens in both CSV and XLXS. Same while selecting All or Selected Option.
```

**Comment by luanfreitasdev** [comment]
This is because in version 4 openspout is not installed by default.

https://v4.livewire-powergrid.com/get-started/upgrade-guide.html#independent-export-engine
