### ISSUE TITLE
[Bug]: When removing either the min or max value from the number filter, both values are cleared

### ISSUE THREAD

**Issue by markgoedegebure** [Power-Components/livewire-powergrid#963]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

4.2.0

### Laravel

9.52.5

### Livewire

2.12.3

### Alpine JS

3.10.2

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When i have a column with a number filter, everything works as expected when filtering with either min, max or both. However, when i remove the value from either min or max, the other value is also removed. 

### To Reproduce...

Create a powergrid table and add a column with a number filter and enter a value for both the min and max fields. Remove either one to see the other one gets cleared as well. This should not happen.

![afbeelding](https://github.com/Power-Components/livewire-powergrid/assets/44771394/ec4ef3b9-5765-4395-a295-bf598adeb0da)

### Extra information

```markdown
public function filters(): array
{
    return [
        Filter::number('yield'),
    ];
}
```

**Comment by luanfreitasdev** [comment]
This is the default behavior of powergrid, as it has no way of determining whether to clear one or the other. All are clean
