### ISSUE TITLE
[Bug]: inconsistent results when using two inputText Filters

### ISSUE THREAD

**Issue by kolydart** [Power-Components/livewire-powergrid#971]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.1

### PowerGrid

4.4.2

### Laravel

10.10.1

### Livewire

2.12.3

### Alpine JS

3.12.1

### Theme

Tailwind 3.x

### Describe the bug.

When I type search criteria in two inputText Filters, the results are inconsistend, based on which filter was filled first.

### To Reproduce...

In a fresh [https://github.com/Power-Components/powergrid-demo](https://github.com/Power-Components/powergrid-demo) installation, I alternately type "Salmão" in `Dish`, and "Luan" in `Chef` input text fields. 

The results differ, depending on which field was filled first. See this [screen capture](https://public.kolydart.gr/Screen%20Recording%202023-05-15%20at%2010.20.46%20AM.mov).

Expected behaviour would be to take into account both filters (boolean AND) no matter which was typed first.

p.s.
Thank you for your extraordinary contribution to the laravel ecosystem!

**Comment by marineusde** [comment]
I can reproduce it, cause its not every time a bug:

If you set the "field" in the Filter::inputText()-Method, you cant filter (bug):

```
    public function filters(): array
    {
        return [
            Filter::inputText('name', 'tablename.name'),
            Filter::inputText('second_field', 'tablename.second_field')
        ];
    }
```

If you remove it, the filter works:
```    public function filters(): array
    {
        return [
            Filter::inputText('name'),
            Filter::inputText('second_field')
        ];
    }
```

I hope, this helps.

**Comment by marineusde** [comment]
Found a second bug, I used different tables:

```
    public function datasource(): null|QueryBuilder|EloquentBuilder
    {
        return FirstModel::query()
            ->select([
                'first_tablename.*', 'second_tablename.city'
            ])
            ->join('second_tablename', 'second_tablename.id', 'first_tablename.second_tablename_id');
    }

    public function filters(): array
    {
        return array_merge(parent::filters(), [
            Filter::inputText('name', 'first_tablename.name'),
            Filter::inputText('city', 'second_tablename.city')
        ]);
    }
```

I will fix it in the branch

**Comment by luanfreitasdev** [comment]
> Found a second bug, I used different tables:
> 
> ```
>     public function datasource(): null|QueryBuilder|EloquentBuilder
>     {
>         return FirstModel::query()
>             ->select([
>                 'first_tablename.*', 'second_tablename.city'
>             ])
>             ->join('second_tablename', 'second_tablename.id', 'first_tablename.second_tablename_id');
>     }
> 
>     public function filters(): array
>     {
>         return array_merge(parent::filters(), [
>             Filter::inputText('name', 'first_tablename.name'),
>             Filter::inputText('city', 'second_tablename.city')
>         ]);
>     }
> ```
> 
> I will fix it in the branch

Are you going to send it on PR [992](https://github.com/Power-Components/livewire-powergrid/pull/992)? I'll mark it as a draft for now. Great job

**Comment by marineusde** [comment]
> > Found a second bug, I used different tables:
> > ```
> >     public function datasource(): null|QueryBuilder|EloquentBuilder
> >     {
> >         return FirstModel::query()
> >             ->select([
> >                 'first_tablename.*', 'second_tablename.city'
> >             ])
> >             ->join('second_tablename', 'second_tablename.id', 'first_tablename.second_tablename_id');
> >     }
> > 
> >     public function filters(): array
> >     {
> >         return array_merge(parent::filters(), [
> >             Filter::inputText('name', 'first_tablename.name'),
> >             Filter::inputText('city', 'second_tablename.city')
> >         ]);
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I will fix it in the branch
> 
> Are you going to send it on PR [992](https://github.com/Power-Components/livewire-powergrid/pull/992)? I'll mark it as a draft for now. Great job

Yes, its the second commit in the branch. thank you :)

**Comment by luanfreitasdev** [comment]
Done in v4.5.2
