### ISSUE TITLE
[Bug]: editOnClick not work

### ISSUE THREAD

**Issue by hitaloramon** [Power-Components/livewire-powergrid#979]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PHP Version

8.2.2

### PowerGrid

4.4.4

### Laravel

10.10.1

### Livewire

2.12.3

### Alpine JS

3.11.1

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

When trying to edit the content through the editOnClick function, an error is thrown Property [$name] not found on component

### To Reproduce...

```php
Column::make('Nome', 'name')
      ->searchable()
      ->sortable()
      ->editOnClick(true),
``` 

```php
public function onUpdatedEditable(string $id, string $field, string $value): void
    {
        Category::query()->find($id)->update([
            $field => $value
        ]);
    }

``` 
![image](https://github.com/Power-Components/livewire-powergrid/assets/12436779/0a63c06f-5a5d-43a9-beb3-0e4f9daaccb8)

**Comment by luanfreitasdev** [comment]
You must configure a property for the column name with array type and define it in rules

https://v4.livewire-powergrid.com/table/cell-actions-buttons.html#editonclick

![image](https://github.com/Power-Components/livewire-powergrid/assets/33601626/2809f47d-0caf-4fd1-a8c1-a67aa6ccdc30)

**Comment by hitaloramon** [comment]
The rule was missing, now it worked.
