### ISSUE TITLE
Classes not recognised

### ISSUE THREAD

**Issue by snapey** [Power-Components/livewire-powergrid#98]
in VS Code all the package class names have squiggly underlines.  I don't have this problem with other packages. Powergrid works just fine.

I have run `composer dump` but it did not help.

**Laravel version (exactly):**
* 8.54.0?

**Screenshots** (***This helps to understand better***)

![DeviceTable_php_—_iotmv](https://user-images.githubusercontent.com/328747/139878273-787dd138-52d1-4a92-b835-0cd02b732313.png)

**Comment by luanfreitasdev** [comment]
Hi @snapey 

Unfortunately I have no idea what's going on.  The component itself is working though this problem?

**Comment by snapey** [comment]
Yes. The component works fine despite the issue in my IDE

**Comment by luanfreitasdev** [comment]
Looks good for now. I will close this problem, if it is a recurring problem, it can be reopened

thanks!

**Comment by snapey** [comment]
its not 'recurring'  - its permanent

It is extremely annoying as files show with errors (in red in the file manager) and it makes it impossible to notice other syntax issues.

**Comment by snapey** [comment]
I have resolved it.  

Open the Command Palette and run `Intelephense: Index Workspace`

Its not a problem I have experienced adding other packages, but seems to have worked.

**Comment by luanfreitasdev** [comment]
Great! This will help other people too. 

Thanks
