### ISSUE TITLE
Table sorting not working, produces sql error orderBy=''

### ISSUE THREAD

**Issue by snapey** [Power-Components/livewire-powergrid#99]
**Describe the bug**

The cols.blade.php contains this for the clickable header cell when sorting is enabled on a column;
```
@if($column->sortable === true)
wire:click="sortBy('{{ $column->dataField ?? $column->field }}')"
@endif
```
However, the $column->dataField is not null by default, it is an empty string so never falls to `$column->field`

The result is `wire:click="sortBy('')"` which results in an eloquent exception when clicked;

Column not found: 1054 Unknown column '' in 'order clause' 

**To Reproduce**
Create table with sortable column. Click the column header.

**Laravel version (exactly):**
* 8.54.0 ?
 
**Do you have any idea how we can fix it?**
Implement a better check for dataField being empty, or default null

**workaround**
publish the layout file and change the wire:click
```
@if($column->sortable === true)
wire:click="sortBy('{{ $column->dataField !='' ? $column->dataField : $column->field }}')"
@endif
```

**Comment by devsquad-luan-freitas** [comment]
Hi. Good observation. 

I'm already correcting with your suggestion. It worked well for me too

**Comment by luanfreitasdev** [comment]
Fixes in v1.4 - https://github.com/Power-Components/livewire-powergrid/releases/tag/v1.4.0

**Comment by webparadoxer** [comment]
SQLSTATE[HY000]: General error: 1 1st ORDER BY term out of range - should be between 1 and 13 (SQL: select * from "users" order by +0 asc, "" asc limit 10 offset 0)
after upgrade

**Comment by webparadoxer** [comment]
any update?!

**Comment by luanfreitasdev** [comment]
public string $sortField = 'id'

This property cannot be empty or null.

**Comment by luanfreitasdev** [comment]
$perPage will only take effect using `setUp`

```
public function setUp()
    {
        $this->showCheckBox()
            ->showToggleColumns()
            ->showPerPage(0)
            ->showRecordCount()
            ->showExportOption('download', ['excel', 'csv'])
            ->showSearchInput();
    }
```

**Comment by webparadoxer** [comment]
ok, thanks.  but sorting dont work(

**Comment by webparadoxer** [comment]
and hide show column
Cannot use object of type stdClass as array

**Comment by webparadoxer** [comment]
![image](https://user-images.githubusercontent.com/5503366/140164165-cd7e9198-9d61-48eb-9ed3-15e528538b5d.png)

**Comment by webparadoxer** [comment]
not work only for me?

**Comment by luanfreitasdev** [comment]
Hello @webparadoxer , how are you using the component, such as collection or model? Could you post it?

**Comment by emiliosh** [comment]
I have a similar problem... I think... 

`SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: character varying + integer LINE 1: select * from "genders" order by name+0 asc, "name" asc limi... ^ HINT: No operator matches the given name and argument types. You might need to add explicit type casts. (SQL: select * from "genders" order by name+0 asc, "name" asc limit 10 offset 0)`

This is my class
`namespace App\Http\Livewire;

use App\Models\Gender;
use Illuminate\Support\Carbon;
use Illuminate\Database\QueryException;
use Illuminate\Database\Eloquent\Builder;
use PowerComponents\LivewirePowerGrid\Button;
use PowerComponents\LivewirePowerGrid\Column;
use PowerComponents\LivewirePowerGrid\PowerGrid;
use PowerComponents\LivewirePowerGrid\PowerGridEloquent;
use PowerComponents\LivewirePowerGrid\PowerGridComponent;
use PowerComponents\LivewirePowerGrid\Traits\ActionButton;

class GenderTable extends PowerGridComponent
{
    use ActionButton;

    public function setUp()
    {
        $this->showCheckBox()
            ->showPerPage()
            ->showToggleColumns();
    }


    public function datasource(): ?Builder
    {
        return Gender::query();
    }


    public function relationSearch(): array
    {
        return [];
    }

    public function addColumns(): ?PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ->addColumn('disabled_at_formatted', function(Gender $model) {
                return Carbon::parse($model->disabled_at)->format('d/m/Y');
            });
    }


    public function columns(): array
    {
        return [
            Column::add()
                ->title(__('Nombre'))
                ->field('name')
                ->sortable()
                ->searchable()
                ->makeInputText(),

            Column::add()
                ->title(__('Nombre corto'))
                ->field('short_name')
                ->sortable()
                ->searchable()
                ->makeInputText(),

            Column::add()
                ->title(__('Deshabilitado desde'))
                ->field('disabled_at_formatted')
                ->searchable()
                ->sortable()
                ->makeInputDatePicker('disabled_at'),
        ]
;
    }


    public function template(): ?string
    {
        return null;
    }

}
`
Before I had

`   public function addColumns(): ?PowerGridEloquent
    {
        return PowerGrid::eloquent()
            ->addColumn('name')
            ->addColumn('short_name')
            ->addColumn('disabled_at_formatted', function(Gender $model) {
                return Carbon::parse($model->disabled_at)->format('d/m/Y');
            });
    }`
