### ISSUE TITLE
[Bug]:  Selecting UUID value checkboxes breaks

### ISSUE THREAD

**Issue by pmutale** [Power-Components/livewire-powergrid#991]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

Yes! When i select a checkbox and retrieve the number of selected inboxes this is what i get back!
`[
    null, NaN
]`
And am sure this has got to do with the... add() in the store
`add(value, tableName) {
        debugger
        value = Number(value)
         ....
        this.remove(value, tableName)
    }
`

### PHP Version

8.1

### PowerGrid

4

### Laravel

9.52.7

### Livewire

2.5

### Alpine JS

3.0.6

### Theme

Tailwind 3.x with tailwind/forms

### Describe the bug.

While selecting individual checkboxes, the `add()` in the alpine store with **pdBulkActions {...}** recognise a `uuid` as an number. Ofcourse, i can imagine that many people use integer values for checkboxes but there should be room for usein `uuid` or a `str` as a value of a checkbox
TO FIX => Just remove this line... 
```js
add(value, tableName) {
    value = Number(value) // Remove this line
```
Will be happy to create a pull request for this

### To Reproduce...

- Load a Powergrid Table with string/uuid unique rows.
- Enable checkboxes feature in your setUp()
- In the Frontend click on any individual checkboxes
- Go into the console and retrieve the number of checked boxes

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello @pmutale , can you send the PR?

**Comment by pmutale** [comment]
@luanfreitasdev Absolutely! I only need to be given permission to create and push a pull request.

**Comment by luanfreitasdev** [comment]
Done in v4.6
