### ISSUE TITLE
[Bug]: Tailwind toggelable component only check for false value

### ISSUE THREAD

**Issue by zxtanzxzx** [Power-Components/livewire-powergrid#996]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - It work after updating the if statement.

### Is there an error in the console?

No

### PHP Version

8.2

### PowerGrid

4.4.2

### Theme

Tailwind 3.x

### Describe the bug.

The toggalable did not apply the correct class

Took a look into source code at [here](https://github.com/Power-Components/livewire-powergrid/blob/2402ff94fc5b864eebac6a32b1dc2c7cc63d60a5/resources/views/components/frameworks/tailwind/toggleable.blade.php#LL50C2-L50C2). There were 2 if else statement that checks for false value. Updated the blue to check for true value or === 1 and it works 
![image](https://github.com/Power-Components/livewire-powergrid/assets/12552846/e7a090e0-1e4f-47e9-9483-7fe0df5c5cf0)
![image](https://github.com/Power-Components/livewire-powergrid/assets/12552846/ad8d2b8b-622e-45e3-b5af-7861415c91ce)

### To Reproduce...

Show a toggalable column in tailwind theme

**Comment by luanfreitasdev** [comment]
Hello. Can you send a Pr?

**Comment by zxtanzxzx** [comment]
@luanfreitasdev PR created
