### ISSUE TITLE
[Bug]: EditOnClick() the input showed by default, without clicking. 

### ISSUE THREAD

**Issue by shakeel2717** [Power-Components/livewire-powergrid#999]
### Have you searched through other issues to see if your problem is already reported or has been fixed?

Yes, I did not find it.

### Did you read the documentation?

Yes, I did not find it.

### Have you tried to publish the views?

Yes - I didn't work.

### Is there an error in the console?

No

### PowerGrid

4.5

### Laravel

10

### Theme

Bootstrap

### Describe the bug.

In new Version, i'm creating a fresh Laravel project, when i install livewire powergird, table is working perfectly, but when i use editOnClick method on a column like i'm always using, the input box showed by default, even i did't click, now the input is not hiding, and i also can't edit any column, please guide me how i can solve this issue?

### To Reproduce...

First click on "FOO" then....

### Extra information

```markdown
<?php
 //...
```

**Comment by luanfreitasdev** [comment]
Hello, can you put more information ?

**Comment by shakeel2717** [comment]
In latest powergird, i'm using Bootstrap 5, everything working perfect, but when i add ->editOnClick() on any column, the html input showed there by default, it should appear after i click on the text, same like older version, 

this mistake is only in bootstrap, that's why for the first time I'm using older version for my latest project, please fix this bug ASAP, The Powergrid is life saver <3  
![Screenshot 2023-05-28 054149](https://github.com/Power-Components/livewire-powergrid/assets/79254929/a7237a52-7825-4f2e-9bcd-b27de526df9e)

**Comment by batuhanhazarguler** [comment]
hello, did you find a solution for this?

**Comment by shakeel2717** [comment]
> hello, did you find a solution for this?

not yet brother, i'm using old version

**Comment by luanfreitasdev** [comment]
I tried with the latest version and it's working. Is my test correct?

https://github.com/Power-Components/livewire-powergrid/assets/33601626/92232dcc-3bb0-4a0c-a44f-2587daf388b1

```
"devDependencies": {
        "axios": "^1.1.2",
        "laravel-vite-plugin": "^0.7.2",
        "sass": "^1.60.0",
        "vite": "^4.0.0"
    },
    "dependencies": {
        "@popperjs/core": "^2.11.7",
        "alpinejs": "^3.12.0",
        "bootstrap": "^5.2.3",
        "flatpickr": "^4.6.13"
    }
```

```
"require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "livewire/livewire": "^2.12",
        "power-components/livewire-powergrid": "^4.8"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.0",
        "spatie/laravel-ignition": "^2.0"
    },
```

**Comment by shakeel2717** [comment]
Problem is only in bootstrap theme

**Comment by luanfreitasdev** [comment]
I'm using bootstrap in this video

**Comment by shakeel2717** [comment]
it's not working on my side, i tried many time, everything is working fine in old version,

can you please record a video to create a basic powerGrid table in a fresh larevel? that wll help alot.

fresh Laravel installation
then install powergrid package
then create table with powergrid:create
then add code in Laravel blade file.

if we are missing anything, we are missing anything, we will figure out.

**Comment by luanfreitasdev** [comment]
I created a simple repository. Take a look, please

https://github.com/Power-Components/powergrid-bootstrap5-demo

**Comment by shakeel2717** [comment]
![Screenshot 2023-07-07 190301](https://github.com/Power-Components/livewire-powergrid/assets/79254929/674a11b7-0f37-48ff-ad71-18109a918ded)

start a new project with bootstrap 5, and still same issue :(

only for this problem, i'm sadly using still version Version 3 of powergrid. unluckily can't use latest powergrid usefull features :(

you send me video with the bootstrap, can you please publish it to a public repo and send me link?

**Comment by shakeel2717** [comment]
yes, i check the repo you sent me, you are using vite, and i'm not using it. i'm just using simple bootstrap 5 cdn link, and if i'm migrate from version 4 to 3, everything start working on.

**Comment by shakeel2717** [comment]
i think i'm not using alpine properly, then i use alpine cdn for version 4
<script src="//unpkg.com/alpinejs" defer></script>

my editonclick fields are hide

![Screenshot 2023-07-07 194329](https://github.com/Power-Components/livewire-powergrid/assets/79254929/a2bf0add-aad8-4ee1-9563-dee576b03074)

**Comment by luanfreitasdev** [comment]
@shakeel2717 . Is this working for you? For the moment I will close the issue. If it happens again, reopen it. Thanks

**Comment by shakeel2717** [comment]
Thank you for your reply,i did't said, it's worked for me, it's only work if i downgrade version, from 4 to 3. then it's start working for me. 

can you suggest me what i need to do, i'm not using vite, mix, or anything, i'm just used my css files and javascript files from public folder, or i used direct from cdn links.

all older version are working fine, only latest not working, and i think its becausee of alpine, where can i add alipine cdn link? when i add link in head, the editOnClick() column data hide.

**Comment by luanfreitasdev** [comment]
With alpine cdn does it work correctly?.

**Comment by shakeel2717** [comment]
NO, if i not use CDN link, the editonclick column show input by default, when i add the alpine cdn, the entire colum hide, no text 
or input or unerline border

without CDN

![Screenshot 2023-07-07 190301](https://github.com/Power-Components/livewire-powergrid/assets/79254929/1d9d5fbe-913b-42f6-83a8-096bb30234a4)

 
 
 with cdn
![Screenshot 2023-07-07 194329](https://github.com/Power-Components/livewire-powergrid/assets/79254929/0a2d1379-e437-4af6-a2ed-bcfeb6b35b68)
